### ISSUE TITLE
Please include all the details about a Spell when sent to VTT

### ISSUE THREAD

**Issue by DarrynGlass** [kakaroto/Beyond20#1003]
**Is your feature request related to a problem? Please describe.**
Most of the information around spells is being sent to the VTT, but what is missing is duration, and Range that would be helpful for players (and me as a DM writing API's for Roll20)

**Describe the solution you'd like**
Include these details in the spell posting (Components are already included, so not sure why the rest are missing)
![image](https://user-images.githubusercontent.com/29684482/178482386-ae987b65-f30d-4b0e-8f29-4bd34d455be4.png)

**Comment by kakaroto** [comment]
All the information is sent by Beyond20, but Roll20 can't display that however because of its own limited capabilities. We're limited to the 5e OGL templates.
https://wiki.roll20.net/D%26D_5e_OGL_Roll_Templates#Attack_.26_Damage

I know that they recently added a new feature to have the spell description displayable through a click, but that doesn't work without having the spell description set up as a custom ability/attribute on a character sheet, so it can't be used. See https://github.com/kakaroto/Beyond20/issues/951

If you need the information, you can have the player click the Display button at the same time.

**Comment by DarrynGlass** [comment]
Why can't it be included in the description like when that option is turned on?
Something like this

&{template:dmg} {{charname=Darryn}} {{rname=Bane}} {{desc=Components: V, S, M(a drop of blood)

Range:30ft

Duration:Concentration, up to 1 minute

Description: Up to three creatures of your choice that you can see within range must make Charisma saving throws. Whenever a target that fails this saving throw makes an attack roll or a saving throw before the spell ends, the target must roll a d4 and subtract the number rolled from the attack roll or saving throw.
At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.}} {{save=1}} {{saveattr=Charisma}} {{savedc=16}}

And I don't see the duration passed at all (this is the original post)

&{template:dmg} {{charname=Darryn}} {{rname=Bane}} {{range=30ft.}} {{desc=Components: V, S, M(a drop of blood)

Description: Up to three creatures of your choice that you can see within range must make Charisma saving throws. Whenever a target that fails this saving throw makes an attack roll or a saving throw before the spell ends, the target must roll a d4 and subtract the number rolled from the attack roll or saving throw.
At Higher Levels. When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.}} {{save=1}} {{saveattr=Charisma}} {{savedc=16}}

**Comment by Aeristoka** [comment]
@kakaroto I had requested that this Issue be opened based on a Discord conversation. Please take a look at my code here to see what you think: https://github.com/kakaroto/Beyond20/pull/1004

**Comment by kakaroto** [comment]
> Why can't it be included in the description like when that option is turned on? This is how components are done.

Ah good idea to put that as part of the description itself. Yeah, that'd work!

**Comment by kakaroto** [comment]
> @kakaroto I had requested that this Issue be opened based on a Discord conversation. Please take a look at my code here to see what you think: #1004

Looks good to me, merged! :)
