### ISSUE TITLE
Empowered spell metamagic option

### ISSUE THREAD

**Issue by BatmanJesus4444** [kakaroto/Beyond20#1006]
Using the Empowered Spell metamagic option is kind of annoying to do online, because you roll your damage, choose which numbers to reroll, remember or note the numbers you aren't rerolling, then custom roll the die you want to reroll, then add them together and tell the party without it being saved in the log. This isn't a problem tabletop because you can just pick up the die and reroll them, but online you can't do that.

If an option similar to what Great Weapon Master has was added that would allow you to set a number to reroll under, or much more realistically, just reroll ones and twos or just ones, that would make it much easier

I don't think it'll be necessary for Beyond20 to use the sorcery points automatically, due to the fact that you need to manually use the points yourself anyway.
 
Well that's my suggestion, I hope it may have been helpful

**Comment by kakaroto** [comment]
Hi, thanks for the suggestion, unfortunately, I don't think it's going to be doable. I'm going to re-post here my answer to you from Discord : 
>  it's a complex situation that I don't think we could really handle with beyond20. I'd say if you want to reroll a dice after the fact, you tell the DM, you substract your sorcery point and you roll your d6 or d8 or whatever as a custom dice roll
> anything else would need to be (very annoying) popup asking the player what they want to do, every time they cast a spell... also, with roll20, we can't get the roll data since the rolls are made by roll20 itself and we get no idea of the results

Also, the fact that it uses a sorcery point means it can't be done automatically for you in case you have no sorcery points left, or you have 1 that you're saving up for something later, etc... 
This has to be a conscious decision by the player after the roll.
