### ISSUE TITLE
Beyond 20 website not loading.

### ISSUE THREAD

**Issue by JustWiz22** [kakaroto/Beyond20#1009]
https://[beyond20.here-for-more.info](https://beyond20.here-for-more.info/)
website is not working, going to said website states site cannot be reached
Troubleshooting wizard states

Package ID: Unknown
Path: Unknown
Error Code: 0x80004005
Context: Restricted

**Comment by kakaroto** [comment]
I don't see any issue with the site, this sounds more like an issue with your internet/router, or maybe a chrome extension that blocked the page or something like that.
