### ISSUE TITLE
Roll20: Set temp hp to empty string if 0

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#101]
Prevents a "0/0" on a token's bar

**Comment by kakaroto** [comment]
There is one actually, I mentioned that blanking the Numerator of Temp HP would get rid of the Temp HP bar on the token
Would it be possible to have the update change both the Numerator and Denominator on a Temp HP change?
Roll20 bumps in this goofy little + sign otherwise with my workaround of Denominator being 0

**Comment by Aeristoka** [comment]
To clarify the comment you pulled from our Discord conversation:

Current Setup:
Bar 3: hp_temp (Roll20)
(blank) / 0 for settings (causes the bar to not show up until Temp HP is assigned)
Current behavior with empty string fix, bar will not show up (excellent)
Current behavior when Temp HP is accrued: Bar displays something like "10/0 +" (the + on the far right of the bar is the Roll20 indication that you have exceeded the maximum for this value, in this case 0)

Proposal, when updating hp_temp on Roll20 from DnDBeyond, set both numerator and denominator on the Token (if possible) to the Temp HP value from DnDBeyond (ie: if 10 Temp HP is acquired, set hp_temp on token to 10/10. 5 damage is taken, set Temp HP to 5/5)

Dependent on if this is an easily alterable value on the token.
