### ISSUE TITLE
Homebrew Crit Rules: Perfect Rolls

### ISSUE THREAD

**Issue by reubneo** [kakaroto/Beyond20#1012]
When rolling damage a crit for a Half Orc or Barbarian, the features that allow you to roll an additional weapon die are treated like all additional weapon damage die and set to the max on the die.

It would be a help if you could add an additional variant to the Critical Hit rule that roles the damage die for these features.

**Comment by Aeristoka** [comment]
It is Beyond20 policy that no additional crit rules will be added beyond what is currently present.

**Comment by kakaroto** [comment]
The brutal critical dice are critical dice, as they are only rolled in case of critical hits, so they follow the same rules for how critical rolls are handled. It would not be possible to handle them differently and having a homebrew rule specific to those features doesn't make sense for Beyond20. We only support widely used homebrew rules.

**Comment by reubneo** [comment]
> 

Fair enough. I’ve never seen anyway run it like that. To me, the wide spread rule was that only the actual weapon damage was maximised since it’s an old holdover from 4e.

But if you’re not going to do it, no point fussing. Thanks anyway
