### ISSUE TITLE
Death Saving Throw for paladin with Aura of Protection incorrectly adds +5

### ISSUE THREAD

**Issue by brother-oak** [kakaroto/Beyond20#1013]
A Paladin character with the Aura of Protection feature adds a +5 to all saving throws, which is all done automatically within D&D Beyond and Beyond20 reflects this.

However, Beyond20 adds a button to automatically roll a death saving throw within the Death Saving Throws tally box that appears when at 0hp. This roll also adds the +5 bonus, but this SHOULD NOT be added in this case, as the paladin is unconscious, and the Aura of Protection should not be active in this case.

**Comment by brother-oak** [comment]
PHB, Paladin Class, Aura of Protection definition:

"Starting at 6th level, whenever you or a friendly creature within 10 feet of you must make a saving throw, the creature gains a bonus to the [saving throw](https://www.dndbeyond.com/compendium/rules/basic-rules/using-ability-scores#SavingThrows) equal to your Charisma modifier (with a minimum bonus of +1). You must be conscious to grant this bonus."

(apologies, I initially thought it was a straight +5 bonus as I was looking at the character sheet, but I can see it depends on your CHA mod. But the issue still stands - you need to be conscious to apply it, and you wont be if you are making death saving throws)

**Comment by Aeristoka** [comment]
Ok, cool, and you are correct, yes.

Discussing w/ @kakaroto how we should handle this. The value is scraped on DnDBeyond from here:
![image](https://user-images.githubusercontent.com/7988297/186712904-7629d5fd-34ef-42f9-9791-81d572f2832f.png)

It might do to bring some logic in that cuts it off, but I'm not sure if it should be that, or if it should be that you/your players keep track of the fact it shouldn't apply.

**Comment by Aeristoka** [comment]
In example, this also picks up if you have a "Stone of Good Luck"
![image](https://user-images.githubusercontent.com/7988297/186713221-05959cdf-1206-41d9-b4b2-5b0a27af624b.png)

**Comment by Aeristoka** [comment]
I think the best I can do (with the limited info DnDBeyond gives us in that section) is this:
![image](https://user-images.githubusercontent.com/7988297/186716379-996e23c9-a1b3-4117-bb79-05f4b01d3952.png)

It will get added, but also pulled off later, so it's a messier formula, but correct.

**Comment by brother-oak** [comment]
Agreed, though I suspect a stone of good luck would still apply to a death
saving throw.

Definitely an edge case, and easy to manually allow for, if you're aware of
it. I only realised when my player claimed to roll a 21 on his death saving
throw, when he shouldn't have had any modifiers applying 😁

I think it's not an issue that DnDB have faced as I don't think they offer
a button to roll death saving throws.

**Comment by kakaroto** [comment]
That's an interesting situation, thanks for bringing it to our attention!
We've implemented a fix which would be available when we next release Beyond20.
Thanks!
