### ISSUE TITLE
Fey Wanderer Ranger Otherworldly Glamour Bug

### ISSUE THREAD

**Issue by JrKenny2408** [kakaroto/Beyond20#1017]
I recently noticed that Beyond 20 is adding my Fey Wanderer Ranger's Wisdom Modifier to their Charisma Saving Throws. 

Here's my Fey Wanderer Ranger, whose Charisma Save is +4 & Wisdom is +2.
![image](https://user-images.githubusercontent.com/113072505/189005624-10da0fcb-8f80-47cb-8c43-74589bff38b6.png)

Here's what happens when it rolls through Beyond 20:
![image](https://user-images.githubusercontent.com/113072505/189005813-a8f51949-054e-497a-9316-30d90980ba43.png)

Rolling on DnD Beyond produces the expected result:
![image](https://user-images.githubusercontent.com/113072505/189005971-4a5f0c16-eea4-4f13-9964-ea2d4ac32900.png)

Browser is Chrome v105.0.5195.52

**Comment by Aeristoka** [comment]
```
Otherworldly Glamour
3rd-level Fey Wanderer feature

Your fey qualities give you a supernatural charm. As a result, whenever you make a Charisma check, you gain a bonus to the check equal to your Wisdom modifier (minimum of +1).
```

**Comment by Aeristoka** [comment]
Oh, are you saying that it's applying too broadly? And shouldn't be on the Charisma Saving Throws? while properly on Charisma Ability Checks?

**Comment by JrKenny2408** [comment]
Yeah. It's working as intended for Charisma checks, however it's also being added to Saving Throws (which it shouldn't do).
