### ISSUE TITLE
Remember Last Selected Damage Type

### ISSUE THREAD

**Issue by matthewbstroud** [kakaroto/Beyond20#1024]
When I cast a spell like Chromatic Orb, I am prompted for a damage type.  I have to select the type from a drop-down and then click Roll.  For each fight, I would likely be selecting a damage type based on my enemy and using it more than once.  It would be nice if the drop-down just defaulted to the last damage type used.

**Describe the solution you'd like**
Last used damage type for a given spell would be stored along with other user settings.

**Describe alternatives you've considered**
Adding a checkbox to the damage query form that would allow the user to set a 'default' damage type.

**Comment by matthewbstroud** [comment]
@kakaroto I would be happy to code this, I have been looking at the character and settings.  I have seen a lot of code that _gets_ settings, but not as much that _sets_ them.  Can you point me in the right direction?

**Comment by Aeristoka** [comment]
If you want to code this, this should NOT be a Chromatic Orb exclusive feature.

There are several damage selectors, they should all work this same way.

They will typically call queryDamageTypeFromArray()

**Comment by kakaroto** [comment]
I'm already in a B20-coding sprint, so I'll handle it at the same time.
