### ISSUE TITLE
v10 - Unable to create native rolls actos.

### ISSUE THREAD

**Issue by idowie** [kakaroto/Beyond20#1026]
**Describe the bug**
In v10 of Foundry, using the "create native rolls Actors" button does not create any actors, only the actors folder. This does not seem to effect v9.

**To Reproduce**
1. Go to the Beyond20 module settings in Foundry
2. Click the button that says "Create Actors"
3. Note that no actors are created, simply the folder these actors are supposed to be located in. 

**Expected behavior**
The button should create actors associated with each user, that can be used for native rolls.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/56931819/194791849-41e315f8-3106-4c76-b9f9-1d27ab369d11.JPG)

**Browser Info (please complete the following information):**
- Brave (chromium)
- Edge
- Desktop App for Foundry

 - Version 10 build 287
 - ![console](https://user-images.githubusercontent.com/56931819/194792031-bac32391-6351-402c-b512-3b847318ae96.JPG)

**Additional context**
Tested with a full load of other modules, as well as with no others enabled, made no difference.

**Comment by Aeristoka** [comment]
The Module definitely isn't ready for v10 yet.
