### ISSUE TITLE
Super advantage Rolls not displaying the right number on screen when used with Digital Dice + VTT Open

### ISSUE THREAD

**Issue by BatmanJesus4444** [kakaroto/Beyond20#1027]
**Describe the bug**
When you roll with super advantage, the number displayed in the bottom right isn't the highest, it displays all 3 numbers in the game log and VTT, just not on the bottom left.

**Expected behavior**
It should display the highest of the three, it doesn't always.

**Screenshots**
![Screenshot (86)](https://user-images.githubusercontent.com/69134963/195801866-88ee1775-eb8b-40db-a1fe-f6f1f07f6792.png)

**Browser Info (please complete the following information):**
 - Chrome
 - Version 106.0.5249.119 (Official Build) (64-bit)

**Comment by kakaroto** [comment]
Thanks! Sounds like this is the issue : https://github.com/kakaroto/Beyond20/blob/master/src/dndbeyond/base/digital-dice.js#L127
We always display as the result, the total of the first roll, regardless of whether it was a discarded roll or not.
