### ISSUE TITLE
Weapon Attack Damage not applied in Calculation Native Rolls

### ISSUE THREAD

**Issue by cckndson** [kakaroto/Beyond20#1040]
**Describe the bug**
When using Native Rolls in Foundry VTT and making a weapon attack specifically and rolling with Beyond20, the actual weapon damage won't apply. It works for spells and features such as sneak attack, but not the actual weapon damage which appears to be because when the item card is made the weapon attack damage is in brackets such as {1d8+5}[piercing] instead of 1d8+5[piercing]. I have tried to overwrite this by simply removing the brackets but when rolling via Beyond20 it simply overwrites the item on the next roll and re-inserts the brackets. It is not just the existence of something like sneak attack either as it does the same for characters without said features. Testing from within Foundry has shown that removing the brackets does fix the issue, and leaving them causes the same issue even when not rolling from Beyond20 so it is purely the brackets causing the issue.

**To Reproduce**
1. Turn on Use Native Rolls in Foundry VTT
2. Have Midi QOL and have it set to apply damage to cards.
3. Roll a melee or ranged attack from DNDBeyond.
4. Damage calculations don't work as expected because of the brackets around the damage.
5. See error

**Expected behavior**
For damage to be calculated and applied like spells, features, and anything else that doesn't appear to be a weapon attack. Ranged and melee both react the same. 

**Screenshots**
![image](https://user-images.githubusercontent.com/83190377/204853692-90e8107a-18fe-4de7-a8a8-96e7feab8d88.png)
![image](https://user-images.githubusercontent.com/83190377/204853810-adbc8d94-a655-4f09-9cc2-7c60b909d094.png)
![image](https://user-images.githubusercontent.com/83190377/204853961-dff5b144-2375-4a72-bd12-f47f8cb0031e.png)
![image](https://user-images.githubusercontent.com/83190377/204854906-3e371874-05e3-409f-ab49-0cbe49860d22.png)

**Browser Info (please complete the following information):**
 - Chrome and Firefox
 - Version 108.0.5359.72 and 107.0.1
 - No actual errors show up as everything sees it as handled properly.

**Additional context**
This is probably such a small use case that it doesn't matter and probably one of those things that seem simple like "remove the brackets" but takes a lot more coding than just "removing the brackets" but wanted to bring it up as I saw similar things but not quite the experience I was receiving.

**Comment by cckndson** [comment]
I forgot to add a screenshot for what happens when the brackets are removed. 

![image](https://user-images.githubusercontent.com/83190377/204857673-869aab3c-4b9c-44d5-8af9-e9decbe13dcc.png)

**Comment by kakaroto** [comment]
Link back to the issue reported on midi-qol repository : 
https://gitlab.com/tposney/midi-qol/-/issues/1087

**Comment by cckndson** [comment]
I appreciate you looking into it. I suspected it wouldn't be as simple as "remove the brackets" and figured you probably get something similar for issues that seem minor but in actuality it takes a lot to change that "minor" issue. I will follow the other thread and in the meantime figure out if I can do something on my end to make it work closer to the expected way.

**Comment by kakaroto** [comment]
> I appreciate you looking into it. I suspected it wouldn't be as simple as "remove the brackets" and figured you probably get something similar for issues that seem minor but in actuality it takes a lot to change that "minor" issue. I will follow the other thread and in the meantime figure out if I can do something on my end to make it work closer to the expected way.

It turned out to be as simple as "replace the brackets with parenthesis" 😁 I've just released an update to the module which fixes it.

**Comment by cckndson** [comment]
> > I appreciate you looking into it. I suspected it wouldn't be as simple as "remove the brackets" and figured you probably get something similar for issues that seem minor but in actuality it takes a lot to change that "minor" issue. I will follow the other thread and in the meantime figure out if I can do something on my end to make it work closer to the expected way.
> 
> It turned out to be as simple as "replace the brackets with parenthesis" 😁 I've just released an update to the module which fixes it.

Thanks, I appreciate you. Have a new patreon member for your hard work! 

Also I noticed crits don't get calculated. That a Beyond20 issue or Midi?

**Comment by Aeristoka** [comment]
> > > I appreciate you looking into it. I suspected it wouldn't be as simple as "remove the brackets" and figured you probably get something similar for issues that seem minor but in actuality it takes a lot to change that "minor" issue. I will follow the other thread and in the meantime figure out if I can do something on my end to make it work closer to the expected way.
> > 
> > 
> > It turned out to be as simple as "replace the brackets with parenthesis" 😁 I've just released an update to the module which fixes it.
> 
> Thanks, I appreciate you. Have a new patreon member for your hard work!
> 
> Also I noticed crits don't get calculated. That a Beyond20 issue or Midi?

Can you provide more context on that? Screenshots and such?

**Comment by cckndson** [comment]
> > > > I appreciate you looking into it. I suspected it wouldn't be as simple as "remove the brackets" and figured you probably get something similar for issues that seem minor but in actuality it takes a lot to change that "minor" issue. I will follow the other thread and in the meantime figure out if I can do something on my end to make it work closer to the expected way.
> > > 
> > > 
> > > It turned out to be as simple as "replace the brackets with parenthesis" 😁 I've just released an update to the module which fixes it.
> > 
> > 
> > Thanks, I appreciate you. Have a new patreon member for your hard work!
> > Also I noticed crits don't get calculated. That a Beyond20 issue or Midi?
> 
> Can you provide more context on that? Screenshots and such?

Absolutely. 

Here is a screenshot of damage calculation non-crit. 
![image](https://user-images.githubusercontent.com/83190377/206058143-20fb6c7a-e213-4645-a665-1899e6669751.png)

Here is a screenshot of damage calculation of a crit. Rules for my games is that a crit is rolled dice + max damage dice. But this doesn't calculate crits in any way.
![image](https://user-images.githubusercontent.com/83190377/206058298-0591fba8-1450-43dc-991b-138be3c7687f.png)

Here is a screenshot of me rolling from the character sheet in Foundry and critting. No sneak attack on it but it does max out the dice for the 8 additional piercing for max damage dice.
![image](https://user-images.githubusercontent.com/83190377/206058801-fdb21009-cdac-43a8-8e06-ed785c45a26a.png)

Please let me know if there is anything else I can provide.

**Comment by kakaroto** [comment]
oh yeah, I forgot about that, they mentionned it in the midi-qol issue. That one looks to be (maybe) a dnd5e issue, as it doesn't double dice inside of the parenthesis formula (or curly braces for that matter).

Will need to reach out to someone knowledgeable about the dnd5e system internals, hopefully they know why or how to fix it
