### ISSUE TITLE
Add support for custom sheet domains

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#1042]
This is the opposite idea of having a custom domain for a VTT where the VTT implements the Beyond20 rolls from receiving the DOM events. Instead, we'd add support for users being able to integrate Beyond20 into other character sheet sites, and Beyond20 receiving pre-parsed roll requests from those sites and transferring them to the VTTs.
The idea came from a meeting with [dScryb](https://dscryb.com) wanting to have a B20 button in their read-aloud texts.

**Comment by Aeristoka** [comment]
Interesting...

**Comment by jeremynyc4** [comment]
Love this. As I mentioned on Twitter, I think this could go a long way toward truly _open_ gaming communities. If I can use my content in one tab, DDB in another, and a Sly Flourish pdf in a third, all pushing roles to whatever platform my players and I are using that night... that would be huge.

**Comment by AGeekInside** [comment]
This sounds great. Is there some place I can go to read up on the expected format for non Beyond20 sites?

**Comment by kakaroto** [comment]
No docs quite yet, it's mostly a "read the source" at this time, though it should be mostly self explanatory (hopefully). Beyond20 posts the requests it sends/receives in the dev console, so for now, you could peak at that and see what the format is.

**Comment by kakaroto** [comment]
Ad-hoc "documentation" (explanation) discussion on the format of the rendered rolls here: 
https://discord.com/channels/446863265545453588/687770075452801157/1102318521553272983

**Comment by kakaroto** [comment]
Documentation is now completed and available here: https://beyond20.here-for-more.info/api
Would probably need a tutorial though at some point
