### ISSUE TITLE
Request: Track Concentration for characters

### ISSUE THREAD

**Issue by esnickell** [kakaroto/Beyond20#1047]
Make it easy for users to track a spell they are concentrating on.

A. Visible marker of holding concentration.
B. Easily reminded when casting a concentration spell while holding concentration on something. 
C. Reminder to make concentration saves when taking damage.

One suggested implementation:
1. A high visibility label, "CONCENTRATION" in the style of "INSPIRATION", that can be toggled on/off. 
2. On the spells sheet, there is some indicator on concentration spells. (Concentration marker red or blinking.) Or maybe clicking cast on a concentration spell pops up a dialog.
3. After confirming damage there is text to the effect, "DC 10 concentration (CON) save?

**Comment by Aeristoka** [comment]
Where exactly do you think this should be? DnDBeyond? VTT?

**Comment by kakaroto** [comment]
Yeah, this seems very much out of scope for Beyond20, as that is basically automation that should be part of the VTT itself (and not all VTTs would even support such a feature).
Beyond20 is not a VTT and does not keep any kind of state or anything like that for what you're doing, it only parses your roll, and sends it to the VTT.
Thanks for the suggestion, but I'm closing this as being out of scope (and I believe it's already supported by some modules in Foundry VTT)
