### ISSUE TITLE
Beyond20 GM dice rolls not Whispering or "To Self" in DnDBeyond Gamelog

### ISSUE THREAD

**Issue by SenorFusion** [kakaroto/Beyond20#1055]
**Describe the bug**
Beyond20 dice rolls not hidden in DnDBeyond Gamelog

**To Reproduce**
Set: Whisper Monster Rolls to the GM
GM Rolls from Monster Statblock
Roll is sent to DnDBeyond Gamelog Visible to all

**Expected behavior**
Roll is sent to DNDBeyond Gamelog as "Self" (i.e. only visible to the DM - this is the default action on DnDB without Beyond20 installed.

**Screenshots**
Beyond20 Roll top
DndBeyond Roll (without Beyond20 Installed)
Both rolled from Encouter Builder > Statblock
![self-roll-example](https://user-images.githubusercontent.com/1929777/217344943-b9ed0bb8-e1be-46bf-8c88-18a8499c4502.png)

**Browser Info (please complete the following information):**
Tried on Chrome and Firefox
Latest Chrome webstore version

**Additional context**
The Monster Images also do not come through on the Beyond20 roll, but they do on the DnBeyond roll

**Comment by IsaacAbramowitz** [comment]
I second this. everytime I wanna whisper I need to set both the game log to DM only and Beyond20 to whisper. adding the extension to your game forces you to have 2 places to set instead of 1 when trying to whisper a roll to your DM

**Comment by SenorFusion** [comment]
> I second this. everytime I wanna whisper I need to set both the game log to DM only and Beyond20 to whisper. adding the extension to your game forces you to have 2 places to set instead of 1 when trying to whisper a roll to your DM

I was actually asking this as DM, being that with roll 20 enabled it's impossible for me to hide my monster stat block rolls from my players.

But the player perspective is not ideal either.

**Comment by kakaroto** [comment]
Oh thanks! That's clearly an oversight, and thanks for catching it. Seems like an important bug to fix!

**Comment by Wyrmwood** [comment]
Also, if you have digital dice enabled, and you whisper a roll, the result is in the character sheet view, as well as the dice roll itself. The tool should disable digital dice when whispering a roll (as well as not put it in the player's game log). 
<img width="348" alt="image" src="https://user-images.githubusercontent.com/8493271/221919959-71439ad9-3887-4813-829d-ef60da672254.png">
