### ISSUE TITLE
Reading stats from non-dndbeyond site?

### ISSUE THREAD

**Issue by AGeekInside** [kakaroto/Beyond20#1056]
I would like to request a feature that allows Beyond20 to read D&D stats from a non-dndbeyond site and send them to supported VTT sites. This would enable me to use Beyond20 with other sources of D&D content that are not affiliated with dndbeyond. For example, I could use Beyond20 with a homebrew wiki or a fan-made character generator.

The feature would work by detecting the same tags as dndbeyond for abilities and other stats on any webpage and sending them to the VTT site of my choice. This way, I could use the same interface and functionality of Beyond20 without being limited to dndbeyond.

This feature would enhance my experience with Beyond20 by giving me more options and flexibility for creating and playing D&D characters online. I think this feature would benefit other users who want to use Beyond20 with alternative sources of D&D content as well.

Thank you for considering this feature request. Please let me know if you have any questions or feedback.

**Comment by kakaroto** [comment]
Hi! That's the planned feature for the next release!
It's tracked in this issue: https://github.com/kakaroto/Beyond20/issues/1042

The idea is to basically allow any site to send roll requests to Beyond20 which would then forward it to the VTTs it can support.  
We won't be adding support for anything other than dndbeyond itself as each site is different and there's so many options out there, but the alternate site itself could add support for sending rolls to Beyond20, or a different extension could just bridge the gap between that site and beyond20.
