### ISSUE TITLE
Damage not updating to VTT

### ISSUE THREAD

**Issue by angel37701** [kakaroto/Beyond20#1057]
With the option chosen in the settings to update the damage from DNDBeyond to Roll20 via beyond20s interface it's not working. Several players in campaigns for several weeks have been having tie issue. 

We have redone the extension, we have redone the option, and it will not update.

**Comment by Aeristoka** [comment]
Can you please post a screenshot of where you're clicking in DnDBeyond, and what, if anything, happens in Roll20?

**Comment by kakaroto** [comment]
Not sure I understand if the question is "update the HP" (of the character sheet) or "Roll the damage" (from an attack roll). As it is, "update the damage" doesn't really make sense to me, so I'm not sure what it is you're asking.

If it's about updating the HP. Have you followed the instructions from this FAQ here: https://beyond20.here-for-more.info/faq#my-hp-from-dd-beyond-doesnt-synchronize-to-my-tokens ?

**Comment by kakaroto** [comment]
Closing stale issue. If you're still encountering the issue, please re-open and provide additional information as requested above.
