### ISSUE TITLE
Otherworldly Glamour for Fey Wanderer is being added twice

### ISSUE THREAD

**Issue by MonarchCDN** [kakaroto/Beyond20#1059]
The bonus for Otherworldly Glamour is added automatically by D&D Beyond but the extension seems to be adding it a second time.

This is the character sheet that I observed this on: [ddb.ac/characters/97117985/TKasyI](url)

**Comment by Aeristoka** [comment]
Already cleaned up here (but not in an official release yet).

Was another instance of DnDBeyond not implementing something, Beyond20 covering it, then DnDBeyond (finally) slipping it in.
