### ISSUE TITLE
Suggestion: Allow whispering death saves to GM

### ISSUE THREAD

**Issue by KWall24** [kakaroto/Beyond20#1061]
Wondering if an option could be added to allow whispering death save rolls to the GM instead of rolling publicly. Makes things a bit more exciting.

**Comment by Aeristoka** [comment]
![image](https://user-images.githubusercontent.com/7988297/230209665-1bddc3b9-61d5-490f-869b-6309ab3aeb0b.png)

All you'd need to do is set up hotkeys like that in Beyond20.
