### ISSUE TITLE
Incorrect Parsing of Aasimar Healing Hands Roll

### ISSUE THREAD

**Issue by imnotpete** [kakaroto/Beyond20#1063]
**Describe the bug**
A 1st-level Aasimar's Healing Hands ability is 2d4 (d4 x proficiency). Beyond20 is only highlighting the `d4` portion, and rolling `1d4` when clicked.

**To Reproduce**
1. Create a 1st-level Aasimar character in DndBeyond
2. Scroll to the "Healing Hands" action
3. Click on the 2d4 roll to roll it
4. It only roles 1d4

**Expected behavior**
It should roll 2d4

**Screenshots**
<img width="962" alt="image" src="https://user-images.githubusercontent.com/11043/236583653-897abf60-3704-4f79-8ec3-363b40fe0f10.png">

It also says this if I hover over the `2` in that `2d4`:
<img width="581" alt="image" src="https://user-images.githubusercontent.com/11043/236583850-c40d24ef-7bc9-4200-b698-14eba5975269.png">

**Browser Info (please complete the following information):**
 - Browser - Chrome
 - Version - 113.0.5672.64 (Official Build) (64-bit)

<img width="761" alt="image" src="https://user-images.githubusercontent.com/11043/236583945-483d3d8f-6f77-4dab-8325-a7e0c7ed4c58.png">

**Additional Context**
Example character: https://www.dndbeyond.com/characters/99920782

**Comment by Aeristoka** [comment]
@kakaroto , they screwed up their formatting again...

@imnotpete basically what you've found is another instance of DnDeyond formatting dice formulas differently everywhere. It gives @kakaroto depression trying to figure out the parsing.

**Comment by kakaroto** [comment]
argg, yeah, reminds me of the fighter's second wind, will need to do some magic trickery to find the right number of dice from the previous text.
Thanks for the report!
