### ISSUE TITLE
Fey Wanderer Ranger doubling bonus (fixed, but not in an official release yet)

### ISSUE THREAD

**Issue by AtomicStick** [kakaroto/Beyond20#1064]
I know this was reportedly fixed by #1050, but it seems to be happening again. Any charisma based roll, whether a straight CHA roll or a CHA-based skill roll, is getting the +2 from Otherworldly Glamour added 2x. 

The character sheet already shows the expected extra +2 in the bonus (and correctly doesn't show it with attribute bonuses) but when this is rolled Beyond20 is adding an additional +2.

**Comment by AtomicStick** [comment]
Ah, I see. Built the extension from source and the issue went away. Thanks.

**Comment by Aeristoka** [comment]
> Ah, I see. Built the extension from source and the issue went away. Thanks.

Yep, that's the way to get the fix right now.

**Comment by Aeristoka** [comment]
> Ah, I see. Built the extension from source and the issue went away. Thanks.

Actually also this: https://github.com/kakaroto/Beyond20#developer-mode-installation

**Comment by kakaroto** [comment]
> 
> I'm going to hold this open so we stop having this issued submitted over and over.
> 
Good idea!

> @kakaroto we might want a 2.8.1 to include the few fixes since 2.8.0 came out.

Humm... not a bad idea, though I'd prefer to just do a coding binge and release 2.9.0. I'll try to get to it next week after the Foundry v11 release mayhem that we're currently in.

**Comment by kakaroto** [comment]
Beyond20 2.9.0 was just released (pending review on the Chrome, Firefox and Edge stores), which brings this fix to the masses.
Thanks for your patience!
