### ISSUE TITLE
Staff of Striking

### ISSUE THREAD

**Issue by jackshoegazer** [kakaroto/Beyond20#1067]
When using the Staff of Striking, when I click the HIT/DC button, the weapon information details are sent to the VTT instead of rolling to hit.

**To Reproduce**
1. Equip and attune to Staff of Striking
2. Click on the HIT/DC to roll to hit with it.
3. See error: no roll, just descriptor text.

**Expected behavior**
Normally, like with any other weapon, the B button rolls the to-hit dice and then give the option to roll damage. This instead only shows the item descriptor text.

**Screenshots**
<img width="1435" alt="Screen Shot 2023-06-06 at 9 30 32 AM" src="https://github.com/kakaroto/Beyond20/assets/135714690/7419e09f-b9f8-418d-9cdd-73a53591a1b8">
<img width="1430" alt="Screen Shot 2023-06-06 at 9 29 53 AM" src="https://github.com/kakaroto/Beyond20/assets/135714690/199e0c65-b612-42a7-9700-efdf578db5a9">

**Browser Info (please complete the following information):**
Chrome Version 113.0.5672.126

**Additional context**
Add any other context about the problem here, such as a link to the character sheet or D&D Beyond page that shows the problem.

**Comment by kakaroto** [comment]
As you can see from your own screenshot, the side panel in D&D Beyond does not show any details about the to-hit value or damages, etc... This is an issue with the information in D&D Beyond.
See FAQ entry for more details: https://beyond20.here-for-more.info/faq#why-doesnt-beyond20-allow-me-to-make-a-melee-attack-with-my-magic-staffs
