### ISSUE TITLE
Great weapon master not calculating -5 when rolling with advantage

### ISSUE THREAD

**Issue by jonweng** [kakaroto/Beyond20#1068]
**Describe the bug**
Great weapon master not calculating -5 on attack roll when rolling with advantage

**To Reproduce**
1. Flip on great weapon master in extension
2. Go to dndbeyond character sheet>attack
3. Right click and select advantage and roll
4. Look in roll20 to check result
5. Roll will not take the -5 to account and Formula will not include the -5

**Expected behavior**
Roll should include -5

**Browser Info (please complete the following information):**
 - latest version of chrome

**Comment by Aeristoka** [comment]
@jonweng So you're using the DnDBeyond Digital Dice version of advantage there. I don't recommend that. The default Hotkey in Beyond20 for Advantage rolling is Shift+Click on the desired roll (that's far better).

@kakaroto Remind me if Beyond20 is able to interoperate with this Digital Dice nonsense stuff in this way.

**Comment by Aeristoka** [comment]
@jonweng there's your answer.
