### ISSUE TITLE
Add support for healing NPC attacks

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#1070]
NPC attacks only recognize damage from the "X damage" regexp.
We could add also "regains X hit points" as a recognizable one for Healing damage.
Example in the Unicorn: https://www.dndbeyond.com/monsters/17042-unicorn

**Comment by ofMoons** [comment]
Hey @kakaroto!  I have an initial basic implementation of this on my own fork that I'd be happy to submit for your review if you're interested.  😊

**Comment by kakaroto** [comment]
> Hey @kakaroto! I have an initial basic implementation of this on my own fork that I'd be happy to submit for your review if you're interested. 😊

That's awesome, thanks! Yes, definitely interested, and I just took a peak at your commit in your fork, and it looks good to me, so please do send it as a PR!
Thanks again for the contribution :)
