### ISSUE TITLE
Suggestion:  Add "Max Normal Damage" as a Critical damage option

### ISSUE THREAD

**Issue by zfreek98** [kakaroto/Beyond20#1077]
**Is your feature request related to a problem? Please describe.**
No; existing crit rules function without issue.

**Describe the solution you'd like**
I've played in two campaigns now that don't like extra damage for critical strikes and instead, rule that crits automatically deal the maximum damage for a normal roll instead.  Can this option be added to the existing options? 

**Describe alternatives you've considered**
Simple change; no alternatives considered.

**Additional context**
None.

Thanks!

**Comment by Aeristoka** [comment]
Beyond20 policy is that no further Critical options will be added. Unless @kakaroto has decided to change that.

**Comment by kakaroto** [comment]
Isn't that exactly what the "perfect rolls" homebrew rule does?

![image](https://github.com/kakaroto/Beyond20/assets/27990/a5cbf42b-44be-450f-be2f-0ee7f4a764c4)

**Comment by zfreek98** [comment]
@kakaroto - Negative.  "Perfect Rolls" totals up max damage PLUS rerolling all damage dice.

**Comment by zfreek98** [comment]
More specifically, it rolls damage, then adds maximum dice damage to the roll.  If your attack's damage roll is 1d6+4, it rolls that as well as adding 6, for a possible 16 damage.  "Max Normal Damage" would simply treat crits as 6+4 on a 1d6+4 roll. 

I suppose this is where calling that feature "Perfect Rolls" can be kind of confusing.  :)
