### ISSUE TITLE
Track health (and other attributes) in Token Bars

### ISSUE THREAD

**Issue by jstephens7** [kakaroto/Beyond20#1078]
**Is your feature request related to a problem? Please describe.**
I see heath is being tracked somewhere within the extension [here](https://github.com/kakaroto/Beyond20/blob/master/FVTT-module/beyond20/beyond20.js#L52). I was wondering:

1. Is this being tracked somewhere already? If yes,
2. Is there some configuration that needs to be done to ensure it's tracked properly?
3. Can we track it in the token bars? This seems like it would be an obvious place to track these stats.

**Describe the solution you'd like**
Double click on the character token, set bar 1 to actorData.attributes.hp.value / actorData.attributes.hp.max.

**Describe alternatives you've considered**
I think this isn't too hard to do manually, but it seems like something that could be added to the extension.
If it is tracked somewhere else, just let me know.

**Additional context**

![Token settings](https://github.com/kakaroto/Beyond20/assets/13037114/ff1379cb-90e6-4a86-829f-d2da3dc712e3)

**Comment by Aeristoka** [comment]
Already a feature: https://beyond20.here-for-more.info/faq#my-hp-from-dd-beyond-doesnt-synchronize-to-my-tokens

**Comment by jstephens7** [comment]
Thanks!
