### ISSUE TITLE
Rage damage not being added to custom attacks

### ISSUE THREAD

**Issue by stumueller** [kakaroto/Beyond20#1081]
**Describe the bug**
Our DM uses a custom crit rule. So I have added a custom action to my dndbeyond sheet to account for this custom crit rule. I have modified it to be a melee attack using str, and it adds the damage modifier specified by the rule. It works fine in its self and will roll critical damage correctly, but when I toggle the rage button in beyond20 rage is not added to this damage. It is added as normal to the rest of my attacks but not this one custom action.

**Expected behavior**
Rage damage is applied to my custom action

**Comment by Aeristoka** [comment]
https://www.dndbeyond.com/classes/barbarian#Rage-51

Beyond20 supports all OFFICIAL things on DnDBeyond. There is specific parsing that Beyond20 does to make sure those are all caught. Beyond20 will not support every custom action that can be created on DnDBeyond.

**Comment by kakaroto** [comment]
Rage rules says when you make a **melee weapon attack**. If you want it to add Rage to it, make a custom melee weapon, not a custom action.
