### ISSUE TITLE
Chat errors on character inputs

### ISSUE THREAD

**Issue by cahudson94** [kakaroto/Beyond20#1083]
**Describe the bug**
When attempting to user certain characters in the chat window they are refused with an error message of "Cannot read properties of undefined (reading '0')"

**To Reproduce**
1. Go to 'Chat Messages'
2. Click on 'The chat input box'
3. Type a message including a character such as "<" or ">"
4. Submit message to see error

**Expected behavior**
The greater than and less than characters should be aloud in regular chat and I am not positive this issue is limited to those two, but that is as far as my testing has found so far.

**Browser Info (please complete the following information):**
 - Browsers tested include both Chrome and Firefox
 - Versions: Chrome - 115.0.5790.171, Firefox - 116.0.2
 - The above message is reflected both in the UI and the dev tools

**Additional context**
This is new behavior since an update from Version 10 to 11.

**Comment by Aeristoka** [comment]
> **Describe the bug** When attempting to user certain characters in the chat window they are refused with an error message of "Cannot read properties of undefined (reading '0')"
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'Chat Messages'
> 2. Click on 'The chat input box'
> 3. Type a message including a character such as "<" or ">"
> 4. Submit message to see error
> 
> **Expected behavior** The greater than and less than characters should be aloud in regular chat and I am not positive this issue is limited to those two, but that is as far as my testing has found so far.
> 
> **Browser Info (please complete the following information):**
> 
> * Browsers tested include both Chrome and Firefox
> * Versions: Chrome - 115.0.5790.171, Firefox - 116.0.2
> * The above message is reflected both in the UI and the dev tools
> 
> **Additional context** This is new behavior since an update from Version 10 to 11.

Did you mean to post this to DnDeyond? This is Beyond20.

**Comment by cahudson94** [comment]
Whoops no foundry thank you!

**Comment by Aeristoka** [comment]
> Whoops no foundry thank you!

Well that's a new one to be mistaken for 😄

**Comment by cahudson94** [comment]
I was looking at both because there is a potentially related issue stopping rolls from coming through.
