### ISSUE TITLE
Missing space at damage type description of magical Items

### ISSUE THREAD

**Issue by BuehrerMassimo** [kakaroto/Beyond20#1085]
**Describe the bug**
When rolling damage with a magical item that has modifiers there is a missing space between the damage type and the details text of the damage modifier.

**To Reproduce**
1. Use magical item that has damage modifiers
2. Roll the damage and see the result in the VTT
3. Damage type will be displayed as follows: Type(details) Damage

**Expected behavior**
Expect at step 3 to display as follows: Type (details) Damage

**Screenshots**
To help explain your problem, add screenshots of where you clicked in D&D Beyond, a screenshot of your Beyond20 character settings if applicable and the result you saw in the VTT.

**Browser Info (please complete the following information):**
 - Browser [Chrome]
 - Version [117]

**Additional context**
<img width="146" alt="image" src="https://github.com/kakaroto/Beyond20/assets/60383431/19b0339c-00ce-4d01-af62-403fb3e1842b">
<img width="65" alt="image" src="https://github.com/kakaroto/Beyond20/assets/60383431/f5a56f41-4ce0-4ace-9e3a-45dbc80b1f5d">

**Comment by Bracciata** [comment]
Made fixes on this!
