### ISSUE TITLE
D20 at Advantage Summing instead of Choosing a Value

### ISSUE THREAD

**Issue by Aerosaurusrex** [kakaroto/Beyond20#1087]
Whenever one of my players rolled a d20 at advantage using Chrome browser and beyond 20 to roll from Dnd Beyond to Roll20, the result summed the two results because they were they same value. ~6,6~+5 instead of ~6~6+5 to strike out the "lower" value. 

**To Reproduce**
1. Using Chrome
2. Using Roll 20
3. Using Beyond 20
4. Roll a d20 at advantage until you see two values that are the same (meaning you roll two 3's or two 4's)

**Expected behavior**
The value should add together instead of selecting the higher of the two. 

**Screenshots**
<img width="297" alt="image" src="https://github.com/kakaroto/Beyond20/assets/84945888/7c83c87f-7927-43b7-b75a-506116026519">

**Browser Info (please complete the following information):**
 - Browser Chrome
 - VTT Roll20

**Additional context**
https://www.dndbeyond.com/characters/110645336 the offending character sheet

**Comment by IsaacAbramowitz** [comment]
Also the character sheet you linked is private or campaign only. It needs to be public otherwise we get redirected to a 403 page.
