### ISSUE TITLE
Cleric: Death Domain: Circle of Mortality is labeled

### ISSUE THREAD

**Issue by ILikeLions** [kakaroto/Beyond20#1088]
**Describe the bug**
This feature is not part of the Death Domain; it is part of the Grave Domain.  This is a very minor issue that should not take long to fix.

**To Reproduce**
1. Go to any character page
2. Click on Beyond20 button
3. Click on More Options
4. Scroll down to and click on Set Hotkeys
5. Set a random hotkey, doesn't matter which
6. Scroll selection box down to Cleric: Death Domain: Circle of Mortality
7. See error

**Expected behavior**
This error is simply a mislabel.

**Screenshots**
![Beyond20 bug](https://github.com/kakaroto/Beyond20/assets/115727107/ee93b0c8-b512-4f2c-a245-dc89865b3226)

**Browser Info (please complete the following information):**
 - Vivaldi
 - 6.2.3105.58

**Additional context**
N/A

**Comment by Bracciata** [comment]
I have made the code change for this
