### ISSUE TITLE
[Proposal] Add Roll History Button for Individual Character Sheets

### ISSUE THREAD

**Issue by Setnour6** [kakaroto/Beyond20#1095]
### Are you willing to contribute to the feature?

No, due to IRL commitments.

### Is your feature request related to a problem? Please describe.

Yes. What upsets me is that when I am not in a DNDB campaign (i.e. IRL with DNDB character sheets), I am not able to access my roll history, and can only do that when my character sheet is linked to a campaign.

### Describe the solution you'd like

This proposal intends to have a roll log specific to the character sheet, with a maximum of 10 rolls (can be customized up to a hard maximum of 50) appearing in the history. It can use the same UI from the given game log found in DNDB campaigns, or can use a custom or other UI.

### Describe alternatives you've considered

You can make a button appear near the dice button (bottom left) or somewhere else you prefer that says "history" or "show history".

Another alternative would be to make the history link with all created character sheets, essentially preventing the individuality of the feature. In that case, the name of the character in the sheet and the character sheet ID (found in the URL) would (also) appear.

### Additional context

Useful for non-party-campaign players (those with character sheets not linked to digital campaigns) and testing with rolls and trying not to forget what roll you rolled on initiative for example. I, myself, am a hybrid player.

**Comment by Aeristoka** [comment]
You should be asking DnDBeyond, not the Beyond20 Extension for this. Nothing we can do about this.

**Comment by Setnour6** [comment]
> You should be asking DnDBeyond, not the Beyond20 Extension for this. Nothing we can do about this.

What came to my mind was that the extension could provide it since it is, of course, an extension. There was a thread about it but it got discontinued. The answer was that it already exists for campaigns. I figured here was a good place to ask but I suppose asking DNDB staff might be the best option now.

**Comment by Aeristoka** [comment]
Literally something we can't do, because of how Beyond20 works. DnDBeyond are the ONLY ones who can.

**Comment by Setnour6** [comment]
> Literally something we can't do, because of how Beyond20 works. DnDBeyond are the ONLY ones who can.

I made a new thread there. Link: https://www.dndbeyond.com/forums/d-d-beyond-general/d-d-beyond-feedback/186530-proposal-add-roll-history-button-for-individual

**Comment by kakaroto** [comment]
It's a good idea, but unfortunately outside the scope of our extension, as Aeristoka mentioned before. You're not the first one though to mention this as an issue with DDB, so I hope that accept the suggestion and implement it.
Good luck!
