### ISSUE TITLE
Barbarian: Wild Magic / Wild Surge

### ISSUE THREAD

**Issue by DJBunge** [kakaroto/Beyond20#1100]
The roller shows the number rolled, but does not show any of the additional information.

I think this is a newer option for the Barbarian class, but I think it could work similarly to the Sorcerer's Wild Magic (assuming that's implemented).

**Comment by kakaroto** [comment]
It depends, if you click on the `d8` to roll it, it will only roll the d8, but if you click on the "Roll table" button above it, it will roll the actual roll table.
Notice the roll icon and button above the actual table
![image](https://github.com/kakaroto/Beyond20/assets/27990/aff1afe0-6de2-4375-8809-09b735b1084c)

As an example (clicked on the d8 once and on the roll table button twice):
![image](https://github.com/kakaroto/Beyond20/assets/27990/677a4a80-8d02-4861-8241-1915f45b6f77)
and on Roll20:
![image](https://github.com/kakaroto/Beyond20/assets/27990/617fc611-1bd8-4fd2-a559-cfd7314bd357)
