### ISSUE TITLE
A digital dice roll with adv/disadv of a skill/save that has +0 modifier does not get sent

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#1101]
Create a skill that has +0 modifier and right click on the skill button to roll the digital dice with advantage or disadvantage. It will throw an error and will not send the roll result to the VTT:
![image](https://github.com/kakaroto/Beyond20/assets/27990/c3299869-b171-4110-a0ba-3d55a51aa86f)

**Comment by IsaacAbramowitz** [comment]
This is pretty normal that Beyond20 doesn't work when right clicking and rolling with adv/disadv.
The way you're supposed to do it is to roll using the hotkeys. By default when you hold shift and click it rolls with advantage and ctrl click for disadvantage.

**Comment by kakaroto** [comment]
> This is pretty normal that Beyond20 doesn't work when right clicking and rolling with adv/disadv. The way you're supposed to do it is to roll using the hotkeys. By default when you hold shift and click it rolls with advantage and ctrl click for disadvantage.

I'm aware :) But it should still work (and it does for any skill that has a modifier other than 0) and I confirmed that this is a bug in the code.
You can read the full thread about the investigation here: https://discord.com/channels/578874022968688640/579077147994488862/1201544314178768896
