### ISSUE TITLE
Sharpness

### ISSUE THREAD

**Issue by drmindsmith** [kakaroto/Beyond20#1105]
When the die roll is a 20, it's supposed to add 14 to the weapon damage. However, for all versions of the swords of sharpness, it's porting +14 on _every _roll._

DDB doesn't do that - never actually adds the +14 at all. It only happens when the B20 extension is running. 

(Chrome, PC, new versions, up to date, etc...)

**Comment by kakaroto** [comment]
Beyond20 doesn't understand how specific weapons function, it is only rolling the damages as reported by D&D Beyond. As you can see on Roll20:
![image](https://github.com/kakaroto/Beyond20/assets/27990/8901da22-3fe5-4c9a-865c-fd9d4e75c112)
or on Foundry:
![image](https://github.com/kakaroto/Beyond20/assets/27990/e0eae5d8-1b56-4f7b-a5df-0a77d85072ed)

In both cases, it does specify the condition ("20 On the Attack Roll") for the specific damage to apply. 
There's always going to be all sorts of conditional damages, and it is always the job of the player to make sure they calculate their actual damage based on the condition of play. In some situations it's extra damage if you have more than 2 enemies around you, or if the terrain is wet, etc... Beyond20 cannot understand those concepts.
Even though "the dice roll was a 20" is a concept that Beyond20 can understand, we don't have AI to parse that damage restriction to actually understand what it should do, and also, most people roll with double to hit (and take the first result, or take the high/low based on whether it's advantage/disadvantage according to the situation), and in that situation, we wouldn't be able to know which of the dice to actually apply.
