### ISSUE TITLE
Weapon attacks and damage do not roll, but show descriptions only

### ISSUE THREAD

**Issue by ianfhunter** [kakaroto/Beyond20#1107]
**Describe the bug**
Instead of rolling attacks and damage on their own, the description of the item is posted.

**To Reproduce**
Start a game as usual, press the hoverover on your attack roll to roll. Observe error in Roll20
Press damage roll, see error again.

**Expected behavior**

I expect to see dice rolls, but instead I see just the description of the objects

**Screenshots**
To help explain your problem, add screenshots of where you clicked in D&D Beyond, a screenshot of your Beyond20 character settings if applicable and the result you saw in the VTT.

**Browser Info (please complete the following information):**
 - Browser [e.g. chrome, firefox] Chrome / Brave
 - Version [e.g. 85] latest, 24/04/2024
 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT

(DnDBeyond)
![image](https://github.com/kakaroto/Beyond20/assets/1540737/26f9182e-9098-4a4c-831b-13d0bf5fec5e)

(Roll20)
![image](https://github.com/kakaroto/Beyond20/assets/1540737/4805a684-5700-4fd5-a977-914b9141a52a)

**Additional context**
Add any other context about the problem here, such as a link to the character sheet or D&D Beyond page that shows the problem.
[www.dndbeyond.com-1713984036631.log](https://github.com/kakaroto/Beyond20/files/15098994/www.dndbeyond.com-1713984036631.log)

**Comment by Rub-A-Duck** [comment]
+1 to this. Was about to open a post myself.
![firefox_YewCbti7kn](https://github.com/kakaroto/Beyond20/assets/168023904/b575b1e0-b78a-4ddb-b8ba-3c792d74033a)

**Comment by GregRivo** [comment]
+1 - all weapon attack rolls and damage are not working. Weirdly, spells are working.

![image](https://github.com/kakaroto/Beyond20/assets/6144885/2e3a9957-6441-43b1-a14b-de587450287d)

**Comment by ChibiScipio** [comment]
+1 - Same thing happening here on D&D Beyond and Roll20 / AboveVTT 

![image](https://github.com/kakaroto/Beyond20/assets/168026252/1bd2c3f8-1707-4da9-9e00-620d4383e72f)

**Comment by hexates** [comment]
I am also experiencing this error

**Comment by Ravioli133** [comment]
Same here - Spells and other dice rolls seem to be working but any weapon attacks are same as above

**Comment by Nak-kun** [comment]
Same for me. Any weapon attack and damage and the unarmed strike just show the description. Spells and other kind of attack work just fine.

**Comment by kakaroto** [comment]
Hi everyone. Yes, I am well aware of the issue. D&D Beyond changed their website today which broke pretty much everything. You don't all need to confirm you're seeing the issue, I'm currently working on figuring out how to get it fixed, please be patient.

**Comment by kakaroto** [comment]
This should be fixed now in the development version (See [here](https://github.com/kakaroto/Beyond20#developer-mode-installation)).
Still requires extensive testing. Will reopen this issue and keep it open until I make an actual release, so newcomers can find the issue and not open a duplicate one.

**Comment by cweatherby** [comment]
Thanks for the quick turnaround - I'm trying out the development build version now and it does appear to be working properly for weapon action attacks and damage rolls properly. Have not _yet_ encountered any other issues with it.

> This should be fixed now in the development version (See [here](https://github.com/kakaroto/Beyond20#developer-mode-installation)). Still requires extensive testing. Will reopen this issue and keep it open until I make an actual release, so newcomers can find the issue and not open a duplicate one.

**Comment by kakaroto** [comment]
Version 2.9.2 was released and is now available on the Chrome Store.
Closing the ticket, thanks all!

**Comment by Kodokbotak** [comment]
> Version 2.9.2 was released and is now available on the Chrome Store. Closing the ticket, thanks all!

Hi, are you currently working on the firefox version? because i use firefox instead of chrome

Thank you in advance

**Comment by kakaroto** [comment]
> Hi, are you currently working on the firefox version? because i use firefox instead of chrome
> 
> Thank you in advance

The release was sent to all 3 stores, Chrome, Firefox and Edge. Chrome has reviewed and approved it after 35 minutes, while Firefox and Edge are still under review. I have no control over their review process or how long it would take before the new update is made available on their stores. I've seen it take from 1 hour to 1 week in the past. Firefox used to be very fast (a couple of minutes to approve new releases) but they changed their procedures in the recent year and now it takes a bit longer. I hope they'll approve it within a day 🤞

**Comment by Kodokbotak** [comment]
Hi, this bug is happening again

**Comment by djwilki** [comment]
Yep, bug is happening again in google chrome.

**Comment by matt12389** [comment]
yeah, it's beck

**Comment by ApeXMinded** [comment]
Yep, came back. Just signal boosting and also to ask if there's any consideration to making a version specifically for Opera GX. I know Opera works on the same basis as Chrome, but it's a little tiring to get multiple pop-ups reminding me that im not "using the preferred Browser" every time I open the page or try to do anything.

**Comment by Kodokbotak** [comment]
Guess who's back....back again..the bug's back, tell a friend

**Comment by jtbg** [comment]
#1133 patches it this time

**Comment by kakaroto** [comment]
And it's fixed again in the dev version! I'll release an update later tonight if I can.


> Just signal boosting and also to ask if there's any consideration to making a version specifically for Opera GX

My best/detailed answer to that question is here: https://github.com/kakaroto/Beyond20/issues/1052#issuecomment-1401204448

**Comment by kakaroto** [comment]
> May i ask where to download the dev version? thank you!

Sure, the instructions are in the README of the project: https://github.com/kakaroto/Beyond20#developer-mode-installation

**Comment by SelikBready** [comment]
Same problem again!
