### ISSUE TITLE
2.9.2 not on firefox extensions yet

### ISSUE THREAD

**Issue by SuperichIRo-07** [kakaroto/Beyond20#1114]
Hello, do you know when 2.9.2 will be available for Firefox users?  The current version on their addons page is still 2.9.1

**Comment by kakaroto** [comment]
The update was submitted to Firefox, Edge and Chrome at the same time. Chrome released it after 35 minutes, but FF and Edge are still "pending review".
We have no information on how long it will take for them to approve it and it is entirely out of our control unfortunately.

**Comment by cgplayer2000** [comment]
Just FYI – I'm using Beyond20 v2.9.2 in Edge right now.  Not sure when it was approved.
________________________________

**Comment by kakaroto** [comment]
> Just FYI – I'm using Beyond20 v2.9.2 in Edge right now. Not sure when it was approved.

You might have installed it on Edge but from the chrome store, because on the edge store, it's not yet approved, I've just checked the developer portal:

![image](https://github.com/kakaroto/Beyond20/assets/27990/2121914b-de75-4d90-8cdf-1015e8167ec4)

**Comment by SuperichIRo-07** [comment]
Thanks for the quick response, ill just use chrome until FF gets approved.

**Comment by cgplayer2000** [comment]
tbh, I guess I didn't know that there was a difference.  🙂

Thanks for letting me know.
________________________________

**Comment by kakaroto** [comment]
Firefox has made public the 2.9.2 release on their store! You can now update.
Thanks for your patience.
