### ISSUE TITLE
Dice formulas and Roll Buttons not appearing in stat blocks in side panel

### ISSUE THREAD

**Issue by ArsonKoala** [kakaroto/Beyond20#1116]
Dice formulas and roll buttons are no longer appearing on stat blocks in side panel of character sheet. Not working for summoned/misc/wildshapes.

**To Reproduce**
1. Go to 'Extras' in character sheet.
2. Click on any summoned creature/wildshape to bring up stat block in side panel.
3. No dice formulas or roll buttons

**Expected behavior**
Dice formulas and roll buttons should appear in stat blocks

**Screenshots**
![image](https://github.com/kakaroto/Beyond20/assets/140349395/6d6c40fa-53e2-411b-9db5-986225e67144)
![image](https://github.com/kakaroto/Beyond20/assets/140349395/453751d2-5210-4315-8d5b-e3221a7efc0a)
![image](https://github.com/kakaroto/Beyond20/assets/140349395/05e701a3-73c8-47ca-be1c-762232053f34)
![image](https://github.com/kakaroto/Beyond20/assets/140349395/df12cc3e-c61b-48ab-b6f7-d3c40bb7862b)

**Browser Info (please complete the following information):**
 - Firefox
 - Version 125.0.2 (64-bit)
 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT

**Additional context**
Applicable settings are turned on. Works on stat blocks outside of character sheet.

**Comment by kakaroto** [comment]
Please see https://github.com/kakaroto/Beyond20/issues/1110#issuecomment-2078516667 for a description of the issue and solution.

**Comment by kakaroto** [comment]
Firefox has made public the 2.9.2 release on their store! You can now update.
Thanks for your patience.
