### ISSUE TITLE
Talespire

### ISSUE THREAD

**Issue by RabidFlea** [kakaroto/Beyond20#1120]
Updated to the latest version of Beyond20 after which I can no longer roll the dice and have it appear in Talespire using dndbeyonds character sheet. There is no Talespire URL that I can find to connect to which I thought might have fixed the problem. If you have any questions that might assit you feel free to ask.

ajbtac1968@gmail.com
Andrew

**Comment by dmportella** [comment]
same issue as this one - https://github.com/kakaroto/Beyond20/issues/1119

**Comment by kakaroto** [comment]
I'm not sure what Talespire you're referring to, but Beyond20 doesn't support it, we only support Roll20, Foundry and Discord.
You may be using a different extension which integrates with Beyond20 and takes the rolls from Beyond20 and sends it to Talespire. I suggest you check with the most recent version of Beyond20 (which was just released) and whatever other Talespire specific extension you may have.
