### ISSUE TITLE
Rolling a save, initiative, or standard ability check does not add modifier

### ISSUE THREAD

**Issue by andrewgreene** [kakaroto/Beyond20#1121]
**Describe the bug**
Clicking in D&D Beyond using the Beyond20 extension to roll a save, a regular/standard ability check (STR, DEX, CON, etc) or initiative does not add any modifier or shows NaN as the modifier. I have tested this in both Chrome and Firefox on Windows and OS X.

**To Reproduce**
1. Go to a character sheet
2. Click on a save, initiative, or ability check (STR, DEX, *not* a skill such Acrobatics)
3. Review the resulting Beyond20 output

**Expected behavior**
A d20 roll that includes the associated modifier

**Screenshots**
To help explain your problem, add screenshots of where you clicked in D&D Beyond, a screenshot of your Beyond20 character settings if applicable and the result you saw in the VTT.

<img width="289" alt="Where I clicked" src="https://github.com/kakaroto/Beyond20/assets/2809602/703e6355-e3c4-450a-9dca-45412cd3adf5">

<img width="502" alt="Result - note the empty parens" src="https://github.com/kakaroto/Beyond20/assets/2809602/f2e46626-0833-4284-9c59-d6df8b8e80fc">

**Browser Info (please complete the following information):**
- Chrome and Firefox
- Windows and OS X
- Beyond20 v2.9.2

**Additional context**
Add any other context about the problem here, such as a link to the character sheet or D&D Beyond page that shows the problem.

Character sheet: https://www.dndbeyond.com/characters/66042991/FfO3U3

**Comment by dmportella** [comment]
same issue as this one - https://github.com/kakaroto/Beyond20/issues/1119

**Comment by ChromeDrifter** [comment]
This bug absolutely wrecked our planned session last night. Can't see a fix if D&D Beyond keep mucking about like this. Switched off Beyond20 and everything worked again. Doesn't really help with the link to Roll20 though...

**Comment by kakaroto** [comment]
Fixed in https://github.com/kakaroto/Beyond20/commit/0f32df0637dd3f03b49ec94f5606ae7cfe7e69d5
Version 2.9.3 was just released (pending approval on browser stores) with the fix. See: https://www.patreon.com/posts/beyond20-v2-9-3-104033738
