### ISSUE TITLE
Rage/Crimson Rite/Similar Setings - A mix of enhancement and also a bug?

### ISSUE THREAD

**Issue by Lunasmeow** [kakaroto/Beyond20#1122]
I can't ever seem to use these toggles. I set the toggle to "permanent" for the on/off setting in the add-on, and I verify the key to turn the toggle on or off, but I can never tell if the thing is _**actually on**_ before rolling damage!

It would be _**much**_ better if in addition to a "press x key to activate" there was the option to just press a literal toggle in the settings that actually _**showed**_ that it was on or off.

Also, I can't seem to get the extra damage from Crimson Rite to actually show up at all in roll20 - and I can't be sure if it's a bug with the feature being "on" but not reporting the extra damage, or if it's a situation of it not being on at all, and the bug is that my custom button I chose not registering to activate the abilities.

I'm a mix of Paladin and Blood Hunter, so it's entirely possible that the additional damage (radiant) I get from Paladin is somehow not allowing the additional damage from Blood Hunter to show up... but I can't be sure and give a nice, accurate bug report, because I can't be certain whether the feature is actually on and not reporting, or off and not turning on!

**Comment by jtbg** [comment]
There is a toggle in the extension dropdown, does it appear for you?

![image](https://github.com/kakaroto/Beyond20/assets/10716475/6c6b9d46-e72c-49ef-847a-7fc009d93af3)

**Comment by Lunasmeow** [comment]
Okay, I see the toggle, and turned it on, so the damage must not be working. At least for Crimson Rite. I can't confirm for Barbarian at the moment.

**Comment by kakaroto** [comment]
> The only issue I can see with that is as a fix is for custom classes. Is it possible for the checks to do an either/or check, where they can check for the class _**or**_ the Class Feature?

We don't support "custom classes", and all our checks are based on class+feature name, because some features have the same name but behave differently depending on the class, and often it also depends on the class level itself (for example, the hemocraft die depends on your Bloodhunter level, so if you have the class feature from a level 1 custom class,, but you're level 10 in another custom class, we'd have no way of knowing where it comes from so if the hemocraft should be a 1d4 or a 1d8 for example)

**Comment by Lunasmeow** [comment]
> > The only issue I can see with that is as a fix is for custom classes. Is it possible for the checks to do an either/or check, where they can check for the class _**or**_ the Class Feature?
> 
> We don't support "custom classes", and all our checks are based on class+feature name, because some features have the same name but behave differently depending on the class, and often it also depends on the class level itself (for example, the hemocraft die depends on your Bloodhunter level, so if you have the class feature from a level 1 custom class,, but you're level 10 in another custom class, we'd have no way of knowing where it comes from so if the hemocraft should be a 1d4 or a 1d8 for example)

Fair enough, makes sense. I didn't expect full support for custom classes - thought maybe it'd just be easy for feature names, but if some features share names (like Unarmored Defence for example) then yeah, it'd be kind of hard.
