### ISSUE TITLE
FireBolt cantrip not pushing to Roll20 (console logs included)

### ISSUE THREAD

**Issue by hsnopi** [kakaroto/Beyond20#1123]
**Describe the bug**
In my character sheet, sorcerer, 
https://www.dndbeyond.com/characters/116173738
i click on any attack and they send the rolls to roll 20 EXCEPT firebolt. For firebolt (cantrip) I can only leverage the right click method and it doesn't send to roll20. 
(ALSO: how do I buy you a beer. I appreciate your work)

**Expected behavior**
when I click the attack boxs for firebolt it should send the result to roll20.

**Screenshots**
To help explain your problem, add screenshots of where you clicked in D&D Beyond, a screenshot of your Beyond20 character settings if applicable and the result you saw in the VTT.
![image](https://github.com/kakaroto/Beyond20/assets/6887293/6fe36c37-a571-484c-bc39-57157a77adcc)

**Browser Info (please complete the following information):**
 - Firefox 126.0
 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT

I rerolled with dev toools open. Looks like a type error... The first roll was a different weapon for comparison as it worked. Feel free to email me or PM me here for more.
--------snip----------------
Has ICID 
<div class="styles_controls__NSnn3">
[gtm.js:1:73](https://www.googletagmanager.com/gtm.js?id=GTM-N3KHV3K%20line%205%20%3E%20eval)
Has ICID 
<div class="ct-sidebar__inner">
[gtm.js:1:73](https://www.googletagmanager.com/gtm.js?id=GTM-N3KHV3K%20line%205%20%3E%20eval)
Has ICID 
<button class="styles_arrows__182cG" aria-label="Hide sidebar">
[gtm.js:1:73](https://www.googletagmanager.com/gtm.js?id=GTM-N3KHV3K%20line%205%20%3E%20eval)
Has ICID 
<span>
[gtm.js:1:73](https://www.googletagmanager.com/gtm.js?id=GTM-N3KHV3K%20line%205%20%3E%20eval)
Has ICID 
<div class="ddbc-combat-attack__label ">
[gtm.js:1:73](https://www.googletagmanager.com/gtm.js?id=GTM-N3KHV3K%20line%205%20%3E%20eval)
Beyond20: Executing panel : ct-action-pane true false false [dndbeyond_character.js:8260:13](moz-extension://9deda99e-da41-4c77-88a3-5aa32488eff9/dist/dndbeyond_character.js)
Beyond20: New side panel is : ct-action-pane [dndbeyond_character.js:9088:21](moz-extension://9deda99e-da41-4c77-88a3-5aa32488eff9/dist/dndbeyond_character.js)
Damage to crits :  1 
Array []
[dndbeyond_character.js:4405:17](moz-extension://9deda99e-da41-4c77-88a3-5aa32488eff9/dist/dndbeyond_character.js)
Beyond20: New side panel is : ct-action-pane [dndbeyond_character.js:9088:21](moz-extension://9deda99e-da41-4c77-88a3-5aa32488eff9/dist/dndbeyond_character.js)
Has ICID 
<div class=" dice-toolbar__dropdown-die">
[gtm.js:1:73](https://www.googletagmanager.com/gtm.js?id=GTM-N3KHV3K%20line%205%20%3E%20eval)
Has ICID 
<div class="dice-die-button" data-dice="d20">
[gtm.js:1:73](https://www.googletagmanager.com/gtm.js?id=GTM-N3KHV3K%20line%205%20%3E%20eval)
Has ICID 
<button class="MuiButtonBase-root MuiBu…tlinedPrimary css-79xub" tabindex="0" type="button">
[gtm.js:1:73](https://www.googletagmanager.com/gtm.js?id=GTM-N3KHV3K%20line%205%20%3E%20eval)
Cookie “Geo” has been rejected for invalid domain. 2 [collector](https://www.dndbeyond.com/cNj12cyX/xhr/api/v2/collector)
Sending message:  
Object { action: "rendered-roll", request: {…}, title: "Unarmed Strike", html: `<div class="beyond20-message"><div class="beyond20-header"><img class="beyond20-character-avatar" src="https://www.dndbeyond.com/avatars/39163/708/1581111423-116173738.jpeg?width=150&height=150&fit=crop&quality=95&auto=webp" title="Unarmed Strike" width="37" height="37"><details><summary><a>Unarmed Strike</a></summary><div class='beyond20-description'>Instead of using a weapon to make a melee weapon attack, you can use an unarmed strike: a punch, kick, head-butt, or similar forceful blow (none of which count as weapons). On a hit, an unarmed strike deals bludgeoning damage equal to 1 + your Strength modifier. You are proficient with your unarmed strikes.</div></details></div><div class='beyond20-roll-result beyond20-roll-cells'><div class="beyond20-roll-cell"><span class='beyond20-tooltip'><span class='beyond20-roll-value beyond20-roll-detail-normal beyond20-roll-total dice-total'>11</span><span class='dice-roll beyond20-tooltip-content'><div class='dice-formula beyond20-roll-formula'>1d20 + 4</div><div class='beyond20-roll-tooltip'><div class='beyond20-roll-dice'><div class='beyond20-roll-dice-formula'>1d20</div><div class='beyond20-roll-dice-rolls'><span class='beyond20-roll-die-result beyond20-roll-detail-normal'>7</span></div></div></div></span></span></div></div><button class="beyond20-button-roll-damages">Roll Damages</button></div>`, character: "Gotchoo", whisper: 0, play_sound: true, source: null, attributes: {}, description: "Instead of using a weapon to make a melee weapon attack, you can use an unarmed strike: a punch, kick, head-butt, or similar forceful blow (none of which count as weapons). On a hit, an unarmed strike deals bludgeoning damage equal to 1 + your Strength modifier. You are proficient with your unarmed strikes.", … }
[dndbeyond_character.js:4012:17](moz-extension://9deda99e-da41-4c77-88a3-5aa32488eff9/dist/dndbeyond_character.js)
Received response :  
Object { success: true, vtt: (1) […], error: null, request: {…} }
[dndbeyond_character.js:5003:13](moz-extension://9deda99e-da41-4c77-88a3-5aa32488eff9/dist/dndbeyond_character.js)
Has ICID 
<span>
[gtm.js:1:73](https://www.googletagmanager.com/gtm.js?id=GTM-N3KHV3K%20line%205%20%3E%20eval)
Has ICID 
<div class="ddbc-combat-attack__label ">
[gtm.js:1:73](https://www.googletagmanager.com/gtm.js?id=GTM-N3KHV3K%20line%205%20%3E%20eval)
Beyond20: Executing panel : ct-spell-pane true false false [dndbeyond_character.js:8260:13](moz-extension://9deda99e-da41-4c77-88a3-5aa32488eff9/dist/dndbeyond_character.js)
Beyond20: New side panel is : ct-spell-pane [dndbeyond_character.js:9088:21](moz-extension://9deda99e-da41-4c77-88a3-5aa32488eff9/dist/dndbeyond_character.js)
TypeError: $(...)[0] is undefined
[dndbeyond_character.js:8489:29](moz-extension://9deda99e-da41-4c77-88a3-5aa32488eff9/dist/dndbeyond_character.js)
    injectRollButton moz-extension://9deda99e-da41-4c77-88a3-5aa32488eff9/dist/dndbeyond_character.js:8489
    documentModified moz-extension://9deda99e-da41-4c77-88a3-5aa32488eff9/dist/dndbeyond_character.js:9089
TypeError: $(...)[0] is undefined
[dndbeyond_character.js:7973:25](moz-extension://9deda99e-da41-4c77-88a3-5aa32488eff9/dist/dndbeyond_character.js)
Beyond20: New side panel is : ct-spell-pane [dndbeyond_character.js:9088:21](moz-extension://9deda99e-da41-4c77-88a3-5aa32488eff9/dist/dndbeyond_character.js)
TypeError: $(...)[0] is undefined[dndbeyond_character.js:8489:29](moz-extension://9deda99e-da41-4c77-88a3-5aa32488eff9/dist/dndbeyond_character.js)
    injectRollButton moz-extension://9deda99e-da41-4c77-88a3-5aa32488eff9/dist/dndbeyond_character.js:8489
    documentModified moz-extension://9deda99e-da41-4c77-88a3-5aa32488eff9/dist/dndbeyond_character.js:9089
----------end snip--------

**Comment by hsnopi** [comment]
} else if (paneClass == "ct-spell-pane") {
        const spell_name = $(".ct-sidebar__heading .ct-spell-name,.ct-sidebar__heading .ddbc-spell-name")[0].firstChild.textContent;

**Comment by kakaroto** [comment]
Hi,
It sounds like you are still on version 2.9.2 of the extension (Firefox addons just approved 2.9.3 today), and were hitting the issue where spells couldn't be rolled since D&D Beyond changed their website last week.
See the release notes of 2.9.3 for more information: https://www.patreon.com/posts/beyond20-v2-9-3-104033738
Thanks!
