### ISSUE TITLE
Rolls still not working

### ISSUE THREAD

**Issue by RandomShawn** [kakaroto/Beyond20#1124]
Broke parsing for spells, making users unable to roll spells, or saving throws/initiative. The issue was known and said it was resolved but I have a lot of my players still having the issue and they had the updated downloaded already

**Comment by kakaroto** [comment]
I'm not seeing any issues with rolling spells and saving throws/initiative. Those are only broken in the older 2.9.2 release. Tell your players to make sure they're on the latest 2.9.3 version (which was approved on the firefox store just a day ago, and on the edge store today.
If necessary, have them export their beyond20 settings, uninstall and reinstall the extension, then restore their beyond20 settings.

**Comment by RandomShawn** [comment]
Will do, if the issues come up again will upload img and repost. Thank you
