### ISSUE TITLE
Straight ability score rolls incorrect for some players

### ISSUE THREAD

**Issue by AKCarter07** [kakaroto/Beyond20#1125]
**Describe the bug**
When rolling a straight Int check: 

- My party member had empty parentheses with no modifier added (they have a +2).
- I had a +2 (I have a +0)

I tested all my straight ability checks, and all of them were incorrect. It looked like the sign was correct, but the number looked like an off-by-one error.
This did not happen when I tried rolling from my party mate's sheet for their character.
This is only happening to two of us.

**To Reproduce**
1.Log into a Foundry server.
2. Log into dndbeyond.
3. Go to a character sheet owned by that dndbeyond account.
4. Roll an ability check.

**Expected behavior**
Expected correct modifier.

**Screenshots**
To help explain your problem, add screenshots of where you clicked in D&D Beyond, a screenshot of your Beyond20 character settings if applicable and the result you saw in the VTT.
<img width="473" alt="clicked" src="https://github.com/kakaroto/Beyond20/assets/107439785/41cb6d09-a002-4b7c-987a-315716e1dbf0">
<img width="277" alt="result" src="https://github.com/kakaroto/Beyond20/assets/107439785/b882f6be-0334-41a0-b1ce-37f727552a34">

**Browser Info (please complete the following information):**
 - Browser Chrome
 - Version 125.0.6422.61 (Official Build) (64-bit)
 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT
   - No errors, but see console snip for the attributes array 
<img width="292" alt="console" src="https://github.com/kakaroto/Beyond20/assets/107439785/81ec9c88-d5ed-4ad9-a934-a4f58e410606">

**Additional context**
These two characters had the problem, however when I rolled on my party member's the numbers were correct, so I don't know if having them is useful.
https://www.dndbeyond.com/characters/63798710
https://www.dndbeyond.com/characters/77589697
This character, on the other hand, rolled fine.
https://www.dndbeyond.com/characters/77586797

**Comment by AKCarter07** [comment]
note, in the foundry screenshot, I rolled the top two rolls (one for Carver, one for Buk), and Buk's player rolled the 2nd roll for Buk.

**Comment by AKCarter07** [comment]
On closer look, my character is getting half-proficiency to straight stat rolls. I'm assuming they're interacting with Jack of All Trades. 
I have no clue what's going on with my party mate's sheet though.

**Comment by kakaroto** [comment]
Hi,
I think your party member with the `()` and no modifier might have been on an older version of Beyond20, as for your own sheet, I didn't have the "issue" until I got Beyond20 to parse your class features, which was a clear indication that it was added it on purpose.
It sounds like it was just a JoT addition
![image](https://github.com/kakaroto/Beyond20/assets/27990/138ae359-96d6-4993-ba3e-d917c3e38e86)

If you don't want it, you can always click the beyond20 icon to disable the JoT modifier on straight ability checks (see last option):
![image](https://github.com/kakaroto/Beyond20/assets/27990/77ae4cf5-0339-4161-9e3b-d7170ef6bda5)
