### ISSUE TITLE
Discord integration failure

### ISSUE THREAD

**Issue by Gryllz90** [kakaroto/Beyond20#1128]
When rolls are clicked on dndbeyond beyond20 fails to send the rolls to discord.
Error says failed to fetch (shown in screenshot below).
No settings have been changed and it has worked for years until tonight.
**Describe the bug**

**To Reproduce**
1. Go to dnd beyond character sheet
2. Click on any dice roll
3. See error 

**Expected behavior**
When expected the roll to be shown in our discord server as previously worked.

**Screenshots**
![image](https://github.com/kakaroto/Beyond20/assets/170768966/17e55885-5caf-4a6c-bc73-bd883125ee95)

**Browser Info (please complete the following information):**
 - Browser - chrome
 - Version 125.0.6422.77
![image](https://github.com/kakaroto/Beyond20/assets/170768966/19066e8c-89c4-46cb-aa62-63f630dd81b5)

**Comment by kakaroto** [comment]
The server had an issue with its certificate, which is why I think this issue occured. I've fixed it since.
Thanks for the report!
