### ISSUE TITLE
Some cantrips cannot be displayed to VTT

### ISSUE THREAD

**Issue by Kodokbotak** [kakaroto/Beyond20#1134]
At least the Light and Minor Illusion cantrips cannot be displayed to VTT but not all though. When clicking the button to display to VTT, nothing happens, nothing shows up. I don't know if there's more cantrips or spells that cannot be displayed. I am using firefox the latest version. 

Thank you.

**Comment by kakaroto** [comment]
Confirmed fixed in the 2.9.4 release
