### ISSUE TITLE
DND Beyond and Roll20 seem to still be having issues.

### ISSUE THREAD

**Issue by Baergin** [kakaroto/Beyond20#1137]
DND Beyond and Roll20 seem to still hate each other with Beyond20 and it's throwing out the same error it was previously when using a spell, ability or weapon attack by simply posting the information of the item/spell/ability instead of doing the actual rolls.  Probably another strange API problem.

**Comment by kakaroto** [comment]
Hi,
I assume you're using Firefox or Edge. It takes them about a week to review/approve an update to the extension. The 2.9.4 release of Beyond20 which adapts to the new DDB website changes was released 2 days ago and is available on the Chrome store.

See https://www.patreon.com/posts/beyond20-2-9-4-105668544

I'll leave this ticket open until next week, in case others are coming here with the same issue.
Thanks

**Comment by albertholaso** [comment]
Hi Kakaroto. I'm running the latest Foundry v12, the latest Dnd5e world, and Beyond20 2.9.4 using the latest Chrome. I'm seeing the same issue as the original post. Descriptions and information are coming through but not the rolls.

**Comment by kakaroto** [comment]
> Hi Kakaroto. I'm running the latest Foundry v12, the latest Dnd5e world, and Beyond20 2.9.4 using the latest Chrome. I'm seeing the same issue as the original post. Descriptions and information are coming through but not the rolls.

That's a different issue, see https://github.com/kakaroto/Beyond20/issues/1127
I haven't even tried Foundry v12 yet and it's so new, I wouldn't recommend anyone to use it for the time being. 
I'm closing this issue since the 2.9.4 release is available on firefox and edge stores too.
