### ISSUE TITLE
Can't roll weapon attack actions

### ISSUE THREAD

**Issue by 2ofspades** [kakaroto/Beyond20#1142]
After clicking the dice icon to roll an attack with a weapon, the VTT (Roll20) will display in the feed a box that displays the weapon's name and an explanation of weapon proficiency. This occurs regardless of if I use the roll icon that appears next to the weapon name or the "to hit" modifier. Using either will produce the same result.

The message displayed in Roll20:
Crossbow, Light
[PC name] Weapon, [item rarity]
Proficiency with a light crossbow allows you to add your proficiency bonus to the attack roll for any attack you make with it.

To Reproduce:
1. Go to character sheet in DDB
2. Click roll icon for a weapon under "Actions"
3. Go to Roll 20
4. See error - instead of attack roll showing, it will only show a box with the weapons name and an explanation about weapon proficiency.

Expected behavior:
I expect for the attack roll to be displayed in the VTT (Roll20) feed, with a button to roll attacks damage.

Browser Info:
 - Browser: Chrome
 - Version:  123.0.6312.94
 
Additional context:
When I roll for eldritch blast and shillelagh from the Action tab in DDB, Roll20 correctly displays the attack roll and the option to roll for damage. It seems the error only occurs for weapon attacks. Additionally, I do not appear to have any trouble rolling other functions, e.g. saving throws, ability checks, etc.

![Screenshot 2024-06-29 2 14 17 PM](https://github.com/kakaroto/Beyond20/assets/174209795/aa68b60c-86eb-45f3-b3d3-f9195d66cf10)

**Comment by kakaroto** [comment]
Are you on version 2.9.3 of the extension? Sounds like you didn't update after the recent D&D Beyond website changes.
I can't reproduce any of the behaviors you described at this time.
