### ISSUE TITLE
Cannot roll saving throws...again and the button to display character picture to VTT has disappeared

### ISSUE THREAD

**Issue by Kodokbotak** [kakaroto/Beyond20#1145]
I'm sorry to the bearer of bad news but they screwed with beyond20 again. Cannot roll saving throws again, display to VTT buttons have disappeard again, but at least rolling attacks and skill checks still work though.

**Comment by ltoons146** [comment]
I concur.  Saving Throws do not roll at all.  It attempts to slide in the description but even the top part of that is missing.   This is true for all slide-in windows.  It looks as if it is behind the layer holding the menu.
![Screenshot 2024-07-11 213710](https://github.com/user-attachments/assets/b0990af3-10dd-4af1-92bc-8d59537593fb)

**Comment by dmportella** [comment]
same issue as https://github.com/kakaroto/Beyond20/issues/1140
