### ISSUE TITLE
No quick roll for initiative roll.

### ISSUE THREAD

**Issue by Celadonz** [kakaroto/Beyond20#1148]
No quick roll is displayed for the initiative roll. So even if it rolls an initiative and is sent to Roll 20, the roll is not added to the turn tracker.

**Comment by DiggidyDale** [comment]
Yeah I am having the same issue, it rolls fine but it is not added to the initiative tracker

**Comment by DiggidyDale** [comment]
Also to add the Saving Throws are also not rolling

**Comment by dmportella** [comment]
this has already been raised there are changes in pull quest to fix it already see https://github.com/kakaroto/Beyond20/issues/1145
https://github.com/kakaroto/Beyond20/issues/1140
