### ISSUE TITLE
Initiative, saving throws and Base state do not roll anymore

### ISSUE THREAD

**Issue by RandomShawn** [kakaroto/Beyond20#1149]
Initiative, saving throws, state check (Base strength to charisma) do not work for the extenstion to roll 20

**Comment by Schroedinger100PCT** [comment]
I can second this.  Our group of 7 people (most if not all oft them on firefox) all experienced the same problem.

**Comment by Kodokbotak** [comment]
bro didn't you check? it's already been reported!

**Comment by dmportella** [comment]
this indeed already been raised and there is already a fix awaiting acceptance to resolve these issues
https://github.com/kakaroto/Beyond20/issues/1145
https://github.com/kakaroto/Beyond20/issues/1140
