### ISSUE TITLE
Unarmed strike attack roll failing

### ISSUE THREAD

**Issue by Sendir** [kakaroto/Beyond20#1150]
**Describe the bug**

Attack rolls made with unarmed attacks open description instead of rolling. All other attacks seem to work fine

**To Reproduce**
1. Go to character sheet
2. Click on unarmed attack

**Expected behavior**

Expect dice to roll and give me attack roll + damage

**Screenshots**
To help explain your problem, add screenshots of where you clicked in D&D Beyond, a screenshot of your Beyond20 character settings if applicable and the result you saw in the VTT.

![image](https://github.com/user-attachments/assets/10cbd6c9-4075-450a-824f-75e2f434831c)

**Browser Info (please complete the following information):**
 - Browser firefox
 - Version 128.0
 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT

![image](https://github.com/user-attachments/assets/0aac24d9-c038-431a-a380-7c5cb9bb3030)

**Additional context**

**Comment by dmportella** [comment]
ty, this has been raised now 5 times XD there is a PR with the fixes already https://github.com/kakaroto/Beyond20/pull/1147

And it was raised on https://github.com/kakaroto/Beyond20/issues/1140 and https://github.com/kakaroto/Beyond20/issues/1145 and https://github.com/kakaroto/Beyond20/issues/1146 and https://github.com/kakaroto/Beyond20/issues/1148 and https://github.com/kakaroto/Beyond20/issues/1149

Hopefully this week it will be released if all goes well <3 ty for raising it, if you find anything else that has not been fixed let us know.
