### ISSUE TITLE
Bonus actions are not rollable

### ISSUE THREAD

**Issue by firelightrpg** [kakaroto/Beyond20#1153]
**Unable to roll bonus action attacks like two weapon fighting and polearm master**
You can roll the hit and damage separately, however, the combined attack and damage only pulls up the description for the feature. 

Similar behavior to #1150, but with bonus action attacks.

**To Reproduce**
1. Go to 'a character sheet'
2. Click on 'the symbol to the left of a bonus action attack'
3. Note: instead of rolling, the feature appears to the right

**Previously, you could roll the attack and damage together**

**Screenshots**
![image](https://github.com/user-attachments/assets/33f0a81f-b168-4f0d-83c7-0326b0d6339e)
![image](https://github.com/user-attachments/assets/fb9d1431-541b-4ada-ba47-38f140fd7007)

**Browser Info (please complete the following information):**
 - Browser chrome and firefox
 - Version [Version 126.0.6478.182 (Official Build) (64-bit), 128.0.2 (64-bit)]

**Note: with chrome, the independent attack and damage buttons work, but with firefox, you cannot make the rolls without adding a custom action**

**Workaround**
With Chrome, you can roll attack and damage separately, but with Firefox, the only way to roll the bonus actions is to make a custom entry and add it as a bonus action. It will appear below the automatically generated attack and will work as normal. 
![image](https://github.com/user-attachments/assets/7301e1b0-948a-4095-8d40-216c312fbdb9)

**Comment by dmportella** [comment]
This is fixed by https://github.com/kakaroto/Beyond20/pull/1147

ty raising it
