### ISSUE TITLE
Issues with Saving Throws and Initiative

### ISSUE THREAD

**Issue by MrPavao** [kakaroto/Beyond20#1155]
Using the latest Chrome and Beyond20, with Roll20 in another tab. Clicking on Initiative rolls initiative on D&D Beyond, but does not send it to Roll20. Clicking a saving throw doesn't roll at all, instead opening the side panel about the saving throw, with no Beyond20 buttons.

To reproduce the Initiative behavior:
1. Open dndbeyond.com character with Beyond20 in one tab.
2. Open roll20.com in another tab and go to a game you're playing.
3. Click the Initiative in dndbeyond. You will see the D&D Beyond dice roll, and no Initiative reported on Roll20.

To reproduce the Saving Throw behavior:
1. Open dndbeyond.com character with Beyond20 in one tab.
2. Open roll20.com in another tab and go to a game you're playing.
3. Click a saving throw, any saving throw.
4. Check your console (Chrome) against mine:
![image](https://github.com/user-attachments/assets/3b054fa2-bea7-4ad3-85bd-a99c4627c3f4)
For diagnostic purposes I first clicked a Dexterity save, then an attack roll.

**Expected behavior**
Both cases should have sent information to Roll20

**Browser Info (please complete the following information):**
 - Error occurs in both Chrome and Firefox.
 - Version127.0.6533.72 (Chrome) and version 128.0.3 (Firefox)

**Comment by dmportella** [comment]
there is a patch awaiting release https://github.com/kakaroto/Beyond20/pull/1147 that will fix this issue

just for the next version to be released soon.

**Comment by dmportella** [comment]
Release has hit the stores, you should update and try again. @MrPavao

**Comment by kakaroto** [comment]
Should all be fixed in the 2.9.5 update, which is now available on chrome (Firefox and edge stores are still pending review).
Closing the issue.
