### ISSUE TITLE
Rolls are not being sent to Foundry while the Use DND Beyond dice option is activated

### ISSUE THREAD

**Issue by gdgalvis** [kakaroto/Beyond20#1156]
**Describe the bug**
While the se DND Beyond dice option is activated no roll is being sent to Foundry VTT, instead the side panel will open with the buttons of Beyond20 and dispaly in vtty. If display is pressed it works as usual, if the Beyond20 button is pressed the console will show the roll, but it will not be receive in foundry.

**To Reproduce**
1. Go to  a DNDBeyond Character sheet  and a Foundry VTT session (make sure use DND Beyond dice option is selected)
2. Click on 'any ability/attack/damage rolll'
3. Go to the foundry session

**Expected behavior**
Expect the rolls to appear in Foundry chat log, they don't appear

**Screenshots**

With DNDB Dice Options enable
![bug1](https://github.com/user-attachments/assets/e44291c5-c19a-4920-868d-7aa41597d017)
![bug2](https://github.com/user-attachments/assets/59ad438a-dc5b-4886-be41-547f425d8017)

With DNDB Dice Options disable
![bug4](https://github.com/user-attachments/assets/b5ab880d-e412-4e32-ab35-7b3897e0024b)
![bug3](https://github.com/user-attachments/assets/16e12f53-b059-4e55-8e97-d6609a337193)

**Browser Info (please complete the following information):**
 - Browser: Brave
 - Version : 1.68.131 Chromium: 127.0.6533.73

**Comment by dmportella** [comment]
hmm weird I am unable to replicate at the moment. My roles are all goign through with digital dice enabled.

What version of FVTT are you using?

![image](https://github.com/user-attachments/assets/fc0cf827-1808-488e-8cc6-f33125bd6902)

**Comment by gdgalvis** [comment]
Version 12 Build 328

**Comment by dmportella** [comment]
Yeah i am on version 11 build 315 that is working there.

**Comment by gdgalvis** [comment]
d
