### ISSUE TITLE
Chat damage buttons for Beyond20 companion module do not work

### ISSUE THREAD

**Issue by RalphTheBard** [kakaroto/Beyond20#1159]
**Describe the bug**
When a Beyond20 roll is made from Dndbeyond, the chat damage buttons that are included with the Beyond20 companion module are not functional. Selecting a token and clicking on the chat damage buttons does nothing.

**To Reproduce**
1. Open up a character sheet on Dndbeyond
2. Click on an attack roll
3. On Foundry, select a monster token in your scene
4. Hover over the character's damage roll in chat
5. Click the button to apply damage
6. Damage is not applied to monster token

**Expected behavior**
The damage is expected to be applied to a scene token when clicking on the chat damage button.

**Screenshots**
N/A

**Browser Info (please complete the following information):**
 - Browser: chrome
 - Version: 127.0.6533.100 (Official Build) (64-bit)
 - Dev console errors:
 > Uncaught (in promise)
TypeError: Cannot create property 'ignore' on number '1'
    at Actor5e.applyDamage (actor.mjs:966:21)
    at HTMLButtonElement.<anonymous> (beyond20.js:726:40)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)

**Comment by dmportella** [comment]
What version of Foundry are you using?

**Comment by RalphTheBard** [comment]
> What version of Foundry are you using?

Foundry: Version 11 Stable - Build 315
D&D 5e: Version 3.3.0

**Comment by RalphTheBard** [comment]
Repros after updating foundry and ruleset.

Foundry: Version 12 Stable - Build 331
D&D 5e: Version 4.0.2

**Comment by kakaroto** [comment]
Thanks, I confirmed the issue. Something changed in the dnd5e system which broke it. It was probably with dnd5e 3.x.
Module has been updated to 1.5.3 with the fix.
