### ISSUE TITLE
Weapon Attacks are broken

### ISSUE THREAD

**Issue by sillvva** [kakaroto/Beyond20#1178]
**Describe the bug**
When clicking the attack roll or damage roll of a weapon attack, it does not do anything whether in a VTT or not. 

Other rolls like non-weapon damage rolls and initiative work fine. HP tracking works fine.

**To Reproduce**
1. Go to any character with a weapon
2. Click on the attack button for a weapon attack in the Actions tab
4. See nothing happen

**Browser Info (please complete the following information):**
 - Browser: I tried 3 different chromium browsers - Arc for Windows, Edge, Chrome
 - Version: Each browser was up-to-date.
 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT
   - I didn't see any. (I did check, assuming that's what was happening)

**Additional context**
I am on the latest version of the extension. In some browsers I had freshly installed it.

**Comment by Thrasher779** [comment]
Already fixed with the 2.9.7 version.
Just install manually or wait till the addon has been approved in the addon-page of your browser

**Comment by dmportella** [comment]
Indeed it is fixed on https://github.com/kakaroto/Beyond20/pull/1175 and further on https://github.com/kakaroto/Beyond20/pull/1177

**Comment by cdfreester** [comment]
I had this same problem last Thursday, October 10th. I just tried removing and reinstalling Beyond 20, went to the Roll20 site for the adventure I am in, and I still could not roll my weapon attack To-Hit or damage rolls. His unarmed attacks and everything else appears to be fine.

**Comment by Kodokbotak** [comment]
alright then another 2 centuries of waiting for the firefox approval

**Comment by dmportella** [comment]
> alright then another 2 centuries of waiting for the firefox approval

Firefox just updated 2.9.8

**Comment by kakaroto** [comment]
Awesome, I see it was also published on the Edge store.
I'll close this issue then.
Thanks!
