### ISSUE TITLE
Subclasses new 2024 rules

### ISSUE THREAD

**Issue by Sincarious** [kakaroto/Beyond20#1181]
the new 2024 books are out and i was excited to start up a new campaign but when i was looking i saw that not all subclasses i owned from other books were there such as Echo knight from the fighter class. if at all possible i would like this to be changed if this could be put in the next patch it would be very much appreciated

**Comment by Nofton** [comment]
It seems you are having an issue with DNDbeyond itself, and not the Beyond20 extension. I'd check out the DND discord for help, or put in a support ticket on DNDbeyond.
