### ISSUE TITLE
Sorcerous Burst Spell only scales 1 element damage type.

### ISSUE THREAD

**Issue by PD8012** [kakaroto/Beyond20#1185]
When I cast the spell sorcerous burst at level 5 or above, the spell should add an extra d8 damage to each damage type. It only adds it currently to the first option, acid.

This issue occurs in any browser and with all sorcerer subclasses (aberrant mind, wild magic, draconic sorcerer). It also occurs on any subpage (spells tab, actions tab, etc.)

https://www.dndbeyond.com/characters/136047139

**Comment by kakaroto** [comment]
I don't see the issue. It does add the extra d8 damage when an 8 is rolled in the damage, and I just tried it with lightning and with psychic damage and it acted correctly once the d8 damage is an 8.
![{1271CEF7-F35B-4F59-889F-9D0A1757108B}](https://github.com/user-attachments/assets/eef7a52f-7551-45f2-97f9-4a8450e18bd9)
![{176473F0-0329-49D4-B617-3A927F96DAF9}](https://github.com/user-attachments/assets/08ec8365-53f1-453d-bb9c-1a29ff5c0d16)

Can you reproduce the issue and provide a screenshot showing no burst damage added while the damage roll is an 8?

**Comment by PD8012** [comment]
Amazing response time. Ty. The issue is not the burst damage, it is the cantrip base damage upgrade is not added to all element types at 5,11, and 17. Ie 2d8 at 5, 3d8 at 11, 4d8 at 17. When you attack, the cantrip base damage is correctly shown for the first type, acid, but for all other damage types, the base damage stays at 1d8–even when casting it at level 16

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kakaroto** [comment]
Ahh I see, you're right, great catch!

Unfortunately, that's not an issue with Beyond20 but rather with D&D Beyond. 
Beyond20 does not calculate what the damage should be, it only rolls what D&D Beyond tells it the damage is, and as you can see, D&D Beyond's damage listing shows 3d8 for Acid but 1d8 for all other damages.
You should file this bug report with the D&D Beyond team directly, pointing out that the damages are inconsistent, see this screenshot of the DDB side panel of the spell:

![{05B12DC3-1B72-4866-88BA-00BB43988A94}](https://github.com/user-attachments/assets/faca0fb3-b021-4319-9aaa-d48782736974)

Good luck!

**Comment by PD8012** [comment]
Appreciate your expertise and prompt attention to this.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
