### ISSUE TITLE
Can't Update Beyond20 on VTT

### ISSUE THREAD

**Issue by boyobejamin** [kakaroto/Beyond20#1189]
**Describe the bug**

Love your software! Thank you so much! Easy issue with the [v1.5.4 release](https://github.com/kakaroto/Beyond20/commit/26be609537b000cfd445cb71d9191bad479b8afe#diff-53410fa8a5608a1ce58fa43e511dc66b7e342c8e9e0eda9c93345e3e09157202R21).

`https://raw.githubusercontent.com/kakaroto/Beyond20/fvtt-module-v1.5.4/FVTT-module/beyond20.zip` presents 404 file not found. May need to be released.

**To Reproduce**
1. Go to VTT
2. Click on Update Modules

```
[beyond20] An unexpected error occurred when downloading file https://raw.githubusercontent.com/kakaroto/Beyond20/fvtt-module-v1.5.4/FVTT-module/beyond20.zip: Not Found
```

**Expected behavior**
File downloads successfully

**Screenshots**
To help explain your problem, add screenshots of where you clicked in D&D Beyond, a screenshot of your Beyond20 character settings if applicable and the result you saw in the VTT.

**Browser Info (please complete the following information):**
 - Chrome, latest
 - Version 12 Build 331
 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT

**Additional context**
Add any other context about the problem here, such as a link to the character sheet or D&D Beyond page that shows the problem.

**Comment by kakaroto** [comment]
ah, thanks! I did a `git push` earlier for the new release, but forgot to do `git push --tags`.
I've just done it now, so it should work.

**Comment by boyobejamin** [comment]
Perfect! Thank you so much!!!
