### ISSUE TITLE
Add key binding selector for the adv/disadv.

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#120]
Perhaps give the choice between all roll types, and whisper or not, etc..

**Comment by 736dave** [comment]
Is this where we might add bless and bardic inspiration on a case-by-case basis?

**Comment by kakaroto** [comment]
No, that's completely unrelated.
To add bless or other modifiers on a case by case basis, please check out the FAQ item here : https://beyond20.here-for-more.info/faq#how-can-i-add-blessguidance-bonus-or-use-elemental-weapon-
