### ISSUE TITLE
The Rogue's "Assassinate" feature doesn't work with Super Advantage.

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#121]

**Comment by HuntsmanWest** [comment]
Hey there, 

love the plugin btw, just leaving this comment here in case it's useful at some point. 

Observed behaviour:
If you activate `assassinate` in beyond20 options, and you want to have beyond20 `Ask every time` for what type of roll you want to make - the plugin will not popup asking what type of roll you want to make, nor roll with super advantage (as the issue has already been raised, and closed, for). It just rolls with advantage on VTT (using roll20 in this case).

Menu showing options set:

![image](https://user-images.githubusercontent.com/78335890/106415891-547fae00-64a4-11eb-9bf7-0ca80843ca5f.png)

Result of clicking attack roll:
![image](https://user-images.githubusercontent.com/78335890/106415993-8b55c400-64a4-11eb-9b79-67843916ba5a.png)

Though once I swap it back to `Roll with super advantage`, the super advantage roll mechanic works fine - although being able to ask for what type of roll at all times would be cool. Just an FYI :)

Cheers
