### ISSUE TITLE
Add support for special spells

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#13]
For example: Chromatic Orb, Chaos Bolt, Magic Weapon, Shadow blade (?), Absorb Elements, etc...

**Comment by GayKiwi** [comment]
Our group makes use of Chaos Bolt heavily atm and cannot understand how to natively read the output for this spell. Currently make use of the following macro:

&{template:traits} {{charname=@{selected}}} {{name=Chaos Bolt}} {{source=Custom Spell}} {{description=Spell Attack [[d20+?{Spell Attack Bonus|3}]]

(  [[d8]] + [[d8]] (Damage Type) + [[d6]] )

First, the Damage Type is selected as indicated above and matched to the information below. Second, the total damage rolled is all three damage dice totalled if the Spell Attack Hit.

If the first two dice rolls are the same number, this spell leaps 30" from the target to another creature requiring a new Spell Attack and Damage roll. This continues till either the first two rolls are different or no other creatures are within range.

Higher levels add an addition D6 per level above 1st.

**Rolled 1** Acid  **Rolled 2** Cold  **Rolled 3** Fire  **Rolled 4** Force  **Rolled 5** Lightning  **Rolled 6** Poison  **Rolled 7** Psychic  **Rolled 8** Thunder.
}}

Spell found at: https://www.dndbeyond.com/spells/chaos-bolt

**Comment by kakaroto** [comment]
Hi @GayKiwi,
ChaosBolt is a difficult spell to automate because of the 'damage type is dependent on the first 1d8 rolled but that 1d8 also applies as damage, and if both 2d8s are the same then the spell becomes special". I can do it easily enough with FVTT but not with Roll20. So I've been procrastinating adding specific support for it.
Unfortunately, until then, Beyond20 will just roll whatever damage D&D Beyond tells it to and unfortunately D&D Beyond says you get 2d8 damage per type, so Beyond20 will roll that for all the types.

See the information the extension gets : 
![image](https://user-images.githubusercontent.com/27990/62678641-09084480-b980-11e9-9d4b-8bf9f05088b4.png)

I haven't had to deal with Chaos Bolt yet in my own games (though one of my players wants to multiclass into sorcerer so he could use that) but as DM, I would rule it as "take the first 2d8 damage that was rolled, and the 1d6 damage and ignore the rest"
I don't think there's a good solution so I think I just might make it roll the 2d8 + 1d6 and have it display "Variable damage type". It won't be 100% automated but better than what it currently displays I guess.

**Comment by GayKiwi** [comment]
I guess the macro will have to work, I will continue working on it to make it roll the correct template. Thanks for the reply.

**Comment by kakaroto** [comment]
I added Chaos Bolt support. For Roll20, there's really not much I can do because of how limited their macro system is, but I got it to show this way (shows "Chaotic energy" as the type, and lets the player look up the roll result for the actual damage type): 
![image](https://user-images.githubusercontent.com/27990/62813388-7dee9200-bad8-11e9-8f6a-6d4788ecf2bd.png)

In FVTT, I have more possibilities and I implemented it this way : 
![image](https://user-images.githubusercontent.com/27990/62813424-b8f0c580-bad8-11e9-8c2e-c0872c025a89.png)
So it makes the roll, finds which types are available and gives you the choice. If both rolls were the same, it can also tell you that it leaps.

**Comment by timc1004** [comment]
Shadow Blade works for damage (must manually add your str/dex to the damage bonus) but it does not roll a "to hit" even with a to hit specified

**Comment by kakaroto** [comment]
That seems like a bug in D&D Beyond because the spell is a melee attack but they're not showing the To Hit value. And even if you set a To Hit override, it won't actually add the to-hit for it, it will only override the to-hit value *if there was one*. Also note: you shouldn't add str/dex to the damage bonus as far as I understand from that spell description. what I've seen people do is create a custom action for Shadow Blade (which btw also doesn't show as an action even if you enable the 'display as attack' option).
