### ISSUE TITLE
Discord: Beyond20 Discord Bot is offline?

### ISSUE THREAD

**Issue by RadicalRebop** [kakaroto/Beyond20#132]
Whenever I add the bot to the discord it says it is offline. Am I doing something wrong?

**Comment by Aeristoka** [comment]
Bot shows as offline as already added to my server, also doesn't respond to commands on my server.

**Comment by RadicalRebop** [comment]
The Bot came online after awhile. So I think this is solved

**Comment by kakaroto** [comment]
I think discord issues caused it to drop. I don't see errors in the log though, but I restarted it and it works now. Thanks for letting me know :)
