### ISSUE TITLE
Jim's magic missle from Acquisitions Inc doesn't calculate damage correctly

### ISSUE THREAD

**Issue by dmeese** [kakaroto/Beyond20#139]
On a crit, it doubles the dice.  it should go from 2d4 to 5d4.

**Comment by Aeristoka** [comment]
That's a weirdly specific Crit thing: https://www.dndbeyond.com/spells/jims-magic-missile

**Comment by kakaroto** [comment]
hehe, yeah, it's really very specific. I'd suggest for those use cases to just roll the extra d4 manually
I'll keep this open to revisit the question for next release

**Comment by kakaroto** [comment]
One year (and 3 days) later, this finally gets fixed! 🥳 Thanks to @Aeristoka for that :)
It should be available in the upcoming release (soon).
Thanks for being patient :)
