### ISSUE TITLE
Add an option to have Disciple of Life add to the spell roll

### ISSUE THREAD

**Issue by Herodragon33** [kakaroto/Beyond20#141]
It would be nice to have an option so when my cleric casts a healing spell the number that is shown is already the total HP the creature regains. Disciple of Life is a passive ability that is always active and I don't know of a time when you wouldn't add it anyways. Every few rolls we always have to remind ourselves "did it add the +6 already?". I would say make it strickly add or don't add with the Disciple of Life toggle itself but I know people like their options.

**Comment by Aeristoka** [comment]
I disagree, I like it being separated to demonstrate where the healing comes from. This also let's you know very specifically that Disciple of Life is indeed included, since you saw it separated.

**Comment by kakaroto** [comment]
Yeah, sorry @Herodragon33 but the disciple of life will remain separate. If it were included, I guarantee 99% of people will think "it's not adding it" and will add it twice during their game. Rare are those who will hover the mouse to see the actual details of the roll, and even those who do, will probably miss it or forget it.
Disciple of Life is already calculated based on the spell level and sent as part of the spell cast. Being unable to do a "+3" calculation on your own when all the numbers are in front of you, would make playing D&D in general difficult.

I do have more control over what the messages look like If you're not using Roll20, so if you use the integrated dice roller, Foundry VTT or the Discord roller, then you would get the break down of heals and the total as well : 
![image](https://user-images.githubusercontent.com/27990/77133097-3948b300-6a38-11ea-9850-8b1d6f7f3814.png)
