### ISSUE TITLE
Outpout dosent seem to work anymore (firefox/chrome)

### ISSUE THREAD

**Issue by ideanic** [kakaroto/Beyond20#146]
Hello,

Last night, me and my group played our usual session on firefox with dndbeyond, roll20 + Beyond20 extension but for some odd reason, when we would send a command from dndbeyond with Beyond20 to roll20 it would only show a blank space instead of the result.

On roll20 I can see the formula (with the up arrow) and everything seem in order.

Exemple : 
`&{template:atk} {{charname=Alfred (junior)}} {{rname=[Warhammer](!
 &#38;&#123;template:dmg&#125; &#123;&#123;damage=1&#125;&#125; &#123;&#123;dmg1flag=1&#125;&#125; &#123;&#123;dmg1=&#91;&#91;1d8+1&#93;&#93;&#125;&#125; &#123;&#123;dmg1type= Bludgeoning&#125;&#125; &#123;&#123;dmg2flag=1&#125;&#125; &#123;&#123;dmg2=&#91;&#91;1d10+1&#93;&#93; | &#91;&#91;1d8&#93;&#93;&#125;&#125; &#123;&#123;dmg2type=Two-Handed | Divine Strike&#125;&#125; &#123;&#123;charname=Alfred &#40;junior&#41;&#125;&#125; &#123;&#123;rname=Warhammer&#125;&#125;)}} {{mod=+5}} {{r1=[[1d20 +5]]}} {{attack=1}} {{rnamec=[Warhammer](!
 &#38;&#123;template:dmg&#125; &#123;&#123;damage=1&#125;&#125; &#123;&#123;dmg1flag=1&#125;&#125; &#123;&#123;dmg1=&#91;&#91;1d8+1&#93;&#93;&#125;&#125; &#123;&#123;dmg1type= Bludgeoning&#125;&#125; &#123;&#123;crit1=Crit: &#91;&#91;1d8&#93;&#93;&#125;&#125; &#123;&#123;dmg2flag=1&#125;&#125; &#123;&#123;dmg2=&#91;&#91;1d10+1&#93;&#93; | &#91;&#91;1d8&#93;&#93;&#125;&#125; &#123;&#123;dmg2type=Two-Handed | Divine Strike&#125;&#125; &#123;&#123;crit2=Crit: &#91;&#91;1d10&#93;&#93; | &#91;&#91;1d8&#93;&#93;&#125;&#125; &#123;&#123;charname=Alfred &#40;junior&#41;&#125;&#125; &#123;&#123;rname=Warhammer&#125;&#125; &#123;&#123;crit=1&#125;&#125;)}} {{always=1}} {{r2=[[1d20 +5]]}}`

The above command, return an empty space instead of the result of an attack with my warhammer. We did try it on chrome and firefox with the same result. It was working fine last week.

**Comment by kakaroto** [comment]
Hi,
I would assume your DM has changed the game's character sheet templates in Roll20 to something other than "D&D 5e by Roll20". You need to configure the game in roll20 to use the correct template, or you can tell Beyond20 to use 'others' for the template to use. The output won't be as nice, but it will work.
If that doesn't fix it or it's not the issue you're having, feel free to re-open this issue.
More information here about it : https://beyond20.here-for-more.info/faq#all-i-see-in-roll20-is-an-empty-message
Thanks!
