### ISSUE TITLE
Roll20 initiative suggestions

### ISSUE THREAD

**Issue by DesktopMan** [kakaroto/Beyond20#150]
If you roll initiative from D&D Beyond it will add the initiative in Roll20 as the currently selected token. Would it be possible to add the token with the matching character/token name instead, or update it if it's already in the initiative list? If the token doesn't exist it could be added as a custom item.

**Comment by kakaroto** [comment]
Unfortunately, that's not possible as Roll20 doesn't allow it. See their wiki on macros and turn tracker here : https://wiki.roll20.net/Macros#Rolling_For_Initiative
> To send a roll result directly to the Turn Tracker, first, select the Token you wish to roll for initiative and then use the below roll option in your macro

There is no method allowed by Roll20 to adding a custom name or affecting a token that isn't selected.
