### ISSUE TITLE
support Elemental Adept

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#152]
> When you gain this feat, choose on of the following damage types: acid, cold, fire, lightning, or thunder. Spells you cast ignore resistance to the chosen type, and whenever you roll damage for a spell that deals damage of the chosen type, treat any rolled 1's as being a 2.

For R20, it can be done using a dice pool like this : `{2, [[1d6]]}kh1`

**Comment by Aeristoka** [comment]
Seems likely Flames of Phlegethos could be covered in this as well: https://www.dndbeyond.com/feats/flames-of-phlegethos
Specifically the second bullet point: When you roll fire damage for a spell you cast, you can reroll any roll of 1 on the fire damage dice, but you must use the new roll, even if it is another 1.

**Comment by kakaroto** [comment]
That's a different case, it's a reroll of the dice, while elemental adept is "consider 1 as if it was a 2" without a reroll.

**Comment by Aeristoka** [comment]
Well I should probably read Elemental Adept all the way, huh :)

**Comment by kakaroto** [comment]
There you go :p https://github.com/kakaroto/Beyond20/issues/153

**Comment by Aeristoka** [comment]
Like a boss
