### ISSUE TITLE
Rolls Twice in Roll20 when "Normal" is selected

### ISSUE THREAD

**Issue by sejsim** [kakaroto/Beyond20#154]
I feel like I troubleshot this, but can't figure out the issue.

When Roll "Normal" is selected in Beyond20, the result in Roll20 is a double roll of both attack and damage, or any check.

When the option is changed to "Always Ask" in Beyond20 and selecting "Normal" roll in Roll20 with the prompt, it rolls correctly.

Help?

**Comment by Aeristoka** [comment]
Character or Monster? Screenshot would also be helpful.

**Comment by sejsim** [comment]
> Character or Monster? Screenshot would also be helpful.

Both Character and Monsters.  All Rolls of All Types.  Two Screenshots.  

First of settings.

<img width="1440" alt="Screen Shot 2020-03-28 at 7 13 43 PM" src="https://user-images.githubusercontent.com/62179161/77836039-003fcb00-7129-11ea-8b26-29399fd5cf6c.png">

Second of Result After Clicking Beyond20 Button Once.

<img width="1440" alt="Screen Shot 2020-03-28 at 7 14 06 PM" src="https://user-images.githubusercontent.com/62179161/77836042-0a61c980-7129-11ea-99ea-0734c378f4ae.png">

Thanks

**Comment by Aeristoka** [comment]
That's almost certainly a Roll20 lagging out issue. We've seen that in my group exclusively when Roll20 is having server issues, and it gets the message from Beyond20 twice.

Try refreshing Roll20, then DnDBeyond, in that order.

**Comment by sejsim** [comment]
> That's almost certainly a Roll20 lagging out issue. We've seen that in my group exclusively when Roll20 is having server issues, and it gets the message from Beyond20 twice.
> 
> Try refreshing Roll20, then DnDBeyond, in that order.

Did that earlier with no improvement. But it's possible the with COVID19 the server volumes on Roll20 are much higher, but one would expect others to have a similar issue more often now as well.

**Comment by Aeristoka** [comment]
> > That's almost certainly a Roll20 lagging out issue. We've seen that in my group exclusively when Roll20 is having server issues, and it gets the message from Beyond20 twice.
> > Try refreshing Roll20, then DnDBeyond, in that order.
> 
> Did that earlier with no improvement. But it's possible the with COVID19 the server volumes on Roll20 are much higher, but one would expect others to have a similar issue more often now as well.

Confirmed in my game tonight, Roll20 was about 25/75 for double rolling/normal rolling with no changes on our Beyond20 settings, so I would bet that Roll20 is having issues. We also had lag in rolls coming through from DnDBeyond.

**Comment by kakaroto** [comment]
Best way to check would be to press F12 on roll20 to get the developer console. Clear the console then do a roll, see if you receive one or two messages from Beyond20 (it should print it in the console). If you receive only one, then it's a roll20 lagging issue as @Aeristoka said, if you receive it twice, then it could be a D&D beyond issue sending the roll twice.
You can also check the console in D&D Beyond to see if it's sending the message twice or once. If it sends it once but Roll20 receives it twice, then... well, I have no idea it shouldn't happen. If it sends it twice, then perhaps there's some reason why it thinks you double clicked even when you didn't.

**Comment by sejsim** [comment]
Seems this confirms it kakaroto.  Cleared chat box and cleared console.  

<img width="1440" alt="Screen Shot 2020-03-29 at 12 23 03 PM" src="https://user-images.githubusercontent.com/62179161/77854400-2f514d80-71b8-11ea-95f5-f5ea05b49923.png">

**Comment by kakaroto** [comment]
Looks like it. B20 receives it once and it gets sent twice. Do you also get that kind of behavior when you roll and send chat message manually ? Since B20 just emulated someone typing the formula in chat and clicking the send button.

**Comment by sejsim** [comment]
Seems to be Chrome related.  Do not get the issue using Firefox.
<img width="1440" alt="Screen Shot 2020-03-29 at 1 14 15 PM" src="https://user-images.githubusercontent.com/62179161/77855575-3d569c80-71bf-11ea-9535-2b657831811e.png">

**Comment by clarkbrent** [comment]
It might be an unrelated Chrome extension. I've had issues in the past while doing frontend dev work thanks to Chrome extensions trying to hook into the DOM on **every** page that loads causing the DOM to remount. I'd imagine that the Beyond20 console log would be printing twice if that were the case though.

**Comment by kakaroto** [comment]
I was able to reproduce this behavior today while testing stuff. I could confirm that I only receive one message, that I only send one message to roll20 but two messages get printed. But then I debugged and could also confirm that the `postChatMessage` function gets called only once, but I couldn't understand why the button click somehow made it trigger twice... 
so I next changed the message that was being written to chat, and I received my modified message and the original roll, so I think there's something else also listening and receiving the same message and printing it (but no console.log about the original message being received and the breakpoint doesn't trigger?). I don't know yet what it would be. But it's definitely weird, because it's not printing anything to the console.

**Comment by kakaroto** [comment]
Ok, I was being stupid. I actually had two Roll20 tabs open, which is why it was sending things twice. Obviously...

**Comment by kakaroto** [comment]
I haven't seen this happening in a while, or any time it did happen, it was because the user had two tabs open to Roll20. So I think this issue is stale and can be closed.

**Comment by inkhsutesou** [comment]
> Ok, I was being stupid. I actually had two Roll20 tabs open, which is why it was sending things twice. Obviously...

Thank you for posting this, as this solved my issue as well : ]
