### ISSUE TITLE
[suggestion] Add spell attack bonus?

### ISSUE THREAD

**Issue by Master-Guy** [kakaroto/Beyond20#155]
Could you make the plugin on DDB look if the Spell Attack Bonus needs to be added?

**Comment by kakaroto** [comment]
In what situation exactly? D&D Beyond itself will already give all the information needed, what's the to hit value if there is one, including any special modifiers or magical enhancements, so if an attack bonus is missing, that would be a D&D Beyond bug.
If there's a very specific spell or feat or something that needs to be handled separately, then please specify which.

**Comment by kakaroto** [comment]
Closing as invalid since it's been answered and D&D Beyond already does it. OP didn't reply in 9 days with any new information.
