### ISSUE TITLE
Seeing HP sync to character sheet but not token

### ISSUE THREAD

**Issue by etriebe** [kakaroto/Beyond20#156]
When I submit damage to my character in DND Beyond, it syncs to the character sheet in Roll20 but not to the green token. I'm not sure if there is some sort of setup I have to do to Roll20 to get my token to support this too.

**Comment by Aeristoka** [comment]
![image](https://user-images.githubusercontent.com/7988297/77937563-c0d0c600-7271-11ea-83fd-48ddf384cf72.png)

**Comment by etriebe** [comment]
Hm... I see a different UI. Does this require a certain level of membership to roll20? How did you get to the token editor? 

![image](https://user-images.githubusercontent.com/7503160/77938422-916a8b00-726a-11ea-913a-3e1bc13731ca.png)

**Comment by Aeristoka** [comment]
Your DM needs to setup the part I'm referencing. Join us over on the Discord server, I can help you easier over there: https://discord.gg/254zpf

**Comment by etriebe** [comment]
Fixed it. Thanks!

**Comment by Aeristoka** [comment]
> Fixed it. Thanks!

Cool! Please close the issue if you're all set now.
