### ISSUE TITLE
[Request] Rogue Reliable Talent

### ISSUE THREAD

**Issue by lanscaper** [kakaroto/Beyond20#158]
Reliable Talent:
By 11th level, you have refined your chosen skills until they approach perfection. Whenever you make an ability check that lets you add your proficiency bonus, you can treat a d20 roll of 9 or lower as a 10.

Similar to the Elemental Adept except you convert [1-9] into [10]

**Comment by kakaroto** [comment]
Nice, thanks for finding this!

**Comment by lanscaper** [comment]
Note that it should also trigger for Custom Skills that have proficiency OR expertise

**Comment by rawrgit** [comment]
I mentioned this in the #support channel on the Beyond20 Discord february 20th as well. This would be a very nice thing to have.

**Comment by kakaroto** [comment]
You definitely did. Sorry, it seems I had forgotten to create an issue for it.

**Comment by rawrgit** [comment]
I'm really looking forward to the next release if this gets into the planned milestone! So so much! :-D
