### ISSUE TITLE
Add support for Astral Tabletop

### ISSUE THREAD

**Issue by ThatOhio** [kakaroto/Beyond20#160]
I've been using Astral Tabletop lately and would love to use this for that game. I will likely switch back to roll20 because of how useful this extension is but would love to use Astral.

https://astraltabletop.com/

I have a good amount of experience with C# and .Net, and a bit of front end experience. I saw your explanation in the card for Foundry, I don't have a ton of time at the moment to attempt the PR, but if I get some time before you can get to it, I will try.

**Comment by kakaroto** [comment]
Moving this to the 2.2 milestone, considering PR #484 has been reviewed and is looking pretty good so far.

**Comment by kakaroto** [comment]
Closing as #484 was merged!
