### ISSUE TITLE
No rolls displayed in Roll 20 chat. 

### ISSUE THREAD

**Issue by AndreScaffidi** [kakaroto/Beyond20#161]
This occurs in both my firefox and chrome versions.

Any rolls - attacks, initiative etc do not show up in the CHAT box. However, initiative will get sent to the tracker as expected.

Also, if I have 3D dice turned on the rolls will occur - there will just be no output in the chat.

Eg: Hit firebolt attack on dnd beyond with my character token selected (same name in both). 3D dice get rolled, character name pops up in chat but nothing else.

**Comment by kakaroto** [comment]
That would be caused by this : https://beyond20.here-for-more.info/faq#all-i-see-in-roll20-is-an-empty-message
