### ISSUE TITLE
Polearm Master

### ISSUE THREAD

**Issue by worthingwc37** [kakaroto/Beyond20#164]
Polearm Master should add ability modifier to damage roll. Per this Sage Advice: https://www.sageadvice.eu/2015/01/24/polearm-feat-and-strength/

Thank you for this extension by the way. No idea how you did it, but it's amazing!

**Comment by worthingwc37** [comment]
Just noticed my problem.

When you use PAM from the Actions Tab -> Bonus Actions, it functions properly.

When you click on it on the Features & Traits Tab -> Feats, it only rolls the D4, does not add the ability modifier to the damage.

**Comment by kakaroto** [comment]
When you click on it from the features tab, you're only displaying the feature description. It becomes up to you to decide on how it needs to be used. The d4 button in there is just for convenience.
The proper way to use PAM is indeed from the bonus actions, where it functions properly.
