### ISSUE TITLE
HP not syncing

### ISSUE THREAD

**Issue by Parthantir** [kakaroto/Beyond20#165]
The names are the same, I used the FAQ suggestion and kept deleting and remaking the Roll20 character and putting 0 and higher number in all 3 HP fields. It initially had an apostrophe in the name that I thought was messing it up, but after removing it and remaking the Roll20 sheet without it too, it still would not sync.
Every other function works as far as I can tell.

**Comment by Aeristoka** [comment]
You still have a mismatch somewhere. If you press F12 to open the console, you should see messages like the attached (DnDBeyond):
![image](https://user-images.githubusercontent.com/7988297/78452901-7a051680-764b-11ea-9646-1d2163392154.png)

And this (Roll20):
![image](https://user-images.githubusercontent.com/7988297/78452911-89845f80-764b-11ea-8835-3a08b0cbc431.png)

**Comment by kakaroto** [comment]
Also make sure you hadn't inadvertently disabled the option. Click the beyond20 settings and in 'More Settings', look for this : 
![image](https://user-images.githubusercontent.com/27990/78452996-ec322700-765c-11ea-9d2f-85fc8fa72100.png)

**Comment by Parthantir** [comment]
I do still have the option turned on. The console is showing an updated HP message, but the character sheet isn't  updating.
![image](https://user-images.githubusercontent.com/63150893/78453209-d10fe900-7655-11ea-8d93-2bf480e9c948.png)

![image](https://user-images.githubusercontent.com/63150893/78453199-bdfd1900-7655-11ea-8af2-edf6a8defe2a.png)

**Comment by kakaroto** [comment]
See the name on the roll20 side, `"name":"Fillad "`, you have a trailing space at the end of the name on the D&D Beyond side.
Someone else had a similar issue a couple of days ago before they figured it out. I plan on fixing that in the next release, see #162

**Comment by Parthantir** [comment]
Perfect, that fixed it. Thank you!
