### ISSUE TITLE
Support for Tableplop VTT

### ISSUE THREAD

**Issue by cjue** [kakaroto/Beyond20#166]
Tableplop [1] is a new VTT which works great for our group.

The only thing slowing us down is the lack of awesome Beyond 20 dice rolling :)

If we create a PR that implements support for Tableplop, would you consider merging it?

[1] https://www.tableplop.com/

**Comment by kakaroto** [comment]
Hi,

I don't have any plans of adding support for new VTTs as the options are many and I am personally only using Foundry VTT (and actually starting a business around it), and my time is very limited.

However, I would gladly accept a PR that adds such an implementation. I'll try to review it in a timely manner and merge once all raised concerns are fixed.
Make sure to add all the appropriate things in such a PR, such as updates to the README, manifest.json, options for where to send rolls to, support for the VTT specific options in the popup, etc...
I plan on moving away from rapydscript and rewriting Beyond20 in pure JS, so if it's possible to write the content script in JS, that'd be great. If you need to use the RollRenderer, then you'd probably need to use a .pyj script in that case, and that's ok too.
Thanks!

**Comment by kakaroto** [comment]
My policy with regards to support for new VTT apps has changed. Please read the updated FAQ about it  https://beyond20.here-for-more.info/faq#can-you-add-support-for-insert-new-vtt-name

Sorry for any wasted time, though it doesn't look like there was any progress on this for a while.
Thanks for understanding.

**Comment by cjue** [comment]
No problem, I mostly gave up after looking into the Tableplop source, and then dndbeyond also added their own dice rolling UI.
