### ISSUE TITLE
Rage damage not being added to rolls

### ISSUE THREAD

**Issue by petunes** [kakaroto/Beyond20#169]
I just started using DDB and Beyond20, so I apologize if I'm doing something wrong.  When I use a Rage in my character sheet in DDB, then attack with a weapon, it is not adding the +2 to the damage for raging...

![image](https://user-images.githubusercontent.com/12788644/78509778-748bf700-7745-11ea-95dc-77143919f13e.png)

![image](https://user-images.githubusercontent.com/12788644/78509798-9a190080-7745-11ea-84f1-a612acba0a33.png)

**Comment by kakaroto** [comment]
Thanks @Aeristoka for taking the question.
As he explained, Beyond20 can't use the rage slots in D&D Beyond because it doesn't know how long the rage might last, or if it was used in a previous encounter, etc.. so instead you decide to enable and disable it as you see fit.

**Comment by petunes** [comment]
Thanks!  Sorry

**Comment by kakaroto** [comment]
No worries, it's by asking that we learn :)
