### ISSUE TITLE
Problem with D&D Beyond

### ISSUE THREAD

**Issue by Fairburne** [kakaroto/Beyond20#174]
It was working yesterday easy to setup.  Today it is not.  I don't know what changed.  I tried uninstalling and reinstalling still not working properly.

When I click on the Beyond 20 quick settings the window opens but I can't interact with it.
If I click on a weapon to attack the window opens but where yesterday I could click on the Beyond 20 icon I now only see Display in VTT.  

Some things are still working.  Skill checks, initiative, saving throws, spell attack all seem to be working.

I'm not sure if a setting got changed or if it is something else entirely.

**Comment by Aeristoka** [comment]
Congrats, you probably got upgraded to the Alpha character sheets on DnDBeyond.

Fix here: https://discordapp.com/channels/578874022968688640/579077106173083659/697111348231798884

**Comment by Fairburne** [comment]
That link didn't do anything.

**Comment by kakaroto** [comment]
That link would only work within the Discord app if you were in the Beyond20 discord server.
This is basically what it linked to : 
![image](https://user-images.githubusercontent.com/27990/78853703-87285980-79ed-11ea-9213-ff97e3b0e8e4.png)

And here are the instructions for the developer mode installation : https://github.com/kakaroto/Beyond20#developer-mode-installation

I have a release planned for tomorrow with the fix, though it could take Chrome a few more days before it gets reviewed and appears on the chrome store.

**Comment by Fairburne** [comment]
Thanks!

**Comment by Fairburne** [comment]
Click on the 'Load Unpacked' button (I did this)
Select the Directory where you extracted this extension (I found the location of the extracted file)

I don't know what to do next.

![2020-04-09 (1)](https://user-images.githubusercontent.com/63383444/78938068-948e2400-7a7f-11ea-89a5-10265e88023c.png)

**Comment by kakaroto** [comment]
Ignore all that. And just update Beyond20. I've released the update and it's now available for both Firefox and Chrome.

**Comment by Fairburne** [comment]
Cool thanks that was easier
