### ISSUE TITLE
Friend Unable to Attack with Beyond20 into Roll20 on both Chrome and Firefox

### ISSUE THREAD

**Issue by KazamaYokaze** [kakaroto/Beyond20#175]
Hi,
I'm DMing for my friends and told them about this extension and it's been working great until recently.
One of our friends has not been able to select and attack with any of his equipment for both Firefox and Chrome. 
Chrome:
![Chrome Attack](https://user-images.githubusercontent.com/34959419/78860122-36f9c900-79e6-11ea-87d5-b3660c719368.png)

Firefox

![Firefox](https://user-images.githubusercontent.com/34959419/78860177-5ee92c80-79e6-11ea-9d8b-fda4caf0f42f.png)

I saw that there was another issue that had the issue solved where his character sheet may be an Alpha Character sheet, but when I view my friends character sheet I am able to attack on his behalf which I did for this previous session, but would like to have him press the button himself. If this is related to his character sheet being upgraded to an Alpha one in D&DBeyond then I apologize for making a repeated issue, but it seems different due to me being able to still make attacks on my own computer.

Thank you,

Kaz

**Comment by KazamaYokaze** [comment]
After rereading the fix, I noticed it may be his account you are alluding too and not the sheet itself my bad and also that you have a fix on the way for this sometime tomorrow. I will close the issue please do let me know if I need to create/reopen because it is different somehow.

Thank you,

Kaz

**Comment by kakaroto** [comment]
Hi, yes, it's related to the user account. What your friend can do to make the rolls himself is to open a new incognito window in which they don't log in, and they can use their sheets without issues. Keep the logged in window in case changes are required (spell slots, HP/resting), and roll from the logged out window.
