### ISSUE TITLE
roll20 chat posts not working on v0.3

### ISSUE THREAD

**Issue by joshbayley** [kakaroto/Beyond20#18]
Hi my party has version 0.2 and roll20 chat posts are working for them, we have same settings (roughly since they changed a bit), "Other Templates" is selected and it was working previously

**Comment by joshbayley** [comment]
Using firefox

**Comment by kakaroto** [comment]
Thanks for the report. Any more information maybe? does it appear blank or does it not send anything at all ? Did you try restarting firefox after the update? Does it work for monster pages or character sheets? Does it happen for only ability/skill checks or 'spell cards' or attacks as well ? Did you click the Beyond20 icon in the address bar on the Roll20 page to see that it is set to send rolls to that campaign ?
If you can't get it fixed while exploring these questions, can you press Ctrl-Alt-J to get the debug console of Firefox and see if any errors appear on it when you click a roll in D&D Beyond and if there is, please post it here.
Thanks!
