### ISSUE TITLE
[Request] Display remaining amount of consumabes and ammo

### ISSUE THREAD

**Issue by SpectreWulf** [kakaroto/Beyond20#180]
While testing I found that only the equipment / item / ammo description and dice rolls ( if any ) are sent to Roll20 chat.

I think it would really be great if in addition to the that the amount of that consumable / ammo remaining can also be displayed? 
Eg: Player drinks a Potion of Healing and clicks on 'Display on VTT' button and it shows the character has 2 potions remaining.

Also is it possible to auto-reduce the ammo count in the Inventory when using Ranged weapons?

PS: This plugin is a game changer! Expect a ration for your generous efforts! <3

**Comment by kakaroto** [comment]
Display quantity as part of the 'display to VTT' is a pretty great idea, thanks for suggesting it! :)
I'll see what I can do about the auto reduce of the ammo. You may want to display the info about your health potion without drinking it, so it can be a bit complicated, maybe having 2 buttons would work here.

**Comment by SpectreWulf** [comment]
Thanks for your quick response, I think a separate button to show the ammo / item quantity will be easier as it will not break the existing workflow logic, and also will give a better UI option to the user if they want to show the quantity.

Thanks for also considering the auto reduce of ammo, that will solve a lot of problems with ammo tracking in games as currently I have scripts running in Roll20 tied to macros for reducing the ammo, but that dissolves into lot of redundant data between the character sheet and Roll20 items.

**Comment by Brunhine** [comment]
I'm not sure it's feasible to solve for auto reducing ammo, there is no way to know which ammo is to be reduced.

It's easy enough to display the quantity of an item, how does this look?
![image](https://user-images.githubusercontent.com/828357/79683348-45ae6000-81de-11ea-9133-2097b0bd5b00.png)

**Comment by kakaroto** [comment]
Looking good. I think they auto reduce would be q separate button. If it detects a - button, it would add a "use and display " in addition to the display in vtt button, on click, it would generate a click on the - button
