### ISSUE TITLE
custom dice aren't cleared from features page 

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#183]
![ezgif-6-5980f6d4b17f](https://user-images.githubusercontent.com/27990/79072187-a35a1e00-7cad-11ea-80f2-11db17682a56.gif)

**Comment by SpectreWulf** [comment]
I just saw this and yes every-time we click on a Feature / Trait the custom dice texts are calculated again and an additional Beyond20 dice gets appended to the dice formula texts

**Comment by kakaroto** [comment]
Gif seems incomplete, so here's a screenshot of the issue : 
![image](https://user-images.githubusercontent.com/27990/79669808-4d451900-818c-11ea-92a1-6ed8e67a2ebd.png)
