### ISSUE TITLE
[Bug] Character Specific special dice rolls feature not showing up for players

### ISSUE THREAD

**Issue by SpectreWulf** [kakaroto/Beyond20#184]
I just had a full DnD 5e session with my players today and I noticed a few major bugs:

1. The toggle menu option for Beyond20 for special class / race specific dice rolls (eg. Half-Orc's Savage Attacks, Disciple of Life from Life Domain Cleric, etc.) are not showing up for my players.

2. When I open the DnDBeyond character sheet and open the Beyond20 menu I can see the class / race specific special dice roll toggle menu, however my players cannot see the same for the same character sheet.

3. Also features like Great Weapon Fighting Style (where it re-rolls 1s and 2s on damage dice) on the attack roll is only triggering for me and not my players.

Campaign Details:
All players are part of my campaign created in DnDBeyond. 
Paid content sharing is enabled in DnDBeyond.

I have attached screenshots regarding these issues:-
-------------------------------------------
**Class / Race Menus not showing up for players**

DM View (for me):
![DM view](https://user-images.githubusercontent.com/21985784/79078777-30da5400-7d28-11ea-9f8f-cbe47c1376b4.jpg)

Player View for the same:
![Player View](https://user-images.githubusercontent.com/21985784/79078788-55cec700-7d28-11ea-85df-a30f119f9daf.jpg)

------------------------------------------
**Rogue Assassin subclass feature not showing up for players**

DM View:
![Rogue Class Feature DM View](https://user-images.githubusercontent.com/21985784/79079065-4fd9e580-7d2a-11ea-82af-dcc318a1c489.png)

Player View:
![Rogue Class Feature Player View](https://user-images.githubusercontent.com/21985784/79079067-56685d00-7d2a-11ea-9c1f-b70051b25973.jpg)

------------------------------------------

**Great Weapon Fighting Style issue:** 

DM Roll:-
![Great Weapons Style DM view](https://user-images.githubusercontent.com/21985784/79078791-67b06a00-7d28-11ea-9c5b-e05534bcdcdb.png)

Player Roll for the same weapon:-
![Great Weapon FIghting Style Player View](https://user-images.githubusercontent.com/21985784/79078909-33897900-7d29-11ea-94d9-5305cf120712.png)

**Comment by Aeristoka** [comment]
Have them click through (on their own PCs/Browsers) into Features/Traits, it'll show up.

![image](https://user-images.githubusercontent.com/7988297/79079969-79b1ee80-7ccf-11ea-90ca-92667ac44db6.png)

Beyond20 has to parse those, and they're not loaded enough for Beyond20 to parse without them clicking into there.

Have them do this EACH time they level up to, to make sure it stays current. Will have to be done on any different PC/Browser combo they use.

**Comment by SpectreWulf** [comment]
> 
> 
> Have them click through (on their own PCs/Browsers) into Features/Traits, it'll show up.
> 
> ![image](https://user-images.githubusercontent.com/7988297/79079969-79b1ee80-7ccf-11ea-90ca-92667ac44db6.png)
> 
> Beyond20 has to parse those, and they're not loaded enough for Beyond20 to parse without them clicking into there.
> 
> Have them do this EACH time they level up to, to make sure it stays current. Will have to be done on any different PC/Browser combo they use.

Aah I see, I will definitely test this the next time we have a session!

**Comment by kakaroto** [comment]
All 3 issues mentioned are side effects of the same root cause, which Aeristoka explained and is explained in more details in this FAQ item : https://beyond20.here-for-more.info/faq#i-have-a-class-featurefeat-that-the-features-page-says-is-supported-sharpshooter-feat-for-example-but-i-dont-see-the-option-to-use-it
Thanks for a thorough and detailed report :)

**Comment by SpectreWulf** [comment]
Thanks a lot for quick reply!
