### ISSUE TITLE
Conditions not syncing on FVTT

### ISSUE THREAD

**Issue by Brunhine** [kakaroto/Beyond20#185]
Conditions no longer syncing with FVTT.

per KaKaRoTo:

> the fix is that in fvtt_script.pyj, it does game.modules.find, but the array became an object, so should be Object.Keys(game.modules).includes("beyond20")

**Comment by Brunhine** [comment]
Closed with #187

**Comment by kakaroto** [comment]
Ah thanks for closing this. I usually put in the commit message "Fixed #185" to get github to auto close issues when I push the commits. Forgot about it here!
