### ISSUE TITLE
Add support for Colussus Slayer

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#186]
apparently similar to toll the dead, applies extra d8 if target is not at full HP

**Comment by Brunhine** [comment]
working on this

**Comment by Brunhine** [comment]
Including PR #192

**Comment by Aeristoka** [comment]
@kakaroto This was already merged into the Dev version, right?

**Comment by kakaroto** [comment]
Ah yeah, I guess that's what happens when the commit doesn't have "Fixes #186" in the commit message and I forget to do it manually!
Thanks
