### ISSUE TITLE
Request: Support for 5e.tools website

### ISSUE THREAD

**Issue by frango9000** [kakaroto/Beyond20#190]
https://5e.tools/

**Comment by kakaroto** [comment]
No. 5e.tools is an illegal copyright infringing website that I don't condone, support or want to get close to in any way, shape or form.

**Comment by frango9000** [comment]
Ok thx for the info, just found it searching for discord bots, could you please delete this?

**Comment by kakaroto** [comment]
Thanks for understanding. Deleting the issue.
