### ISSUE TITLE
Beyond20 FVTT message on ForgeVTT.com

### ISSUE THREAD

**Issue by Aeristoka** [kakaroto/Beyond20#193]
![image](https://user-images.githubusercontent.com/7988297/79185761-1a3e0680-7dd5-11ea-997d-4497f91f5439.png)

The above message appears when it shouldn't on ForgeVTT.com, as this site is whitelisted in Beyond20.

**Comment by kakaroto** [comment]
I don't think it does anymore, so I think this was fixed in eb376ab76830e0238f336128744a077f5d253e20
