### ISSUE TITLE
Beyond 20 not showing rolls on roll20.net anymore

### ISSUE THREAD

**Issue by Maretini** [kakaroto/Beyond20#194]
Hi guys,
Beyond20 has been working fine for me in the past, but for the past week or so it's not showing any rolls anymore after I click on the beyond20 logo or on display in VTT.
This is the same for both me and my players. When I do, it just shows my name in chat with a blank space behind it. 

When I click the attack in this screenshot:
https://gyazo.com/73c7647a042a5086900bbdefd4ca2841

This is what it shows like in Roll20:
https://gyazo.com/8a7a8596cf3d19bc2a2e578964c9e44e

Does anyone have any idea what might be wrong here? 

Extra info:
Using the extension on chrome with addblocker disabled.

Kind regards,
Maretini

**Comment by kakaroto** [comment]
Hi @Maretini, I'm going to blame your DM for that : https://beyond20.here-for-more.info/faq#all-i-see-in-roll20-is-an-empty-message
:)
