### ISSUE TITLE
Support for native Foundry VTT self hosted application as gamemaster

### ISSUE THREAD

**Issue by TheXanathar** [kakaroto/Beyond20#195]
As a DM/GM using Foundry VTT, I would love to have the ability to use Beyond20 without having to open a separate webpage and login to my own game that I'm hosting.

Can the module for FVTT Beyond 20 be looking for the inputs from the webpage on dndbeyond?

A DM/GM should be able to have total control online, that means if a player has connection issues or whatever the case may be, the GM can play for them.  The ability to use Beyond20 makes things go so much faster.

**Comment by kakaroto** [comment]
Beyond20 is a browser extension, it can only work within the same browser. The Foundry application is an Electron browser with no address bar and no support for installing extensions. For the same reason Beyond20 cannot send rolls from Chrome to Firefox, it cannot send rolls from Chrome to Electron.
The Foundry app is nothing more than a browser, what I suggest (and what I do) is to open it, don't login in it, just leave it running in the background, then login as GM in your browser.
This isn't about GM or not GM, it's simply about the technology not making it possible. Sending the rolls across to the other application would be the same as you clicking on your browser on your desktop and it sending it your other browser in your laptop. It's just not doable.
