### ISSUE TITLE
{REQUEST} Ability to adjust Critical range of attack rolls.

### ISSUE THREAD

**Issue by captnmorgan119** [kakaroto/Beyond20#196]
Certain feats, spells, weapons, and class abilities cause the critical range to be adjusted 19-20, 18-20. Depends on the reason Hexblade curse for instance, I also think the champion fighter has improved critical. Would be good to add an option in settings to adjust this. You can do it in roll 20 with  1d20cs>19. Thanks!

**Comment by Aeristoka** [comment]
I believe most all of these are already supported, so long as you click into the Features & Traits portion of the character sheet, which allows Beyond20 to parse them.

**Comment by captnmorgan119** [comment]
Can you tell me how to access those settings I have clicked into the features and traits tab but still see no settings for changing the critical range
