### ISSUE TITLE
More Options - Select where to send rolls to - Discord only

### ISSUE THREAD

**Issue by Alarich** [kakaroto/Beyond20#203]
In the KaKaRoTo discord channel, the user **Radkon** recently posed a question on how he would be able to send rolls only to discord without having the popup appear for the result in dndbeyond:
![image](https://user-images.githubusercontent.com/5496089/79549073-21983500-809f-11ea-8c58-4b96393134df.png)

Assuming this is the "D&D Beyond Dice Roller" mentioned in the setting on where to send rolls to, Beyond20 could benefit from having an additional option for "Discord only".
If it is not the Dice Roller, then perhaps there would be another way to disable the popup when sending rolls to Discord?

Setting in question:
![image](https://user-images.githubusercontent.com/5496089/79549229-6328e000-809f-11ea-99b7-f107dc0246c9.png)

**Comment by kakaroto** [comment]
My answer from discord :
> @Radkon the reason for that is because if you have damage rolls separate, you'd have the "roll damages" button in that popup. I don't yet have a way for getting interaction from discord to know when the user wants to roll damages (I plan on using reaction emojis for that), so for now it's this way
also, the discord integration was more of a "it can also do this!" rather than a full fledged implementation. But yeah, seems like the discord rolling is going to be a big part of things now

**Comment by Aeristoka** [comment]
This has been fixed (for a bit now):
![image](https://user-images.githubusercontent.com/7988297/117358376-51b1a200-ae73-11eb-9fbb-0e091a369268.png)
