### ISSUE TITLE
Display custom modifiers on the modifier field

### ISSUE THREAD

**Issue by spisin** [kakaroto/Beyond20#204]
I hope rolls with modifiers show as this figure.
![roll](https://user-images.githubusercontent.com/63902131/79633363-f6e1d580-819f-11ea-9089-eff83b4ee3d5.jpg)

It displays custom modifiers on the modifier field. Then we don't have to mouseover on the results to check modifiers from now.

I have roll20.pyj for this. May I send my code?

**Comment by Aeristoka** [comment]
Send the PR, he'll look it over to see if he wants it.

**Comment by spisin** [comment]
I don't have a permission to push.

**Comment by Aeristoka** [comment]
You should be able to open a Pull Request

**Comment by kakaroto** [comment]
Thanks! That sounds like a useful change. You would need to send a Pull Request for it.
See github's normal workflow for contributing changes, it's explained here : 
https://gist.github.com/Chaser324/ce0505fbed06b947d962
If you **really** have issues doing it, you could send a patch (`git format-patch origin/master` I believe)

**Comment by spisin** [comment]
I could not select my branch for a Pull Request.

The patch is here.
[0001-Display-custom-modifiers-on-modifier-field-of-roll20.patch.tar.gz](https://github.com/kakaroto/Beyond20/files/4498080/0001-Display-custom-modifiers-on-modifier-field-of-roll20.patch.tar.gz)
