### ISSUE TITLE
All rolls are made twice

### ISSUE THREAD

**Issue by ThaScientist** [kakaroto/Beyond20#209]
Dont really know when it started, but beyond20 started rolling everything twice for me, unlike the advantage option the rolls are in sequence, changing the roll option from "normal roll" to "ask everytime" and then chosing "normal roll" in the dialog window makes it so attack roles are made normal again while checks and other rolls are still duplicated

Feels like the "normal roll" option in the menu is bugged to act as double roll or smth

**Comment by kakaroto** [comment]
Not sure why you closed this immediately after creating it, but I just noticed it.
This looks like a duplicate of #154 by the way

**Comment by ThaScientist** [comment]
I deleted it because I found it was a duplicate and it seems like I or Roll20 was experiencing lag which looks to be the cause of the issue
