### ISSUE TITLE
per-character settings may get confused if more than 1 sheet is open

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#216]
From Aeristoka :
>@KaKaRoTo If I have two separate DnDBeyond character sheets open at the same time, it appears that (at least) the weapon rolls (Both together/1 hand/2 hand) are overriden by the second character sheet
IE: I had 2 hand only set on 1st character sheet, Roll both on 2nd Character sheet

**Comment by Aeristoka** [comment]
Open 1 character sheet, have Versatile Weapon, set rolls to "2-hand only" (or 1-hand only). Open second character sheet, configure Versatile rolls to "Roll both" (or leave at defaults).

Rolls from 1st character sheet respect the settings of the 2nd character sheet.

**Comment by kakaroto** [comment]
I think this got fixed by the pyj -> js change, cause it works and the behavior seems to match what I expect (I did see it misbehave before too, but not anymore).
