### ISSUE TITLE
Digital dice integration

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#220]
'nough said :)

**Comment by cjol** [comment]
Is the vision for this to carry the result from the DDB roller into Roll20, or simply to trigger identical rolls within roll20 when a DDB roll is triggered? I can see the latter being a little annoying (getting rolls on multiple screens) but possibly more futureproof as DDB integrate their dice roller more deeply into new parts of the product.

**Comment by kakaroto** [comment]
The plan is to make the rolls in D&D Beyond and send the results only to the VTT. 
One issue with it is that the results will simply appear as numbers in Roll20 so you wouldn't be able to see the details of the roll from hovering over it. That's a limitation on Roll20 that I can't really do much about (and I assume it's also meant to prevent someone from faking results).
With Discord/Foundry, I won't have that problem though, so there's that at least.

"Use Digital Dice" will be an option that can be turned on/off, so those who dislike that behavior won't have to use it.

**Comment by adrianthewriter** [comment]
I'd like to see beyond20 hijack the digital dice buttons in dndbeyond and use them to trigger the roll in roll20 (instead of clicking in the side panel). The digital dice in dndbeyond look great, but they don't do me any good if I'm using roll20 with my party (who don't all use dndbeyond, including my DM). I'd rather have it work that way then trying to send dndbeyond's dice results to roll20 because then my DM can see I'm not cheating somehow because I'm still rolling with roll20.

**Comment by kakaroto** [comment]
> I'd like to see beyond20 hijack the digital dice buttons in dndbeyond and use them to trigger the roll in roll20 (instead of clicking in the side panel). The digital dice in dndbeyond look great, but they don't do me any good if I'm using roll20 with my party (who don't all use dndbeyond, including my DM). I'd rather have it work that way then trying to send dndbeyond's dice results to roll20 because then my DM can see I'm not cheating somehow because I'm still rolling with roll20.

That's why it would be an option. I don't plan on hijacking the digital dice (let's stay friendly with the D&D Beyond team, shall we?) but I'm thinking of possibilities of making both digital dice and beyond20 rollable easily.
About to start my [stream](https://twitch.tv/KaKaRoToDM) working on this, so we'll see how it goes
