### ISSUE TITLE
additional critical option

### ISSUE THREAD

**Issue by mordrek70** [kakaroto/Beyond20#222]
hi there,  we were using a variant critical rule at out table game of dnd 5e.  instead of the normal double dice, we used the rule where you rolled the normal dice but you would add the max damage of a second dice.
for example, criting with a short sword, the damage would be 1d6+6+dex/str mod, indead of the 2d6+dex/str mod (or the (d6x2)+dex/str mod).  we found it made Crits more satisfying even if you rolled badly.
is it possible for this to be added in to the options? or can it be adjusted some how?

thnaks and regards

**Comment by kakaroto** [comment]
Hi, this is already supported. Choose the 'homebrew: perfect rolls' option in the critical hit rule settings.

![image](https://user-images.githubusercontent.com/27990/80347493-58f2a880-883a-11ea-8fcb-b73e07becf17.png)

**Comment by mordrek70** [comment]
Thanks,

The Homebrew description was vague and I did not understand this.

 

Regards

 

rod
