### ISSUE TITLE
Unable to get data into roll20

### ISSUE THREAD

**Issue by justinabrahms** [kakaroto/Beyond20#226]
Hi there. I just installed the extension (firefox on windows).

I have open my character sheet on DNDBeyond & our campaign on roll20. When I click the icons in DNDBeyond, I just get a blank message in roll20. I've hard-refreshed both tabs. Open to any other suggestions.

<img width="223" alt="empty-messages" src="https://user-images.githubusercontent.com/3853/80441245-60a86080-88bf-11ea-9324-948cb359dd3e.PNG">

**Comment by kakaroto** [comment]
Here's a suggestion 😄 
https://beyond20.here-for-more.info/faq#all-i-see-in-roll20-is-an-empty-message
