### ISSUE TITLE
Arrow of Slaying rolls incorrectly

### ISSUE THREAD

**Issue by Aeristoka** [kakaroto/Beyond20#233]
An Arrow of Slaying (rolled only from a PC Character sheet) rolls incorrectly

![image](https://user-images.githubusercontent.com/7988297/80919732-f2352980-8d28-11ea-9415-2a54a08d615b.png)

Perhaps improperly parsing the attack part of the block for the Arrow of Slaying? Specifically happens when clicking the "Beyond 20" button.

![image](https://user-images.githubusercontent.com/7988297/80919750-011bdc00-8d29-11ea-992b-72547998be98.png)

**Comment by kakaroto** [comment]
Humm.. I'm not sure why the first damage is "--" but I feel like this is maybe more of a D&D Beyond bug because it's displaying things improperly?
I'm not sure how or whether I should handle damages of type "--"

**Comment by Aeristoka** [comment]
Definitely hard to say, since it is just a (very special) piece of ammunition, that you have to shoot (so they included an attack block? but with no attack stats?), and it really should just be an additional damage roll.
