### ISSUE TITLE
Versatile also rolls two-handed damage by default when shield equipped

### ISSUE THREAD

**Issue by Rarst** [kakaroto/Beyond20#236]
Observed a player over a couple of games repeatedly confused about both "Total Damage" and "Total Two-Handed Damage" showing up on a versatile weapon roll. They were trying to add it up together or pick two-handed damage while having shield equipped.

If it is possible to detect that shield is equipped (it does show up in AC breakdown if that helps) it would make sense to omit two-handed damage from the roll by default.

As a general suggestion maybe make it more clear when choice is mutually exclusive?

E.g. instead of:
> **Total Damage:** 1
> **Total Two-Handed Damage:** 2

Have it say something like:
> _Choose:_
> **Total One-Handed Damage:** 1
> _or_
> **Total Two-Handed Damage:** 2

**Comment by kakaroto** [comment]
I think it's a good suggestion to change the "Total Damage" into "Total One-Handed Damage" but adding a "Choose" with 'or' is just going to bloat the text in my opinion.
By the way, if your player isn't aware, they can set their character options to always use versatile weapons single handed, just click the beyond20 icon in the addressbar from within their D&D Beyond character sheet.

**Comment by Rarst** [comment]
> By the way, if your player isn't aware, they can set their character options to always use versatile weapons single handed

I recommended the extension to the group, but I am not the DM. Awkward to intrude on their turn to deal with settings. :) So pondering how this could be more clear out of the box.
