### ISSUE TITLE
Dice Roller UI disables Beyond20

### ISSUE THREAD

**Issue by Inshal240** [kakaroto/Beyond20#238]
I cannot make Beyond20 rolls with the DNDBeyond's Dice Roller enabled. 
![image](https://user-images.githubusercontent.com/5384262/81102834-7d244880-8f10-11ea-92d3-aa7f00d162b1.png)

One needs to find the part of Beyond20's bounding box by hovering around DNDBeyond's roller elements like so.
![image](https://user-images.githubusercontent.com/5384262/81103146-ec9a3800-8f10-11ea-9e87-7d29e97ce5a9.png)

**Comment by shaneknows** [comment]
You can work around this for now by disabling the feature under the character drop down.

![image](https://user-images.githubusercontent.com/4079954/81105470-f5274a00-8ee1-11ea-8557-a4824cc19358.png)

**Comment by kakaroto** [comment]
First of all, what you're thinking of/talking about is the Beyond20 "quick rolls" feature which is just a shortcut. Beyond20 is at its core and has always been about rolling from the sidebar windows (and the quick roll buttons only open the sidebar and simulate you clicking on the roll from there).
So really, just open the side panel and click beyond20 from there, at least until #220 is done and the next release is out.
![image](https://user-images.githubusercontent.com/27990/81115752-36bff100-8ef2-11ea-943a-c2014fe04260.png)
