### ISSUE TITLE
Great Weapon Fighting with Polearm Mastery Bonus Attack

### ISSUE THREAD

**Issue by thayertr** [kakaroto/Beyond20#239]
I searched on this list and the github and didn't see this one.  I think this is actually an issue with DNDBeyond not having the Two-Handed attribute on the Polearm Master Feat's Bonus Attack.  Great Weapon Fighting allows you to re-roll 1s and 2s on damage rolls made by a two-handed weapon, and the Bonus Attack would apply as it is using a two-handed weapon.  This was confirmed by Jeremy Crawford, and I added it as a bug/feature request on DNDBeyond.  I think a two-handed checkbox on the Bonus Attack would fix it on their end but was hoping you knew of a way on your end instead?

**Comment by thayertr** [comment]
![image](https://user-images.githubusercontent.com/64875051/81127193-721ae980-8f0b-11ea-8ec8-f2f19c4b298b.png)

**Comment by thayertr** [comment]
![image](https://user-images.githubusercontent.com/64875051/81127355-f2d9e580-8f0b-11ea-8b98-960190c3b796.png)

**Comment by thayertr** [comment]
![image](https://user-images.githubusercontent.com/64875051/81127406-1ac94900-8f0c-11ea-9bc8-988125b91e19.png)

**Comment by Aeristoka** [comment]
I believe I have this fixed in PR #232
