### ISSUE TITLE
Use browserAction for chrome and FVTT

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#24]
having an all_urls permission causes the chrome extension to spend a week in review on the chrome webstore. I need to use browser actions to avoid the broad permissions.
This will cause FVTT users to be forced to click the Beyond20 icon before it gets enabled but there doesn't seem to be another choice unfortunately.

**Comment by grufftech** [comment]
This is the issue that causes broken icons, correct?  

Double checking before I open a fresh issue. 


![image](https://user-images.githubusercontent.com/2072164/62646685-bd17ba00-b903-11e9-8e2a-a3b354e6848a.png)

**Comment by kakaroto** [comment]
Hi @grufftech, no it doesn't have anything to do with that. 
This issue is about making Beyond20 require less permissions from the browser so the chrome webstore doesn't take a week to review it every time I release an update. The consequence of doing that is that you'd have to click on the Beyond20 extension icon in the toolbar once for it to 'load on the current page' basically. 
Anyways, for your problem itself, I'd say you only see that broken icon on the main Electron app (since there is no chrome extension loaded in it) or on another player's instance when that player doesn't have Beyond20 installed. This is because you need to install (and enable) the Beyond20 companion module in FVTT. It's purpose is to fix the formatting and icons for the players who do not have the extension loaded. (also make sure it's up to date).

**Comment by kakaroto** [comment]
Done in 4cf32ae52e4e6ded7963b36725697d77679f0d28
