### ISSUE TITLE
PC/NPC Names on Roll Details lowercased in FVTT

### ISSUE THREAD

**Issue by Aeristoka** [kakaroto/Beyond20#248]
On Dev version of Beyond20, all PC/NPC names associated with any roll via Beyond20 -> FVTT are set to all lowercase text

![image](https://user-images.githubusercontent.com/7988297/81420858-ce4d5b80-910d-11ea-8e27-242cd05090ed.png)

**Comment by kakaroto** [comment]
Guess saying "Fixes kakaroto:#248" doesn't get it auto closed for some reason.. I don't know 🤷
