### ISSUE TITLE
Great Weapon Fighting (maybe) should reroll all weapon damage dice

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#249]
including things like Flame Tongue dice .
Will need to check exact wordings and how it's meant to be ruled and confirm first.

**Comment by Aeristoka** [comment]
https://rpg.stackexchange.com/questions/94046/which-damage-dice-exactly-does-the-great-weapon-fighting-fighting-style-allow-yo

Makes an argument for yes, but also might just be Crawford's personal game ruling?

**Comment by Aeristoka** [comment]
https://twitter.com/jeremyecrawford/status/988279492698296321?lang=en

That seems to indicate Yes, GWF rerolls all Damage Dice of a weapon
