### ISSUE TITLE
Mithril Chain Armour imposing strength and dex penalities when it shouldn't

### ISSUE THREAD

**Issue by GrayedFox** [kakaroto/Beyond20#250]
Link to D&D beyond description: https://www.dndbeyond.com/magic-items/mithral-armor

"Mithral is a light, flexible metal. A mithral chain shirt or breastplate can be worn under normal clothes.

If the armor normally imposes disadvantage on Dexterity (Stealth) checks or has a Strength requirement, the mithral version of the armor doesn't."

The player/character should not have any strength or dexterity penalties when wearing a Mithril version of an armor even if they are not proficient in that armor.

![image](https://user-images.githubusercontent.com/6493307/81448788-456f0800-917f-11ea-9f4a-f4564a2e28c0.png)

Thanks for the great work :) just thought I'd post this issue

**Comment by Aeristoka** [comment]
that is 100% a DnDBeyond issue. I would file an issue with them. Those Disadvantage badges are still basically brand-new, so their code for that isn't working 100% yet.

**Comment by kakaroto** [comment]
The disadavtange icon is added by D&D Beyond and has nothing to do with Beyond20, so this looks like it's a D&D Beyond bug and should be reported to them directly.
Thanks.

**Comment by GrayedFox** [comment]
My mistake, thank you for pointing out. I just noticed it's also purely an aesthetic - the actual rolls are not affected (just a very, very misleading icon). Best.
