### ISSUE TITLE
Custom Roll dice ignore for initiative in roll renderer

### ISSUE THREAD

**Issue by mshow1323** [kakaroto/Beyond20#253]
Can you add an initiative modifier to Custom Roll dice formula bonus?
Sometimes Guidance or Gift of Alacrity are added as initiative modifier.  After all, the Guidance Spell affects skill check rolls, and an Initiative roll is a skill check :)

**Comment by Jhazor** [comment]
yes if you put something in the Custom Roll dice formula bonus field it will be added if you roll initiative Beyond 20 just applies anything in that field to ALL d20 rolls so you just need to  remember to take it out again after rolling initiative

**Comment by mshow1323** [comment]
It doesn't work for initiative rolls

**Comment by mshow1323** [comment]
> yes if you put something in the Custom Roll dice formula bonus field it will be added if you roll initiative Beyond 20 just applies anything in that field to ALL d20 rolls so you just need to remember to take it out again after rolling initiative

It doesn't work for initiative rolls

**Comment by Jhazor** [comment]
I literally just tested it in Roll 20 myself - it combines the numbers automatically but if you have roll 20 actually roll the 3d dice or mouse over so you can see the actual macro formula - it's very clearly adding extra dice

![image](https://user-images.githubusercontent.com/59282727/81474013-a982e200-91fa-11ea-81ba-a7bc13551ff7.png)

**Comment by mshow1323** [comment]
Then I did something wong?

<img width="1023" alt="Screen Shot 2020-05-09 at 7 42 07 AM" src="https://user-images.githubusercontent.com/54748102/81474082-c7cfea00-91c8-11ea-8179-c72eece674c9.png">
<img width="604" alt="Screen Shot 2020-05-09 at 7 42 35 AM" src="https://user-images.githubusercontent.com/54748102/81474083-c9011700-91c8-11ea-98a0-8ee8e123fef5.png">

**Comment by Jhazor** [comment]
ok looks like a bug with Beyond 20's own internal roller it's not picking it up

**Comment by mshow1323** [comment]
Got it...it's a hiccup when you're not using you Roll20 and just using the script.  It wourks correctly directly into Roll20

**Comment by mshow1323** [comment]
So basically, unless I have Roll20 open, it won't work correctly....I had dreams of using this at the table in live games too
Thanks Jhazor

**Comment by Jhazor** [comment]
I expect this will get flagged as a bug and corrected

**Comment by kakaroto** [comment]
Yep, if it gets ignored for the internal roller, then that's a bug, thanks for reporting it, will get to fixing! :)

**Comment by kakaroto** [comment]
Tested this and seems to have been fixed already in the development version from some other recent change.

**Comment by mshow1323** [comment]
<img width="1105" alt="Screen Shot 2020-05-16 at 6 48 06 AM" src="https://user-images.githubusercontent.com/54748102/82119092-4be21e80-9741-11ea-9c97-522c73447589.png">
<img width="776" alt="Screen Shot 2020-05-16 at 6 48 18 AM" src="https://user-images.githubusercontent.com/54748102/82119096-4edd0f00-9741-11ea-9d3f-dc568e1d2c39.png">

**Comment by mshow1323** [comment]
It still isn't working correctly

**Comment by kakaroto** [comment]
Are you using the development version ?

**Comment by mshow1323** [comment]
I doubt it. I'm a new user and just started using it last week, so I would say that its unlikely

**Comment by kakaroto** [comment]
In that case, it's normal for it not to work, as you can see, this was fixed **yesterday** and the last update to the extension was from April 9th. You have to wait until the next release before checking if it indeed is fixed or not. You can follow the progress for the next release on this milestone to see how far along I am to get a release ready https://github.com/kakaroto/Beyond20/milestone/5
The README of this repository explains how to manually install the development version of the extension if you really can't wait.

**Comment by mshow1323** [comment]
Awesome, thanks
