### ISSUE TITLE
Always Roll Advantage

### ISSUE THREAD

**Issue by mshow1323** [kakaroto/Beyond20#254]
In native Roll20 toggling on Always Roll with Advantage, still prevents rolling initiative with advantage.
In Beyond20 toggling Always Roll with Advantage is causing  2 d20s to roll, and add the result together.
Is there a way to make it work like native Roll20?

**Comment by mshow1323** [comment]
Never mind

**Comment by kakaroto** [comment]
For Roll20, since only the number displayed gets sent to the tracker using their macro, I can't have it roll 2 separate results as it wouldn't know which one to add, so it had to be done using a `2d20kh1` dice formula instead, which means roll 2d20 and **k**eep the **h**ighest one.
