### ISSUE TITLE
Polearm Master Bonus Action attack

### ISSUE THREAD

**Issue by alanlawton** [kakaroto/Beyond20#258]
Is it possible to associate the Bonus Action attack from the Polearm Master feat with a weapon, so that any magical bonuses to attack and damage associated with a weapon apply to this attack as well.

**Comment by kakaroto** [comment]
You can't associate spells or magical bonuses to an attack (not even a regular one).
What you can do is customize the weapon in D&D Beyond to give it the bonuses you want.
