### ISSUE TITLE
clicking spell attack custom icon doesn't respect advantage

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#261]
Referring to this 
![image](https://user-images.githubusercontent.com/27990/81517993-a119cc80-930a-11ea-99dc-201a9e835344.png)

**Comment by OrbitalBliss** [comment]
Also, these Quick Roll Areas does not "mouse pointer when hovering on it" and don't show the Quick Roll Tooltip/Arrow.

**Comment by kakaroto** [comment]
Those aren't quick roll areas, they are custom dice buttons. They contain all the information needed to make the roll. The Quick roll areas are areas you can click which will automate the process of opening the side panel and emulating a click on the "Beyond20" button within that side panel. That's not the case for these spell attacks.
