### ISSUE TITLE
Add Support For Rolling Equipment (E.G Tools & Playing Cards)

### ISSUE THREAD

**Issue by 36ve** [kakaroto/Beyond20#27]
Need a button that doesnt output the text and description of the tools but allows you to roll with profienciy and skill (if any) certain equipment items such as tools and playing cards.

**Comment by kakaroto** [comment]
Humm.. I could make it handle "tool" items differently and give that option automatically. The way I've been doing it is that if you have proficiency with something, you just create a custom skill instead. For example, I added a custom "Thieve's tools" skill to my skills list, and if set it as proficient. If you don't specify the ability, it will query you for it in the VTT. 
If you don't have proficiency, then you'd just be clicking on the ability itself to roll.
![image](https://user-images.githubusercontent.com/27990/61651872-c4dd2a80-ac84-11e9-9560-0dc62e8fd35e.png)
