### ISSUE TITLE
Spells doing null damamge

### ISSUE THREAD

**Issue by Knight6254** [kakaroto/Beyond20#272]
![TEst](https://user-images.githubusercontent.com/65407747/82061687-a4a4af00-968e-11ea-98f8-e2110f08af81.gif)
Since spells cannot be cast from a monsters sheet I was going to the spells page and using the in-text rolls to do so. However, I noticed those rolls did not have the beyond20 format and also if you apply damage with them it simply sets hp to 0.

**Comment by Aeristoka** [comment]
@kakaroto I observed this last night in my game as well, it appears that the spell rolls (for just damage) are not being formatted into Beyond20 Rolls, and those rolls don't apply damage properly.

Casting from Spell Slot, works properly:
![image](https://user-images.githubusercontent.com/7988297/82062368-3e685e00-9687-11ea-9407-81b9b66a58e6.png)

![image](https://user-images.githubusercontent.com/7988297/82062384-44f6d580-9687-11ea-9fbc-41ed8402649f.png)

Cast from "Cast on VTT" works properly:
![image](https://user-images.githubusercontent.com/7988297/82062438-56d87880-9687-11ea-9d4c-5e49a9e839a2.png)

![image](https://user-images.githubusercontent.com/7988297/82062477-6788ee80-9687-11ea-8558-b68e3c2c27fb.png)

Cast from Quick Roll in body of text, doesn't send a Beyond20 formatted message:
![image](https://user-images.githubusercontent.com/7988297/82062540-812a3600-9687-11ea-9674-129dcf696ac4.png)

![image](https://user-images.githubusercontent.com/7988297/82062573-89827100-9687-11ea-8565-54e4ddd5f3c0.png)
