### ISSUE TITLE
Life Transference error in Foundry message in Dev version (?)

### ISSUE THREAD

**Issue by pandanielxd** [kakaroto/Beyond20#273]
Earlier I noted a bug with Life Transference not doubling healing, I saw that this issue got fixed yesterday on stream, but with changing the healing value to a string, the Total Healing now seems to be bugged (at least on the stream it was, and it was committed that way) showing undefined. 

This might have been fixed at a later point in the stream though.. but not from what I could see :).

![s3pljNy](https://user-images.githubusercontent.com/65407753/82062033-c96a4800-96c9-11ea-81db-57541e0c2d80.png)

**Comment by kakaroto** [comment]
This seems to be fixed now that I've tried it. It shows 0 though, which isn't great, but better than undefined, and don't think there's much I can do about that now.
