### ISSUE TITLE
Butchers Bib

### ISSUE THREAD

**Issue by Fairburne** [kakaroto/Beyond20#274]
I don't know if this is a bug or if I am just to stupid to figure it out.  I have the butchers bib on a character.  It's attuned on DnD Beyond but when using Beyond 20 and I roll a 19 it does not recognize that as a crit.  Is there something I can do to make it work?  As of now I just have to remember that a 26 at my current level +7 to attack is a crit.  I forget that a lot.

**Comment by Aeristoka** [comment]
Can you post a link to the item in question? Is it Homebrew? Maybe a link to the character sheet as well.

**Comment by Fairburne** [comment]
It's a new item from Wildemount.  https://ddb.ac/characters/24386293/UZYRdk

**Comment by kakaroto** [comment]
Even as homebrew, D&D Beyond doesn't have the concept of what is a crit and what isn't. Beyond20 supports the special class features (Improved Critical, Superior Critical) that grant that effect, but it doesn't support magical items as it can be complicated (homebrew, is it equipped, is it attuned, etc.. and we don't track the equipment at this time anyway).
Beyond20 provides a convenience of making rolls easier, so it does the roll for you and does the math, but you still do have to check your rolls and remember what class features and other abilities your character has.

**Comment by Fairburne** [comment]
So I just have to do a better job remembering that a 26 is a crit.  Oh well I was hoping.

**Comment by kakaroto** [comment]
Well, you are playing a game that usually requires you to roll the dice yourself :p With the digital dice integration coming soon, it will be better I assume as you'd see the dice and seeing the 19 should make it easier to remember.

**Comment by Fairburne** [comment]
Not seeing the 19 in Roll 20 is definitely a part of it. I just have to do
a better job of reminding myself.
