### ISSUE TITLE
Rolling Initiative with with advantage in Roll20

### ISSUE THREAD

**Issue by mshow1323** [kakaroto/Beyond20#275]
Normally when we roll with advantage it shows the two rolls separately in the chat box.  However, when rolling initiative with advantage inside Roll20, it does the replacement for you.  
I believe it's caused by 2d20kh1.  Is there a way to recode this to the typical rolling with advantage script?

**Comment by kakaroto** [comment]
No it's not possible because when rolling initiative and adding it to the tracker, you can only add one number to the tracker, which is why it does it this way.
If you disable the option to add to tracker, it should show the two rolls separately though.

**Comment by jrichview** [comment]
That works. I'll just have to turn it back on when playing my other characters. Thx.

**Comment by jrichview** [comment]
That works. I'll just have to turn the option back on when playing characters that don't have advantage on initiative.
