### ISSUE TITLE
How do we enable DDB Dice Roller integration in Beyond20? 

### ISSUE THREAD

**Issue by jfabre** [kakaroto/Beyond20#276]
I'm sorry if it's a stupid question, 

but I would love to use the new dice roller from DDB to roll in Roll20 and I can't figure out how to enable it.

Thanks for your hard work.

**Comment by Aeristoka** [comment]
https://github.com/kakaroto/Beyond20#developer-mode-installation You'll have to have the dev version installed for now, as there is no official release (yet) that has the integration.
