### ISSUE TITLE
Tiebreaker Initiative doesn't work on Dev Version

### ISSUE THREAD

**Issue by Aeristoka** [kakaroto/Beyond20#277]
In src/dndbeyond/content-scripts/character.js the following:
![image](https://user-images.githubusercontent.com/7988297/82130625-3e04bb80-978a-11ea-8e96-185347729974.png)

returns 0 for all values except Dex (as it should), but the final return is Charisma, so tiebreaker is set to 0.

**Comment by kakaroto** [comment]
Nice catch..
I've seen your 2 PRs, but the cause is the pyj to js conversion. the proper fix is this : 
```js
return acc + (abi[1] == 'DEX' ? parseInt(abi[2]) : 0);
```

**Comment by Aeristoka** [comment]
Way more prettier
