### ISSUE TITLE
Parsing Issue for Odd Monster Damage Formatting

### ISSUE THREAD

**Issue by Aeristoka** [kakaroto/Beyond20#283]
https://www.dndbeyond.com/monsters/orc-war-chief

Has a damage block on "Greataxe Attack" that is not being parsed properly:
![image](https://user-images.githubusercontent.com/7988297/82348222-cc10ba00-99b5-11ea-8565-b51c07e6d52f.png)

Rolls as:
![image](https://user-images.githubusercontent.com/7988297/82348276-dcc13000-99b5-11ea-8306-5be4192821fe.png)

**Comment by kakaroto** [comment]
took forever to get a regexp that would work, but I got it.
