### ISSUE TITLE
Expanded critical range

### ISSUE THREAD

**Issue by Mangoray** [kakaroto/Beyond20#285]
My DM recently handed out an item which lowers the critical range by one. so a natural 19 and 20 both crit.
He mentioned it stacks with the Improved Critical feature from Fighter/champion subclass.
So that means the weapon crits on 18,19 and 20.

However, DNDbeyond doesn't support a custom critrange on items.

Is it possible to add a custom Critrange to rolls as a feature in Beyond20?
(in roll20 it's possible to do so with /roll 1d20cs>18 )

**Comment by HaarisQureshi** [comment]
I'd love this too! Also got an item from my DM that does this. Would also be useful for the Improved Crit feature

**Comment by freddieknets** [comment]
I'd absolutely love this too!

Ideally it would get this from a specific keyword in the description of the item (homebrew obviously) but I'd already be very thankful if this could be a general option to switch on and off in the options menu, like the rage for a barbarian.

**Comment by Aeristoka** [comment]
> I'd absolutely love this too!
> 
> Ideally it would get this from a specific keyword in the description of the item (homebrew obviously) but I'd already be very thankful if this could be a general option to switch on and off in the options menu, like the rage for a barbarian.

I agree that would be cool, but I believe the thought process we've been heading down is putting it as a Setting in Beyond20 instead, so you'd have to configure it, but you can set it to whatever you need in settings.

**Comment by freddieknets** [comment]
Sure, that would be a nice addition already. What about an intermediate solution? Keep it as a setting in Beyond20, but allow it to be set for each weapon independently (Beyond20 should easily be able to read the weapons you have from your equipment list). Most strength-based characters have a few backup weapons (possibly ranged) for which the expanded crit range wouldn't apply. That why one can avoid confusion.

**Comment by Aeristoka** [comment]
> Sure, that would be a nice addition already. What about an intermediate solution? Keep it as a setting in Beyond20, but allow it to be set for each weapon independently (Beyond20 should easily be able to read the weapons you have from your equipment list). Most strength-based characters have a few backup weapons (possibly ranged) for which the expanded crit range wouldn't apply. That why one can avoid confusion.

I doubt that will be looked at (per weapon). That is an absolute nightmare of settings to keep track of.

**Comment by freddieknets** [comment]
Mm not necessarily.
That way, one only needs to change the Beyond20 settings once: when making the character sheet (or when getting a new weapon).
In the way you mention, one needs to change the Beyond20 settings every time when switching the attack to a different weapon (which typically happens several times per encounter), easily leading to confusion when forgetting to do so (I already often forget to put off the barbarian rage, which is only once per encounter).

**Comment by Aeristoka** [comment]
> Mm not necessarily.
> That way, one only needs to change the Beyond20 settings once: when making the character sheet (or when getting a new weapon).
> In the way you mention, one needs to change the Beyond20 settings every time when switching the attack to a different weapon (which typically happens several times per encounter), easily leading to confusion when forgetting to do so (I already often forget to put off the barbarian rage, which is only once per encounter).

You misunderstand, the CODE to keep track of that would be a nightmare, and likely not worth it.

**Comment by freddieknets** [comment]
Ah ok, then I misunderstood indeed. Thanks for the reply
