### ISSUE TITLE
Disciple of Life bonus is gone

### ISSUE THREAD

**Issue by Silverbojangles** [kakaroto/Beyond20#286]
The "disciple of life" feature for Life clerics is no longer added to the healing rolls in Roll20

**Comment by Aeristoka** [comment]
No it's not?
![image](https://user-images.githubusercontent.com/7988297/82515406-6156a000-9ad5-11ea-8756-890a85bcf0f9.png)

https://beyond20.here-for-more.info/faq#i-have-a-class-featurefeat-that-the-features-page-says-is-supported-sharpshooter-feat-for-example-but-i-dont-see-the-option-to-use-it

**Comment by Silverbojangles** [comment]
I can only speak for myself, 
![Capture](https://user-images.githubusercontent.com/65690390/82571122-1f1a7680-9b48-11ea-9ca6-12004b6f01c4.JPG)
and it is not working for me

**Comment by Aeristoka** [comment]
> I can only speak for myself,
> ![Capture](https://user-images.githubusercontent.com/65690390/82571122-1f1a7680-9b48-11ea-9ca6-12004b6f01c4.JPG)
> and it is not working for me
> and I no longer see an option to turn it on.
> ![Capture](https://user-images.githubusercontent.com/65690390/82571335-6e60a700-9b48-11ea-8085-6451c8b9e454.JPG)

Can you send me a link to the character?

**Comment by Silverbojangles** [comment]
Sure!
https://ddb.ac/characters/29027071/vH0Vbl

**Comment by Aeristoka** [comment]
![image](https://user-images.githubusercontent.com/7988297/82574333-26d81c00-9b44-11ea-932e-6c32be6f243e.png)

Make sure to click over to "Features & Traits" to make it parse the Features & Traits properly.

**Comment by Silverbojangles** [comment]
Alright, maybe I am looking at the wrong place for "features and traits". Where can I find it?

**Comment by Aeristoka** [comment]
![image](https://user-images.githubusercontent.com/7988297/82575853-3bb5af00-9b46-11ea-9589-b06cd07f4313.png)

Beyond20 requires that once when you first use a new character with Beyond20 (and every time you level up/add a feat) you click on this button so that it actually LOADS (just based on how DnDBeyond works) so that Beyond20 can parse it.

**Comment by Aeristoka** [comment]
I believe this should be closed.
