### ISSUE TITLE
Savage Attacks is ignored for one handed versatile weapons

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#287]
From a ko-fi comment. Need to check it out and confirm/fix
> One thing, for a Half Orc character rolling a Nat20 with a versatile weapon, it looks like it only rolls the savage attacks extra damage die for the 2 handed option.

**Comment by Aeristoka** [comment]
Just verified, it doesn't IGNORE the damage, but it mis-classes it under "Brutal Critical" (it was written up along with Barbarian Brutal Critical I assume). See my PR #282 which separates Savage Attacks from Brutal Critical.

However, if you DO have a versatile weapon, and have it "Roll Both Damages Separately" it ONLY adds the "Brutal Critical" (savage attacks) damage as the secondary (two-handed) damage die.
![image](https://user-images.githubusercontent.com/7988297/82601144-51d66600-9b6c-11ea-9389-a8e290a958ea.png)

When you do a 1-handed only or 2-handed only roll, both roll their "Brutal Critical" (Savage Attacks) damage properly.

**Comment by kakaroto** [comment]
Will not fix.
Rolling both single and two handed is a convenience and should not be used in special situations like having Savage Attacks. Selecting the way the versatile weapon is handled would be required in that case.
