### ISSUE TITLE
QuickRoll tooltip doesn't fire for saving throws

### ISSUE THREAD

**Issue by kbuzsaki** [kakaroto/Beyond20#290]
It looks like the updated character sheet might have broken how the quickroll tooltip is implemented for saving throws.

In particular, there's now a "background" svg image `.ddbc-box-background` that comes before the content in the z index, which eats any mouse events that would have gone to the saving throw modifier box and triggered the tooltip.

One way to fix this is to add the `pointer-events: none;` property to those elements or to the `.ddbc-box-background` css class. That seems to have fixed the issue for me and I don't see any immediate drawbacks for it.

I'd send a pull request, but I'm not sure what the right way to do this in a chrome extension is, I'm just hacking around :)

**Comment by Aeristoka** [comment]
Is this on the official 1.1 version? Or the Dev version from GitHub?

**Comment by kbuzsaki** [comment]
This issue is present on both versions for me.

**Comment by kakaroto** [comment]
Hey, was about to say "It's a known issue, no idea why it happens, drove me crazy" but there you go, coming up with the solution too! Thanks :D
I'd have to check what that background is that eats up the mouse events and whether it's safe to disable pointer events to it, but at least that's a solution! Thanks!
As for how to fix it, there's a beyond20.css file in the src where overriding the `.ddbc-box-background` css
