### ISSUE TITLE
Support for Homerule: Critical Hit damage

### ISSUE THREAD

**Issue by Ryuichiro** [kakaroto/Beyond20#30]
Optional Critical Hit damage rules:
- [ ] additional roll is always perfect e.g.
Great Axe crit damage bonus would be *12* instead of *1d12*.
- [ ] add weapon attribute to crit roll e.g.
Great Axe crit damage bonus would be *1d12 + {STRmod}* instead of *1d12*.
- [ ] additional roll mirrors the normal role.

**Comment by kakaroto** [comment]
That's a good idea. I don't know how I'd like to set it up because I don't want to overflow with config options. But I might add a separate options menu just for "Homebrew rules". With regards to Critical damage, there should be a 3rd option of 'double damage' instead of rerolling dmg dice.

**Comment by Ryuichiro** [comment]
I thought about allowing formulas with their own custom syntax so it could be reused for other homebrew formulas in the future, but that's way more work and I've no idea how to compile with make on windows.
