### ISSUE TITLE
Versatile Weapons Improperly Reading Brutal Critical Hits

### ISSUE THREAD

**Issue by Seraluke** [kakaroto/Beyond20#306]
I don't know if this has been address or not, but with versatile weapons it rolls the higher dice damage and not both of them when a brutal critical hit happens. For example, a half-orc wielding a warhammer one-handed should roll an extra 1d8 when a critical hit happens, not a 1d10 as is the case.
![Screen Shot 2020-05-28 at 9 47 50 PM](https://user-images.githubusercontent.com/66101797/83215558-e290e100-a12c-11ea-9632-a8d967b9e412.png)

**Comment by Aeristoka** [comment]
1. Set your weapon damage to ONLY roll 1-handed (or 2-handed) as the case may be
![image](https://user-images.githubusercontent.com/7988297/83216173-de14fa00-a125-11ea-9576-c6552a839bbf.png)
2. @kakaroto has stated this is a wontfix, as it is quite complicated, and you should only be rolling one type (1-handed/2-handed) anyhow, the Versatile "Roll Both" is just a convenience

@kakaroto This can be closed

**Comment by Seraluke** [comment]
Just saw the pull request. Thanks for letting me know!
