### ISSUE TITLE
Crimson Rite damage does not apply to Unarmed Strike - Claws

### ISSUE THREAD

**Issue by RFrench90** [kakaroto/Beyond20#313]
The extra damage from the Blood Hunter's 'Crimson Rite' feature can be active on the Lycan subclasses 'Unarmed Strike - Claws' attack. Beyond20 does not represent this in Roll20.

After allowing the extension to parse the Features & Traits tab on the DnDBeyond Character sheet, the switch for "Bloodhunter: Crimson Rite - Add Crimson Rite damage" appears. Once activated, Roll20 properly reports Crimson Rite damage.

After switching the character into "Hybrid Transformation" (Class Feature of the Lycan Blood Hunter)via the editor, and clicking through the features tabs again, I return to the actions tab and use Beyond 20 to attack with 'Unarmed Strike - Claws (DEX)'.

The attack shows up in Roll20, but does not carry Crimson Rite damage.

I have tried turning the CR switch on and off. I have tried reinstalling the extension and making it's first "look" at the character sheet one with Hybrid Transformation active. In every case, attacks with normal weapons apply Crimson Rite damage, but Unarmed Strike - Claws does not.

Hope this makes sense.

Ross

**Comment by Aeristoka** [comment]
@RFrench90 Do you have a Character Sheet link you can give me for testing? I bet I can get this fixed up for you.

**Comment by RFrench90** [comment]
Hi Jared,

Thanks very much! The character sheet I was looking at is here:
https://ddb.ac/characters/27616512/kzNEHp

Let me know if there's anything else I can do.

Ross

**Comment by Aeristoka** [comment]
@RFrench90 Hop on over to the Discord if you would, and ping me there: https://discord.gg/24TZ2F

**Comment by RFrench90** [comment]
Hi Jared, I wish I could right now but I've been pulled into something.
What do you need me to do?

Ross

**Comment by Aeristoka** [comment]
Just ease of communication:
![image](https://user-images.githubusercontent.com/7988297/83290291-a6e52e00-a1a3-11ea-9935-c4b7cb5440d5.png)

Got it fixed, I'll be opening a Pull Request for @kakaroto to look over.

**Comment by RFrench90** [comment]
Fantastic! Will you let me know if it goes live?

Great work guys!

Ross

**Comment by kakaroto** [comment]
Thanks for the detailed report @RFrench90 and @Aeristoka for the fix. I've merged it so should be available on the next release.
