### ISSUE TITLE
Elemental Adept doesn't apply "min2" suffix to Critical Hits

### ISSUE THREAD

**Issue by Aeristoka** [kakaroto/Beyond20#319]
Main Damage Roll:
![image](https://user-images.githubusercontent.com/7988297/83340078-3ddbe400-a291-11ea-8b71-254f59bcf283.png)

Critical Damage Roll:
![image](https://user-images.githubusercontent.com/7988297/83340081-4af8d300-a291-11ea-9d78-2cde8b8b4f40.png)

**Comment by kakaroto** [comment]
Whatchadowin man! Why you keep opening these issues! I don't deserve this!
😭

**Comment by kakaroto** [comment]
I mean, thanks for finding this! Well done! Appreciated! 👍
