### ISSUE TITLE
Toll the Dead acts strangely

### ISSUE THREAD

**Issue by OrbitalBliss** [kakaroto/Beyond20#326]
Toll the Dead still seems to work strangely.
When cast (by a 5th level caster), If I tell it the target has NOT taken damage... it rolls 2d8 & 2d12 for damage and combines them.
If I tell it the target has taken damage... it rolls 2d12 twice and again combines the rolls for the total.

Just double checked with 1st level character.  Same thing.
If I say yes damaged, it rolls 2d12 total.
If I say no, it rolls 1d8 & 1d12 and combines for the total.

**Comment by OrbitalBliss** [comment]
![image](https://user-images.githubusercontent.com/6807265/83480496-8e0d9e80-a469-11ea-8438-1c2ff3f6a148.png)

![image](https://user-images.githubusercontent.com/6807265/83480618-e5137380-a469-11ea-8e23-60fd4ff20528.png)

![image](https://user-images.githubusercontent.com/6807265/83480679-096f5000-a46a-11ea-9d7e-680e3e2896cd.png)

**Comment by kakaroto** [comment]
weird, can you link me to your character sheet, and/or show a screenshot of the side panel of the spell ?

**Comment by OrbitalBliss** [comment]
![image](https://user-images.githubusercontent.com/6807265/83486969-2c086580-a478-11ea-9b17-343e6d1aa723.png)

https://www.dndbeyond.com/profile/OrbitalBliss/characters/18474195

**Comment by OrbitalBliss** [comment]
No!  I found it.  I still had access to a Homebrew version of TtD from another player, that was what was added to the character, not the real TtD... now i've turned off the homebrews from them,  Real Toll the Dead works fine.
Was really convincing because it asked for the Damaged target confirmation and everything!!!
Sheesh.  Embarassing.

**Comment by kakaroto** [comment]
Embarrassing PEBKAC error indeed 😝
At least it's not my bug! Not much i can do but bury this thread.
