### ISSUE TITLE
Barbarian Indomitable Might

### ISSUE THREAD

**Issue by Aeristoka** [kakaroto/Beyond20#329]
https://www.dndbeyond.com/classes/barbarian#IndomitableMight-69

Indomitable Might
Beginning at 18th level, if your total for a Strength check is less than your Strength score, you can use that score in place of the total.

**Comment by Aeristoka** [comment]
@kakaroto I haven't found a very clean way to implement this yet, as this isn't like Rogue Reliable Talent {1d20, 10}kh1 + @modifier, this is {1d20+@modifier, @StrengthScore}kh1

**Comment by kakaroto** [comment]
`1d20min${score - modifier}` :)
