### ISSUE TITLE
Cast spell on monster details page

### ISSUE THREAD

**Issue by ParadoxGery** [kakaroto/Beyond20#33]
if I run an encounter with a spellcasting monster I open up the monster details page to see its spells
I can click the to hit button to roll the hit but then if I need to roll damage I first need to open the spell page to klick the damage roll

**Comment by kakaroto** [comment]
There's nothing that can be done for that, there is no way of clicking inside of the tooltip. If you have an idea on how to make it work, I'm open to suggestions.

**Comment by ParadoxGery** [comment]
would it be possible to follow the link or parse the popup content?

**Comment by kakaroto** [comment]
Ok, I've investigated this a bit, and it looks like I can fetch the tooltip's content. I was worried about the fact that long spells are cropped, but the server returns the full description, it's just the tooltip display that is cropped. Unfortunately, just like a spell page, there's no real information on how to do an attack (no to-hit, what damages, you do, etc..) and I'm not sure how to implement this. I was thinking of just parsing all the roll formulas and display them next to the spell but it would make things ugly... one other possibility that I just thought of, is to have a beyond20 icon next to each spell and clicking it would display the spell card in the VTT, then you can click those dice formulas from the VTT chat directly. That would work much better I believe.
Alright, that's the plan for now and I'll try to add this for the next release. If you have a better suggestion on how to best implement it, let me know.

**Comment by ParadoxGery** [comment]
as long as it will be whispered as by the setting whisper monster roll this sounds like a good plan
