### ISSUE TITLE
Digital Dice Initiative does not apply to the Turn Tracker

### ISSUE THREAD

**Issue by PeterMMurnaghan** [kakaroto/Beyond20#341]
When rolling initiative with Digital Dice enabled, the selected token does not get added to the turn tracker. Even if the token is already in the tracker, the initiative rolled is not applied to the tracker.

This only occurs with D&D Beyond Digital Dice enabled - disabling that feature (and the associated Beyond20 toggle) allows for tokens to have their initiative added to the turn tracker.

**Comment by kakaroto** [comment]
I'll have to check if it can still work, but there's a chance it's not possible because the 'add to tracker' is a dice rolling modifier macro in Roll20. If you're rolling in D&D Beyond, and only displaying the results in Roll20, it wouldn't work.

**Comment by kakaroto** [comment]
Tested today and can confirm that I can make it work 🥳 even with a static value roll, so this is fixable!
