### ISSUE TITLE
Using beyonds digital dice breaks roll20 display

### ISSUE THREAD

**Issue by nathanenns** [kakaroto/Beyond20#342]
When the option to use beyonds digital dice is off, it will display rolls using the D&D 5e roll20 sheet like normal, however once you toggle the option to use beyonds digital dice, it changes the output to use beyond20 roll renderer no matter what option is selected or if you are using the d&d 5e sheet.

**Comment by kakaroto** [comment]
Not a bug, it's by design. You either use the Digital Dice which render it for you or you use Roll20's sheet template which needs to do the rolls by themselves.
