### ISSUE TITLE
Can’t roll attack

### ISSUE THREAD

**Issue by kimvilla** [kakaroto/Beyond20#343]
I’m using the digital dice from DnD beyond. When I click on attack, it doesn’t send to Roll20. 
Also, all the saving throw or ability check are displayed "to hit" on Roll20.

**Comment by Aeristoka** [comment]
Second part is just a grammatical issue, it only affects the display.

Assuming you're on Beyond20 2.0, DO NOT click on the Beyond20 boxes for to-hit and Damage, click on the quick Rolls for Beyond20, or click on the weapon to pop out the box on the side.
![image](https://user-images.githubusercontent.com/7988297/83641851-538c2a80-a56b-11ea-856e-d2aef85b842c.png)
