### ISSUE TITLE
Hexblade Curse Toggle - Missing

### ISSUE THREAD

**Issue by StonefoxSB3** [kakaroto/Beyond20#345]
Since the update, I no longer have a toggle for attacking a hexblades cursed target as a warlock. it was incredibly useful and hopefully hasn't been removed purposefully.

**Comment by Aeristoka** [comment]
Do you have a character sheet link I can test with?

**Comment by StonefoxSB3** [comment]
https://www.dndbeyond.com/profile/stubaker3/characters/29704769

Is that what you need?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by StonefoxSB3** [comment]
https://ddb.ac/characters/29704769/4nqY50

Or this one

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Aeristoka** [comment]
Thanks, do you also have a screenshot?

**Comment by Aeristoka** [comment]
Nevermind, make sure you click to "Features & Traits" so it parses the features & traits. This is required to have DnDBeyond load those parts of the Character Sheet properly so they can be parsed by Beyond20:
![image](https://user-images.githubusercontent.com/7988297/83647345-08294a80-a572-11ea-94b9-611305673a8e.png)

**Comment by StonefoxSB3** [comment]
Thats great , appreciate the quick reply
