### ISSUE TITLE
Roll20 Character Sheet setting not formatting correctly in Roll20

### ISSUE THREAD

**Issue by Jacoloped** [kakaroto/Beyond20#346]
The campaign in Roll20 is set up with the D&D 5E by Roll20 character sheet and before the update the rolls would format correctly, but now they are formatting as the standard Beyond20 Roll Renderer.

**Comment by Aeristoka** [comment]
The D&D 5e formatting for Roll20 will only work if you disable Digital Dice on DnDBeyond. You get to pick one.
