### ISSUE TITLE
Roll20 on with popout chat

### ISSUE THREAD

**Issue by Brazedowl** [kakaroto/Beyond20#348]
I don't know if this is on the extension side or the roll20 side but...

I like to pop the chat out into its own window so I can throw it on another screen and make the battle-map bigger. Alas when I do that I cannot see the dice breakdown when I hover over with my mouse. It just shows HTML code for images. 

![Annotation 2020-06-03 094841](https://user-images.githubusercontent.com/56116837/83644608-76c0d500-a57f-11ea-906f-4464ecd4eee3.jpg)

**Comment by kakaroto** [comment]
Yeah, that's a Roll20 bug and unrelated to beyond20, as we have no control over that tooltip. You can see the same issue when using their own character sheets or if you just write `[[1d20]]` manually to the chat for example.
