### ISSUE TITLE
Properly handle quick roll position when there is an ad banner at top of DNDB page

### ISSUE THREAD

**Issue by Brazedowl** [kakaroto/Beyond20#350]
I don't know if its because of my screen resolution, but the little quick roll beyond20 icon blocks the initiative box so it's impossible to click upon unless you carefully and slowly approach from one side. And even then, it's no longer a quick roll. The side panel pops up and I have to click again on the beyond 20 button. Flipping the icon down rather than up would solve the problem right quick.

![Annotation 2020-06-03 094841](https://user-images.githubusercontent.com/56116837/83646713-06678300-a582-11ea-841c-8ef943350ae5.jpg)

**Comment by Aeristoka** [comment]
Nearly certainly your Screen Resolution
![image](https://user-images.githubusercontent.com/7988297/83646834-6dc90700-a571-11ea-9475-0d64ad14c6fa.png)

**Comment by texasbobs** [comment]
Doesn't seem to matter where I click, the initiative does not roll.

![image](https://user-images.githubusercontent.com/19479196/83657608-ae7f4b00-a586-11ea-9f6d-7f4c4c4310a7.png)

**Comment by Aeristoka** [comment]
Ah, can both of you @Brazedowl and @texasbobs  try closing the reminder about Mythic Odysseys of Theros at the top of the screen? @kakaroto was mentioning that this stop bar was shifting things down improperly.

**Comment by texasbobs** [comment]
That did it.  Thanks. I'm sure that will get a lot of people.

**Comment by Aeristoka** [comment]
> That did it. Thanks. I'm sure that will get a lot of people.

Yeah... Dang it DnDBeyond...
