### ISSUE TITLE
Beyond20 Popup In Odd Location

### ISSUE THREAD

**Issue by texasbobs** [kakaroto/Beyond20#352]
The little Beyond20 d20  previously would pop up over the item you were rolling.  Now it pops up over other items.

![image](https://user-images.githubusercontent.com/19479196/83658024-47ae6180-a587-11ea-99cb-6913f60ee86c.png)
It isn't clear exactly what is being rolled here; animal handling or acrobatics.  (It is acrobatics in this case.)

The same goes for attacks.
![image](https://user-images.githubusercontent.com/19479196/83658194-7f1d0e00-a587-11ea-9d58-9a0acce7481b.png)
This is actually a longbow attack.

**Comment by Aeristoka** [comment]
Close the popup at the top of your DnDBeyond page, it's shifting everything down.

Duplicate of #350

**Comment by texasbobs** [comment]
Closed.  Due to Mythic popup.
