### ISSUE TITLE
Add separate control for initiative vs other rolls for advantage/disadvantage

### ISSUE THREAD

**Issue by gareth3001** [kakaroto/Beyond20#354]
We have the same issue described here:

https://github.com/kakaroto/Beyond20/issues/205

The problem is, my players have so many ways to attack with advantage (hidden Rogues, Barbarians with Reckless Attack, and so on) that everyone finds it easier to just leave the "Type of roll" to "always roll twice" or "Roll with Advantage".  Would it be possible to separate out the control for the initiative roll into a separate checkbox, so that we don't have to select the type of roll for initiative every time as shown in issue #205?  That would allow Barbarians with Feral Instincts to set "Roll with Advantage" and everyone else could just use "Normal roll".

**Comment by Aeristoka** [comment]
Have them use the key controls for Advantage/Disadvantage

Shift: Roll with Advantage
CTRL: Roll with Disadvantage

It would be a ton of duplicative code to separate this one thing out for a very extreme edge case scenario.

**Comment by gareth3001** [comment]
Oh that works great, I must've missed that in the patch notes.

**Comment by Aeristoka** [comment]
> Oh that works great, I must've missed that in the patch notes.

Has been a feature since 0.9 👍 

https://beyond20.here-for-more.info/support#release-notes
