### ISSUE TITLE
Critical success and failures (Nat 20 and 1) not showing when using D&D Beyond Digital dice 

### ISSUE THREAD

**Issue by Samb6771** [kakaroto/Beyond20#355]
Before using the new feature, natural 20s and 1s would pop up in Roll20 in the format of dice rolls in roll20. However, when using the digital dice integration feature. It uses a new font/format which does not show the natural 1.

The 7 is a natural one but only shows it if you scroll over it. In the new format, it does not appear green or red, as it would usually would in roll20.

Preferably I would like to the rolls with the digital dice to keep the old roll20 format.
![ab21dde5c232e1eedcf0c2610e394daf](https://user-images.githubusercontent.com/66382056/83669228-35d8b880-a59f-11ea-89be-7453ad073106.png)

**Comment by Aeristoka** [comment]
You get to pick one, Roll20 formatting or DnDBeyond Digital dice.

This is due to how @kakaroto had to code things to implement the Digital Dice on DnDBeyond.

**Comment by Samb6771** [comment]
> You get to pick one, Roll20 formatting or DnDBeyond Digital dice.
> 
> This is due to how @kakaroto had to code things to implement the Digital Dice on DnDBeyond.

That is good to know! Are there plans to implement a way to see a natural 1 or 20 at a glace?

Thanks for the swift reply!

**Comment by kakaroto** [comment]
Came here to say it can't be done because of how roll20 is annoying, then I found a way to force it... 
So far, it seems like most of the stuff I do is hacks on top of hacks in order to force Roll20 to act properly 🤣 
Force critical success : `[[1d1cs>1cf<0 - 1]]`
Force critical fail : `[[1d1cs<0cf>1 - 1]]`
