### ISSUE TITLE
Great Weapon Fighting and Polearm Master Bonus Attack - Not displaying/calculating in Roll20

### ISSUE THREAD

**Issue by exsuit** [kakaroto/Beyond20#360]
Great to see Great Weapon Fighting supported and working. However, I've noticed that the Polearm Master bonus attack doesn't seem to be behaving in the same way as regular attacks in Roll20. Regular attacks show the final damage, and you can mouse over to see if it re-rolled a 1 or 2. However, the Polearm Master bonus attack is simply showing the equation and not rerolling. Not sure if this is intentional
![image](https://user-images.githubusercontent.com/66351827/83700099-3c236f00-a649-11ea-81d8-aba121ea1825.png)

**Comment by Aeristoka** [comment]
Can you confirm your version of Beyond20 for me?

Also, got a Character Sheet link I can test with?

**Comment by exsuit** [comment]
Version 2.0

Here is the character I was testing it with last night: ddb.ac/characters/29692101/CaaFWL

**Comment by Aeristoka** [comment]
Submitted a bugfix pull request for it @exsuit , top roll is before, bottom roll is after:
![image](https://user-images.githubusercontent.com/7988297/83700920-6af80180-a5c5-11ea-8c67-305d91aae09a.png)

**Comment by exsuit** [comment]
Brilliant - thanks so much!
