### ISSUE TITLE
Quick rolls preventing 'cast' button from DNDB

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#363]
From `@Aqueon`
> After update 2.0 extension blocks dndbeyond's spellslot tracking when clicking "cast" button on spells tab. Removing Quick Roll areas in Beyond20 settings seems to resolve this, however it obviously removes the convenience of using this button to send the result to Roll20 and tracking spellslots on dndbeyond at the same time (with Quick Roll areas disabled you have to open the spell side-tab and click on "cast on vtt" there and still track your spellslots manually)

**Comment by Aeristoka** [comment]
I am not able to replicate this

**Comment by kakaroto** [comment]
No, pretty sure it's because quick rolls now do `event.stopPropagation()` to prevent the digital dice (for skills) from rolling, which will break the cast button. I just tried it and can confirm it. Though I'm noticing it's a bit screwy sometimes, quick roll doesn't appear, or I can move to a different one and quick roll appear on the previous cast button, not sure what's happening here...

**Comment by farling42** [comment]
It also breaks the popup that normally appears from the CAST button for a character who is warlock & wizard, so has PACT and SPELL slots. Normally a popup asks for which type of slot is being used. This doesn't appear when beyond20 is intercepting the button click.
