### ISSUE TITLE
Class features not set untill "Features & Traits" tab is selected.

### ISSUE THREAD

**Issue by shortlad** [kakaroto/Beyond20#369]
I noticed the Reliable Talent Feature wasn't being set to true when making skill checks. The issue is in dndbeyond_character.js updateFeatures(). It looks for element ".ct-features .ct-classes-detail" but doesn't find it and leaves _class_features as an empty array. Once you click on the "Features & Traits" tab updateFeatures() is able to find the element and populate the _Class_features property and things work as expected.

This appears to affect all of the character's features and traits until that tab is selected. Not sure of a solution other than forcing it to load that tab, calling updateFeatures(), the returning to the previous tab if all the features are empty arrays. But that does not seem to be an elegant solution.

**Comment by kakaroto** [comment]
Beyond20 has always worked this way. You need to do this once after you install the extension or after you level up. 
See https://beyond20.here-for-more.info/faq#i-have-a-class-featurefeat-that-the-features-page-says-is-supported-sharpshooter-feat-for-example-but-i-dont-see-the-option-to-use-it
Having a more intelligent method where it would cache the last time it had parsed it, and compare with the current PC level is something I'm thinking about, but I don't want to "go" to the features tab, but rather show a warning to the user. On mobile for example, it's not a simple click, as you'd need to pop open the tabs list then select features, etc.. and I don't want it messing with the user's page.

**Comment by shortlad** [comment]
I see, that makes sense. I was thinking it reset the features when you reloaded the page but it does persist the values from the last time you loaded that tab. But I have verified it works, I had been clearing it while debugging so it was self inflicted. 

Thanks for the quick answer and maintain such an awesome extension. It has saved my group during this quarantine!

**Comment by kakaroto** [comment]
Aha! The infamous self inflicted developer-generated bug! :) Yeah, it does keep a cache, so it's not as bad as you initially thought :) I thought you were aware but you just wanted a better solution for the first-time users.

> Thanks for the quick answer and maintain such an awesome extension. It has saved my group during this quarantine!
Thanks! Glad to hear it :)
