### ISSUE TITLE
great weapon fighting and enhanced criticals

### ISSUE THREAD

**Issue by psudopixel** [kakaroto/Beyond20#373]
i think this worked in the pre-2.0 versions, but great weapon fighting does not appear to be re-rolling 1s and 2s on damage.

it also appears to not be catching a fighters extended criticals...

**Comment by Aeristoka** [comment]
https://beyond20.here-for-more.info/faq#i-have-a-class-featurefeat-that-the-features-page-says-is-supported-sharpshooter-feat-for-example-but-i-dont-see-the-option-to-use-it

Open Features & Traits so it can parse those Class Features (and any Feats you have). This has always been a requirement, as DnDBeyond doesn't load these things up until you click that Tab, and Beyond20 can't parse those features until they're loaded.

**Comment by psudopixel** [comment]
that makes sense, I did not realize that.  it just seemed to work last time!
