### ISSUE TITLE
Polearm Master Bonus attack not sending correct syntax (minor bug report)

### ISSUE THREAD

**Issue by Rashkavar** [kakaroto/Beyond20#384]
I'm playing a fighter with the Polearm Master feat, and have experienced some odd issues with the bonus action attack that feat grants, due to an apparent conflict with the Great Weapon Fighting Style option available to Fighters and other classes with the Fighting Style option.

The to hit roll is normal, but the damage roll comes out in the form of X<=2+Y, where X is the result of a d4 roll and Y is the strength modifier that gets added to the damage.

I've tested using a dummy character with the feat using a class that doesn't have the Fighting style option, a class that does but uses something other than Great Weapon Fighting, and finally after switching to Great weapon fighting (once it had recognized that I had that fighting style; either I had to wait a bit for that to catch up, or I had to click the Beyond20 button in the description of the feature to have it roll with the reroll 1's and 2's syntax.)  Only once I had it rolling with the syntax meant to reroll 1's and 2's was I able to reproduce the issue.

See the attached image for an example.  

(If I mouseover the damage for the glaive attack that's being resolved properly, I get "Rolling 1d10ro<2+4=3+4" (using the 3 rolled on the d10 roll as per the picture))

![PolearmMasterTechSupportImage](https://user-images.githubusercontent.com/63379519/83984227-e4a32e80-a8e8-11ea-9ce4-99ea46669ae2.png)

**Comment by Aeristoka** [comment]
Already fixed and merged (for Beyond20 2.1, not yet released) in #361

**Comment by Rashkavar** [comment]
Awesome.  Guess I should've spent that time looking at what progress had already been done rather than trying to isolate the problem.  Ah well, good practice.  Cheers!
