### ISSUE TITLE
support for more tools (instruments)

### ISSUE THREAD

**Issue by pandanielxd** [kakaroto/Beyond20#387]
Would it be possible to add the option to roll for instruments as well, just like other tools (for example Thieves' Tools, etc). They pretty much have the same description as the other tools which already have that option _(If you have proficiency with a given musical instrument, you can add your proficiency bonus to any ability checks you make to play music with the instrument.)_.

Thanks in advance :)

**Comment by Aeristoka** [comment]
@pandanielxd Can you provide a couple screenshots of what you mean? It might be possible, but a solid referential starting point will definitely help to get this rolling :).

**Comment by pandanielxd** [comment]
Sure sure! 
For example a Viol shows this when you display it in VTT:
https://i.imgur.com/SqTVHzf.png

Thieves' Tools on the other hand:
https://i.imgur.com/tYX9mrw.png
show this after I click that away:
https://i.imgur.com/mirtm00.png

**Comment by kakaroto** [comment]
Sounds fair. Guess I need to keep a list of the known instruments now...

**Comment by pandanielxd** [comment]
This should be all of them I do believe https://i.imgur.com/uZFXjoz.png
