### ISSUE TITLE
Roll20: Crit Fail/Success when rolling a Bonus Die

### ISSUE THREAD

**Issue by jaredkent** [kakaroto/Beyond20#393]
It appears as though when adding a "Custom Roll Dice Formula", roll20 will take the bonus die and treat it as a critical fail or success, regardless of what the d20 rolled. As an example, pictured. I attach 1d4 to my rolls for Bless. d20 was a 5, plus 5 spell attack modifier, plus 1 from Bless. Even though this was a natural 5 and adds up to 11, roll20 still treats this as a critical fail because of the bonus die. The same happens if the bonus die hits it's max, in this case rolling a 4 with a d4 is treated as a critical success.

I was able to manually solve the problem by taking this Bless formula +?{Use Bless|Yes,1d4|No,0}, and changing 1d4 to "1d4cs0cf0". Telling it to ignore critical fails/success. 

I tested and this problem does NOT occur with the "Custom Damage Dice Formula"

![Screen Shot 2020-06-11 at 12 46 41 PM](https://user-images.githubusercontent.com/19612384/84432388-9c825580-abe1-11ea-91b9-1bb6191505b2.png)

**Comment by kakaroto** [comment]
That's weird because Beyond20 already has code to convert custom dice formulas so they don't appear as crits (with the cs/cf trick, though mine is less nice, should have thought to make it =0 instead of >100).
I'll have to test and confirm what caused it to break.
Thanks.
