### ISSUE TITLE
Damage 3D Dice in Roll20 doubled

### ISSUE THREAD

**Issue by JasonSherry** [kakaroto/Beyond20#394]
When I use an attack, like Crossbow and with spells, from my dndbeyond character sheet the to hit dice is only shown once, but the damage dice are doubled. In the chat log everything is correct, the dice only show up once (or as they should).

I have Auto Damage Role set to Don't in my character sheet, per Known Issue. Using the standard D&D 5E By Roll20 character sheet.

For now I'm disabling 3rd dice, so the DM and other players aren't confused.

**Comment by kakaroto** [comment]
As answered in Discord (assuming you're the same person who asked there), this is an issue from Roll20's limitations and there's nothing that can be done about it, see : https://beyond20.here-for-more.info/faq#why-is-beyond20-rolling-too-many-damage-dice-on-roll20
