### ISSUE TITLE
Odd roll20 behavior

### ISSUE THREAD

**Issue by DarrynGlass** [kakaroto/Beyond20#397]
This might not be a bug, but a setting in Roll20.  My DM is starting a new campaign, but the behavior of Beyond20 is different in this new one.

In the old campaign, it rolled the dice (I have 3d dice turned on for both) and displayed the to hit, the DC Save and the damage.
![image](https://user-images.githubusercontent.com/29684482/84513864-b2e6ea80-ac8f-11ea-8086-fe78e4238c7b.png)

In the new campaign, it only rolls the to hit and the format is WAY different. 
![image](https://user-images.githubusercontent.com/29684482/84513927-cabe6e80-ac8f-11ea-8f31-8a22e567ab87.png)

I am pretty sure this is a setting on Roll20, but wanted to ask and see.

**Comment by Aeristoka** [comment]
Your DM isn't using (in the Roll20 Campaign Settings) the "D&D5e by Roll20" character sheet. This forces the Beyond20 Roll Renderer output.

@kakaroto please close

**Comment by DarrynGlass** [comment]
That is what I thought it might be.  Thank you I will reach out to them.
