### ISSUE TITLE
Suggestion:  Add option to display spell description when rolling

### ISSUE THREAD

**Issue by DarrynGlass** [kakaroto/Beyond20#398]
It would be nice to have an option to automatically display the spell description in the VTT when you cast a spell.

**Comment by kakaroto** [comment]
There's a button for that right next to the cast button, it would be much more annoying if it did that on every roll.
If you're using Foundry, the name is clickable to expand and show the spell description.

**Comment by DarrynGlass** [comment]
Well I was thinking an option that can be turned on or off, but yeah the button will work.  And no, playing on Roll20.  Thanks for your response.  It is just something my DM thought would be very useful.  I can always just click twice :)

**Comment by Aeristoka** [comment]
> Well I was thinking an option that can be turned on or off, but yeah the button will work. And no, playing on Roll20. Thanks for your response. It is just something my DM thought would be very useful. I can always just click twice :)

Just get him to switch to FoundryVTT, solves all the problems.

**Comment by DarrynGlass** [comment]
LOL I will bring that up.  Thanks.
