### ISSUE TITLE
support for Natural Explorer

### ISSUE THREAD

**Issue by pandanielxd** [kakaroto/Beyond20#399]
At level 1 Rangers get the following feature:

> Natural Explorer:
> You are particularly familiar with one type of natural environment and are adept at traveling and surviving in such regions. Choose one type of favored terrain: arctic, coast, desert, forest, grassland, mountain, swamp, or the Underdark. **When you make an Intelligence or Wisdom check related to your favored terrain, your proficiency bonus is doubled if you are using a skill that you’re proficient in.**

yadayadayada some extra fun stuff that don't really have to do with Beyond20. 

I was wondering if there could be a switch like for example Hexblade's Curse (https://i.imgur.com/viOTCQ8.png) to enable you being in your favored terrain, and thus doubling your proficiency bonus when making an Intelligence or Wisdom check (related to your favored terrain, which is probably most of them I do imagine).

Thanks in advance :)

**Comment by kakaroto** [comment]
isn't that what the custom roll modifier is for? I don't know if having a checkbox for "in favored terrain" is worth having, but it might... will think on it.

**Comment by pandanielxd** [comment]
Guess it _would_ work, but it would add the custom mod to any type of check. Not that that is an incredibly big problem either I guess :P.

**Comment by HaarisQureshi** [comment]
If it helps as a workaround, I only recently realised you can create custom skills in DnDBeyond, I've just made Natural Explorer (and anything else with conditional proficiencies, like stonecutting) as custom skills. Basically means you can roll your skills with the different modifer without having to go through the Beyond20 extension menu

**Comment by pandanielxd** [comment]
That would work well as a workaround I think, thank you :).

**Comment by Aeristoka** [comment]
@pandanielxd Any reason to keep this open?

**Comment by pandanielxd** [comment]
I still think it could be worthwhile even if there are workarounds. Kakaroto said he'd think about it a year ago so I don't think that that sentiment is shared :P. 
Can be closed if that is indeed the case^^.

**Comment by Aeristoka** [comment]
> I still think it could be worthwhile even if there are workarounds. Kakaroto said he'd think about it a year ago so I don't think that that sentiment is shared :P.
> Can be closed if that is indeed the case^^.

Maybe I'll be nice and work up an implementation 😉

**Comment by Aeristoka** [comment]
@pandanielxd 
![image](https://user-images.githubusercontent.com/7988297/117485092-369f6a80-af25-11eb-9350-6ad114905ba1.png)
