### ISSUE TITLE
Support for Channel Divinity: Sacred Weapon

### ISSUE THREAD

**Issue by Ferarchi** [kakaroto/Beyond20#404]
Ability to add the + to your attack rolls by toggling on or off for next roll.

"As an action, you can imbue one weapon that you are holding with positive energy, using your Channel Divinity. For 1 minute, you add your Charisma modifier to attack rolls made with that weapon (with a minimum bonus of +1). "

**Comment by kakaroto** [comment]
Since you have to toggle it on/off, it would make more sense for you to simply enter the modifier in the `custom damage modifier`, which is what it was made for. I don't think having it as a toggle is necessary

**Comment by Ferarchi** [comment]
sorry if i misunderstand the Custom Modifier as fairly new to beyond20, but wouldn't it be painful to be changing the modifier for bless and sacred weapon or it asking you everytime for either.

**Comment by kakaroto** [comment]
Entering "+3" to the custom modifier isn't much more painful than clicking on the checkbox as you'd have to enable/disable (add/remove) the option when you use the Channel Divinity and when its effects have elapsed.
For things like Bless, you can have it ask you for it every time if you're using Roll20. See the FAQ item here with the macro for it : https://beyond20.here-for-more.info/faq#how-can-i-add-blessguidance-bonus-or-use-elemental-weapon-

**Comment by Ferarchi** [comment]
that can work, thanks.

**Comment by Ferarchi** [comment]
downside is this gets asked on every single roll same with the modifier. not just attack rolls or saving rolls.

**Comment by kakaroto** [comment]
That's true. I thought you'd add it/remove it as needed when you use the channel divinity and when the in-game 1 minute is elapsed.

Considering that this basically making a single weapon have a magical bonus, it might just make more sense to change that weapon to have a magic bonus.
You can use D&D Beyond's own "Customize" interface for that, and it would make it easier I guess than the whole custom Beyond20 option or custom roll modifier.

![image](https://user-images.githubusercontent.com/27990/84584447-91424c00-add2-11ea-80b6-7a99aa42c9e7.png)

**Comment by Ferarchi** [comment]
That sounds better and i've just done the macro for bless in Roll20 as its only an addition roll when required.
