### ISSUE TITLE
Make adv/disadv badge clickable for adv/disadv roll and stop auto-override

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#408]
Following discord conversation, due to some adv/disadv being situational and D&D Beyond not always providing the situation in which it applies or an easy way to programatically parse that, it might be better to just never force it, and instead make the badge itself clickable.
See https://discordapp.com/channels/578874022968688640/578874022968688642/722374946143207424

**Comment by kakaroto** [comment]
Affects #396 and there's also a adv+disadv (situational) icon that should do a query.

**Comment by HaarisQureshi** [comment]
@kakaroto I wonder if DnDBeyond's recently introduced right-click to roll with adv/disadv influences this?

**Comment by kakaroto** [comment]
No, it wouldn't influence it, as I'm not handling right clicks, and I'll be making the adv/disadv badge itself clickable, so it would be a different workflow, which I hope it easier to use quickly as well.

**Comment by HaarisQureshi** [comment]
Fair - is there a way to let those buttons also trigger the rolls? Just thinking about how it might confuse new users is all

**Comment by kakaroto** [comment]
It would be possible, but I would personally say that it might be better to keep those as "this is the way to use the digital dice only, without it sending to a VTT", as I originally didn't want to hook on the original buttons, as to not interfere with the regular site behavior.
Once I work on fixing this (along with #367), I may re-evaluate though.
