### ISSUE TITLE
Selecting a different monster in the Initiative tracker does not change what gets rolled for their initiative.

### ISSUE THREAD

**Issue by shadow7412** [kakaroto/Beyond20#411]
![image](https://user-images.githubusercontent.com/286341/84957317-490e8b00-b13e-11ea-8e69-28ee0309a3bd.png)
(Note - the advantage icon is because of my shortcut key to take screenshots. It was rolled normally)

## To reproduce
* Add multiple monster types to a combat in the D&D Encounter tool, ideally with different initiative scores.
* Click one of them (optionally roll initiative from that monster sheet)
* Click the other.
* Roll initiative. Note that this rolls the first monster's initiative instead of the selected one.

Initiative is probably not the most useful thing to roll from this screen - but it proves that when we switch character sheets, not all rolls are being correctly updated. This needs to be a clean swap so that it's easier (and accurate) to roll any of a monsters abilities from this screen.

**Comment by kakaroto** [comment]
Just tested this. The correct initiative is rolled, but the "Roll Initiative" value displayed is wrong. The "Roll initiative" line is not part of the original D&D Beyond statblock, Beyond20 adds it, and the value is simply the dexterity value. In your screenshot above, if it was larger, you'd have noticed that whatever monster you rolled had a dexterity of 3. So the initiative is rolled correctly, but it's a display issue only.
Regardless, fixing now, thx!
