### ISSUE TITLE
Output format in Roll20 different using digital dice

### ISSUE THREAD

**Issue by KenBieber** [kakaroto/Beyond20#412]
As you can see in the attached screenshot, the output format in Roll20 changes when not using digital dice versus when using digital dice.  This test was done in the same Roll20 campaign with the same DnDBeyond character in the same web browser: Chrome.

In the first roll of the screenshot, I am not using digital dice.  The output format in Roll20 is as expected.  

In the second roll of the screenshot, I am using digital dice.  The output format in Roll20 is **not** as expected.

The only changes I made between the two rolls were enabling both "Dice Rolling" in DnDBeyond and "Use D&D Beyond's Digital Dice" in Beyond20.

![Digital Dice Different Output](https://user-images.githubusercontent.com/67157040/85143518-d70a7480-b217-11ea-88a2-44dd42187858.JPG)

**Comment by Aeristoka** [comment]
This is expected behavior:

If you use Digital Dice on DnDBeyond, you are using the internal Beyond20RollRenderer, which has the tabular output.
If you don't use Digital Dice on DnDBeyond, Beyond20 can use the Roll20 rolls and formatting.

You get to pick one, essentially.

**Comment by KenBieber** [comment]
It is expected behavior to change the output format?  It's displaying the same information, just differently.

**Comment by Aeristoka** [comment]
> It is expected behavior to change the output format? It's displaying the same information, just differently.

Correct.

**Comment by kakaroto** [comment]
In one format it's actually using the character sheet template and letting roll20 do the rolls, in the other format it only receives the results, no rolls are made, and it just gets what information needs to be displayed.
It might be impossible to achieve the same format with rolls pre-made, but I'll give it a try for the next update (or the one after).

**Comment by jacksomstar107** [comment]
this happened to me randomly does anyone know how to get it back to normal?
