### ISSUE TITLE
Sunlight Sensitivity (Drow) always rolls with disadvantage

### ISSUE THREAD

**Issue by Invice** [kakaroto/Beyond20#415]
The **Drow** trait **Sunlight Sensitivity** (see below) always rolls with disadvantage without checking the precondition. When clicking while using the modifiers (ALT, CTRL, SHIFT) you can either get an advantage or disadvantage result. The "Ask every time" option does not open a prompt for selecting the normal roll and directly rolls with disadvantage.

As discussed in #396 this might be expected behaviour due to the order in which modifiers are applied. However, as the source of this disadvantage is a racial trait it is impossible to activate/deactivate it depending on the environment or the type of the perception check.

Edit: This might be fixed by #408. If so please close and ignore this issue ;)

### Sunlight Sensitivity:
> You have disadvantage on attack rolls and on Wisdom (Perception) checks that rely on sight when you, the target of your attack, or whatever you are trying to perceive is in direct sunlight.

**Comment by kakaroto** [comment]
Yep, #408 would fix it. I'm closing it, but it's a good example of the kind of traits that could cause this issue.
