### ISSUE TITLE
Damage Roll instruction used by Roll20 is cut short when special characters in CHR name

### ISSUE THREAD

**Issue by brother-oak** [kakaroto/Beyond20#417]
I won't bore you with the long story as to how I tracked this issue down - I spotted an issue with one of my characters that didn't happen with other characters and did my best to debug why it was happening - here's what I think is the issue:

TL;DR: 
When there is a double-quote character in a character name in DNDBeyond, the damage roll instruction sent to Roll20 (when auto roll crit and damage is NOT set in options) is cut short, meaning the weapon name is never displayed, and critical damage rolls are also never displayed correctly. This may happen with other non-alphanumeric characters too.
I am using Roll20 5e character sheets - I suspect it may not occur with the "default" template.
EDIT: Just tried it with **single quotes** in the name (i.e. Jinx 'Chef' Podcastle III, and it worked ok, so it may just be double quotes that are the problem?

Detail:
I have a character called: **Jinx "Chef" Podcastle III**
if I set "auto roll damage and crit" to ON, then the following message is sent to Roll20 for a critical OR a non-critical hit:
`&{template:atkdmg} {{charname=Jinx "Chef" Podcastle III}} {{rname=Kukri}} {{mod=+8}} {{r1=[[1d20 +8]]}} {{attack=1}} {{damage=1}} {{dmg1flag=1}} {{dmg1=[[1d6+5]]}} {{dmg1type= Piercing}} {{crit1=Crit: [[1d6]]}} {{normal=1}}`
This is displayed correctly for both critical and non-critical hits.

However, if "auto roll damage and crit" is set to OFF, then the following message is sent to Roll20 for a to-hit:
```
&{template:atk} {{charname=Jinx "Chef" Podcastle III}} {{rname=[Kukri](!
 &#38;&#123;template:dmg&#125; &#123;&#123;damage=1&#125;&#125; &#123;&#123;dmg1flag=1&#125;&#125; &#123;&#123;dmg1=&#91;&#91;1d6+5&#93;&#93;&#125;&#125; &#123;&#123;dmg1type= Piercing&#125;&#125; &#123;&#123;charname=Jinx "Chef" Podcastle III&#125;&#125; &#123;&#123;rname=Kukri&#125;&#125;)}} {{mod=+8}} {{r1=[[1d20 +8]]}} {{attack=1}} {{rnamec=[Kukri](!
 &#38;&#123;template:dmg&#125; &#123;&#123;damage=1&#125;&#125; &#123;&#123;dmg1flag=1&#125;&#125; &#123;&#123;dmg1=&#91;&#91;1d6+5&#93;&#93;&#125;&#125; &#123;&#123;dmg1type= Piercing&#125;&#125; &#123;&#123;crit1=Crit: &#91;&#91;1d6&#93;&#93;&#125;&#125; &#123;&#123;charname=Jinx "Chef" Podcastle III&#125;&#125; &#123;&#123;rname=Kukri&#125;&#125; &#123;&#123;crit=1&#125;&#125;)}} {{normal=1}}
```
Which looks ok. However, the DAMAGE instruction (if the pink weapon name is clicked on in Roll20) in this instance is:
```
!
 &{template:dmg} {{damage=1}} {{dmg1flag=1}} {{dmg1=[[1d6+5]]}} {{dmg1type= Piercing}} {{charname=Jinx 
```
Which DOES actually make the roll, and at first glance looks ok, but it doesn't display the character name - the instruction has been cut short due to the next character in the name being a double quote.
This becomes more obvious in a critical hit (which is how I spotted a problem in the first place). The equivalent for a Crit damage instruction is:
```
!
 &{template:dmg} {{damage=1}} {{dmg1flag=1}} {{dmg1=[[1d6+5]]}} {{dmg1type= Piercing}} {{crit1=Crit: [[1d6]]}} {{charname=Jinx 
```
which does do the crit roll, but does not display it due to the instruction being cut short.

To debug this, I changed my character name to remove the quotes, and here are the respective instructions being sent (I just included those for Auto Damage and Crit option set to OFF as that is where the problem manifests):
To Hit roll (same as before, I think):
```
&{template:atk} {{charname=Jinx Chef Podcastle III}} {{rname=[Kukri](!
 &#38;&#123;template:dmg&#125; &#123;&#123;damage=1&#125;&#125; &#123;&#123;dmg1flag=1&#125;&#125; &#123;&#123;dmg1=&#91;&#91;1d6+5&#93;&#93;&#125;&#125; &#123;&#123;dmg1type= Piercing&#125;&#125; &#123;&#123;charname=Jinx Chef Podcastle III&#125;&#125; &#123;&#123;rname=Kukri&#125;&#125;)}} {{mod=+8}} {{r1=[[1d20 +8]]}} {{attack=1}} {{rnamec=[Kukri](!
 &#38;&#123;template:dmg&#125; &#123;&#123;damage=1&#125;&#125; &#123;&#123;dmg1flag=1&#125;&#125; &#123;&#123;dmg1=&#91;&#91;1d6+5&#93;&#93;&#125;&#125; &#123;&#123;dmg1type= Piercing&#125;&#125; &#123;&#123;crit1=Crit: &#91;&#91;1d6&#93;&#93;&#125;&#125; &#123;&#123;charname=Jinx Chef Podcastle III&#125;&#125; &#123;&#123;rname=Kukri&#125;&#125; &#123;&#123;crit=1&#125;&#125;)}} {{normal=1}}
```
Damage on a non-crit roll:
```
!
 &{template:dmg} {{damage=1}} {{dmg1flag=1}} {{dmg1=[[1d6+5]]}} {{dmg1type= Piercing}} {{charname=Jinx Chef Podcastle III}} {{rname=Kukri}}
```
Damage on a crit Roll:
```
!
 &{template:dmg} {{damage=1}} {{dmg1flag=1}} {{dmg1=[[1d6+5]]}} {{dmg1type= Piercing}} {{crit1=Crit: [[1d6]]}} {{charname=Jinx Chef Podcastle III}} {{rname=Kukri}} {{crit=1}}
```

As you can see, the full damage instructions are sent - there is no cutting short of the instruction, and the correct damage is displayed.

I don't know exactly how Beyond20 works, but I'm guessing the full information is sent in the "to hit" roll correctly, but Roll20 extracts the "damage" portion incorrectly if there are quotes in the full instruction, so I'm guessing that a fix would either need the character name (and maybe even the weapon name) to be parsed before sending the message to Roll20, and some characters substituted, or if this won't work, maybe a FAQ note (or flag in the options?) to say that characters and weapons with certain characters in the name may not work correctly?

**Comment by brother-oak** [comment]
A little more investigation (just in case it helps the developers):
I manually changed the "to hit" instruction processed by Roll20 to replace the double quotes with &#34 in the character name and it seems to work ok - i.e. a to hit instruction of:
```
 &{template:atk} {{charname=Jinx "Chef" Podcastle III}} {{rname=[Kukri](!
 &#38;&#123;template:dmg&#125; &#123;&#123;damage=1&#125;&#125; &#123;&#123;dmg1flag=1&#125;&#125; &#123;&#123;dmg1=&#91;&#91;1d6+5&#93;&#93;&#125;&#125; &#123;&#123;dmg1type= Piercing&#125;&#125; &#123;&#123;charname=Jinx &#34Chef&#34 Podcastle III&#125;&#125; &#123;&#123;rname=Kukri&#125;&#125;)}} {{mod=+8}} {{r1=[[1d20 +8]]}} {{attack=1}} {{rnamec=[Kukri](!
 &#38;&#123;template:dmg&#125; &#123;&#123;damage=1&#125;&#125; &#123;&#123;dmg1flag=1&#125;&#125; &#123;&#123;dmg1=&#91;&#91;1d6+5&#93;&#93;&#125;&#125; &#123;&#123;dmg1type= Piercing&#125;&#125; &#123;&#123;crit1=Crit: &#91;&#91;1d6&#93;&#93;&#125;&#125; &#123;&#123;charname=Jinx &#34Chef&#34 Podcastle III&#125;&#125; &#123;&#123;rname=Kukri&#125;&#125; &#123;&#123;crit=1&#125;&#125;)}} {{normal=1}}
```
Will then create a correct damage roll (with double quotes rather than being cut short)
So a solution could be to pre-parse the character/weapon name (or the whole instruction sent to Roll20) to replace any double quote with &#34 before sending.

**Comment by kakaroto** [comment]
I dont' know how I missed seeing this bug report. Thanks for posting it. I'll fix this.
