### ISSUE TITLE
Blood hunter: how to roll wisdom/intelligence checks without advantage?

### ISSUE THREAD

**Issue by mikkabouzu** [kakaroto/Beyond20#421]
Blood hunters get Hunter's Bane: 

> You have advantage on Wisdom(Survival) checks to track fey, fiends, or undead, as well as on Intelligence ability checks to recall information about them.

Dndbeyond depicts this with a little advantage icon next to these skills, and whenever I roll, beyond20 rolls with advantage (I tried rolling with disadvantage, but that won't cancel out). 
Is there a way to do flat rolls for these? The advantage is situational, it shouldn't apply to every roll.

**Comment by HaarisQureshi** [comment]
Hold alt to roll a neutral roll. 
I also believe there is plans to rework the adv/disadvantage system so it doesn’t force a type of roll.

**Comment by mikkabouzu** [comment]
Alt works like a charm, thanks!
