### ISSUE TITLE
Advantage on Initiative

### ISSUE THREAD

**Issue by jrichview** [kakaroto/Beyond20#423]
I keep my B20 advantage setting on ALWAYS ASK because I like it to only roll advantage when I actually need it. However, though my character does have advantage on initiative rolls, it never asks. It just does a normal roll.

No big crisis, I can roll twice of course. But a nice to have.

**Comment by HaarisQureshi** [comment]
Mouseover - does it not show two rolls and picking the higher one? It doesn't show it the same way as the other advantage rolls, but usually it does roll with advantage in the background

**Comment by jrichview** [comment]
Yes I just discovered that. It's a bit unexpected that it doesn't actually show the advantage roll clearly like a normal advantage roll, but I literally just realized under the hood it is rolling 2 d 20s and using the larger number as your initiative. So I'll just remember this.

I assume there's something tricky regarding the API where initiative is concerned, to get it to work with the turn order.

**Comment by Aeristoka** [comment]
If you're going to Roll20, that's 100% correct, it has to be fiddled with to add to the Turn Tracker properly

I believe if you mouseover the formula it will show 2d20kh1, which means, roll 2 D20s, and keep the highest one (for advantage, as in this case)

**Comment by kakaroto** [comment]
Yeah, if you disable the "add to turn tracker" option, it will roll the 2 d20s separately, but to add to turn tracker, you need to have a single result for it to know what value to add.
