### ISSUE TITLE
Beyond20 broken with July 7th D&D Beyond sheet update

### ISSUE THREAD

**Issue by DariusArgent** [kakaroto/Beyond20#427]
![image](https://user-images.githubusercontent.com/13587952/86841336-1fdd7c80-c0a4-11ea-8c8e-d78e1e3ee58c.png)

When clicking an action that is a weapon and click on the Beyond 20 red button nothing happens in Roll20.
I also get a console error.

**Comment by kakaroto** [comment]
That's a new one! Thanks for reporting!

**Comment by darkbeholder** [comment]
In addition it looks like it is unable to get the character data. The dndbeyond character sheet looks to have slightly been updated today also which probably caused this.

```
Got message :  
Object { action: "get-character" }
dndbeyond_character.js:5617:13
Received character:  
Object { name: null, avatar: null, id: "3023384", type: "Character", abilities: (6) […], classes: null, level: null, race: null, ac: "22", proficiency: "+6", … }
popup.js:1315:17
```

**Comment by jorgegonzalez** [comment]
same here

**Comment by maxmiliano** [comment]
> In addition it looks like it is unable to get the character data. The dndbeyond character sheet looks to have slightly been updated today also which probably caused this.
> 

DarkBeholder is right. 
DDB has just released an update today.

Changelog:
https://www.dndbeyond.com/changelog/844-character-sheet-changelog-july-7th-updates

**Comment by sirtinypup** [comment]
Also not sure this is the same thing with spellcasting but under the spell it says "Null" now.

**Comment by kakaroto** [comment]
This should be fixed now in the development version. See the README file on how to install it.
@sirtinypup I'm not sure about what you mean, maybe a screenshot, but try the dev version first to see if it was related.
Thanks!
