### ISSUE TITLE
[Request] New option for "Whisper monster rolls to the DM"

### ISSUE THREAD

**Issue by Daekesh** [kakaroto/Beyond20#434]
It'd be great if the option for monster rolls to the GM had the option to only whisper the initiative rolls. Or perhaps a separate check box to save you adding multiple options, depending on combinations. I usually do all my rolls in public for monster stuff, but I'd like the initiative rolls to be automatically hidden, in case I have them hiding on the gm layer, around a corner, etc. It'd save me some hassle!

**Comment by kakaroto** [comment]
Sorry but I don't think I'll add such a feature, it would bloat the interface which already has too many features. I think it's not too much to ask of the DM to switch it to whispers, do the initiative rolls, then switch it back (and the amount you would save would never amount to the time it would take me to add such a feature).
