### ISSUE TITLE
Quick Roll Attack Spells don't roll attack roll (d20) when using the actions tab

### ISSUE THREAD

**Issue by jaredkent** [kakaroto/Beyond20#435]
When clicking any of the quick rolls in the action tab, either to the left of the attack name, the attack roll, or the damage roll buttons, attack spells will not roll a d20 for attack. Instead they just roll damage. This is happening on roll20 as well as within DnDBeyond (and I'd assume FVTT as well but haven't tested.) If rolling the same attack spell from the spells tab, it rolls the d20 as normal.

**Comment by mahe4** [comment]
I have a similar problem.
For me, every Spell seems to work fine, but weapon attacks don't seem to work.
When i click in the actions tab on a spell, it rolls normally, but when i click on a weapon, nothing happens.

**Comment by Aeristoka** [comment]
> I have a similar problem.
> For me, every Spell seems to work fine, but weapon attacks don't seem to work.
> When i click in the actions tab on a spell, it rolls normally, but when i click on a weapon, nothing happens.
> And the Shift or Ctrl mods don't work anymore, for advantage or disadvantage.
> The plus and minus dice are showing instead of the beyond dice, but nothing is rolled.
> EDIT: nevermind, shift and control work on spells. mistake on my part. only weapons don't seem to work.

Gonna need some screenshots here, as I have weapons working perfectly fine.

**Comment by mahe4** [comment]
Since i can't screenshot an action, here is a video link of what happens


[https://youtu.be/uJMkrhgm69c](url)

**Comment by Aeristoka** [comment]
> https://youtu.be/uJMkrhgm69c

Can you give me a character sheet to test with?

**Comment by mahe4** [comment]
[https://ddb.ac/characters/31106793/vHgAUX](url)

**Comment by Aeristoka** [comment]
> https://ddb.ac/characters/31106793/vHgAUX

Thanks much, confirmed what the issue is.

@kakaroto This is related to the new logic from: https://github.com/kakaroto/Beyond20/commit/4ff498094e145f9293160f9bbf1ccfebdd1ce761

Which appears to be too aggressively setting to_hit to "null", then immediately doing a legit if statement around "undefined", which WOULD grab the right to_hit, but now the compared value is "null" rather than undefined.
