### ISSUE TITLE
[Request] Add Wizard (Bladesinger) Bladesong-options, similar to how you implemented a Barbarian's rage

### ISSUE THREAD

**Issue by rupshall** [kakaroto/Beyond20#436]

**Comment by kakaroto** [comment]
> You can use a bonus action to start the Bladesong, which lasts for 1 minute. It ends early if you are incapacitated, if you don medium or heavy armor or a shield, or if you use two hands to make an attack with a weapon. You can also dismiss the Bladesong at any time you choose (no action required).
While your Bladesong is active, you gain the following benefits:
• You gain a bonus to your AC equal to your Intelligence modifier (minimum of +1).
• Your walking speed increases by 10 feet.
• You have advantage on Dexterity (Acrobatics) checks.
• You gain a bonus to any Constitution saving throw you make to maintain your concentration on a spell. The bonus equals your Intelligence modifier (minimum of +1).
You can use this feature twice. You regain all expended uses of it when you finish a short or long rest.

As discussed on Discord, the only thing it can do is force advantage on acrobatics check, and probably do a query for constitution saving throws to ask if it's to maintain concentration or not.

> On later levels it also adds the Int Mod to damage, is that something you can do?

Need to find exact wordings, but that's something that makes more sense to add support for.

**Comment by rupshall** [comment]
This is where the damage comes in:

Song of Victory
Starting at 14th level, you add your Intelligence modifier (minimum of +1) to the damage of your melee weapon attacks while your Bladesong is active.
