### ISSUE TITLE
"Customize" Tab in the weapon sidebar breaks attack rolls

### ISSUE THREAD

**Issue by theinfectgamer** [kakaroto/Beyond20#437]
In the sidebar opened up when you click on a weapon, if you add any customization in the "customize" drop down menu, there will be no attack roll displayed in roll20. This is true even if the customizations don't modify the "to hit" or "damage bonus" or similar (such as customizing the "name" or "notes" field). Customizing the damage related fields do seem to correctly alter the damage rolls however as far as I'm aware.

This is rolling without customization:

![image](https://user-images.githubusercontent.com/68026048/86952469-0b8b9500-c121-11ea-8a81-cb337045821b.png)

Then I change any of the fields:

![image](https://user-images.githubusercontent.com/68026048/86952722-67eeb480-c121-11ea-8a82-bf1bbcf18198.png)

Even the name or notes field:

![screenshot1](https://user-images.githubusercontent.com/68026048/86953095-ec413780-c121-11ea-8452-6ba6ac465e67.png)

And there is no attack roll.

**Comment by kakaroto** [comment]
Thanks for the detailed report. I'll look into it!

**Comment by kakaroto** [comment]
This is actually caused by the same thing as #435 and was fixed at the same time!
