### ISSUE TITLE
Issues with Attack Customization

### ISSUE THREAD

**Issue by thedrviking** [kakaroto/Beyond20#442]
I have been unable to get beyond20 to actually roll/import an ATK roll for weapons that have been customized or have an intrinsic modifier to the, such as a 1+ magical weapon. Only the damage roll appears in the the VTT (Roll20). If i remove the customization the ATK and DMG rolls appear normally. Am I doing something wrong? Plus one weapons put in the character sheet from the compendium AND weapons customized in the character sheet to have these properties are both functioning this way.

**Comment by pandanielxd** [comment]
This should already be fixed in the dev version ( https://github.com/kakaroto/Beyond20#developer-mode-installation )

**Comment by thedrviking** [comment]
Excellent! Thank you so much, I did not notice there was a different Dev version. Much Appreciated!
