### ISSUE TITLE
[Request] Right click context menu?

### ISSUE THREAD

**Issue by hypergig** [kakaroto/Beyond20#445]
It would be super dope if you could right click on any dice roll and get a context menu with options like:
* With advantage
* With disadvantage
* Hide
* Show (if you are the gm)

Or even just a pop up much like your extension menu where you can dial in an adhoc roll.

**Comment by Aeristoka** [comment]
You can already use Shift + Click for Advantage, CTRL + Click for Disadvantage, and Alt + Click for normal roll (on forced advantage/disadvantage rolls)

**Comment by hypergig** [comment]
I am so sorry, I did know realize I could do that!

**Comment by Aeristoka** [comment]
> I am so sorry, I did know realize I could do that!

Hey, no worries, it's an oft-missed feature.

**Comment by kakaroto** [comment]
> Hey, no worries, it's an oft-missed feature.
Now that the hotkeys are displays in the quick settings popup, hopefully, more people will notice it :)
