### ISSUE TITLE
Extra Damage Toggle doesn't work: Protector Aasimar - Divine Soul - Roll20

### ISSUE THREAD

**Issue by DeChagny** [kakaroto/Beyond20#447]
I got an issue when I use the dndbeyond character sheet and open the beyond20 menu to activate the Radiant Soul toggle on my Protector Aasimar it either doesn't show the static extra dmg (the field shows Radiant Soul but no number) or doesn't forward the roll at all to Roll 20.

**Comment by Aeristoka** [comment]
Please post some screenshots of the issue for troubleshooting purposes.

**Comment by DeChagny** [comment]
Screenshots below. It seems like direct attacks don't reach roll20 at all and are effects leave out the extra damage.
[https://ibb.co/3BFxbh7](url)
[https://ibb.co/3BFxbh7](url)

**Comment by kakaroto** [comment]
That looks like maybe you haven't updated to the latest Beyond20 release? Make sure you check that Chrome/Firefox automatically updated to 2.1.1 and confirm which version you use.

**Comment by DeChagny** [comment]
checked that asap as I had that bug because I saw a message popping up about the update
should be correct, right?

I also restarted the whole browser... but maybe it's my VTT that conflickts with it, I'll check on that as well, thanks for nugging me in that direction. I'll update as soon as I know more

https://ibb.co/9yFZJLW

**Comment by kakaroto** [comment]
Humm.. thanks for checking, that sounds like Beyond20 isn't correctly parsing the character's level anymore? Will need to verify from my side.

**Comment by DeChagny** [comment]
FYI
I updated my VTT Enhancement Suite and it didn't change the issue.
So I can exclude that at least. Hmm.
Any more infos I could provide?
I'm using chrome and will try this on firefox later to see if that behaves somehow different.

**Comment by DeChagny** [comment]
Okay, I checked this on Firefox as well. I dunno if firefox has less options but this toggle won't show up there.
Gonna check if I did something wrong in the setup process.
Installed beyond20 and VTT enhancement suite afterwards.

Still gonna double check.

**Comment by Aeristoka** [comment]
I can't replicate this issue.

![image](https://user-images.githubusercontent.com/7988297/87312666-19089c80-c4de-11ea-85ed-734922108eea.png)


Try 100% disabling VTT Enhancement Suite, see if it works then.

**Comment by DeChagny** [comment]
I disabled the VTT Enhancement Suite and still had the same issue. I guess this must be a local issue on my side and not a bug from beyond20. So I'll close this topic and try to find the problem on my side. Thanks for your time! :/

**Comment by Aeristoka** [comment]
I'd say try to Remove Beyond20 from your browser, then add it again. We've seen some weirdness where settings get stuck in strange ways, that usually resolves it.

**Comment by DeChagny** [comment]
Guess we thought the same. I removed all P&P relevant add ons of chrome and solely reinstalled beyond20. Same behaviour.
Completely reinstalled chrome and addon, still unchanged.
Tried it on two different PCs and did behave on them like on my own.
That's starting to get pretty weird, I doubt I'm the only one playing a protector-aasimar but having this issue on other people's PCs as well still doesn't give me a repro that's worth a penny.
Even a PC that had nothing at all to do  with roll20 and used a different browser (firefox)

**Comment by Aeristoka** [comment]
Can you send me a character sheet to test with?

**Comment by DeChagny** [comment]
Sure thing, here you go.

https://ddb.ac/characters/31978415/Lq8W8h

**Comment by Aeristoka** [comment]
@kakaroto 
![image](https://user-images.githubusercontent.com/7988297/87348924-c72e3980-c512-11ea-8c30-5d5425f6ad73.png)

**Comment by Aeristoka** [comment]
@kakaroto You were right, it did NOT parse the character level...

![image](https://user-images.githubusercontent.com/7988297/87349341-618e7d00-c513-11ea-91c1-9c7074122f87.png)

**Comment by Aeristoka** [comment]
@DeChagny Are you the owner of the character sheet you posted? Or are you using it on the Public view

**Comment by Aeristoka** [comment]
@DeChagny You found a very important bug!

**Comment by kakaroto** [comment]
Thanks for finding this @Aeristoka and reporting the problem @DeChagny and being patient while it got figured out!
Seems I made a typo when I fixed the sheets with D&D Beyond's update from last week, and XP based leveling doesn't properly parse the level :(

**Comment by DeChagny** [comment]
Glad I was able to find something of worth.
Thank you both for your hard work!
