### ISSUE TITLE
DNDB Digital Dice result notification need to be cleaned up

### ISSUE THREAD

**Issue by jaredkent** [kakaroto/Beyond20#448]
Digital dice attack rolls aren't adding the hit modifier after the 1d20 roll.

**Comment by jaredkent** [comment]
![image](https://user-images.githubusercontent.com/19612384/87227617-40d6f380-c36a-11ea-90f6-487919f410da.png)

**Comment by kakaroto** [comment]
As explained on Discord, the digital dice are only showing the dice results, the actual modifiers get added by Beyond20 in the actual roll result that is sent to the VTT.
Note: that notification is generated by D&D Beyond to give the results of the digital dice that were rolled, it's not created by Beyond20, I only change the `Custom` title to `Beyond20` to make it more pleasing. But I'm noticing that it's showing the `=18` result which used to also be replaced by the Beyond20 icon, so something may have changed which broke that.
So, while the original issue you raised is invalid, I'm changing the issue to better fit the information I've gotten from it.
Thanks

**Comment by kakaroto** [comment]
Fixed with https://github.com/kakaroto/Beyond20/commit/c9734657bed56a1b3c6efe1bdb9dd8d349894c40
(seems I had this issue duplicated as #476 and #481)
