### ISSUE TITLE
Digital Dice attack rolls add damage roll to the attack roll result

### ISSUE THREAD

**Issue by jaredkent** [kakaroto/Beyond20#449]
![image](https://user-images.githubusercontent.com/19612384/87227605-361c5e80-c36a-11ea-95e1-c1dd4bcabbf0.png)

**Comment by kakaroto** [comment]
As explained elsewhere, that notification is created by D&D Beyond to give us the result of the rolls themselves, Beyond20 uses that information to actually build the correct roll that it sends to your VTT.
So, this isn't "damage is added to the attack" but rather "all dice needed for an attack are rolled at once" which is something I worked really hard to actually get working :)
In other words: not a bug, but a feature :)
