### ISSUE TITLE
Digital Dice attack rolls don't query my custom dice formula.

### ISSUE THREAD

**Issue by jaredkent** [kakaroto/Beyond20#450]
![image](https://user-images.githubusercontent.com/19612384/87227630-56e4b400-c36a-11ea-9426-2c4aa67f76e1.png)

**Comment by kakaroto** [comment]
As explained in Discord, the query formula is a roll20 specific formula, so it will only work if the roll is executed on Roll20.
Thanks for reporting it, but I'm closing this as I consider it invalid.
