### ISSUE TITLE
When Digital Dice are on "Auto roll Damage and Crit" is stuck on. Turns itself back on immediately after turning it off and closing the menu.

### ISSUE THREAD

**Issue by jaredkent** [kakaroto/Beyond20#451]
Digital Dice also don't seem to be rolling a separate damage die if this setting IS on. This may be attached to Digital Dice adding the damage roll to the attack roll total. See previous issue.

**Comment by kakaroto** [comment]
This is a known issue that will require some work. Closing as it's a duplicate of #307
