### ISSUE TITLE
Enable Advantage on Initative

### ISSUE THREAD

**Issue by Heljspe** [kakaroto/Beyond20#453]
When rolling with advantage on initiative it only rolls once in Roll20. Advantage rolls work for other rolls, but doesn't appear to work for initiative.

**Comment by Aeristoka** [comment]
Mouseover the result on Roll20, the dice formula is "2d20kh1" which means "Roll 2 d20s, keep the highest 1", it works just fine.

**Comment by Heljspe** [comment]
Oh perfect! Sweet, my bad then. :p Thanks. :)
