### ISSUE TITLE
When a spell level is incremented/decremented, there is an additional spell cast for every increment/decrement

### ISSUE THREAD

**Issue by Aeristoka** [kakaroto/Beyond20#459]
Steps to reproduce:

1. Open a spell (at any level), click the increment, decrement
![image](https://user-images.githubusercontent.com/7988297/87615904-01453a00-c6d1-11ea-99be-85e60cb3cab9.png)

2. Remember the number of times (cumulatively) that you clicked both these buttons.
3. Click the "Cast" Button
![image](https://user-images.githubusercontent.com/7988297/87616001-44071200-c6d1-11ea-9b6e-45f364cd6238.png)
(in this case, 2 increments, 3 decrements were clicked)
4. Observe that "New side panel" has two console posts for EACH of the increments/decrements (in addition to the initial click to open)
![image](https://user-images.githubusercontent.com/7988297/87616194-c68fd180-c6d1-11ea-8581-80021eb4d15f.png)
5. Observe that we will have 5 spells cast
![image](https://user-images.githubusercontent.com/7988297/87616161-b1b33e00-c6d1-11ea-906c-18f0f5bd7c86.png)

**Comment by kakaroto** [comment]
Fixed by ca0da4a08cfd00e9e0c19fee402783da72fe3ff7
