### ISSUE TITLE
Build instructions in README don't work on Windows.

### ISSUE THREAD

**Issue by MicahZoltu** [kakaroto/Beyond20#464]
`npm run build` does `run-s clean build:*`, which results in an error:
> 'run-s' is not recognized as an internal or external command, operable program or batch file.

I'm not sure where `run-s` is supposed to come from, but I don't see it as an NPM dependency.

Similarly, if try to manually build and package with `npm run build; npm run package:firefox` I get the following error:
> 'web-ext' is not recognized as an internal or external command, operable program or batch file.

This one is a tad more surprising since there is a `web-ext` dependency.  If I change the command to do the following instead it works:
```
node ./node_modules/web-ext/bin/web-ext build --source-dir=./build/firefox/ --artifacts-dir=./build/firefox/web-ext-artifacts/
```

I believe in this case the issue is that the `web-ext` NPM package is not installed as an NPM runnable binary (it isn't in `node_modules/.bin`).

**Comment by kakaroto** [comment]
Build instructions in the readme say that you first need to run `npm install` which you don't seem to have done.
`run-s` comes from the `npm-run-all` dev dependency, as well as `web-ext` which does get installed in the .bin directory.

**Comment by MicahZoltu** [comment]
I did do an `npm install` first, neither `npm-run-all` nor `web-ext` add anything to the `bin` folder (at least for me), which means they cannot be executed directly.

**Comment by kakaroto** [comment]
I don't know what to tell you. I've tested this personally on a windows machine, in a clean checkout to make sure the readme instructions were correct before I published the last release to make sure nothing was missing (the 2.0 release had something missing in the readme, so I made sure it worked for 2.1).
I get 102 files in my `node_modules/.bin` here after an `npm install`.

**Comment by MicahZoltu** [comment]
In your local install, do you see anything in `node_modules/.bin` other than 3 `gulp` files?  This is what I see (which means only `gulp` is available from a command prompt as I understand it):
![image](https://user-images.githubusercontent.com/886059/87896471-ec72f880-ca7a-11ea-8e12-0302b32bdaab.png)

**Comment by MicahZoltu** [comment]
If it matters I'm using NodeJS 14.

**Comment by Aeristoka** [comment]
Worked fine for me first try as well, so I'm also not sure what to tell you.

**Comment by kakaroto** [comment]
> If it matters I'm using NodeJS 14.

It might matter, I'm on node 13.5.0 with npm version 6.13.4. I just did a clean git clone again and after `npm install` I get the same 102 files in the .bin dir, including web-ext and run-s. 
gulp is the first dependency in the package.json, so are you sure your `npm install` didn't get interrupted or error out before it finished installing the other deps ?

**Comment by MicahZoltu** [comment]
Hmm, I did get an error the first time I did `npm install`, but then running it again worked without any error.  I'll do a clean and try it again.
