### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MicahZoltu** [kakaroto/Beyond20#466]
Option to remove components from the Roll20 spellcasting.

![image](https://user-images.githubusercontent.com/886059/87887702-f7696100-ca59-11ea-9c05-3371b1148b6f.png)

I don't know why this is being included, but it isn't something my table needs to see every time someone casts a spell and it adds noise to the chat logs.  If information about components is necessary, the "Display on VTT" serves that purpose well.

I'm using `master` (not a release version) if that matters.

**Comment by kakaroto** [comment]
Check the Beyond20 options. It's configurable, and it's included because a lot of people forget that some spells have material costs 
![image](https://user-images.githubusercontent.com/27990/87895292-0973e100-ca13-11ea-91aa-9753a92c33e4.png)
