### ISSUE TITLE
Add a "display character image" for character sheets

### ISSUE THREAD

**Issue by HaarisQureshi** [kakaroto/Beyond20#470]
Much in the way that you can send a monster stat block image to VTT (and soon item image), would be a nice feature to be able to send the character image (e.g. during session 1 where the characters introduce each other). I imagine reading the image is possible as the app already does so during Discord rolls where it is displayed. 

During discussion on Discord, the current issue is a UI one, as currently it's not clear where to best place a button without compromising the current snug fit.

**Comment by HaarisQureshi** [comment]
As an idea, I know it doesn't match the UI consistency of stat blocks (where the button is a 'Send to VTT' static button), but is it possible maybe to have the Send to VTT button be a pop-up, maybe when you mouse over the picture?

**Comment by kakaroto** [comment]
I think the UI issue of "where to place the button" is now fixed as D&D Beyond made the avatar visible within the sidepanel so a button there would work quite well.
![image](https://user-images.githubusercontent.com/27990/94221007-44cdd880-feb8-11ea-9d43-534190bf44b5.png)
