### ISSUE TITLE
Feature request: Option to set Sharpshooter/GWM use for every attack

### ISSUE THREAD

**Issue by LoneFenris** [kakaroto/Beyond20#471]
I notice a lot of players with Sharpshooter or Great Weapon Master will use those features more often than they don't. It'd be nice if there was a way to set those features to be used for more than just the next attack. Maybe a subswitch that will tell the extension to turn it off after one use or to leave it on until turned off?

**Comment by Aeristoka** [comment]
Rules as Written, each one must be declared on each attack, so they're likely to just remain as toggle on, use, they toggle off.

Strongest workaround: Make a custom weapon that rolls as if they're on.

**Comment by Cancleout** [comment]
maybe a shortcut key?

**Comment by kakaroto** [comment]
> maybe a shortcut key?

Definitely no. I don't want Beyond20 to be an app with a thousand shortcuts or options. It already has too many options to my taste. It should be there to help play on DNDB, not do everything for the players.
As Aeristoka suggested, the correct way of doing it is to customize the weapon, that's what D&D Beyond's customizations are for.
