### ISSUE TITLE
Feature request: Halfling Luck

### ISSUE THREAD

**Issue by voltaiac** [kakaroto/Beyond20#475]
Having to reroll every time you roll a nat 1 with a halfling _can_ be automated. Roll20 uses the 1d20ro<1 command for practically all d20 rolls, including but not limited to death saves and initiative. I'd love to do this myself but I don't know how to code...

**Comment by kakaroto** [comment]
Surprised nobody mentioned this until now! Yep, can definitely add support for it.

**Comment by maxmiliano** [comment]
The OP mentioned that:
> Having to reroll every time you roll a nat 1 with a halfling _can_ be automated.

Just to clarify, halfling luck doesn't grant rerolling **every** nat 1. The reroll must be used (even if it is another nat 1).

**Comment by Aeristoka** [comment]
> The OP mentioned that:
> 
> > Having to reroll every time you roll a nat 1 with a halfling _can_ be automated.
> 
> Just to clarify, halfling luck doesn't grant rerolling **every** nat 1. The reroll must be used (even if it is another nat 1).

Yes, that's right, and that's what the in-progress implementation is doing, if it gets a 1 on the initial roll (for the applicable use cases), it will reroll just one time, and it will use that new roll.
