### ISSUE TITLE
Add-on prevents Firefox Inspector from showing styles

### ISSUE THREAD

**Issue by jefgodesky** [kakaroto/Beyond20#479]
**Steps to Reproduce:**

1. Install the Beyond 20 addon in Firefox (79.0).
2. Load any page and inspect any element.

**Expected Behavior:** The Inspector's main panel (labeled "Inspectorr") shows the DOM, styles related to the element selected, and a third panel with options for layout, computed styles, changes, etc.

**Observed Behavior:** The section where styles should be displayed is completely blank.

**Comment by kakaroto** [comment]
Hi, first of all that makes no sense, as the extension has no control over that in any way at all. Second of all, I just upgraded to v79 to test and I have no issues with the styles section of the inspector, so I'd say check for your local settings maybe? Either way, I very much doubt that Beyond20 has any relation to the issue you're having.
