### ISSUE TITLE
Entirely customize the D&D Beyond digital dice notification

### ISSUE THREAD

**Issue by PHRAETUS** [kakaroto/Beyond20#481]
With the Beyond20 extension installed, rolls made in DnD Beyond with the digital dice directly from the character sheet, are not adding the modifiers. The modifiers are added in Beyond20 & passed down to Discord, if set up to do so.
![Initiative](https://user-images.githubusercontent.com/69392948/89712929-37759100-d9d3-11ea-96e0-bdde48251ce2.JPG)

**Comment by kakaroto** [comment]
Not a bug, that's the custom dice formula. If you roll an attack, you'll see the dice from all the rolls (to hit and damages).
That information box is created by D&D Beyond itself and is parsed by Beyond20 to figure out the digital dice results.
Leaving this issue open though as the plan is to completely remove those results once they are parsed.
