### ISSUE TITLE
New VTT support for dungeon-revealer?

### ISSUE THREAD

**Issue by bryceosterhaus** [kakaroto/Beyond20#488]
Hi, I was curious what the process for adding another VTT would be? I currently use https://github.com/dungeon-revealer/dungeon-revealer and it would be awesome if beyond20 could work for that as well. 

If there is anything that needs to be done on their side, I created an issue at https://github.com/dungeon-revealer/dungeon-revealer/issues/654.

I am happy to contribute for this feature

**Comment by Aeristoka** [comment]
It would be you yourself doing the coding to make it happen, and submitting the Pull Request to get it done, then supporting it thereafter.

**Comment by bryceosterhaus** [comment]
@Aeristoka sounds good! Thanks for the info

**Comment by kakaroto** [comment]
My policy with regards to support for new VTT apps has changed. Please read the updated FAQ about it  https://beyond20.here-for-more.info/faq#can-you-add-support-for-insert-new-vtt-name
