### ISSUE TITLE
Question about hexblade’s curse

### ISSUE THREAD

**Issue by DarrynGlass** [kakaroto/Beyond20#489]
I have a multi-class rouge/warlock (hexblade) and the crit on 19 does not seem to be working.  I am pretty sure this is my fault, but is there any help for this?

![image](https://user-images.githubusercontent.com/29684482/90178106-0bf6fb80-dd71-11ea-93a1-d012863c9c2e.png)

**Comment by pandanielxd** [comment]
https://i.imgur.com/vtxNxHB.png
Have you enabled the setting?

**Comment by DarrynGlass** [comment]
Ah it wasn't showing up.  I did look there first thinking it was like the rouge's sneak attack, but the option was not showing.  Thanks!

**Comment by kakaroto** [comment]
It probably didn't show because of this : https://beyond20.here-for-more.info/faq#i-have-a-class-featurefeat-that-the-features-page-says-is-supported-sharpshooter-feat-for-example-but-i-dont-see-the-option-to-use-it
