### ISSUE TITLE
Change auto-roll damage & crit to a per-character option?

### ISSUE THREAD

**Issue by somanyrobots** [kakaroto/Beyond20#490]
Would it make sense to make auto-damage & crit a character option, instead of a global one? In practice, I find myself always preferring this setting on _except_ when I'm playing paladins. There are some other decide-after-the-attack-hits effects, but like 90% of the use case is just about smites.

**Comment by kakaroto** [comment]
I think there may be a lot of global options that may need a per-character override. I'll keep this in mind to think it through, though it won't go into the next release, maybe the one after.

**Comment by kakaroto** [comment]
Considering that with the Digital Dice option now, you can click a different area to roll hit+damage, only to hit, or only damage, I think this can be closed.
