### ISSUE TITLE
remove "roll twice" option in query roll for the renderer 

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#492]
Roll20 query: 
![image](https://user-images.githubusercontent.com/27990/90370596-a4c09c00-e03b-11ea-86ba-b45bdad40b28.png)

Renderer query : 
![image](https://user-images.githubusercontent.com/27990/90370621-abe7aa00-e03b-11ea-99e4-210be02e4494.png)

Not sure it makes sense to roll twice when the user is being asked what they want. I think it needs to be removed.
Alternatively, it could be moved down to the end of the list and added in the roll20 query as well. Either way, something needs to be done here.
Opinions on the subject are welcome (cc @Aeristoka)

**Comment by Varkolaak** [comment]
My suggestion here would be to move it to be between Disadvantage & Roll Thrice, then use the resulting list for both the integrated and roll20 queries - that way if there is a group out there that uses it for something then it's not taken away from them.
