### ISSUE TITLE
Spirit Guardians rolling 6d8 instead of 3d8

### ISSUE THREAD

**Issue by Travis101** [kakaroto/Beyond20#495]
When I cast Spirit Guardians with the plugin, it should roll 3d8 (radiant OR necrotic) but it is rolling them both together (6d8). This does not happen with the extension off. 

Let me know if you need any other specifics but this should be easy enough to reproduce. 

Example Character sheet
https://www.dndbeyond.com/profile/Travis101/characters/34146110

![image](https://user-images.githubusercontent.com/69984120/90806431-61905280-e2f3-11ea-9f96-fa8a13e3209f.png)

**Comment by Aeristoka** [comment]
turn off Digital Dice. It's showing you ALL the dice it rolled (which will display as two separated 3d8s on the damage output).

The actual output is 100% fine.

**Comment by Aeristoka** [comment]
![image](https://user-images.githubusercontent.com/7988297/90806770-b96e8f80-e2da-11ea-8dde-a2fb6d910d45.png)
 Example of the straight DnDBeyond output.

**Comment by kakaroto** [comment]
This is related to #476 that notification shows all the dice (the to hit, and any and all damages) as Beyond20 does a custom roll with the digital dice and that notification is from D&D Beyond itself. That's where Beyond20 gets the results from.
