### ISSUE TITLE
Crossbows not showing attack roll

### ISSUE THREAD

**Issue by gabemahoney** [kakaroto/Beyond20#496]
When I click the "Beyond 20" button from the Heavy or Light crossbow panel in DndBeyond, roll20 only displays a damage roll. Roll20 does not display the attack roll.

Here is an example of what I see in roll20 after clicking the "Beyond 20" button from the Heavy or Light crossbow panel in DnDBeyond: https://www.dropbox.com/s/cip4ixm4enbts5i/Screen%20Shot%202020-08-20%20at%2010.11.36%20PM.png?dl=0

**Comment by kakaroto** [comment]
My guess is you're clicking on it from the equipment page, not from the action page. You'll notice that D&D Beyond does not provide any "To Hit" information from the equipment page.
Once you equip it and roll it once from the actions, Beyond20 will cache the to-hit value for later use from the equipments page.

Please confirm that this is your situation and close the issue if it is.

**Comment by gabemahoney** [comment]
You are correct.
