### ISSUE TITLE
Paladin dueling feat not automatically calculated

### ISSUE THREAD

**Issue by gabemahoney** [kakaroto/Beyond20#497]
I have a Paladin with the dueling feat. The dueling feat should add +2 to melee attack rolls if I am using a one-handed melee weapon and not other weapons.

My character's str bonus is +5 and his proficiency with simple weapons is +2. With a simple one-handed weapon (in this case, a longsword) equipped, beyond20 only gives him a +7.

His dueling feat should be added to that bonus giving him a +9. 

The only equipped items on the dndbeyond character sheet are the longsword, a shield and splint armor.

**Comment by Aeristoka** [comment]
You're calculating that wrong.

Proficiency is added ONLY to To-Hit rolls, not to damage.

So To-Hit is 1d20 + (relevant mod) + Proficiency (if proficient)
Damage is 1dx (the weapon damage die) + (relevant mode)

and in this case

+ (dueling) 2

This is DnDBeyond taking care of it 100% correct in this case. Beyond20 does not and has not ever calculated in things like that, as DnDBeyond already provides them.
