### ISSUE TITLE
Crash in parsing a homebrew attack

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#503]
the regexp was making some undefined value : 
https://www.dndbeyond.com/monsters/1081547-wintersplinter-cos

```html
<p><em><strong>Grasping Root.</strong></em> <em>Melee Weapon Attack</em>: +8 to hit, reach 15 ft., one creature. <em>Hit</em>: 5 (1d6 + 2) bludgeoning damage and the target is <a class="tooltip-hover condition-tooltip" href="/compendium/rules/basic-rules/appendix-a-conditions#Grappled" data-tooltip-href="//www.dndbeyond.com/conditions/6-tooltip?disable-webm=1&amp;disable-webm=1">grappled</a> (escape DC 15).&nbsp; The root has AC 15 and can be severed by dealing 6 slashing damage or more to it at once. Cutting the root doesn’t hurt the blight but ends the grapple.&nbsp; The Grasping Root attack can only be&nbsp; targeted against a creature not already grappled.</p>
```

```
Error handling response: TypeError: Cannot read property 'replace' of undefined
    at Monster.parseHitInfo (chrome-extension://gnblbpbepfbfmoobegdogkglpbhcjofh/dist/dndbeyond_monster.js:3637:33)
```

**Comment by Aeristoka** [comment]
I don't know if I feel like this is a thing that should be addressed personally. It makes sense to make things fit nicely onto the officially released Monsters/etc., but do we want to be covering every Homebrew case?

**Comment by kakaroto** [comment]
I wouldn't make it work because it's homebrew, but it shouldn't be throwing an unhandled exception for sure. The bug isn't "make it work with this", it's "there'a crash during parsing" :)
I also had tested the use case of "<value> <damage type> damage" where the value is a fixed amount and doesn't have a dice formula in parenthesis like this : https://www.dndbeyond.com/monsters/bat
So the regexp should have worked for "6 slashing damage" and I need to understand why.

**Comment by Aeristoka** [comment]
Yep, just saw your response on Discord and understood, after I had replied here.

**Comment by kakaroto** [comment]
It's called multi-threaded ~~process~~ discussions with no mutex 🤣
