### ISSUE TITLE
support FoundryVTT 0.7.x+

### ISSUE THREAD

**Issue by breunigs** [kakaroto/Beyond20#504]
FoundryVTT 0.7.x, which is currently is alpha changed the way dice rolls work – and thus unfortunately broke Beyond20. The specific error message is `Uncaught (in promise) TypeError: pool.roll is not a function` when looking at the console in the fvtt tab, but I guess it's not going to be particularly helpful to post the full stacktrace.

**Comment by Aeristoka** [comment]
Already present in the Dev version:

https://github.com/kakaroto/Beyond20#developer-mode-installation

**Comment by breunigs** [comment]
ah, great to hear!
