### ISSUE TITLE
FoundryVTT Error - Can't roll, errors in console.

### ISSUE THREAD

**Issue by LaytonGB** [kakaroto/Beyond20#507]
![image](https://user-images.githubusercontent.com/29107364/92330373-40a35d80-f066-11ea-934a-17a048a9642f.png)

---

Descriptions still go through fine.
![image](https://user-images.githubusercontent.com/29107364/92330378-587ae180-f066-11ea-814d-03023b61bf9f.png)
Monsters still work.
![image](https://user-images.githubusercontent.com/29107364/92330470-ed7dda80-f066-11ea-8e05-38d94ef1d146.png)

If there is any way I can help please let me know, thanks.

**Comment by Aeristoka** [comment]
Downgrade FoundryVTT to 0.6.5/0.6.6 or install the Dev version of Beyond20 from GitHub

**Comment by LaytonGB** [comment]
Will do, thanks for fast reply!

**Comment by LaytonGB** [comment]
Scratch that, I'm already on 0.6.6 
![image](https://user-images.githubusercontent.com/29107364/92330483-12724d80-f067-11ea-99b4-cdb8cc10591a.png)

**Comment by Aeristoka** [comment]
Ok, screenshot of the broken weapon?

**Comment by LaytonGB** [comment]
Its all of them, this character just can't roll.
Here's a link to the character: https://www.dndbeyond.com/profile/FuriousR/characters/20056873
I'll test some other characters now.

**Comment by LaytonGB** [comment]
Other characters work fine, it is that character only. He cannot roll at all.

**Comment by LaytonGB** [comment]
If it helps, that is the only character I've opened with the D&D Beyond Character App on mobile.

**Comment by LaytonGB** [comment]
I found the cause, it was totally me being an idiot.
This was in the Custom Die Roll formula bonus, because it makes a d4 button on roll20: `0[Roll &#100;4](!&#13;/r d4)`

Once removed, everything works fine. Sorry about the time waste.

**Comment by kakaroto** [comment]
Ha, thanks for figuring it out, since that formula wasn't in the original request (it's hidden within the character settings object), I didn't see it, it all looked good and I was perplexed at the "invalid arithmatic expression"

**Comment by LaytonGB** [comment]
Happy I could catch it before I went to bed. 👍
It could be a nice feature to add a chat input that comes out after the roll? That way I can input `[Roll d4](!&#13;/r d4)` instead of the previous abomination. 😅 Not sure how many people would make use of it though.

**Comment by kakaroto** [comment]
With the recently merged PR #460 you could add it to specific attacks as `[[after]]/some-macro[[/after]]` (with Furnace module, you can call macros from chat that way)

**Comment by LaytonGB** [comment]
> With the recently merged PR #460 you could add it to specific attacks as `[[after]]/some-macro[[/after]]` (with Furnace module, you can call macros from chat that way)

I'm struggling a bit with this. Where should I insert my text? On D&D Beyond? In foundry?

**Comment by kakaroto** [comment]
You'd customize an attack and put that as a custom note for the attack.

**Comment by LaytonGB** [comment]
Thanks, with that I've got it working! This is fantastic, thanks much 👍
