### ISSUE TITLE
Request: Option to deactivate initiative rolls from DnD Beyonds encounters

### ISSUE THREAD

**Issue by pascalwacker** [kakaroto/Beyond20#508]
Currently there's the option `Add initiative roll to the Turn Tracker`, to enable/disable initiative rolls. However it doesn't work for the ["encounters"](https://www.dndbeyond.com/my-encounters). If you set up an encounter and run that (with auto rolled initiative for the monsters), it will start the combat tracker on Roll20, clear it and add all the monsters as well as the players in the encounter (for me that are the dummy players "Player A", "Player B", etc.)

The following problems arise from this behaviour:
1. All monsters of the encounter get added to the combat tracker, also the ones on the GM layer, since there's no way of telling which is which.
2. If there are multiple monsters of the same type, ex. two bandits, named "Bandit 1" and "Bandit 2" on Roll20, it doesn't know which is which.
3. Since it clears the current combat tracker, all players that have already rolled get removed and have to reroll.

I think the best option would be to add another toggle switch "Add Initiative roll from Encounters to the Turn Tracker".

A quick fix could be to check the url of the page the initiative roll originates from, and if it's `/https:\/\/www\.dndbeyond\.com\/combat-tracker\/.*/` either ignore it, or handle it depending on the setting in `Add initiative roll to the Turn Tracker`. I personally would prefer a second option for it, so I don't need to toggle the switch when DMing/being a player.

**Comment by Aeristoka** [comment]
@shadow7412

**Comment by kakaroto** [comment]
1. If the monsters on the GM layer have the same name as their encounter's counterpart ("Bandit (A)", "Bandit (B)", etc..), they will be matched correctly and will be hidden as expected in the combat tracker
2. same as 1)
3. You'd enter the player's initiatives in D&D Beyond's encounter as you'd need to track it there, and it would get copied to the tracker in Roll20.

Finally, there's already an option to disable the combat tracker sync (towards the bottom of the full options).
![image](https://user-images.githubusercontent.com/27990/92415852-cab3fa80-f128-11ea-9536-293b1a5e33a0.png)

**Comment by amenokos** [comment]
Along with the information provided by @kakaroto, a very simple solution is to create corresponding **extra** tokens on the GM layer of Roll20 that have the same names as the monster in the Combat Tracker for an encounter you've built. For example, if you've created an encounter for your players to combat four goblins, you'd need to create four tokens in Roll20 on the GM layer named: Goblin (A), Goblin (B), Goblin (C), and Goblin (D), Although you'll see those monsters on the Roll20 Turn Order panel as the DM, they'll be dimmed and your players won't see them at all. 

If you put these **extra** tokens inside a wall (that has a dynamic lighting border), you can also later bring them to the Object layer one-by-one to have them revealed on the Turn Order panel. but your players would still not see the extra tokens.
