### ISSUE TITLE
Savage Attack not being added to Polearm Master Bonus Attack

### ISSUE THREAD

**Issue by HamburgerPun** [kakaroto/Beyond20#509]
Should be adding an additional d4 to critical hits with the bonus action attack associated with the Polearm Master feat.

**Comment by Aeristoka** [comment]
Screenshots of your situation would be helpful to troubleshoot.

**Comment by HamburgerPun** [comment]
As I was making screenshots, I noticed it won't add the Savage Attack crit if I customize the action.  I changed the name from "Polearm Master - Bonus Attack" to "Keytar - Bonus Attack" and it wouldn't add the extra die.  When I removed customizations, it added the extra die.  

So not at all a big deal!  I can still provide screenshots if needed, but I don't think this issue needs to be addressed

**Comment by kakaroto** [comment]
Ah yeah, that would make sense, Beyond20 wouldn't know it's the Polearm Master attack if the name doesn't match.
Thanks!
