### ISSUE TITLE
Bug: Paladins Improved Divine Smite does not apply to the Polearm Master - Bonus Attack

### ISSUE THREAD

**Issue by pandanielxd** [kakaroto/Beyond20#514]
The setting is enabled, and works perfectly for "normal" Action attacks, but it does not do anything when rolling for the bonus attack of Polearm Master 

![image](https://user-images.githubusercontent.com/65407753/93324165-d2a12800-f815-11ea-9b73-22916c742c0d.png)
![image](https://user-images.githubusercontent.com/65407753/93324190-d9c83600-f815-11ea-8edf-20e2189997f6.png)
![image](https://user-images.githubusercontent.com/65407753/93324205-ddf45380-f815-11ea-915b-f2073835a25b.png)

Here is a link to the sheet: https://www.dndbeyond.com/profile/pandanielxd/characters/35724719

**Comment by kakaroto** [comment]
That was fixed in the development version already (see #468) so should be available with the next release. 👍
