### ISSUE TITLE
Brutal critical does not apply greater weapon fighting

### ISSUE THREAD

**Issue by mithom** [kakaroto/Beyond20#515]
according to dndnext (and i agree), greater weapon fighting should apply on brutal critical or savage attack dice. This is currently not the case on roll20. currently this is just (for a greatsword for example) 1d6 and not 1d6ro<2

**Comment by Aeristoka** [comment]
Can you provide some references for your argument, as well as screenshots of this not happening, and an example character link?

**Comment by mithom** [comment]
the dndnext link that i meant to link https://rpg.stackexchange.com/questions/104650/how-does-the-great-weapon-fighting-fighting-style-interact-with-critical-hits-an

**Comment by mithom** [comment]
a character that has both: https://ddb.ac/characters/35892281/PdKJzX

**Comment by mithom** [comment]
screenshot of not heaving greater weapon fighting
![image](https://user-images.githubusercontent.com/9282831/93638512-b65ce100-f9f7-11ea-945c-93d14d5f74c9.png)

**Comment by mithom** [comment]
it does work on the regular crit die and the regular rolls

**Comment by mithom** [comment]
has this been resolved, or closed due to inactivity? Thanks for the great job you've done btw!

**Comment by kakaroto** [comment]
It was resolved, you can click the commit hash (666c181) above to see the fix
![image](https://user-images.githubusercontent.com/27990/94653857-39204e80-02ca-11eb-8fec-f61ebfacca5f.png)
