### ISSUE TITLE
Initiative Tracker handles multiple monsters of same name

### ISSUE THREAD

**Issue by buddha314** [kakaroto/Beyond20#516]
Party fighting three rats, each rat gets their own initiative in the Encounter Tracker but on Roll20 they all appear as the first rat.  Is there a way to find three rats on the VTT and identify them to cycle through or are token identified exclusively by display name?

BTW, patron!  Love your work!

**Comment by buddha314** [comment]
BONUS:  Would be great if, in the above scenario where multiple monsters of the same name are encountered, if colored dots could be associated with each automatically.  That might not be possible via the API, but it would make it easier to track with the players.

**Comment by kakaroto** [comment]
> Party fighting three rats, each rat gets their own initiative in the Encounter Tracker but on Roll20 they all appear as the first rat. Is there a way to find three rats on the VTT and identify them to cycle through or are token identified exclusively by display name?

In the Encounter Tracker they have different names automatically : "Rat (A)", "Rat (B)" and "Rat (C)". If on Roll20, you have tokens with the matching names, the tokens will match with the combat tracker and it will sync as expected.

> BTW, patron! Love your work!

Thanks! ❤️ 

> BONUS: Would be great if, in the above scenario where multiple monsters of the same name are encountered, if colored dots could be associated with each automatically. That might not be possible via the API, but it would make it easier to track with the players.

That wouldn't be possible, I don't think. Using different names per token remains the best way to differentiate them.

**Comment by cgplayer2000** [comment]
Also, both on Roll20 and on Foundry there are API scripts (Roll20) and modules (Token Mold, for one) that allow one to add numbers or other types of distinguishers to differentiate between mooks.  I use Token Mold and it works great.
