### ISSUE TITLE
Request: Fix Steel Defender and Beast Companion stat blocks.

### ISSUE THREAD

**Issue by adriangaro** [kakaroto/Beyond20#518]
I know this may be outside of the scope of the extension, but considering it already alters the stat blocks to insert the roll buttons, would it be possible for the extension to fix the broken stat blocks for these two features when they are viewed in the Extras tab in a player character sheet?

The stat blocks are broken as they are not updating the stats properly. Some of the issues DnDBeyond currently has with these two specifically are that they are not updating with your proficiency increase. 

For example, on the steel defender somehow only athletics skill is increased to 6 compared to proficiency which already stays at 4 when you have +2 proficiency. The actions are also not updating their to hit, damage and heal amounts. Probably saving throws are also not updated, according to the 'Might of the Master' feature on it.

In the case of beastmaster companion, the only one updating correctly is the AC. The to hit and damage aren't updated.

Now I know these are currently limitations on the DnDBeyond side, so not an issue for Beyond20, but I think it would be a good fix since if it is possible/wanted to be implemented as there would be no need to make either a stablock in roll20/any other vtt for the companions or having to create homebrewed fixed versions for them.

**Comment by Aeristoka** [comment]
This is beyond the scope of the extension really, as Beyond20 scrapes what is easily there, and works from that.

**Comment by adriangaro** [comment]
Yeah expected as much, although thanks for the quick response!

**Comment by Aeristoka** [comment]
I super wish that DnDBeyond would actually scale it themselves, as the parsed values would always be accurate. They haven't yet, but they have also been doing massive core changes to how DnDBeyond character sheets work, so here's hoping!

Please close the issue as well if you would.
