### ISSUE TITLE
Beyond 20 send attack and skill “text” to the display feature?

### ISSUE THREAD

**Issue by SirAron111** [kakaroto/Beyond20#519]
Is it possible to show the text of the attacks and abilities i do with beyond 20 from monster stat blocks on discord? Currently, when I have it set to send the rolls to discord it only flat out shows the numbers, but not the text for the damage. Which sometimes confuses my players on what part of the damage they should take. Especially since it simply adds all numbers together to a total.

For example this attack from the Water Elemental Myrmidon has two different damage types, but the bot puts them together in one and with no “text” added to it, it can be confusing for the players what dmg they take now.  (many monsters have such problems)

Trident. Melee or Ranged Weapon Attack: +7 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 7 (1d6 + 4) piercing damage, or 8 (1d8 + 4) piercing damage if used with two hands to make a melee attack
I mean if you can read the dice formula, you should be able to read and display the text the specific dice formula is part of.
Here is what it looks like atm, even in the Dev Version (tested it).

![Unbenannt](https://user-images.githubusercontent.com/39855956/94198415-8611b880-feb7-11ea-92eb-0b044703d5f6.PNG)

**Comment by Aeristoka** [comment]
Can you provide an example from rolling in DnDBeyond itself, or to Roll20, as a reference?

**Comment by SirAron111** [comment]
Sure here. the stat block on dnd beyond and the roll send to roll 20 instead of discord.

![Unbenannt](https://user-images.githubusercontent.com/39855956/94199151-aaba6000-feb8-11ea-80fc-f0afe8f5ed19.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/39855956/94199154-aaba6000-feb8-11ea-9629-3a937b308656.PNG)

what i mean to ask is. Is it possible to add a toggle so it not only shows the rolled numbers. but also adds a little text box under it, that show the actuall description of the attack when send to the discord.
