### ISSUE TITLE
[Request] Allow mappable hotkeys for toggleable class features that only apply to the next roll.

### ISSUE THREAD

**Issue by jellylamp** [kakaroto/Beyond20#525]
It would be really nice if you could toggle a class/feat feature (i.e. Great Weapon Master) with a hot key similar to the ctrl and shift for advantage and disadvantage feature.  

These would probably need a custom user-mapped field that lets them decide the hotkey because there can be multiple of these toggle-able features (its a big list).

Alternatively, adding a setting to allow them to stay on would be another good way to make this more user friendly.

![image](https://user-images.githubusercontent.com/10146513/94512548-4960fc80-01ea-11eb-9afa-f663bfbc4aeb.png)

**Comment by Aeristoka** [comment]
Related to #120

**Comment by kakaroto** [comment]
the hotkeys would be for things like whisper rolls and roll type, but not for specific toggleable settings, there are dozens of those, it would be quite complicated to do a hotkey for each, and impossible to manage in a usable UI.
If you want to use that feature as 'always on', the proper way to go about it is to create customize your weapon to add the penalty/damage as bonuses. D&D Beyond has an easy to use interface for customizing weapons, and that's what it's for.

**Comment by jellylamp** [comment]
I disagree DND Beyond has an easy way to do this. If you are using a magical weapon the weapons homebrew options are extremely limited.

Always wanting to attack with certain feats like great weapon master make sense to allow a permanent toggle on. For example a barbarian with reckless attack its almost always worth it.

**Comment by kakaroto** [comment]
> I disagree DND Beyond has an easy way to do this. If you are using a magical weapon the weapons homebrew options are extremely limited.

How exactly is it difficulty to click the customize button on the weapon (whether magical or not) and add -5 and +10 to the bonus fields there? 

![image](https://user-images.githubusercontent.com/27990/95146284-6a29d480-074b-11eb-8d5f-153020c4c6c5.png)

**Comment by jellylamp** [comment]
My apologies, I thought you meant to do it through the homebrew magical item menu which imo is very difficult to customize for weapons and doesn't auto update on your sheet right away. You are correct your way is much easier.

I'd still like to see this as a low priority enhancement. Its much easier to toggle on/off per monster as needed via the plugin than going in and editing your weapon each time, especially if there are already values there.  Again for example I have a fighter with GWM, I use it depending on a monsters AC, but then have to toggle it 3 times should I choose to use it, or in your example modify per monster in the app.

But its up to you I guess. I'd be willing to take a stab at it as a contributor if that makes a difference.

**Comment by Aeristoka** [comment]
> My apologies, I thought you meant to do it through the homebrew magical item menu which imo is very difficult to customize for weapons and doesn't auto update on your sheet right away. You are correct your way is much easier.
> 
> I'd still like to see this as a low priority enhancement. Its much easier to toggle on/off per monster as needed via the plugin than going in and editing your weapon each time, especially if there are already values there. Again for example I have a fighter with GWM, I use it depending on a monsters AC, but then have to toggle it 3 times should I choose to use it, or in your example modify per monster in the app.
> 
> But its up to you I guess. I'd be willing to take a stab at it as a contributor if that makes a difference.

This has been discussed a ton already. What you do is not edit the item every time, you keep TWO copies of the weapon, one "Normal", one "GWM" or "Sharpshooter" as appropriate. That way it's nice and quick.

@kakaroto is right, if there are toggles for all that kind of thing, it will get pretty insane pretty fast.

**Comment by kakaroto** [comment]
Yeah, creating a homebrew item for that would be complex, but just customizing the weapon. I also don't suggest to edit it when wanting to use it, but rather to have 2 copies of the weapon, one regular and one with the bonuses and custom name saying `<weapon name> (GWF)` for example, then you just roll the one you want to use based on that. Editing each time which be boring.

As for contributing the change, I wouldn't accept it. It's not a difficult change but I don't want to have extra options and extra complexity, I'm already quite annoyed by the amount of options  already available and I don't want it to basically become like trying to configure the linux kernel config for building it... I want to reduce the number of options instead of increasing them.

**Comment by jellylamp** [comment]
Fair enough, thanks for the responses y'all
