### ISSUE TITLE
Rolls from D&D Beyond not posting to FVTT via Beyond20

### ISSUE THREAD

**Issue by AggieBear** [kakaroto/Beyond20#526]
been having issues getting rolls to go from Roll20 to FVTT. It requires players to refresh Chrome regularly and then re-engage Beyond20.

![image](https://user-images.githubusercontent.com/72158902/94720337-f4240880-0319-11eb-91f6-c925238fbfbd.png)

**Comment by Aeristoka** [comment]
Actually an issue with VTTA (these are not Beyond20 Rolls).

Please close.

**Comment by kakaroto** [comment]
Yeah, that looks like VTTA overriding the Beyond20 icons in a monster's page. You should be able to disable that from the vtta extension settings.
