### ISSUE TITLE
beyond digital dice adding total

### ISSUE THREAD

**Issue by nathanenns** [kakaroto/Beyond20#529]
I noticed that when using beyonds digital dice, it is adding a totals box at the bottom after the roll.  And for most situations that is probably a good thing, however there are a few times when you can hit 2 enemies for 2 different damage values in 1 attack.  So would it be possible to either remove that, or add it as a toggle?

**Comment by kakaroto** [comment]
Remove it: no, because for some thing you can have a lot of damages adding up
Toggle: no, because there are way too many toggle already
Solution: Look at the details of the roll in that situation instead and ignore the totals 🤷‍♂️
