### ISSUE TITLE
Roll20: Beyond20 Roll Renderer Broken

### ISSUE THREAD

**Issue by CodedQuotes** [kakaroto/Beyond20#530]
Release: V2.2

Rolls no longer appear in Roll20 when the Roll20 Character Sheet setting uses Beyond20 Roll Render (including if the roll renderer defaults to Beyond20 RR due to a mismatch with the campaign sheet setting). Not entirely sure if there's other confounding factors - one of my players raised this issue with me as they used the B20 RR and their rolls stopped working. I am able to replicate in two ways:

1. Beyond20: Roll20 Character Sheet Setting set to "Beyond20 Roller Renderer"; Roll20 Game Setting: Character Sheet Template set to either "None" or "D&D 5E By Roll20".

2. Beyond20: Roll20 Character Sheet Setting set to "D&D 5E by Roll20"; Roll20 Game Setting: Character Sheet Template set to "None".

**Comment by Aeristoka** [comment]
Fixed by #528 , just waiting on @kakaroto to review and merge

**Comment by kakaroto** [comment]
It should have been fixed by 849eddb99a9ea9a64a788f4000f86c252e588f74
I have no idea why that commit is empty 😠

**Comment by Aeristoka** [comment]
> It should have been fixed by [849eddb](https://github.com/kakaroto/Beyond20/commit/849eddb99a9ea9a64a788f4000f86c252e588f74)
> I have no idea why that commit is empty 😠

Aliens
