### ISSUE TITLE
Deflect missiles displaying as two rolls

### ISSUE THREAD

**Issue by SittingHill** [kakaroto/Beyond20#531]
The snippet for Monk's Deflect Missiles displays as two separate rolls.  In this example: the first is an unmodified d10, the second a d20+6

![image](https://user-images.githubusercontent.com/72323705/95003436-f77ef480-05a4-11eb-8e1a-240420d3288b.png)

The sidebar description accurately displays it as one roll of a d10
![image](https://user-images.githubusercontent.com/72323705/95003426-e1713400-05a4-11eb-8bb1-1fc9e073fc60.png)

I looked into it a little more.  The bug seems to involve snippet codes.  I made a custom feat to test this. The following screenshot is displayed on a character with a constitution modifier of 3.  The text for the test feat's snippet field is as follows:

`Snippet field 1: rolls d12{{modifier:con#signed}} to do something d12 + your constitution`

![image](https://user-images.githubusercontent.com/72323705/95003521-b3d8ba80-05a5-11eb-9831-a8e6662d3a89.png)

From left to right, the three rolls display as follows on Roll 20: 
![image](https://user-images.githubusercontent.com/72323705/95003673-05357980-05a7-11eb-8b66-234b1b438986.png)

**Comment by kakaroto** [comment]
Nice catch, thanks for the detailed report!

**Comment by kakaroto** [comment]
ahh, it's the `{{modifier:con#signed}}` that's an issue, because the text gets modified in such a way that Beyond20 considers the snippet to be 3 separate parts and it replaces the dice in each independently. This might be harder to fix than I thought :(

**Comment by kakaroto** [comment]
Yep, bumping this to 2.3, it's gonna be messy to fix it and I don't want to risk breaking the entire dice parsing because of it. Not in a bugfix release.

**Comment by heizusan** [comment]
I assume that since I've seen the update tab show up, my extension has been updated, but I am still seeing this issue in the Twilight Cleric's ability.

**Comment by Aeristoka** [comment]
> I assume that since I've seen the update tab show up, my extension has been updated, but I am still seeing this issue in the Twilight Cleric's ability.

Screenshot? Example Character Sheet?

**Comment by Aeristoka** [comment]
@kakaroto Confirmed on a Monk.

https://www.dndbeyond.com/profile/Blue_Skog/characters/33385437

Works: Deflect Missiles

Doesn't work: Quickened Healing

**Comment by heizusan** [comment]
> > I assume that since I've seen the update tab show up, my extension has been updated, but I am still seeing this issue in the Twilight Cleric's ability.
> 
> Screenshot? Example Character Sheet?

And it appears that clicking either die reference (features tab or the feature details sidebar) rolls the d6 without adding character level.

![Screenshot (95)](https://user-images.githubusercontent.com/469534/120339892-bdd8c780-c2b2-11eb-85bc-7b6263871137.png)

**Comment by Aeristoka** [comment]
> > > I assume that since I've seen the update tab show up, my extension has been updated, but I am still seeing this issue in the Twilight Cleric's ability.
> > 
> > 
> > Screenshot? Example Character Sheet?
> 
> And it appears that clicking either die reference (features tab or the feature details sidebar) rolls the d6 without adding character level.
> 
> ![Screenshot (95)](https://user-images.githubusercontent.com/469534/120339892-bdd8c780-c2b2-11eb-85bc-7b6263871137.png)

Can you provide the Character Sheet URL as well? The more examples that are readily available, the easier it'll be to track it down.

**Comment by heizusan** [comment]
> > > > I assume that since I've seen the update tab show up, my extension has been updated, but I am still seeing this issue in the Twilight Cleric's ability.
> > > 
> > > 
> > > Screenshot? Example Character Sheet?
> > 
> > 
> > And it appears that clicking either die reference (features tab or the feature details sidebar) rolls the d6 without adding character level.
> > ![Screenshot (95)](https://user-images.githubusercontent.com/469534/120339892-bdd8c780-c2b2-11eb-85bc-7b6263871137.png)
> 
> Can you provide the Character Sheet URL as well? The more examples that are readily available, the easier it'll be to track it down.

https://www.dndbeyond.com/profile/heizusan/characters/33486242

**Comment by matthewbstroud** [comment]
I see this was closed, but it still seems to be an issue?  When you use Twilight Sanctuary from DNDBeyond Sheet.  The roll link in FoundryVTT doesn't contain the level modifier.
![image](https://user-images.githubusercontent.com/17620888/200426873-a1ca9111-3631-4c5b-b37f-78651a949031.png)

**Comment by matthewbstroud** [comment]
So, it will only roll 1d6.

**Comment by Aeristoka** [comment]
> So, it will only roll 1d6.

Correct, because DnDBeyond doesn't ever specify the Cleric Level in what is parsed right there. Beyond20 is just shipping over what DnDBeyond provides in the sidebar.

**Comment by Aeristoka** [comment]
![image](https://user-images.githubusercontent.com/7988297/200427296-1ef2e1ec-09bc-4a4f-b8df-e8f3ebd6f978.png)

It's something DnDBeyond would have to fix and make Dynamic in some way.

**Comment by Aeristoka** [comment]
Where DnDBeyond HAS done their job right, you can roll it:
![image](https://user-images.githubusercontent.com/7988297/200428127-37d17132-dc85-4830-8d45-43c14d66beeb.png)

**Comment by matthewbstroud** [comment]
Okay, I was thinking when the text was parsed that you could look for plus your [class] level and calculate the modifier.   No big deal.

**Comment by Aeristoka** [comment]
> Okay, I was thinking when the text was parsed that you could look for plus your [class] level and calculate the modifier. No big deal.

That's not the purpose of displaying the sidebar text to a VTT. We send exactly what DnDeyond presented.

**Comment by matthewbstroud** [comment]
Since it shows up correctly here, I am wondering if there is an opportunity to put a cast button by the ability on the actions page.
![image](https://user-images.githubusercontent.com/17620888/200441017-9e1600cd-ec92-48b4-bbf7-0eac26340822.png)

**Comment by Aeristoka** [comment]
That's literally what that Beyond20 Icon is for, as demonstrated in my above screenshot.

> Since it shows up correctly here, I am wondering if there is an opportunity to put a cast button by the ability on the actions page. ![image](https://user-images.githubusercontent.com/17620888/200441017-9e1600cd-ec92-48b4-bbf7-0eac26340822.png)
