### ISSUE TITLE
Beyond20-AstralTT Roll Calculation Issues

### ISSUE THREAD

**Issue by dandoesdesign** [kakaroto/Beyond20#538]
@adriangaro 

Long time Beyond20 user, first time poster! Loving the v2.2,

I am finding a few small issues, detailed below.

1) the dice roll calculation(?) in astral seems all whack, (img attached)
2) Clicking on a non-roll oriented spell (shield, for example) does not send anything to Astral.
3) The "Click to roll damage" box in astral doesn't seem to work off the B20 roll - it just opens recurring chat windows. 
4) When making a skill check, it has a line of text in the description box that just says "name         roll" 
5) Rolling damage, on damage oriented spells sends the spell description to astral, but not the damage dice roll.

I think thats all for now, please let me know if there's anything I can do to help - love Beyond 20!

<img width="344" alt="Screen Shot 2020-10-04 at 1 05 11 pm" src="https://user-images.githubusercontent.com/72326964/95005620-e5ee2900-0646-11eb-8596-7cc250720525.png">

**Comment by kakaroto** [comment]
Btw, I've had a few other people reporting in the Astral discord that the 'Display in VTT' button isn't working for them either.

**Comment by dandoesdesign** [comment]
<img width="342" alt="Screen Shot 2020-10-04 at 2 08 28 pm" src="https://user-images.githubusercontent.com/72326964/95006024-1afc7a80-064b-11eb-9371-ebbd2a771236.png">

One quick update, I tried again, and clicking the damage roll weirdly seems to work now - however it doubles up the spell description, which can end up spamming the chat quite a bit. It would be great if the rolled damage could appear inline?

**Comment by adriangaro** [comment]
I guess for the roll formula that is whacky you used the digital dice?

Astral has no way atm of creating a roll with an already calculated output, so I had to do that workaround to show the roll amount and if it is a crit or fumble.

In this case, I know it looks funky. Maybe I should look for another workaround for the rolls which use the digital dice.

On the second, I'll see what I can do to reduce the duplication.

**Comment by Redmega** [comment]
Hi there, I'm one of the devs from Astral :wave:

Would be happy to answer any questions/comments/concerns you may have using our syntax.

> Astral has no way atm of creating a roll with an already calculated output, so I had to do that workaround to show the roll amount and if it is a crit or fumble.

I think something like `!(1d[23])` would work better for you than `1d0 + 23`. If it's a crit add `cr=1`, for fumbles add `fr=1`.

> It could be an interesting thing to investigate how the delayed rolls work in astral since that might allow me to somehow use that mechanism for inlining the rolls.

Delayed rolls have the same syntax as other rolls except you need to add an extra `!`. So `!!(1d20)` will show "Click to roll" and then roll a 1d20 upon clicking.

**Comment by Mgilbride** [comment]
Rolls are definitely not making it to Astral. I noticed that under Beyond20 settings button in D&D Beyond does not list Astral as an option. 

![image](https://user-images.githubusercontent.com/741811/96675089-2bde0900-1338-11eb-8aab-0840ed7d5dbd.png)

It is listed under settings for the Beyond20 extension from within Chrome extensions. 

Discord working fine.
