### ISSUE TITLE
Failure to auto-roll damage and crit even when option is enabled

### ISSUE THREAD

**Issue by SirRaiuKoren** [kakaroto/Beyond20#542]
Title.

Even when the option is enabled in both Roll20 and D&D Beyond, making attacks from the Beyond character sheet does not auto-roll damage and crits.

**Comment by Aeristoka** [comment]
Do not click the +7 icon (or whatever it is for you), that is the DnDBeyond Digital Dice hook, click the crossed swords/spell icon to the left of that. (Disable DnDBeyond Digital Dice to see this more clearly)

**Comment by Aeristoka** [comment]
@kakaroto second person who has gotten messed up by this today.

**Comment by kakaroto** [comment]
Sounds like a FAQ item is brewing...
