### ISSUE TITLE
Suggestion - Make alert on detecting new sheet/level up a toggled option.

### ISSUE THREAD

**Issue by MykeMyke** [kakaroto/Beyond20#543]
Make the alert on detecting a new sheet / level up a toggled option. It's not helpful to every workflow (e.g. AL). Thanks!

**Comment by kakaroto** [comment]
That makes no sense, the alert happens once when you change your character changes its level, you click once on the features tab and that's it, you won't see it again until the next level up. If Beyond20 doesn't know about your character's class features, it can't roll things appropriately (sneak attack, great weapon fighting, halfling luck, etc...).

Having yet another option whose sole purpose is to cripple the functionality makes no sense.
