### ISSUE TITLE
With DnDBeyond Digital Dice Enabled + Homebrew "Perfect Crits" Enabled, Crit Damage shows as 0

### ISSUE THREAD

**Issue by Aeristoka** [kakaroto/Beyond20#544]
With DnDBeyond Digital Dice Enabled + Homebrew "Perfect Crits" Enabled, Crit Damage shows as 0, this shows up on DnDBeyond:

As well as on VTTs:
Roll20
![image](https://user-images.githubusercontent.com/7988297/95094740-75e3af80-06e7-11eb-8516-a12840b288a0.png)

FoundryVTT
![image](https://user-images.githubusercontent.com/7988297/95094899-a75c7b00-06e7-11eb-9067-ac7144fcbd98.png)

**Comment by Varkolaak** [comment]
I managed to replicate this with Digital Dice fully disabled and "Auto Roll Damage and Crits" also disabled.  Turning "Auto Roll Damage and Crits" back on gave correct results

![1](https://user-images.githubusercontent.com/69788528/95095391-e5c35b80-0722-11eb-84b8-52a1b8097347.JPG)
![2](https://user-images.githubusercontent.com/69788528/95095394-e65bf200-0722-11eb-9e7e-0b9637e0f944.JPG)

**Comment by amenokos** [comment]
I'm experiencing the same issue. As soon as I disabled DnDBeyond's Digital Dice, the issue went away, but I really enjoy using my digital dice.

**Comment by kakaroto** [comment]
Ha, glad that I found this issue while reviewing if I missed anything. It helped me find a bug in the new digital dice manager class for 2.3 release!
