### ISSUE TITLE
Alt override doesn't work on Linux+Chrome

### ISSUE THREAD

**Issue by Respheal** [kakaroto/Beyond20#550]
I can only replicate this issue on Linux so I'm not sure how widespread this is, but I'm not able to roll dice when holding Alt to override advantage/disadvantage. Nothing happens (no dice at all) when I hold alt and click the Beyond20 dice roller button. The dice roll fine when I _don't_ hold Alt and click the button. On Windows+Chrome, Alt+click rolls a single dice as expected.

If this is unique to a specific version of Linux+Chrome, I'm running:
OS: Linux Mint 19.3 (Tricia)
Chrome version: Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by kakaroto** [comment]
Alt is used for opening the menu in applications, on chrome, it doesn't affect it, as long as you click while holding, but if you press alt then release it, it will put the focus on the menu, which makes it not work.
I would assume the issue for you has more to do with the desktop environment you use (Gnome, KDE, XFCE, whatever). This shouldn't be a problem once I get the time to implement #120 which would let people set their own hotkeys for various types of triggers.
