### ISSUE TITLE
Custom Text with Always Ask Whisper rolls on

### ISSUE THREAD

**Issue by SauerCarey** [kakaroto/Beyond20#552]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
To help explain your problem, add screenshots of where you clicked in D&D Beyond, a screenshot of your Beyond20 character settings if applicable and the result you saw in the VTT.

**Browser Info (please complete the following information):**
 - Browser [e.g. chrome, firefox]
 - Version [e.g. 85]
 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT

**Additional context**
Add any other context about the problem here, such as a link to the character sheet or D&D Beyond page that shows the problem.

**Comment by Aeristoka** [comment]
Did you forget to fill out all the requested info?

**Comment by SauerCarey** [comment]
duplicate issue
