### ISSUE TITLE
Quick Rolls from Main Page not auto rolling damge

### ISSUE THREAD

**Issue by Chucklaz** [kakaroto/Beyond20#555]
**Describe the bug**
When using the Quick Rolls from main page damage is not auto displayed.  Works properly when rolling from the sub pages.

**To Reproduce**
1. Go to weapon/spell attack on main screen
2. Click on hit/dc field
3. display in Roll20 chat shows pink box instead o damage already displayed

**Expected behavior**
damage shown at time of roll

**Browser Info**
 - Browser: Firefox
 - Version: 81.01(64 bit) for Mac OSX

**Additional context**
works as previous versions/expected from the drill down screen on weapon or spell

**Comment by Aeristoka** [comment]
That is the Digital Dice Hook, and was changed to properly not Auto Roll Damage (as the To-Hit Digital Dice box would not auto roll damage without Beyond20).

Click the crossed swords/spell icon to the left (which will pop up a box with the Beyond20 icon) to roll hits and auto roll damage

**Comment by Chucklaz** [comment]
So it is correct that we now need to take an extra step and open the drill down menu to roll with damage? 

See attached with marked up screen shots

**Comment by Aeristoka** [comment]
No, click on the Crossed Swords to the left to Quick Roll, the change to the Digital Dice click area was a correction of behavior.

**Comment by Chucklaz** [comment]
Sorry - maybe it is me - I am not seeing any cross swords icon - either on the main page, the sub page (as shown below) or on the settings window.  Can you send a screen shot of where that icon should be?

Thanks for the help!

**Comment by Chucklaz** [comment]
Never mind - found it - I am an idiot!

**Comment by kakaroto** [comment]
yeah, quick rolls was always the button on the left of the action/spell, when I added it to the digital dice to-hit and damage buttons, the fact that it rolled both to-hit+damage on those was a bug which was now corrected.
