### ISSUE TITLE
Reliable Talent breaks rolls in FVTT 0.7.3

### ISSUE THREAD

**Issue by FaeyUmbrea** [kakaroto/Beyond20#556]
**Describe the bug**
All characters with the Reliable Talent feature break macro based rolls where the feature applies. It causes an error message to be printed to the browser regarding the roll object within foundry not existing.

**To Reproduce**
1. Go to a Foundry instance running 0.7.3 of FVTT
2. Open a DnDB character with the Reliable Talent feature
3. Make sure digital dice use is off and attempt rolling on a proficient skill

**Expected behavior**
The expected behavior is a roll being sent to the vtt and being executed by the vtt's roller

**Screenshots**
![unknown (1)](https://user-images.githubusercontent.com/1144986/95681510-8234a480-0be0-11eb-9e26-7cfbc452cb71.png)
The screenshot shows the roll request sent to the VTT

**Browser Info (please complete the following information):**
 - Browser: Edge Chromium
 - Version 86
 - Error: "Can not read field "formula" of undefined"

**Additional context**
This is exclusive to FVTT 0.7.x, it works perfectly fine on 0.6.6

**Comment by Aeristoka** [comment]
@kakaroto It appears to be with the creation of Native FoundryVTT rolls, my guess is in this code block

`createRoll(dice, data) {
	const new_data = {}
	const parts = [dice];
	for (let key in data) {
		if (data[key]) {
			const new_key = key.replace("_", "").toLowerCase();
			new_data[new_key] = data[key];
			parts.push(new_key);
		}
	}`

The formula ends up with `@cha` in it, rather than the charisma modifier itself.
![image](https://user-images.githubusercontent.com/7988297/95681985-1f231d80-0ba0-11eb-8661-cccfbe9dc40d.png)

![image](https://user-images.githubusercontent.com/7988297/95681994-32ce8400-0ba0-11eb-8267-19d01483163c.png)

**Comment by kakaroto** [comment]
Yeah, the bug is from Foundry itself, not Beyond20, it's already been reported and fixed, so it should work once 0.7.4 is out.
See https://gitlab.com/foundrynet/foundryvtt/-/issues/3612 and https://gitlab.com/foundrynet/foundryvtt/-/issues/3751

**Comment by Aeristoka** [comment]
> Yeah, the bug is from Foundry itself, not Beyond20, it's already been reported and fixed, so it should work once 0.7.4 is out.
> See https://gitlab.com/foundrynet/foundryvtt/-/issues/3612 and https://gitlab.com/foundrynet/foundryvtt/-/issues/3751

Ah, good to know!

**Comment by FaeyUmbrea** [comment]
Sadly 0.7.4 did  not fix this issue. 
I have just tested it and it's the exact same error with the exact same reason for occuring.

**Comment by Aeristoka** [comment]
Yep, verified here, and bug submitted here: https://gitlab.com/foundrynet/foundryvtt/-/issues/3822
