### ISSUE TITLE
Option to change "hide monster" text from ???

### ISSUE THREAD

**Issue by kennethburgener** [kakaroto/Beyond20#558]
When using the "hide monster and attack name" option, I think the "???" looks noisy.  I prefer the text to just be blank, but maybe someone else might like it to say "(hidden)" instead.

I would also like to see an option to just "Hide monster name" only.  I certainly prefer to have the Monster's name hidden, but I am indifferent on the attack name being hidden.

For my purposes, I was able to just hack a version of the code that replaced the "???" with a bank:
```
diff --git a/dist/roll20.js b/dist/roll20.js
index 2deaba7..c65c8cd 100644
--- a/dist/roll20.js
+++ b/dist/roll20.js
@@ -2855,14 +2855,14 @@ function template(request, name, properties) {

     if (request.whisper == WhisperType.HIDE_NAMES) {
         if (properties["charname"])
-            properties["charname"] = "???"
+            properties["charname"] = ""
         // Take into account links for disabled auto-roll-damages option
         if (properties["rname"])
             properties["rname"] = properties["rname"].includes("](!") ?
-                properties["rname"].replace(/\[[^\]]*\]\(\!/, "[???](!") : "???";
+                properties["rname"].replace(/\[[^\]]*\]\(\!/, "[???](!") : "";
         if (properties["rnamec"])
             properties["rnamec"] = properties["rnamec"].includes("](!") ?
-                properties["rnamec"].replace(/\[[^\]]*\]\(\!/, "[???](!") : "???";
+                properties["rnamec"].replace(/\[[^\]]*\]\(\!/, "[???](!") : "";
         delete properties["description"];
     }
     for (let key in properties)
```

**Comment by kakaroto** [comment]
That's again another option that I think is just too much. I actually want to cut down and remove some of the customization options because it has become unbearable and unusable with the amount of options that Beyond20 has. I think this is just a style preference and it wouldn't actually affect a game, so I don't think that'll be implemented.
