### ISSUE TITLE
Add option for "Hide monster name" only

### ISSUE THREAD

**Issue by kennethburgener** [kakaroto/Beyond20#559]
In addition to the "Hide monster and attack name" option, I would like to see a "Hide monster name" only.  I certainly prefer to have the Monster's name hidden, but I am indifferent on the attack name being hidden.

**Comment by DMOORENomad** [comment]
Yes please! Also, having a way to use "names" of monsters would be awesome, but that may have to be on the DNDBeyond side too, i.e. "Gary" instead of "Guard"

**Comment by kakaroto** [comment]
I don't think I'll add the option. there's already too many options as is, and I think if you want to hide the name, there's no reason to also show the attack name as that could also be spoilery, and if there's a need, you can just say as the DM "it uses its claws" without it having to show it in the roll data.
