### ISSUE TITLE
Enabling "Use Digital Dice" on D&D beyond ALWAYS crashes the page when attempting a roll.

### ISSUE THREAD

**Issue by tigerhawkvok** [kakaroto/Beyond20#560]
**To Reproduce**
1. Enable digital dice 
![image](https://user-images.githubusercontent.com/165937/95802818-59c9aa80-0cb3-11eb-8f1d-ba62a40b7abf.png)

2. Attempt a roll 
![image](https://user-images.githubusercontent.com/165937/95802843-66e69980-0cb3-11eb-95a7-4b153f587c53.png)

**Expected behavior**

Digital dice roll and result is sent to Roll20 (or whatever)

**Screenshots**

![image](https://user-images.githubusercontent.com/165937/95802887-8087e100-0cb3-11eb-8c37-314a952e04ff.png)

**Browser Info (please complete the following information):**
 - Browser: Chrome
 - Version 85
 - Console:

![image](https://user-images.githubusercontent.com/165937/95802928-a01f0980-0cb3-11eb-8fe4-308cad38371e.png)

**Additional context**

Character sheet: https://ddb.ac/characters/23968003/dWLUKz

**Comment by tigerhawkvok** [comment]
It replicates today. The dice roll fine when I disable the beyond20 extension, and the page doesn't crash (tested with five consecutive rolls). If I enable the extension, I sometimes get the first roll to work OK after a reload (though it behaves like beyond20 isn't intercepting it at all), then others crash the page with the toggle turned on. If I turn off the "use digital dice" toggle, Beyond20 works fine (though of course the digital dice don't).

**Comment by kakaroto** [comment]
Can you click manually on the custom dice (in the lower left corner) from D&D Beyond to do a custom roll ? That's what beyond20 does when digital dice are enabled. The only DOM manipulation that Beyond20 does is simulate a click by calling `$(custom_dice_button).click()` basically.

**Comment by tigerhawkvok** [comment]
Thanks -- that was very helpful @kakaroto  . Turns out the extension "Autoconvert", even though I whitelisted D&DBeyond, was interfering here.
