### ISSUE TITLE
No damage rolls when attacking

### ISSUE THREAD

**Issue by Ravenspath** [kakaroto/Beyond20#561]
Hi,
Something changed in regards to when you attack and getting damage rolls. 
This is what I saw before:
![roll20 orig](https://user-images.githubusercontent.com/72817985/95894680-0dcc4380-0d4f-11eb-9fb7-b4cc35c63150.png)

And now I see this without the damage
![rol20 no dmg](https://user-images.githubusercontent.com/72817985/95894754-26d4f480-0d4f-11eb-9163-0d6b2b40ead4.png)

I read that there was a bug similar to this which was fixed in 2.2.1 but it doesn't seem resolved for me. It may be a setting that has changed that I'm not aware of, but I can't seem to get it back no matter what I do.

**Comment by Aeristoka** [comment]
https://beyond20.here-for-more.info/faq#is-auto-roll-damages-broken

Please close.
