### ISSUE TITLE
roll 20 shows item block instead of rolling attack for items displayed as attack

### ISSUE THREAD

**Issue by frederik-b** [kakaroto/Beyond20#563]
steps to reproduce:
- add staff (Staff - Arcane focus, common) to inventory
- open item sidebar
- open customize
- check Display As Attack
- switch to Actions
- click to roll for attack or attack&damage

result:
item card for Staff is displayed

expected result:
weapon attack is rolled and displayed

**Comment by kakaroto** [comment]
https://beyond20.here-for-more.info/faq#why-doesnt-beyond20-allow-me-to-make-a-melee-attack-with-my-magic-staffs
