### ISSUE TITLE
Roll20 'speak as' seems broken in 2.2.1

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#565]
the rolls aren't being sent with speak as character anymore in roll20. Might be a new bug, or they changed the way the combobox needs to be parsed.

**Comment by shadowclaw** [comment]
I was testing this and it appears that the dndbeyond character sheet can have leading or trailing spaces in the name which are not present in the values of the combobox on roll20.  I was able to fix this (for me at least) by changing "character = character.toLowerCase()" to "character = character.toLowerCase().trim()" on line 20 in content-script.js.
