### ISSUE TITLE
Rolling doesn't work when using the mobile views

### ISSUE THREAD

**Issue by Kasuko** [kakaroto/Beyond20#57]
I know mobile isn't supported, but it happens to work. Just found a minor issue with the defaults in the Character class.

When using a mobile browser the browser doesn't load the Actions and this causes an exception when trying to roll information for the Character before opening the Actions page.

I have already debugged this and can say that the below fix allows us to use Beyond20 on mobile browsers.

I would open a PR for this, but I develop on a MacBook and my Rapydscript transpiler seems to be adding some additional weird things around a decimal separator that I don't trust.

```diff
diff --git a/src/dndbeyond.pyj b/src/dndbeyond.pyj
index 7a0f490..23cf5dc 100644
--- a/src/dndbeyond.pyj
+++ b/src/dndbeyond.pyj
@@ -138,6 +138,7 @@ class Character(CharacterBase):
         self._class_features = []
         self._racial_traits = []
         self._feats = []
+        self._actions = []

     def updateInfo(self):
         self._id = $("#character-sheet-target").attr("data-character-id")
```

**Comment by kakaroto** [comment]
Ah, thanks! my bad. In the meantime making sure you open the actions view would get it to populate the actions array and keep it cached so it doesn't happen anymore. 
Also thanks for testing on mobile! Very happy to know that it is a possibility :)
