### ISSUE TITLE
Hunter's Mark rolling separately for each possible damage type. 

### ISSUE THREAD

**Issue by auranykh** [kakaroto/Beyond20#571]
**Describe the bug**
Hunter's Mark rolls 3d6 when Beyond20 is enabled and 1d6 when it is disabled on Firefox. From what I can tell it's rolling multiple times because the spell codifies 1d6 three different times for each physical damage type (bludgeoning, piercing, and slashing). 

**To Reproduce**
1. Have a character with the hunter's mark spell at level 1. 
2. Have Beyond20 open. 
3. Cast Hunter's Mark or roll the damage in D&D Beyond. 

**Expected behavior**
This should roll 1d6 instead of 3d6. Damage could reflect the damage of the last weapon rolled, but that's just an idea and might be hard to implement. It could also be fixed with a multi damage type being added as "bludgeoning, piercing, or slashing", then let the user determine which it is. 

**Screenshots**
To help explain your problem, add screenshots of where you clicked in D&D Beyond, a screenshot of your Beyond20 character settings if applicable and the result you saw in the VTT.

Beyond20 is disabled:
![Beyond 20 is off](https://user-images.githubusercontent.com/10267293/97119595-b3849880-16e7-11eb-86a2-4aae8c3a90f7.png)

Beyond20 is enabled (VTT is currently not opened)
![Beyond20 is on (VTT is currently not pulled up)](https://user-images.githubusercontent.com/10267293/97119610-d57e1b00-16e7-11eb-8b55-7e60c3b5d3fb.png)

**Browser Info (please complete the following information):**
 - Firefox 82.0 (64-bit)
 - There don't appear to be any errors related to this in the console.

**Comment by Aeristoka** [comment]
Asked and answered previously: https://github.com/kakaroto/Beyond20/issues/356#issuecomment-639122609

Though I'll leave room for @kakaroto if he has changed his opinion.

**Comment by auranykh** [comment]
Ah, no worries. I read through the comment and it makes sense that handling each case individually wouldn't be optimal, especially with the game growing. Feel free to close the issue if it's not worth fixing.

**Comment by kakaroto** [comment]
Yeah, it's not the greatest user experience to have that but I'm dreading having a long list of special cases, I'm already hating all the special features that Beyond20 has to handle.  For now, I'll keep this issue open, I'll revisit it later, but I haven't *yet* changed my mind.

**Comment by Aeristoka** [comment]
Handled in #742
