### ISSUE TITLE
Damage roll not rerolling 1s and 2s as per Great Weapon Fighting

### ISSUE THREAD

**Issue by drewski1967** [kakaroto/Beyond20#574]
When rolling damage for an attack by a character with Great Weapon Fighting, it appears that 1s and 2s are not being rerolled.

**Comment by Aeristoka** [comment]
Character sheet for testing and screenshots please.bi have personally tested this extensively, so I'm interested in what's happening here.

**Comment by drewski1967** [comment]
Hi there,

The problem occurred with a Homebrew magic weapon I had made from scratch.  I’ve since created another on using a template, and it’s works properly.  So, I think the problem was I missed something in the weapon creation.  In short, it’s me, not your program. 😊 Sorry to bother you.

Thanks, Andy

**Comment by Aeristoka** [comment]
Here are the qualifiers for it from the code:

Have the "Great Weapon Fighting" class features
Attack is Melee
Melee Weapon is Versatile or Two-Handed

Get all that figured, and you should be good, even on a homebrew

**Comment by drewski1967** [comment]
Thanks for the quick response.

Andy
