### ISSUE TITLE
Crit + improved divine smite calculation wonky when 'Versatile weapon choice' is set to 'roll both damages seperately.'

### ISSUE THREAD

**Issue by Mangoray** [kakaroto/Beyond20#575]
**Describe the bug**
In Roll20, damage dice for Two-handed attack + Improved Divine smite is mixed up when Critting and the option  'Versatile weapon choice' is set to 'roll both damages seperately.'

**To Reproduce**
1. Have a lvl 11 Paladin
2. Enable Force Critical hits in Beyond20
2. Set 'Versatile weapon choice' to 'roll both damages seperately.' in Beyond20
3. Attack with a Versatile weapon (longsword, 1d10 when two-handed)
4.  Damage for Two-Handed attack is written like: 13 | 2 + 1 | 7 with the dice being as follows:
13 (1d10+4) | 2 (1d8) + 3 (1d10) | 8 (1d8)
The 1d8 is the improved divine smite
The 1d10 is the longsword 2-hand attack

**Expected behavior**
Damage for Two Handed attack is written like: 13 (1d10+4) + 1 (1d10) | 2 (1d8) + 8 (1d8)

**Screenshots**
![rolls1](https://user-images.githubusercontent.com/33783311/97644028-7c94e680-1a49-11eb-849b-fa41ab6c0743.gif)

**Browser Info (please complete the following information):**
 - Browser chrome 
 - Version 86.0.4240.111 (Official Build) (64-bit)
 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT

**Additional context**
A workaround is to set the 'Versatile weapon choice' to Two-handed before attacking.
![roll2](https://user-images.githubusercontent.com/33783311/97644277-2e341780-1a4a-11eb-9f12-8baab069d540.gif)

**Comment by kakaroto** [comment]
That's normal behavior, Beyond20 doesn't add the "+", that's all from roll20's side, anything before the "+" is normal damage, anything after the "+" is crit damage, and we have no control avoid it.
To specifically avoid this sort of confusion with Roll20's idiotic behavior, by default, Beyond20 adds a "Crit: " prefix so it should have been "13 | 2 + Crit: 1 | 7".
I assume you manually removed the critical prefix yourself from the beyond20 settings.

It's basically in your screenshot : 
13 Slashing (two handed) | 2 (Radiant) + 1 Critical Slashing (two handed) | 7 Critical Radiant
