### ISSUE TITLE
SHIFT, CTRL hotkeys don't roll multiple dice.

### ISSUE THREAD

**Issue by TheKrush** [kakaroto/Beyond20#577]
**Describe the bug**
SHIFT should be advantage, and CTRl should be disadvantage but I'm not seeing any additional dice being rolled. Also if you have it ask everytime you roll for that it defaults to whatever you previously selected instead of using the hotkey to select the advantage/disadvantage.

**To Reproduce**
1. Hold SHIFT while rolling a d20 check.
4. See only a single dice rolled.

**Expected behavior**
Multiple dice roll when using the hotkeys.

**Screenshots**

**Browser Info (please complete the following information):**
 - Chrome Version 86.0.4240.111 (Official Build) (64-bit)

**Additional context**

**Comment by Aeristoka** [comment]
@TheKrush Can you provide a screenshot of where you're clicking? They do work perfectly fine for Shift/CTRL/ALT + Roll for Advantage/Disadvantage/Normal (overriding an auto-advantage).

My guess is you're not having the DnDBeyond window focused when using the hotkeys, which makes it so Beyond20 doesn't pick up the hotkeys.

**Comment by TheKrush** [comment]
![image](https://user-images.githubusercontent.com/671500/97790843-760d8880-1b89-11eb-8af5-689aecfc5703.png)
For me it colors the stuff right based on the hotkey but when it rolls dice on dndbeyond it only rolls one, and with it off it also only sends one roll to roll20.

**Comment by Aeristoka** [comment]
You have it set to "always ask" you about how to roll, so of course the hotkeys won't work then, you've purposely overriden the default behavior.

**Comment by TheKrush** [comment]
Changing it to normal
![image](https://user-images.githubusercontent.com/671500/97791308-5036b280-1b8e-11eb-94a2-748d7e80969f.png)
Has the same results.

**Comment by Aeristoka** [comment]
You're not holding Shift+Clicking then, or you still don't have the Beyond20 window focused. It works perfectly.

**Comment by TheKrush** [comment]
It changes the button color just fine, and I recall it previously working.

**Comment by kakaroto** [comment]
Hey, thanks for the report. I can confirm that If the roll type is set to "Ask every time", it does ignore the Shift/Ctrl/Alt hotkey. I can't reproduce the issue with any of the other roll type options.

And I agree that this is a bug, as the hotkeys should override whatever setting you have. I'll get this fixed for the next release.
Thanks!
