### ISSUE TITLE
Cutting Words Functionality

### ISSUE THREAD

**Issue by KevinDW007** [kakaroto/Beyond20#582]
**Is your feature request related to a problem? Please describe.**
I have a bard in my party who has the skill [Cutting Words](https://roll20.net/compendium/dnd5e/College%20of%20Lore#h-Cutting%20Words)
The idea is that he can know the outcome of a monster roll, and choose to use bardic inspiration to roll a die and subtract it.
It is however tricky to implement (both with or without a VTT) without having to make public rolls for all to see or having to think about anouncing it every time.

**Describe the solution you'd like**
It would be nice if there was an option in Beyond20 to set a Cutting Words target. This target would then automatically get whispered all monster rolls (without modifiers)
I'm using Roll20 so for that i would assume a simple text field where you type the name of the user who needs to get whispered should suffice.

**Describe alternatives you've considered**
I have tried:
- Announcing my rolls verbaly: Downside = everyone can hear it + prone to forgetting + i have to search for the core die roll without the modifier
- Making all rollls public: Downside = everyone can see it + also shows modifiers / attack information
- Combining Roll20 output and discord output (put the bard in a discord channel where the rolls get whispered): I didn't seem to be able to make both work at the same time, but it would still give the problem of showing the modifiers. Also, i think i wouldnt have the granularity in setting it up correctly as the "always whisper / never whisper / ..." settings are global.

**Additional context**
None

**Comment by KevinDW007** [comment]
After messing around in the code myself for a bit, i would like to add the following notes/complexities:

Since rolls are made in Roll20, it is not possible to re-use the roll outcome from the extension. This means that we can't whisper once to the gm, and a second time to the user.

My suggestion for whispering to the bard would be to implement a gm override. In the settings we can include a text field as suggested above, and it would override the "/w gm" to "/w override-setting". I implemented this [here ](https://github.com/kakaroto/Beyond20/blob/master/src/roll20/content-script.js#L656) in a very basic manner as such:
```
if (settings["gm-override-name"]) {  
  roll = request.replace("/w gm", "/w " + settings["gm-override-name"]);  
}  
postChatMessage(roll, character_name);
```

This allows to post rolls visible to the bard, while still seeing them as a gm. However, there are 2 problems with this approach:
1. The modifiers are visible to the Bard as well. I don't really have a way around this, apart from maybe an integration with [HiddenRolls](https://wiki.roll20.net/Script:HiddenRolls) I'm not sure if this would work, since I haven't tested it, but it seems like a viable option.
2. Because I am overriding all gm whispers, there is no control over which rolls are visible to the bard. So there would still be a need to override this somehow. Maybe an ask everytime option or an override key?

**Comment by kakaroto** [comment]
Hi,

Thanks for the detailed report. Unfortunately this is a highly specific thing that I'm not sure is something I'd like to see added in Beyond20.
Also, `Cutting Words` (as well as other similar features) actually say : 
> You can choose to use this feature after the creature makes its roll, **but before the GM determines** whether the Attack roll or ability check succeeds or fails, or before the creature deals its damage`
which technically means that no, the Bard does not know of any monster rolls, they need to make the decision to substract **without knowing** the roll. If they know the roll, it's too easy, they use it when it can help them, whereas the purpose is to use it when they need, and they may or may not be wasting it.. that's part of the game (i.e: "I **really** need this attack to not hit, so I'll using Cutting Words and I hope it helps", vs "oh, it's below AC, so I won't waste my ability on it").

**Comment by KevinDW007** [comment]
Hi,

Thanks for considering. I understand the specificity is why you would want to avoid adding this.

As an informational side note to the cutting words skill: 
Appearantly there is some discussion on this due to the vagueness of the description. Since it states that the bard can choose to do it after the roll, it implies that there is a reason for this. Most discussion come to the consensus that the bard can know the roll without the modifiers. This is also backed by a Jeremy Crawford statement on twitter. 
[Link](https://rpg.stackexchange.com/questions/91834/how-much-does-a-bard-know-when-they-decide-to-use-cutting-words) to the discussion on stackexchange.

**Comment by kakaroto** [comment]
Thanks for that link. I see the difference now, that's because it assumed rolling in person with physical dice, so you see the dice result, but not the actual roll result. That'd be pretty though to achieve in the context of VTTs.

I would just do "if the bard wants to know, let them ask, and I can type `/w bard 13` manually if needed".

> Combining Roll20 output and discord output (put the bard in a discord channel where the rolls get whispered): I didn't seem to be able to make both work at the same time, but it would still give the problem of showing the modifiers. Also, i think i wouldnt have the granularity in setting it up correctly as the "always whisper / never whisper / ..." settings are global.

Somehow I missed responding to this earlier. Discord wouldn't work when using Roll20 if you make the rolls in Roll20 (as opposite to using the "Beyond20 roll renderer" or making the rolls using D&D Beyond's digital dice). So you can enable digital dice, for monsters, it means rolling them from the encounters page only, or you can enable the Beyond20 roll renderer in the beyond20 options from the roll20 page. Though that would affect how they are displayed.
Monsters have a "hide monster and ability name" type of whisper which could help with that too, as they would see the total, but not the modifiers. That would make the rolls public though unfortunately... unless you set it to send to Discord only with a whisper channel just for the bard.

I hope that helps.
