### ISSUE TITLE
Improperly Formatted Rolls in Roll20

### ISSUE THREAD

**Issue by authyrtyr** [kakaroto/Beyond20#584]
I'm noticing that on most of my campaigns that I'm in the Beyond20 rolls are formatted in a purple table but in one of them they are formatted in a nice box which I think is how it's supposed to go.
![image](https://user-images.githubusercontent.com/8037494/99265580-d9d1bb80-27ef-11eb-93c7-cca43af547df.png)
![image](https://user-images.githubusercontent.com/8037494/99265633-e7874100-27ef-11eb-9666-b653cfcaca7b.png)

I'm only seeing the box formatting (the 2nd image) in one of the four campaigns I'm in. I don't know if this is a known bug but I couldn't find any other mention of it. Given the inconsistency between campaigns I'm not sure what the steps to reproduce are but the one where it's working is the most recently created campaign. Under normal circumstances though, to reproduce it you only need to roll anything through Beyond20.

Browser Info:
 - Browser: Chrome
 - Version: 86.0.4240.193

I don't see any particularly insightful console errors but I'll paste screenshots of the debug objects from Beyond20 sending the roll data back and forth.
First on the side of Roll20
![image](https://user-images.githubusercontent.com/8037494/99267563-18687580-27f2-11eb-9ed6-f5a3fa7a5292.png)
Second on the side of DnDBeyond
![image](https://user-images.githubusercontent.com/8037494/99267629-2f0ecc80-27f2-11eb-83fa-eb6788ac4025.png)

**Comment by Aeristoka** [comment]
Tell your DM in that one campaign to set the Roll20 Campaign settings (NOT Beyond20 settings) to this:
![image](https://user-images.githubusercontent.com/7988297/99267822-ad16a780-27e1-11eb-8f35-94912c4ed99c.png)

This is not a Beyond20 bug, you're seeing Beyond20RollRenderer displayed rolls, since your DM changed that "Character Sheet Template" on Roll20.

**Comment by authyrtyr** [comment]
Thanks. I didn't see it but I was looking  for a FAQ with stuff like this because I suspected this sort of thing might be the case.

**Comment by Aeristoka** [comment]
Please close the issue if you have it figured.

**Comment by authyrtyr** [comment]
I want to get my DM to update it and confirm it was the source of the issue before I close it if that's alright.

**Comment by kakaroto** [comment]
There is a FAQ entry about it, but it's actually quite outdated since the behavior is now different. But this is what was discussing this specific issue : https://beyond20.here-for-more.info/faq#all-i-see-in-roll20-is-an-empty-message
