### ISSUE TITLE
Tashas Caldron of everything (TCOS) Monk quickened healing error

### ISSUE THREAD

**Issue by Elddric** [kakaroto/Beyond20#585]
**Describe the bug**
the new optional feature for monks shows the following

Quickened Healing
As an action, you can spend 2 ki points to regain **scalevalue - No level scale data available**+4 hit points.

**To Reproduce**
Must have access to TCOS book in DNDBeyond.

1. make sure optional features is on for the characters.
2. create monk and level up to 4th level and select Quickened heal and switch to character mode.
3. look at the quickened heal stat in DNDBeyond. it shows the error.
4. If you click on the beyond20 icon to roll to the VTT  it rolls a 1D20 + bonus. This is wrong. instead of a 1d20 it should be The martial arts die that you use for unarmed strike that increases with monk level.

Here is the text of the feature Quickened Healing
4th-level monk feature As an action, you can spend 2 ki points and roll a Martial Arts die. You regain a number of hit points equal to the number rolled plus your proficiency bonus.

**Comment by Aeristoka** [comment]
@Elddric That is a DnDBeyond issue, not a Beyond20 issue. Please do report it to them, as they'll have to fix it.
