### ISSUE TITLE
Alchemist Artificer: Alchemical Savant should not apply to `Aid`

### ISSUE THREAD

**Issue by wapiflapi** [kakaroto/Beyond20#591]
Thanks for the awesome plugin! It makes playing with d&d beyond so much easier :-)

**Describe the bug**

When Casting the `Aid` spell as an Alchemist Artificer the Alchemical Savant feature is applied / displayed while according to the rules it shouldn't apply because there is no _roll_ involved.

**Expected behavior**

The Alchemical Savant feature should not apply when there is no roll involved. When there are no dice in the roll20 "roll" it shouldn't apply.

> **Alchemical Savant**
> *5th-level Alchemist feature*
> 
> You've developed masterful command of magical chemicals, enhancing the healing and damage you create through them. Whenever you cast a spell using your alchemist’s supplies as the spellcasting focus, you gain a bonus **to one roll** of the spell. That roll must restore hit points or be a damage roll that deals acid, fire, necrotic, or poison damage, and the bonus equals your Intelligence modifier (minimum of +1).

> **Aid**
> Your spell bolsters your allies with toughness and resolve. Choose up to three creatures within range. Each target's hit point maximum and current hit points increase by 5 for the duration.

**Screenshots**

![image](https://user-images.githubusercontent.com/1619783/100543688-d871ab80-3251-11eb-9a5a-0d847b6747a9.png)

**Comment by Aeristoka** [comment]
@wapiflapi PR in to fix this.
