### ISSUE TITLE
Graphic Bug

### ISSUE THREAD

**Issue by charrsasaurus** [kakaroto/Beyond20#592]
Rolls are now showing up in roll 20 as boxes with purple text almost like excel.

**Comment by Aeristoka** [comment]
This is due to a Roll20-side change. It will indeed have to be fixed in Beyond20, but they "pulled the rug out from under us" on it.

For now, as a workaround, you can past this in the Roll20 Dev Console:

`document.body.append($(`<input type="hidden" value="1" name="isOGL" id="isOGL">`)[0]);`

**Comment by Seguaro** [comment]
> This is due to a Roll20-side change. It will indeed have to be fixed in Beyond20, but they "pulled the rug out from under us" on it.
> 
> For now, as a workaround, you can past this in the Roll20 Dev Console:
> 
> `document.body.append($(``)[0]);`
> 
> Should get you working for the moment.

Fix doesn't seem to work with Firefox. Is there a similar fix for Firefox?

**Comment by Aeristoka** [comment]
That I'll have to ask @kakaroto about, he provided the first fix as well.

**Comment by wizzard-lizzard** [comment]
> > This is due to a Roll20-side change. It will indeed have to be fixed in Beyond20, but they "pulled the rug out from under us" on it.
> > For now, as a workaround, you can past this in the Roll20 Dev Console:
> > `` document.body.append($(``)[0]); ``
> > Should get you working for the moment.
> 
> Fix doesn't seem to work with Firefox. Is there a similar fix for Firefox?

I was using firefox tonight, and it was working fine.

**Comment by Seguaro** [comment]
> > > This is due to a Roll20-side change. It will indeed have to be fixed in Beyond20, but they "pulled the rug out from under us" on it.
> > > For now, as a workaround, you can past this in the Roll20 Dev Console:
> > > ` document.body.append($(`)[0]); ``
> > > Should get you working for the moment.
> > 
> > 
> > Fix doesn't seem to work with Firefox. Is there a similar fix for Firefox?
> 
> I was using firefox tonight, and it was working fine.

When I try to put in the fix in the Firefox console, I get an undefined error.

`document.body.append($(``)[0])
undefined`

**Comment by amenokos** [comment]
> > > > This is due to a Roll20-side change. It will indeed have to be fixed in Beyond20, but they "pulled the rug out from under us" on it.
> > > > For now, as a workaround, you can past this in the Roll20 Dev Console:
> > > > ` document.body.append($(`)[0]); ``
> > > > Should get you working for the moment.
> > > 
> > > 
> > > Fix doesn't seem to work with Firefox. Is there a similar fix for Firefox?
> > 
> > 
> > I was using firefox tonight, and it was working fine.
> 
> When I try to put in the fix in the Firefox console, I get an undefined error.
> 
> `` document.body.append($(``)[0]) undefined ``

I receive the same error in Chrome's dev console.

**Comment by DarrynGlass** [comment]
According to KaKaRoTo it is supposed to be this:
document.body.append($(`<input type="hidden" value="1" name="isOGL" id="isOGL">`)[0]);

**Comment by DarrynGlass** [comment]
> > > > > This is due to a Roll20-side change. It will indeed have to be fixed in Beyond20, but they "pulled the rug out from under us" on it.
> > > > > For now, as a workaround, you can past this in the Roll20 Dev Console:
> > > > > ` document.body.append($(`)[0]); ``
> > > > > Should get you working for the moment.
> > > > 
> > > > 
> > > > Fix doesn't seem to work with Firefox. Is there a similar fix for Firefox?
> > > 
> > > 
> > > I was using firefox tonight, and it was working fine.
> > 
> > 
> > When I try to put in the fix in the Firefox console, I get an undefined error.
> > ` document.body.append($(`)[0]) undefined ``
> 
> I receive the same error in Chrome's dev console.

Yes it will give you the undefined error, but it still fixes the issue.  You also need to do this every time you reload the game, and every player will have to do this also (not just the DM)

**Comment by DarrynGlass** [comment]
![image](https://user-images.githubusercontent.com/29684482/100714502-744b0680-337b-11eb-992c-fc04393c9be7.png)

From Discord

**Comment by amenokos** [comment]
When I type the following:
document.body.append($(<input type="hidden" value="1" name="isOGL" id="isOGL">)[0]);

I receive the following:
Uncaught SyntaxError: Unexpected token '<'
![Screenshot 2020-12-01 at 12 07 04](https://user-images.githubusercontent.com/69495414/100772709-f401c100-33cd-11eb-8aa6-5d46a2e761e9.png)

Additionally, my rolls continue to show the table with the purple box even after I've entered this into the console.
When you say that every player has to do this, do you mean that everyone has to do it for **just my rolls** to display correctly?

**Comment by jbreckel** [comment]
the formatting is a bit off:
paste it like this:

`document.body.append($('<input type="hidden" value="1" name="isOGL" id="isOGL">')[0]);`

**Comment by Aeristoka** [comment]
I apologize, it looks like the GitHub code tags stripped nearly everything from my first reply with the fix...

**Comment by DarrynGlass** [comment]
> When you say that every player has to do this, do you mean that everyone has to do it for **just my rolls** to display correctly?

Every player will have to do this in their browser of choice so see **their** rolls with the correct template.

**Comment by amenokos** [comment]
> the formatting is a bit off:
> paste it like this:
> 
> `document.body.append($('<input type="hidden" value="1" name="isOGL" id="isOGL">')[0]);`
> 
> the purple box comes from your client side.
> if you add this bit, the roles will look normal for everybody.

Thank you, jbreckel. It worked perfectly when formatted thusly.

**Comment by amenokos** [comment]
> > When you say that every player has to do this, do you mean that everyone has to do it for **just my rolls** to display correctly?
> 
> Every player will have to do this in their browser of choice so **their** rolls will use correct template. For any player that does not do this their rolls will use the purple default template.

That's what I assumed. Thanks for clarifying.

**Comment by kakaroto** [comment]
This is now fixed with this commit https://github.com/kakaroto/Beyond20/commit/fe156a77af905233871dac50aa95e42be22673aa
Using the development version will fix the issue if anyone is impatient and can't wait for v2.3 to be released.

https://github.com/kakaroto/Beyond20#developer-mode-installation

**Comment by tjstinso** [comment]
> According to KaKaRoTo it is supposed to be this:
For posterity, this needs to be formatted ;) 
```document.body.append($('<input type="hidden" value="1" name="isOGL" id="isOGL">')[0]);```
