### ISSUE TITLE
Rolls not displaying properly in Roll20

### ISSUE THREAD

**Issue by HamburgerPun** [kakaroto/Beyond20#593]
With the character sheet set to D&D 5e, any rolls in Roll20 are using what I assume is the Beyond20 renderer.  This is happening on all games on Roll20.  

I have changed the character sheet setting from 5e to Beyond20 and back.  Have also logged out and back into Roll20 and D&D Beyond.  

I am unaware of any updates to Roll20, but everything was fine three days ago.

**Screenshots**
![Beyond20 roll renderer](https://user-images.githubusercontent.com/70948592/100941094-e7549a00-34ad-11eb-878d-bb7eb5649657.PNG)
![Beyond20 settings](https://user-images.githubusercontent.com/70948592/100941162-081cef80-34ae-11eb-8879-1d3dfb023110.PNG)

**Browser Info (please complete the following information):**
 - Chrome
 - Version 87.0.4280.66

**Comment by DarrynGlass** [comment]
This was due to a change in Roll 20 that broke things.  See https://github.com/kakaroto/Beyond20/issues/592#issuecomment-737506439

**Comment by Aeristoka** [comment]
@HamburgerPun Use the Dev version, which already has a fix (if you don't want to wait for a new release).

@kakaroto please close.

**Comment by HamburgerPun** [comment]
> @HamburgerPun Use the Dev version, which already has a fix (if you don't want to wait for a new release).
> 
> @kakaroto please close.

Thank you!
