### ISSUE TITLE
Beyond20 Rolls sent to Roll20 in default template instead of D&D 5e By Roll20 template

### ISSUE THREAD

**Issue by kinchj** [kakaroto/Beyond20#594]
This happened to a player of mine last session, and now it's happening to me.  All rolls are being sent to Roll20 in the default template (purple header with two columns) instead of the D&D 5e By Roll20 template.  I didn't change any settings, and I've confirmed that the Beyond20 option for Roll20 Character Sheet Setting is still set to the D&D 5e By Roll20, and the game settings on Roll20 are also set to the D&D 5e By Roll20 sheet.  It's happening on both my main account and my test account, and in 3 different games.

**Comment by GuineaThePig** [comment]
![Screenshot 2020-12-03 130535](https://user-images.githubusercontent.com/75427583/101015831-424ac780-3568-11eb-8c4c-06dbf598ac78.png)

Has been happening for at least a couple of days, I started noticing this on Tuesday. It's especially an issue for spells. Settings have not changed, it's happening to me and all my players.

![Screenshot 2020-12-03 130742](https://user-images.githubusercontent.com/75427583/101016087-95bd1580-3568-11eb-9b1d-f81efbbd88df.png)

**Comment by DarrynGlass** [comment]
This was due to a change in Roll 20 that broke things. See [https://github.com/kakaroto/Beyond20/issues/592#issuecomment-737506439]

Use the Dev version, which already has a fix (if you don't want to wait for a new release).

@kakaroto please close.

**Comment by kinchj** [comment]
Thank you! I wasn't able to find that issue while searching GitHub (I'm fairly new to using GitHub) as my keyword searches weren't pulling anything up.
