### ISSUE TITLE
Sync back HP into DNDB from R20 tokens

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#6]
Suggestion : Modifying HP from a R20 token would make the HP change in D&D Beyond

**Comment by figotech** [comment]
I really really hope this is possible cause I usually substract the damage the PCs receive in the token and its synced to the Roll20 hp stat.

**Comment by kakaroto** [comment]
It probably won't be, because this issue was opened one year ago and still remains open for a good reason.
D&D Beyond doesn't show sheet changes live, so changing the HP won't affect anyone having the sheet open unless they reload. Also making DNDB modifications is not in my plans.

**Comment by TheBeardedB** [comment]
What about the other direction? Would it be possible to sync changes to a characters HP in D&D Beyond to a selected character token? Similar to how rolling initiative works currently. I know this is probably a separate issue but thought I would ask here since it's tenuously related.

**Comment by Aeristoka** [comment]
> What about the other direction? Would it be possible to sync changes to a characters HP in D&D Beyond to a selected character token? Similar to how rolling initiative works currently. I know this is probably a separate issue but thought I would ask here since it's tenuously related.

This has been a feature from very early in Beyond20: https://beyond20.here-for-more.info/faq#my-hp-from-dd-beyond-doesnt-synchronize-to-my-tokens

**Comment by TheBeardedB** [comment]
Amazing!! Thanks for the quick response

**Comment by rcozmyer** [comment]
Love the live HP gauge update. The Roll 20 Token Features page has an example of linking your AC and Spell Save DC to the other two bars/numbers, but it seemed like Beyond20 wouldn't update those attributes on my Roll20 character sheet. Not sure what other things would be cool to put in these bars. I was keeping track of my total spells available in one of the bars, but I'm not sure if that's practical.

**Comment by kakaroto** [comment]
You can link AC and Spell save DC but those are not dynamic properties that would change multiple times within the same hour, so there is no syncing of that and there won't be in the future either. You can input those values manually if you need to.
As for spell slots, I don't think it's practical honestly, and if you use the D&D Beyond sheet (which is what Beyond20 is for), then you already have that information on your sheet.

**Comment by rcozmyer** [comment]
Awesome, thanks. I just did some testing by changing the numbers in my DDB character sheet, and I guess I was just expecting an immediate change. Spell slots seemed like they'd be helpful, but honestly I don't know, as I've only played a couple of adventures up to level 4 or so.

**Comment by kakaroto** [comment]
Closing this as it was determined long ago that it goes against the basic design of Beyond20, and it won't be implemented.
