### ISSUE TITLE
Beyond20 not working w Roll20

### ISSUE THREAD

**Issue by daelio** [kakaroto/Beyond20#603]
It only shows "purple bars" for everything this week [https://ibb.co/5B3cmRK](url). Usually my stuff all looks like the DM but now it's all purple

**Comment by Aeristoka** [comment]
Duplicate of #592 and #593 and #594 and #595 

Fixed in the Dev version: https://github.com/kakaroto/Beyond20#developer-mode-installation
See also the Beyond20 Discord for another workaround: https://discord.gg/WGNSHcGNRB

Please close.
