### ISSUE TITLE
Dice Rolling from D&D Beyond over to Roll20

### ISSUE THREAD

**Issue by Nyx-WildSiren** [kakaroto/Beyond20#606]
Description:
When I go to roll an ability check from D&D Beyond over to Roll20, the roll just shows up in the chat log, versus allowing me to actually drag & roll my 3D dice

(Have D&D Beyond open, as well as be in a game in Roll20)
1. On D&D Beyond, click on an ability check, as if to roll
2. You will hear the audible beep saying that a roll has been done on Roll20
3. When you switch to your Roll20 tab, you will see that the dice were auto-rolled and the total is put in the chat log. No 3D Dice were even rolled on screen, and you weren't able to click and drag to roll the dice

**Screenshots**
![Roll 20 -1](https://user-images.githubusercontent.com/75553254/101270014-8b964500-3729-11eb-80e8-7243dcd10c50.PNG)
![Roll 20 -2](https://user-images.githubusercontent.com/75553254/101270029-bd0f1080-3729-11eb-9b6c-c29c89edefa0.PNG)

**Browser Info (please complete the following information):**
Browser: Google Chrome - Current version as of 12/05/2020

**Additional context**
https://www.dndbeyond.com/profile/Nyx_WildSiren/characters/26158232

This happens regardless of if I click on the ability check, the small Roll20 icon that pops up when I hover over an ability stat, or if I click on said ability and then click on the Roll 20 text inside the abilities description.
I have double checked all of my Roll20 & D&D Beyond & Beyond 20 settings, and there is nothing that is causing this issue as far as I can tell.
I do notice that by enabling/disabling quick rolls that it either enables/disables Beyond 20 rolling to Roll20 altogether, and instead rolls the dice with D&D Beyonds' dice even though I have that turned off.

**Comment by Aeristoka** [comment]
Duplicate of #592 and #593 and #594 and #595 and #603 and #605 

Fixed in the Dev version: https://github.com/kakaroto/Beyond20#developer-mode-installation
See also the Beyond20 Discord for another workaround: https://discord.gg/WGNSHcGNRB

Please close.

**Comment by Nyx-WildSiren** [comment]
Thank-you, apologies for opening a duplicate issue!
