### ISSUE TITLE
Adding Death Save Status In FVTT

### ISSUE THREAD

**Issue by flangelier** [kakaroto/Beyond20#608]
**Is your feature request related to a problem? Please describe.**
Not really... It just something that we could see in FVTT if the person is unconsious.

**Describe the solution you'd like**
In Foundry (I don't know if it's possible in the other VTT) When someone drop to 0 hp, an unconscious could appear and every time it roll a Death Saving Throw, the "result" could be display as a Green dot (passed) or Red dot (failed), so we could easy see the status of the PC.
Also, If the PC passed 3 death save, he could be stabilized (with 0 hp), if he fail 3 death save, we could have the Death "Status" and if he roll a Nat 20, the PC could gave 1 HP and Prone Status.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by Aeristoka** [comment]
You can accomplish this really easily with Combat Utility Belt's Condition Lab, or Health Estimate (both great modules).

Essentially both would make the proper status on the Character/NPC when it's appropriate, in part based of syncing the 0 HP state from DnDBeyond -> FoundryVTT via Beyond20.

**Comment by kakaroto** [comment]
Yeah, I think that's a bit beyond the scope of Beyond20, and FVTT has awesome modules to do that already.
