### ISSUE TITLE
Make crits on ability rolls more clear

### ISSUE THREAD

**Issue by tjstinso** [kakaroto/Beyond20#609]
It looks like a you've defined some new custom markup for messages in roll 20. The new system has clear strenghts on attack rolls, but it feels like a regression on ability rolls. I want a clear visual cue when we get a critical rolls. Simply changing the color of text to green/red in the same manner as the roll 20s native messages. 

Roll 20s native messages do this clearly:
![image](https://user-images.githubusercontent.com/10609667/101310540-fd42c180-3803-11eb-82fd-8fb0f9c10aba.png)

Effectively, suppose the following roll were actually a crit:
![image](https://user-images.githubusercontent.com/10609667/101310101-ccae5800-3802-11eb-844c-0b81a7c7122f.png)

I want it to look like:
![image](https://user-images.githubusercontent.com/10609667/101310673-63c7df80-3804-11eb-997d-6d9821b2ed2c.png)

**Comment by tjstinso** [comment]
This should be a small change, I can probably do it myself if you don't have the time.

**Comment by kakaroto** [comment]
> It looks like a you've defined some new custom markup for messages in roll 20.

I haven't, but Roll20 changes something on their page which break Beyond20's ability to detect if the D&D sheet template is enabled (see #592 among others).
As for the criticals being green, this should already be the case, but I just tested and confirmed it seems to be bugged, only works if using digital dice, but doesn't show the colors if digital dice are disabled.

**Comment by tjstinso** [comment]
Interesting. Thanks for the quick response

**Comment by amenokos** [comment]
When I tested this issue using the development version, the colors for both crit hits and fails worked for me with digital dice enabled or disabled within either Beyond20's settings or my DDB character sheet's settings. I tried all combinations of settings (Digital Dice Feature: Both disabled, B20 disabled with DDB enabled, B20 enabled with DDB disabled, and both enabled) and never experienced this bug with the dev version.

**Comment by tjstinso** [comment]
I’m not on dev. I posted this issue as a public consumer. It sounds like
someone fixed this for non virtual dice on dev.

For my own reference, what is your release cycle? I might hop on dev to get
a better feel for things.

**Comment by kakaroto** [comment]
> When I tested this issue using the development version, the colors for both crit hits and fails worked for me with digital dice enabled or disabled within either Beyond20's settings or my DDB character sheet's settings. I tried all combinations of settings (Digital Dice Feature: Both disabled, B20 disabled with DDB enabled, B20 enabled with DDB disabled, and both enabled) and never experienced this bug with the dev version.

I'll retest and fix, but the bug is if you use Roll20 + Beyond20 Roll renderer + Digital dice disabled. It might have worked for you because of the dnd5e sheet template.



> I’m not on dev. I posted this issue as a public consumer. It sounds like someone fixed this for non virtual dice on dev. For my own reference, what is your release cycle? I might hop on dev to get a better feel for things.

Release cycle is "whenever there's been enough changes to warrant a release", it's been usually 1 to 2 months between releases, but no set schedule. I have one planned for later today though, so I'm sure you can wait if you're not keen on switching to the development version.

**Comment by tjstinso** [comment]
Oh yea no rush for me. I’m interested in switching to dev strictly out of
interest rather than necessity. I’ve looked over the code a bit to resolve
confusion among my friend groups understanding of the data flow, but I’ve
not gone so far to contribute... yet

**Comment by Aeristoka** [comment]
@tjstinso Is this still an issue on 2.5.0?

**Comment by Aeristoka** [comment]
Closing because of no response (and has been fixed).
