### ISSUE TITLE
Great Weapon Fighting rerolls 1s and 2s for Heavy Crossbow

### ISSUE THREAD

**Issue by Mangoray** [kakaroto/Beyond20#61]
The Great Weapon Fighting style should only allow rerolls of 1's and 2s for 2handed **melee** weapons.

Currently it also re rolls for 2hand heavy crossbow attack

(as work around, if i add a 'custom attach action' in dndbeyond and specify it's a ranged attack, with the same stats as the heavy crossbow, it works fine)

**Comment by kakaroto** [comment]
Thanks for the report, you're right! I only checked for two-handed property and not for 'attack type: melee'.
Will fix!
