### ISSUE TITLE
Dice no longer rolling in Roll20 from DNDBeyond.

### ISSUE THREAD

**Issue by Speciaiev** [kakaroto/Beyond20#610]
We cannot get dice to roll in Roll20 VTT from DNDBeyond character sheets since most recent updates. 

We just get the ugly purple boxes and no dice bouncing around in Roll20.

I'm using Google Chrome is up to date
Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by SoulMourne** [comment]
Hello,

The bug comes from an update on Roll20's side. This is fixed on the developer mode and should be available in the next update. Please see #592

**Comment by DarrynGlass** [comment]
From discord:

Roll20 has made a change to their site yesterday which causes some functionality from Beyond20 to stop working, forcing all rolls to be sent using the default roll template even if your character sheet template is set to D&D 5e.

As a temporary workaround, you can use the development version of Beyond20 which fixes the issue.
For instructions, check out https://github.com/kakaroto/Beyond20#developer-mode-installation

@kakaroto  please close

**Comment by Speciaiev** [comment]
Thank you! This fix worked for me.
