### ISSUE TITLE
Added dice via hotkey resulting in total of 0 in Roll20 

### ISSUE THREAD

**Issue by dbriann** [kakaroto/Beyond20#614]
when using a hotkey do add a bonus dice to a roll, the total given in roll20 is always 0. it happens only when using a hotkey and only with bonus dice. hotkeys for a minus dice works well.

the comand sent to roll20 gives a  "+ +" before the dice command... that must break something. but for a minus dice it sends a "+ -" before the dice command, but still works...

when using the Custom Roll dice formula bonus it works all good, but the roll20 code gives only 1 "+" before the dice command

**Comment by twglomski** [comment]
Able to verify. Here's an example:

`&{template:atkdmg} {{charname=Sabado Domingo}} {{rname=Rapier}} {{mod=+6 + 1d4cs0cf0}} {{r1=[[1d20 +6+ + 1d4cs0cf0[CUSTOM]]]}} {{attack=1}} {{damage=1}} {{dmg1flag=1}} {{dmg1=[[1d8+5]]}} {{dmg1type= Piercing}} {{crit1=Crit: [[1d8]]}} {{normal=1}}`

returns this in Roll20: 

![image](https://user-images.githubusercontent.com/8115237/101645714-4a898380-39fc-11eb-8a1f-0531fc86431e.png)

removing the `+` right after the original modifier:

`&{template:atkdmg} {{charname=Sabado Domingo}} {{rname=Rapier}} {{mod=+6 + 1d4cs0cf0}} {{r1=[[1d20 +6 + 1d4cs0cf0[CUSTOM]]]}} {{attack=1}} {{damage=1}} {{dmg1flag=1}} {{dmg1=[[1d8+5]]}} {{dmg1type= Piercing}} {{crit1=Crit: [[1d8]]}} {{normal=1}}`

displays correctly:

![image](https://user-images.githubusercontent.com/8115237/101645888-7dcc1280-39fc-11eb-8aa4-d3f12ff4338a.png)

**Comment by 3ricTheR3d** [comment]
As a temp containment if you go to Custom Roll dice formula bonus and input +0 then roll20 appears to work correctly (with an additional +0 in the formula)
