### ISSUE TITLE
Support for Roll20 Macros in Custom Damage dice formula bonus

### ISSUE THREAD

**Issue by Cube-o** [kakaroto/Beyond20#617]
**Describe the feature**
In the current FAQ under [How can I add Bless/Guidance bonus or use Elemental Weapon?](https://beyond20.here-for-more.info/faq#how-can-i-add-blessguidance-bonus-or-use-elemental-weapon) there is an example of using `+?{Use Bless|Yes,1d4|No,0}` in the _Custom Roll dice formula bonus_ field. This syntax however does not work in the _Custom Damage dice formula bonus_, making it impossible to ask for things like Hex or Hunter's Mark.

**Current Behavior**
When entering for example  `?{Use Hex|Yes, 1d6|No, 0}`, it gets parsed as 3 separate bonus damages `["?{Use Hex|Yes", " 1d6|No", " 0}"]`, because multiple bonuses are delimited by commas. And when it gets sent to Roll20 it does all sorts of crazy things. There is a possible workaround with omitting the labels for the options, changing the formula (and thus also the commas) to `?{Use Hex|1d6|0}`. But that, well, lacks the labels then.

**Proposed Change**
Introduce the option to escape the commas. It is a simple change - instead of using `split(",")`, use `split(/(?<!\\),/)`. That will result in splitting into separate bonuses only on commas that are not escaped, a.k.a. not preceded by `\`.

With your blessing I can create a PR for it myself.

**Comment by kakaroto** [comment]
Escaping the comma is a great idea! And it's an easy fix. I can do it, but if you want to do the PR and get your name in the contributors list, go ahead :)

**Comment by Cube-o** [comment]
ok, will get to it tomorrow :)

**Comment by kakaroto** [comment]
This was fixed in 5a3dae7dc7d3e0fb7819a9cc288f893ed19f4ba1
Thanks!

**Comment by dmportella** [comment]
There is support for bless now as a effect, check the effects in the dialog.

<img width="710" height="655" alt="Image" src="https://github.com/user-attachments/assets/a4e56584-98e3-40db-bb87-bb93f521fc49" />

I will check the custom stuff

**Comment by SelikBready** [comment]
> There is support for bless now as a effect, check the effects in the dialog.

Yeah, I use bless just as an example, I'm looking for my own custom effect with confirmation. Thanks!

**Comment by kakaroto** [comment]
> Hate to necropost, but is it still supposed to work?
> I tried both `+?{Use Bless|Yes,1d4|No,0}`, `+?{Use Bless|Yes\,1d4|No\,0}` and `+?{Use Bless|1d4|0}` and none of these options work, neither in dice nor in damage rolls.

It should, unless you use the digital dice option which makes it roll the dice on D&D Beyond's and only send the results. D&D Beyond can't recognize the roll20 macros, so those would only work if you have it roll the dice on roll20's side.
I'm going to assume that this is why it's not working for you.
