### ISSUE TITLE
Minus Minus when Rolling Wisdom

### ISSUE THREAD

**Issue by nahiara1511** [kakaroto/Beyond20#619]
I'm using the extension with DnD Beyond. My character has a 3 as his wisdom stat and hence his modifier is --4. For some reason, the extension rolls Wisdom -- 3, making it a Wisdom + 3.

**To Reproduce**
1. Go to DnD Beyond
2. Use Beyond20 to roll Wisdom
3. Wait until it rolls

**Expected behavior**
For the dice to roll a Wisdom - 4.

**Screenshots**
**![image](https://user-images.githubusercontent.com/75750943/101669920-504d8c00-3a31-11eb-9c64-4dd8890b2c9d.png)**
![image](https://user-images.githubusercontent.com/75750943/101669956-5c394e00-3a31-11eb-87f2-866733da5da0.png)

**Browser Info (please complete the following information):**
 - Chrome
 - Version 87.0.4280.88 (Official Build) (64-bit)

**Additional context**
Character Sheet: ddb.ac/characters/38801835/2WZL5a

**Comment by kakaroto** [comment]
Thanks. I can confirm, it's because of jack of all trades, as it adds +1, so the -4 becomes -4 + 1 = -3, and it checks "oh it's negative, so it should be `- modifier` which ends up as `- -3` 🤦

**Comment by ConlonNovak** [comment]
Replicated again, my Jack of All Trades Bard has the same issue. -2 becomes --1 which resolves to +1 in the final roll. Only seems to affect numbers smaller than -1.
