### ISSUE TITLE
"Roll Initiative!" duplicated when using Encounter Builder

### ISSUE THREAD

**Issue by Kasuko** [kakaroto/Beyond20#62]
I was using Beyond20 as a GM to run an encounter from D&D Beyond and it was amazing!

However, one minor issue is that if you use the new Encounter Builder, which is a great way to see multiple monsters in a single view, then every time you switch the stat block a new "Roll Initiative!" section is added to the stat block.

To reproduce, just make a new encounter using the Encounter Builder that contains 2 unique enemies. Then switch back and forth between them multiple times.

![Screen Shot 2019-11-29 at 7 25 26 AM](https://user-images.githubusercontent.com/86419/69869236-40c23180-127a-11ea-9be3-8d1ce286094d.png)

**Comment by kakaroto** [comment]
ah yes! I've seen similar behavior for other things with the encounter builder, but forgot to test the roll initiative in there and fix it. Thanks for the report, will get it fixed! :)
