### ISSUE TITLE
Roll20 Hot Keys not replacing asking for roll each time

### ISSUE THREAD

**Issue by ghost** [kakaroto/Beyond20#620]
Despite setting up hot keys in Roll20, rolls are only being executed based on previously selected type of roll in settings. I.E. any hot key used for a roll only produces the type of roll set in settings.

**Comment by Aeristoka** [comment]
Can you be more specific here? I'm not at all sure what you mean.

**Comment by kakaroto** [comment]
Closing this as it's very unclear what the issue is, and we haven't received any new information.
Feel free to re-open the issue with more information and steps to reproduce the bug you seem to encounter.
