### ISSUE TITLE
Custom hotkeys don't work with advantage if shift clicked first

### ISSUE THREAD

**Issue by 3ricTheR3d** [kakaroto/Beyond20#622]
**Describe the bug**
When using a Custom Hotkey & Advantage (Shift)
If you press Shift then the hotkey you only roll with advantage and not using both Custom Hotkey & Advantage (bug)

If you press Custom Hotkey then Shift you roll using both Custom Hotkey & Advantage (desired behavior)

Issue only found using Shift for Advantage. If advantage is mapped to another key (z) order pressed doesn't make a difference.

Issue not seen with disadvantage (ctrl)

Suspect issue may be caused from custom hotkeys being case sensitive. Where it should be case insensitive to support using Shift for Advantage

**To Reproduce**
1. Custom HotKey bound "b" to Custom Modifier +1d4 (Bless/Guidance)
2. Roll weapon pressing Shift then b --> only roll with Advantage (Bug)
3. Roll weapon pressing b then Shift  --> roll with Advantage and Bless (Desired Behavior)

**Expected behavior**
Order of key presses should not make a difference. Pressing Shift then Custom Hot Key (b) should roll with both advantage and bless

**Comment by DarrynGlass** [comment]
There are two solutions for this.  If you want to keep SHIFT for Advantage, then when you create a new hot key (b for bless) hit Caps Lock so that it is an upper case B.  Then it works.

The other option is remapping Advantage to a different key (like a).

The keys are case sensitive which is where the issues is happening (SHIFT for advantage and b for bless ends up with B which is not b).

**Comment by DarrynGlass** [comment]
I think this issue was opened to help address this
https://github.com/kakaroto/Beyond20/issues/618

**Comment by rmogstad** [comment]
> There are two solutions for this. If you want to keep SHIFT for Advantage, then when you create a new hot key (b for bless) hit Caps Lock so that it is an upper case B. Then it works.
> 
> The other option is remapping Advantage to a different key (like a).
> 
> The keys are case sensitive which is where the issues is happening (SHIFT for advantage and b for bless ends up with B which is not b).

However, it will now not work unless you are holding SHIFT, so it creates the opposite problem...

**Comment by DarrynGlass** [comment]
> However, it will now not work unless you are holding SHIFT, so it creates the opposite problem...

Hmmm.  I have always had to hold the hot key (SHIFT in this case) to have it affect the roll.  If I just press SHIFT, the icon changes to the + die, but as soon as I release it, it goes back to the normal die.  This is why I remapped ADV to the "a" key instead.

**Comment by rmogstad** [comment]
> > However, it will now not work unless you are holding SHIFT, so it creates the opposite problem...
> 
> Hmmm. I have always had to hold the hot key (SHIFT in this case) to have it affect the roll. If I just press SHIFT, the icon changes to the + die, but as soon as I release it, it goes back to the normal die. This is why I remapped ADV to the "a" key instead.

My point is that if you bind +1d4 to B instead of b, now you can only use it with advantage (unless you keep caps lock on, which will make it not work *with* advantage again), and you can't bind both B and b. Overall, there is no good workaround

**Comment by DarrynGlass** [comment]
> My point is that if you bind +1d4 to B instead of b, now you can only use it with advantage (unless you keep caps lock on, which will make it not work _with_ advantage again), and you can't bind both B and b. Overall, there is no good workaround

That is a good point.  Best work around is to map Advantage to a different key.

**Comment by kakaroto** [comment]
> My point is that if you bind +1d4 to B instead of b, now you can only use it with advantage (unless you keep caps lock on, which will make it not work _with_ advantage again), and you can't bind both B and b. Overall, there is no good workaround that allows you to keep advantage on the SHIFT key. I've also mapped adv to a for now, but it doesn't matter because the +1dx are also currently broken :D

You can bind both `b` and `B`, that's what people have been doing as a workaround. 
And yes #618 is meant to fix this, so this is a duplicated.
