### ISSUE TITLE
Super (dis)Advantage "++" | "--" roll icons. Scale the five icons with three (or five) different colours

### ISSUE THREAD

**Issue by choraltrickster** [kakaroto/Beyond20#623]
Thanks for adding the ability to roll for super advantage.

The icon doesn't change from the 'normal' icon when the hotkey is pressed (yet the roll rolls with super-advantage as intended)

Requests:
- Add roll icons for super-advantage and super-disadvantage: -- | - | B | + | ++
- scale the icons by colour using 5 colours (or just three maybe)

**Comment by kakaroto** [comment]
Good point about being able to change the icon, that part of the logic was for when it was only the alt/shift/ctrl hotkeys, and there wasn't one for super advantage even if that was a roll option (it does show the correct icon if you select that as your default roll type, but not when using the hotkey).
