### ISSUE TITLE
Blinking Conpendium

### ISSUE THREAD

**Issue by kanrei** [kakaroto/Beyond20#625]
**Describe the bug**
The extension makes the spell, monster conpendium blink. I don't know why but I opened the compendium blocking the extension and it openend without blinking.
**To Reproduce**
Go to 'https://www.dndbeyond.com/monsters/wolf'
The moment it charges it begins to blink all the time. The tab stops reacting well and it makes intereacting with the site difficult
**Expected behavior**
I just want fot the tab to stop blinking.

**Screenshots**
There is a video inside the zip.
[Blinking screen.zip](https://github.com/kakaroto/Beyond20/files/5676057/Blinking.screen.zip)

**Browser Info (please complete the following information):**
 - Browser Chrome (Versión 87.0.4280.88 (Build oficial) (64 bits)) and Brave (Versión 1.17.75 Chromium: 87.0.4280.88 (Build oficial) (64 bits))
 - Version [e.g. 85]

**Comment by Aeristoka** [comment]
You have two versions of Beyond20 enabled then, likely the Chrome Store + a manually installed Dev version.
