### ISSUE TITLE
Is there a feature to turn off alertify notifications after rolling a dice? 

### ISSUE THREAD

**Issue by nirokun** [kakaroto/Beyond20#632]
I'm always frustrated when i roll a dice in DnD beyond and appears a modal/pop up/alert with the results, i'm already have DnD Beyond alert in right bottom AND getting Discord message from the Discord Bot.

I really want a button or option (if there is any i didn't find it) to turn down this alerts after rolling some dice.

In this image we can see three notifications for a simple roll.
![imagen](https://user-images.githubusercontent.com/46892820/102422173-eca10100-3fe4-11eb-9dcc-dc26645811b4.png)

**Comment by kakaroto** [comment]
The notification in the corner is from D&D Beyond for the digital roll, that's what Beyond20 parses. Then it shows you the actual results (in this case it's one roll, but it will often be attack, with advantage/disadvantage + damages + class feature extra damages + totals calculation.
That popup is only shown when there is no VTT that it can find to send the rolls to. In the case of Discord, it has no knowledge/guarantee that the message was sent and displayed in Discord, so if it's not, you end up with no results at all. Also, if you don't have "auto roll damages" enabled, you have no way in Discord to tell it to roll damages after you do an attack.
There *is* however, an option to not show those messages when sending to discord and when you have whispering enabled.
