### ISSUE TITLE
Fix digital dice parsing when rolling manually with advantage

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#633]
![image](https://user-images.githubusercontent.com/27990/102523142-29144180-4065-11eb-81b3-ff7838d3243c.png)

![image](https://user-images.githubusercontent.com/27990/102523155-2ca7c880-4065-11eb-8060-92f150bcdbdc.png)

**Comment by Aeristoka** [comment]
@kakaroto isn't this fixed now?

**Comment by kakaroto** [comment]
Indeed! Thanks!
