### ISSUE TITLE
Rogue feature Reliable Talent not working if dice are enabled when sending to VTT

### ISSUE THREAD

**Issue by GlapointeNexone** [kakaroto/Beyond20#634]
As a rogue when you roll dice for a skill that you are proficient, the Reliable Talent ability of the rogue lv 11 and above give the effect, if the roll is lower than 10 the result will be 10 + ability score. 
Without the dice feature enabled in DnD Beyond, Beyond20 send the roll to the VTT correctly.
If the dice feature is enabled the feature will not be considered for the roll.

Exemple : 
 If the Dice are not enabled the formula displayed is : Rolling {1d20, 0d0 + 10}kh1 + ability. like this 
![image](https://user-images.githubusercontent.com/67755091/102721708-8b21b080-42ca-11eb-90f7-331b37b9396a.png)

If the Dice are enabled the formula will be Rolling [1d20 + ability]. like this 
![image](https://user-images.githubusercontent.com/67755091/102721759-d76cf080-42ca-11eb-8fdc-1971e7276acb.png)

Browser Info : 
 - Browser : chrome
 - Version : 87.0.4280.88 (Build officiel) (64 bits)
 - If applicable, any dev console errors : No console error

**Comment by Aeristoka** [comment]
I had it show up with Digital Dice on as this:

![image](https://user-images.githubusercontent.com/7988297/105638475-0594a180-5e30-11eb-8e9b-2938883c2ac1.png)

Can you test again? Making sure you clicked to "Features & Traits" so it has the feature parsed.

**Comment by GlapointeNexone** [comment]
Yes I confirm that this is working. I tested with dice enabled and without dice in DnD Beyond. Thank you !
