### ISSUE TITLE
Disadvantage in Chrome on macOS activates context menu

### ISSUE THREAD

**Issue by mikeschnier** [kakaroto/Beyond20#639]
Hi Kakaroto, I've been enjoying Beyond20 and wanted to provide feedback about an issue I've had.

The current modifier key for disadvantage (Control ^) is also the keyboard shortcut for the context menu on macOS. This causes attempts to roll with disadvantage to instead open the context menu. An option to change the modifier key could be a possible workaround.

From the changelog, it looks like this might have also been an issue in the past but the issue is present in version 2.3.0 running in the most recent version of Chrome (87.0.4280.88).

<img width="361" alt="image" src="https://user-images.githubusercontent.com/64474502/102963121-570ae300-44b6-11eb-8a2e-7ae6c276f6fc.png">

**Edit:** Thanks Kakaroto! I thought a setting to change the key had to be there but didn't see it. Works like a charm.

**Comment by kakaroto** [comment]
Ah, that's why it was the Meta key (Command instead of Control) for Macs! Version 2.3.0 switched it to being only Control by default, which is where the issue is.
You can already change  it, go to 'more options' then click on the setup hotkeys button.
Thanks for the report!

**Comment by Aeristoka** [comment]
@mikeschnier can you verify if this still needs to be open now that you can modify this with Hotkey Manager?

**Comment by mikeschnier** [comment]
@Aeristoka Sorry, I thought this was closed. It's no longer an issue for me but I would suggest that default hotkeys which conflict with the browser or OS will lead to feedback even if they are modifiable.

**Comment by Aeristoka** [comment]
> @Aeristoka Sorry, I thought this was closed. It's no longer an issue for me but I would suggest that default hotkeys which conflict with the browser or OS will lead to feedback even if they are modifiable.

The default hotkeys have all been changed to use actual keys instead of the more general way they were done before.
