### ISSUE TITLE
Feat: SharpShooter Flattens to hit bonus

### ISSUE THREAD

**Issue by KealGSeo** [kakaroto/Beyond20#644]
**Describe the bug**
Sharpshooter feat fully replaces the "to hit" to "-5" instead of calculating the bonus to hit and subtracting 5.

**To Reproduce**
1. Create level 1 fighter, choose archery subclass and take Sharpshooter feature
2. Set Dexterity to 16 for a total of +7 to longbow attack
3. Equip Long Bow
4. Roll attack with Sharpshooter feat

**Expected behavior**
Roll should equal 1d20+7-5. 1d20 standard attack, 3 proficiency bonus + 3 dexterity to attack + 2 archery subclass, -5 sharpshooter. (Rather it just defaults to 1d20-5)

**Screenshots**

**Browser Info (please complete the following information):**
 - Browser chrome
 - Version 87.0.4280.88

**Additional context**

**Comment by Aeristoka** [comment]
Doesn't seem to be having the issue for me:
![image](https://user-images.githubusercontent.com/7988297/103503340-35442100-4e11-11eb-86e2-43447d7507ad.png)

Can you better describe when you saw this? Perhaps include screenshots?

**Comment by KealGSeo** [comment]
This is the character sheet I am using.
https://ddb.ac/characters/42195368/rCjA3z

These two screen shots are just weapon attacks, acts as expected:
![first click result](https://user-images.githubusercontent.com/28343985/103598732-5d935480-4ed1-11eb-9534-e2a8d90ce857.jpg)
![first click](https://user-images.githubusercontent.com/28343985/103598733-5e2beb00-4ed1-11eb-82dd-8fdfc50dbaa1.jpg)


These two are of of the "bug" which I admittedly may be clicking in the wrong spot:
![second click results](https://user-images.githubusercontent.com/28343985/103598811-81569a80-4ed1-11eb-86a0-00a62215fd42.jpg)
![second click](https://user-images.githubusercontent.com/28343985/103598812-81ef3100-4ed1-11eb-8405-c947bd7d6e19.jpg)

**Comment by Aeristoka** [comment]
Yep, that's not where you click. Beyond20 parses all those roll areas, and it literally just establishes a "1d20 +- modifier"

To use sharpshooter, you need to toggle it on in the Beyond20 Settings:
![image](https://user-images.githubusercontent.com/7988297/103599031-5fedb280-4ec1-11eb-92ae-9ad49a36765c.png)

![image](https://user-images.githubusercontent.com/7988297/103599046-6845ed80-4ec1-11eb-8161-4bafbd987e6f.png)

**Comment by KealGSeo** [comment]
Thank you for the clarification. Since it was rolling from the feat I assumed that was the correct place to click.
