### ISSUE TITLE
Advantage/Disadvantage not highlighted

### ISSUE THREAD

**Issue by SanguineSleet** [kakaroto/Beyond20#648]
When rolling at advantage or disadvantage it shows up in roll20 but the other players don't know what roll is the one to use, especially if you have an item or ability that gives Advantage the DM may not know what you are rolling. Using the CHROME extension in Chrome

**To Reproduce**
Just roll with advantage or disadvantage 

**Expected behavior**
Maybe the one not rolled would be greyed out and the other dark, or a colour difference. Something to make it distinguishable of what type of roll you did.

![image](https://user-images.githubusercontent.com/77248895/104135836-6b792780-5360-11eb-99fa-07d6145993de.png)

**Comment by Aeristoka** [comment]
> When rolling at advantage or disadvantage it shows up in roll20 but the other players don't know what roll is the one to use, especially if you have an item or ability that gives Advantage the DM may not know what you are rolling. Using the CHROME extension in Chrome
> 
> **To Reproduce**
> Just roll with advantage or disadvantage
> 
> **Expected behavior**
> Maybe the one not rolled would be greyed out and the other dark, or a colour difference. Something to make it distinguishable of what type of roll you did.
> 
> ![image](https://user-images.githubusercontent.com/77248895/104135836-6b792780-5360-11eb-99fa-07d6145993de.png)

You have "Roll Twice" enabled, this is what it looks like:

Rolling with Advantage:
![image](https://user-images.githubusercontent.com/7988297/104135926-1d5c2800-5350-11eb-8b54-e3959d60026d.png)

Rolling with Disadvantage
![image](https://user-images.githubusercontent.com/7988297/104135932-23ea9f80-5350-11eb-9ce2-6427150caaf9.png)

**Comment by SanguineSleet** [comment]
> > When rolling at advantage or disadvantage it shows up in roll20 but the other players don't know what roll is the one to use, especially if you have an item or ability that gives Advantage the DM may not know what you are rolling. Using the CHROME extension in Chrome
> > **To Reproduce**
> > Just roll with advantage or disadvantage
> > **Expected behavior**
> > Maybe the one not rolled would be greyed out and the other dark, or a colour difference. Something to make it distinguishable of what type of roll you did.
> > ![image](https://user-images.githubusercontent.com/77248895/104135836-6b792780-5360-11eb-99fa-07d6145993de.png)
> 
> You have "Roll Twice" enabled, this is what it looks like:
> 
> Rolling with Advantage:
> ![image](https://user-images.githubusercontent.com/7988297/104135926-1d5c2800-5350-11eb-8b54-e3959d60026d.png)
> 
> Rolling with Disadvantage
> ![image](https://user-images.githubusercontent.com/7988297/104135932-23ea9f80-5350-11eb-9ce2-6427150caaf9.png)

Okay, I was using the hot keys for it, so holding shift or control to quick roll at advantage/disadvantage. It should do the same thing as having he double roll. But it's not

**Comment by Aeristoka** [comment]
I was using the HotKeys as well. The default setting is a single roll. You have "Always Roll Twice" enabled, but those hotkeys highlight Advantage/Disadvantage just fine for me.

Do you have the DnDBeyond window focused while using the Hotkeys? if you don't, your "Always Roll Twice" setting is the only thing that will apply, and the Hotkeys will not.

**Comment by SanguineSleet** [comment]
I have it set for normal roll:
![image](https://user-images.githubusercontent.com/77248895/104136176-93698a80-5362-11eb-86fc-4bb53b8f8481.png)

if DNDBeyond item is already creating advantage for an item is me using hotkeys causing it to not work and just make it look like a double roll?

**Comment by Aeristoka** [comment]
Nope, that would highlight just fine:
![image](https://user-images.githubusercontent.com/7988297/104136227-146c5600-5352-11eb-821b-5d1f73ebc0e7.png)

![image](https://user-images.githubusercontent.com/7988297/104136230-19c9a080-5352-11eb-99f4-4c60eff2b831.png)

**Comment by SanguineSleet** [comment]
Weird, just tried it again and got this:
![image](https://user-images.githubusercontent.com/77248895/104136259-ff4bf300-5362-11eb-8b80-56ea39da4d5d.png)

So not sure where in my settings its going wrong, or its not linking properly

**Comment by Aeristoka** [comment]
And using CTRL to override Disadvantage on a Stealth:
![image](https://user-images.githubusercontent.com/7988297/104136256-382f9c00-5352-11eb-8685-5632b14751e1.png)

![image](https://user-images.githubusercontent.com/7988297/104136263-3ebe1380-5352-11eb-85da-7c8606b806d0.png)

Are you seeing the pop-up change to the Disadvantage/Advantage icon like in my image above?

**Comment by SanguineSleet** [comment]
Yes I see either the Plus or Negative when making the roll, but yet its still showing like the above.

**Comment by Aeristoka** [comment]
> Weird, just tried it again and got this:
> ![image](https://user-images.githubusercontent.com/77248895/104136259-ff4bf300-5362-11eb-8b80-56ea39da4d5d.png)
> 
> So not sure where in my settings its going wrong, or its not linking properly

I'd say try removing/re-installing Beyond20. It looks like (maybe) the "Always Roll Twice" is stuck in some way.

Also, make sure you don't have an official + Dev Version installed.

**Comment by Aeristoka** [comment]
> Yes I see either the Plus or Negative when making the roll, but yet its still showing like the above.

Then it isn't registering the Hotkey press, which means you don't have the DnDBeyond window focused.

To focus the window, you have to click on the DnDBeyond Page, then Shift+Click or CTRL+Click on that page, it'll change the icon.

**Comment by SanguineSleet** [comment]
> > Yes I see either the Plus or Negative when making the roll, but yet its still showing like the above.
> 
> Then it isn't registering the Hotkey press, which means you don't have the DnDBeyond window focused.
> 
> To focus the window, you have to click on the DnDBeyond Page, then Shift+Click or CTRL+Click on that page, it'll change the icon.

Sorry I meant I was seeing the Plus or Negative change in the icons, its my rolls I meant are still showing like the above "my perception check not showing if rolled at advantage or disadvantage"

I am running 2.3.0, will try and uninstall and try re-installing it.

**Comment by Aeristoka** [comment]
> > > Yes I see either the Plus or Negative when making the roll, but yet its still showing like the above.
> > 
> > 
> > Then it isn't registering the Hotkey press, which means you don't have the DnDBeyond window focused.
> > To focus the window, you have to click on the DnDBeyond Page, then Shift+Click or CTRL+Click on that page, it'll change the icon.
> 
> Sorry I meant I was seeing the Plus or Negative change in the icons, its my rolls I meant are still showing like the above "my perception check not showing if rolled at advantage or disadvantage"
> 
> I am running 2.3.0, will try and uninstall and try re-installing it.

And do make sure you didn't have both Official + a Dev version installed.

**Comment by SanguineSleet** [comment]
thanks! I reinstalled it and it works, you can close this one!

**Comment by Aeristoka** [comment]
> thanks! I reinstalled it and it works, you can close this one!

I can't actually, but you can, because you opened it 👍

**Comment by amenokos** [comment]
I was having the same issue. Uninstalling 2.3.0 and reinstalling 2.3.0 fixed the issue for me also.
