### ISSUE TITLE
Rage Toggle

### ISSUE THREAD

**Issue by ShaiddaiLynn** [kakaroto/Beyond20#649]
**Describe the bug**
Rage toggle isn't appearing on new barbarian characters.

**To Reproduce**
1. Go to Beyond 20 options on DND Beyond.
2. Scroll to the bottom.
3. Rage Toggle is nonexistant.

**Expected behavior**
I expected there to be a rage toggle to add my +2 damage and advantages.

**Screenshots**
To help explain your problem, add screenshots of where you clicked in D&D Beyond, a screenshot of your Beyond20 character settings if applicable and the result you saw in the VTT.
![Untitled](https://user-images.githubusercontent.com/44856595/104147400-b52f3580-5393-11eb-8436-8755e223f28f.png)

**Browser Info (please complete the following information):**
 - Browser [e.g. chrome, firefox] Chrome
 - Version [e.g. 85] Version 87.0.4280.141 (Official Build) (64-bit)

**Additional context**
Add any other context about the problem here, such as a link to the character sheet or D&D Beyond page that shows the problem.
https://ddb.ac/characters/9575863/HmjteR

**Comment by kakaroto** [comment]
When you opened your sheet, it would have shown you this : 
![image](https://user-images.githubusercontent.com/27990/104147970-68049100-539e-11eb-9e40-959e25a91bbc.png)

Did you actually go to the 'Features & Traits' panel in D&D Beyond as asked before you checked for the Rage toggle ?
