### ISSUE TITLE
Togglable or Hotkey Hex, Hunter's Mark, Green Flame Blade, ect

### ISSUE THREAD

**Issue by AntRuff** [kakaroto/Beyond20#652]
**Is your feature request related to a problem? Please describe.**
Maybe I am just misusing the tools, but I've had trouble getting Beyond20 to make use of the Custom Roll Modifiers on anything other than a d20 roll. Not sure if that was intended, but it becomes an issue when trying to use make use of spells like Hex, Hunter's Mark, and Green Flame Blade during attacks.

**Describe the solution you'd like**
If possible, would you be able to add Hotkey options or a toggle switch for spells and abilities that modify the damage of an attack that isn't a passive feature. Spells like Hunter's Mark, Hex, Green Flame Blade, Booming Blade, Magic Weapon, Elemental Weapon, and Holy Weapon. Some abilities that would also benefit would be Divine Smite and Eldritch Smite, where you can also be prompted for the level of the spell slot used and if it is targeting undead in the case of Divine Smite. There may be other spells or abilities that have a similar need, but these were the main ones that I could think of. Thanks.

**Comment by PirateSwayze** [comment]
This would be very useful. I have also tried using the "Custom modifier: + 1d6" Hot Key for Hex, but it doesn't work with the damage roll, just augmenting the D20 during the attack roll. It would be nice if there were two sections for Custom Modifier, one for Attack Roll and one for Damage Roll. 

But as @AntRuff mentioned, having specific options for Spells like Hex, Hunter's Mark, Divine Smite, etc, would be great. Especially if this allowed for options like spell slot used for Divine Smite.

**Comment by SnickerSnac** [comment]
Having exactly the same issue, while the full list of options would be great just having the custom modifiers apply to ant roll should do the job
