### ISSUE TITLE
No Discord Secret Key Field

### ISSUE THREAD

**Issue by Umbyology** [kakaroto/Beyond20#654]
I'm using Chrome for the Mac (all updated to the latest versions), everything seems to work fine, except when I tried to set up a Discord Integration there was no field to enter my secret key (see attached image).

Am I missing something?  Suggestions?

![Screen Shot 2021-01-16 at 1 28 01 PM](https://user-images.githubusercontent.com/22547499/104821093-1ecd9a80-57ff-11eb-87cc-accf2d33eae1.png)

**Comment by kakaroto** [comment]
Click on the "Do not send to discord" option to open the menu, then there will be a "add new channel" or something like it.

**Comment by Umbyology** [comment]
I don't want to create a NEW channel. I want to use an existing channel I already have setup.

**Comment by kakaroto** [comment]
I never said create a new channel, I said ADD channel, you need to add the channel to Beyond20 settings so it knows where to send the rolls. Beyond20 is never going to modify anything in your discord server, so it doesn't even have the ability to create a channel.
Just click where I told you to click.

**Comment by Umbyology** [comment]
Ah, I see. The wording threw mw off a bit. Got it ... seems to work great. Nice job! THX!
