### ISSUE TITLE
Chaos Bolt Damage not working

### ISSUE THREAD

**Issue by brewksy** [kakaroto/Beyond20#655]
Chaos Bolt: If the d8 damage rolls are equal, dialog box never shows up and damage roll stalls and will not be produced.  Using Foundry VTT.

**Comment by Aeristoka** [comment]
Appears specific only to FoundryVTT @kakaroto 
![image](https://user-images.githubusercontent.com/7988297/104847348-b92feb80-589c-11eb-9bd6-35a399c72298.png)

Working roll (so, the "choose from the two damage types rolled"):
![image](https://user-images.githubusercontent.com/7988297/104847380-d95faa80-589c-11eb-81d3-231f5fad3500.png)

Broken (two die rolled the same, so damage is just auto-selected):
![image](https://user-images.githubusercontent.com/7988297/104847397-f8f6d300-589c-11eb-82ee-b5ca13555f5c.png)

**Comment by Aeristoka** [comment]
@kakaroto Here it is. On the matched numbers, so damage auto selected, it ALSO does the "leaps to another close" (Chaos Bolt feature), and it is putting that into damage_rolls.

![image](https://user-images.githubusercontent.com/7988297/104847582-22fcc500-589e-11eb-9123-131de893a890.png)

**Comment by Aeristoka** [comment]
This is the line causing that issue:
![image](https://user-images.githubusercontent.com/7988297/104847961-06618c80-58a0-11eb-97b4-70b8853b5146.png)

**Comment by kakaroto** [comment]
Thanks @Aeristoka for the bug hunting and detailed report.

> @kakaroto Here it is. On the matched numbers, so damage auto selected, it ALSO does the "leaps to another close" (Chaos Bolt feature), and it is putting that into damage_rolls.
> 
> ![image](https://user-images.githubusercontent.com/7988297/104847582-22fcc500-589e-11eb-9123-131de893a890.png)

Solution is to replace : `...damage_rolls.map(d => d[1])` into `...damage_rolls.map(d =>d[1]).filter(r => !!r)`
