### ISSUE TITLE
When using Custom Damage Dice with a roll20 query, the commas are replaced with a pipe symbol

### ISSUE THREAD

**Issue by DarrynGlass** [kakaroto/Beyond20#656]
**Describe the bug**
I have entered the following into the Custom Damage Die Formula, to support a weapon I have that does extra damage to giants
?{Giant|Yes,[[2d6]][Giant]|No,  }

When I roll, the template is sent to Roll20 like this
&{template:atkdmg} {{charname=Darmin}} {{rname=Waythe}} {{mod=+8 + 0}} {{r1=[[1d20 +8+0[CUSTOM]]]}} {{attack=1}} {{damage=1}} {{dmg1flag=1}} {{dmg1=[[2d6+7]]}} {{dmg1type= Slashing}} {{crit1=Crit: [[2d6]]}} {{dmg2flag=1}} {{dmg2=**?{Giant|Yes | [[[[2d6]]]][Giant]|No | }** | [[1d8]]}} {{dmg2type=Custom | Custom | Radiant}} {{crit2=Crit: [[2d6]] | [[1d8]]}} {{normal=1}}

To make it easier to see the change

?{Giant|Yes,    [[2d6]][Giant]  |No | }                               What I entered
?{Giant|Yes | [[[[2d6]]]][Giant]|No | }              What gets sent
![image](https://user-images.githubusercontent.com/29684482/104849106-aa056980-58ad-11eb-97df-d715a46bffaa.png)

**To Reproduce**
1. Go to Custom Roll dice formula bonus
2. Enter ?{Giant|Yes, [[2d6]][Giant]  |No | }    
3. Roll a weapon attack and select Yes to the prompt

![image](https://user-images.githubusercontent.com/29684482/104849177-fb155d80-58ad-11eb-88a8-8652403412b3.png)
![image](https://user-images.githubusercontent.com/29684482/104849183-0b2d3d00-58ae-11eb-89cd-4746b3d48313.png)
![image](https://user-images.githubusercontent.com/29684482/104849198-24ce8480-58ae-11eb-817f-226b896149c6.png)

**Expected behavior**
I would expect the roll template to be this:
&{template:atkdmg} {{charname=Darmin}} {{rname=Waythe}} {{mod=+8 + 0}} {{r1=[[1d20 +8+0[CUSTOM]]]}} {{attack=1}} {{damage=1}} {{dmg1flag=1}} {{dmg1=[[2d6+7]]}} {{dmg1type= Slashing}} {{crit1=Crit: [[2d6]]}} {{dmg2flag=1}} {{dmg2=**?{Giant|Yes, [[[[2d6]]]][Giant]  |No | }** | [[1d8]]}} {{dmg2type=Custom | Custom | Radiant}} {{crit2=Crit: [[2d6]] | [[1d8]]}} {{normal=1}}
![image](https://user-images.githubusercontent.com/29684482/104849293-7a0a9600-58ae-11eb-8b81-c5a4ff7f3065.png)

**Browser Info (please complete the following information):**
 - Chrome 
 - Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by kakaroto** [comment]
The commas are used to separate damages, so you would usually do : `Hex: 1d6, some other magics: 1d4` for example. There's a pending change (#627) which would allow to detect those roll20 queries and/or escape the commas so that they are not interpreted by Beyond20 as custom damage separators.

**Comment by DarrynGlass** [comment]
Ah ok.  Thanks.  I'll close this one as you already have a issue about it.
