### ISSUE TITLE
Roll20 Purple box is back :-(

### ISSUE THREAD

**Issue by br3wm45t3r** [kakaroto/Beyond20#659]
Sometime between Thursday and Sunday something has happened to return the die roll display to the "purple box" in Roll20. Having this result in both Firefox and chrome.
I have reinstalled the extension through both the extension/app store and github methods.

**To Reproduce**
1. Go to DnD Beyond select a character
2. Open Roll20 Table
3. Click on Beyond20 roll button

**Expected behavior**
Roll comes through in the old Purple Box format - harder to read, and definitely not as pretty.

**Screenshots**
![Screenshot 2021-01-17 18 34 56](https://user-images.githubusercontent.com/12076338/104859432-5289ec80-58f3-11eb-86a9-4ccfa300ab12.png)

**Browser Info:**
 - Chrome 87.0.4280.14
 - Firefox Version 84.0.2 (32-bit)

**Comment by Aeristoka** [comment]
Go into the Roll20 Campaign settings, and verify this setting:
![image](https://user-images.githubusercontent.com/7988297/104859794-eb653b80-58e4-11eb-9f5d-9fa5a0780fa1.png)

Most likely, you changed that.

**Comment by br3wm45t3r** [comment]
You are completely right! Thank you!

**Comment by alexwynn89** [comment]
This didn't work for me sadly. I followed the steps that you outlined but I still have the purple box issue.

**Comment by Aeristoka** [comment]
> This didn't work for me sadly. I followed the steps that you outlined but I still have the purple box issue.

You're referencing an old closed issue, please reference #765
