### ISSUE TITLE
bi-directional integration with D&D beyond

### ISSUE THREAD

**Issue by jazztec** [kakaroto/Beyond20#662]
I'm creating my own VTT and I'd love to contribute to this extension.  I'm very interested to see if you'd consider adding bi-directional integration with D&D Beyond.  e.g. Rolling dice in the VTT and using D&D Beyond stats, or marking off spell slots.

**Comment by kakaroto** [comment]
Hi jazztec,
I unfortunately would not considering adding bidirectional integration with D&D Beyond. Beyond20 is complex enough as it is and having rolls on one side then grabbing the modifiers on the other side then sending it back just seems to be overly complicated with zero benefits. I've also taken in the past a stance about Beyond 20 being only a passive observer on D&D Beyond, and only doing the "parse html -> send it to the VTT", so all rolls/events are uni directional.

As for support for your own VTT, I'd suggest you read my official stance on that in the FAQ : https://beyond20.here-for-more.info/faq#can-you-add-support-for-insert-new-vtt-name

If there's anything else you need, let me know!
Thanks.
