### ISSUE TITLE
Decimal places appearing in Roll 20

### ISSUE THREAD

**Issue by BimbleBomble** [kakaroto/Beyond20#664]
Initiative rolls only from D&D Beyond going to Roll 20. All come out as a number with a decimal point, eg 10.11. Other rolls seem OK.

![Roll 20 issue](https://user-images.githubusercontent.com/77896302/105610649-8c05a080-5da8-11eb-976b-39d8ba4ab968.png)

This is seen on different characters created in D&D Beyond

I'm running windows 10 and Google Chrome browser...

**Comment by Aeristoka** [comment]
In Beyond20 Options -> More Options you have enabled "Tiebreaker Initiative"

![image](https://user-images.githubusercontent.com/7988297/105610749-75daee80-5d6e-11eb-97b3-80c301326162.png)

**Comment by BimbleBomble** [comment]
Doh! \that might be it.... Thanks very much :-)

**Comment by Aeristoka** [comment]
It's actually very useful, what it does (as it says) is add dex score as a decimal, if you have that for all Player Characters + All NPCs, then Ties in initiative are usually just broken for you already. Very handy.
