### ISSUE TITLE
Piercer Attack Roll uses Dmg Roll instead

### ISSUE THREAD

**Issue by ALDCNC** [kakaroto/Beyond20#668]
**Describe the bug**
In DNDB clicking the "Drop" button rolls the dmg instead of the attack roll.

**To Reproduce**
1. Go to https://www.dndbeyond.com/monsters/piercer
2. Click on"Drop"
3. See error: "the extension rolls the dmg roll instead of the attack. 

**Expected behavior**
Attack roll (and DMG roll) should be calculated

**Screenshots**
![Screenshot 2021-01-26 233427](https://user-images.githubusercontent.com/78094425/106012322-4c310880-6089-11eb-858d-0bfc5cf18109.png)
![Screenshot 2021-01-27 101235](https://user-images.githubusercontent.com/78094425/106012347-518e5300-6089-11eb-9f01-0ac30f97d176.png)

**Browser Info (please complete the following information):**
 - Browser Chrome
 - Version [e.g. 85] Version 88.0.4324.104 (Official Build) (64-bit). BDND: 2.3.0
 - Using Roll20.  

**Additional context**
N/A

**Comment by Aeristoka** [comment]
Confirmed, doesn't roll the attack, though there is the "+3" button assigned a Die to roll. Seems like another instance of them formatting things all over the place...
