### ISSUE TITLE
Is there a way to specify the damage types for Custom Damage Dice formula bonus?

### ISSUE THREAD

**Issue by aryairani** [kakaroto/Beyond20#669]
Currently it just says "Custom", can I Custom-ize it? e.g. 1d6 necrotic damage instead of custom?

![image](https://user-images.githubusercontent.com/538571/106323000-b17d2900-6244-11eb-9580-bf4ac6070014.png)

I did this ^, but it felt kind of cluttered.

**Comment by kakaroto** [comment]
Yes, you can enter it this way : `Necrotic: 1d8` so it shows up as Necrotic instead of Custom. If you have multiple, you can also separate them with commas, like this `Necrotic: 1d8, Hex: 1d6`

**Comment by aryairani** [comment]
Thanks!
