### ISSUE TITLE
Add +5 damage for Charger Feat as a pull down toggle

### ISSUE THREAD

**Issue by fireboy92k** [kakaroto/Beyond20#671]
From our Discord discussion:
that Feat could be implemented as a toggle like other similar things
so, if you knew you were fulfilling the requirements for the +damage, toggle it on, then roll, it would add, and toggle it back off

From me:
Suppress the 1d20 + 5 roll from the Features UI if possible as well to eliminate confusion.

**Comment by Aeristoka** [comment]
Pull request is in!
