### ISSUE TITLE
Beyond20 not displaying spell save DC on some spells on roll20

### ISSUE THREAD

**Issue by Du85x** [kakaroto/Beyond20#672]
**Describe the bug**
Hello I have my character sheets on DNDBeyond and have played with friends extensively on Roll20. Since a couple fo weeks we have noticed that when casting some spells the spell save DC is not displayed when the spell is cast. We only see the spell description displayed. 

**To Reproduce**
1. Go to 'your character sheet in dndbeyond'
2. Click on 'spells, and then cast a spell that requires a DC save (example is fear, hold person, banishment, levitate)'
3. Scroll down to 'the chat of roll 20 and see the output'
4. See error: some of the spells are not displaying the spell save DC when the spell is cast, only the spell description

**Expected behavior**
when I click to cast the spell I expect to see the spell description, spell save Dc and damage (if applicable ) displayed in the roll 20 chat

**Screenshots**
To help explain your problem, add screenshots of where you clicked in D&D Beyond, a screenshot of your Beyond20 character settings if applicable and the result you saw in the VTT.

![1](https://user-images.githubusercontent.com/78385362/106520079-13ca6980-6491-11eb-9353-23e5215b2ca0.JPG)
![2](https://user-images.githubusercontent.com/78385362/106520083-14fb9680-6491-11eb-9d3b-eaf4bb6b58f5.JPG)
![image](https://user-images.githubusercontent.com/78385362/106520167-32c8fb80-6491-11eb-9f50-c51bec921eb8.png)
![image](https://user-images.githubusercontent.com/78385362/106520190-3eb4bd80-6491-11eb-8566-ccff6efe751f.png)
![image](https://user-images.githubusercontent.com/78385362/106520215-4a07e900-6491-11eb-9fc4-9fda947cd290.png)
![image](https://user-images.githubusercontent.com/78385362/106520247-54c27e00-6491-11eb-8467-1cbf764ff0b5.png)

**Browser Info (please complete the following information):**
 - Browser [ both chrome & firefox]
 - Version [e.g. 85]
 - 
![image](https://user-images.githubusercontent.com/78385362/106520317-758ad380-6491-11eb-9b97-64d9fe3dc62a.png)

 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT

**Additional context**
Add any other context about the problem here, such as a link to the character sheet or D&D Beyond page that shows the problem.

**Comment by kakaroto** [comment]
Unfortunately, that's how Roll20's spell card is made, there is no way to display the spell save DC on it.

See the OGL sheet spell card template here : 
https://wiki.roll20.net/D%26D_5e_OGL_Roll_Templates#Spell

So Beyond20 will show it as part of an attack, but not as part of a "display spell card" event

**Comment by Aeristoka** [comment]
> Unfortunately, that's how Roll20's spell card is made, there is no way to display the spell save DC on it.
> 
> See the OGL sheet spell card template here :
> https://wiki.roll20.net/D%26D_5e_OGL_Roll_Templates#Spell
> 
> So Beyond20 will show it as part of an attack, but not as part of a "display spell card" event

ah, that is good to know

**Comment by Du85x** [comment]
ok, so it only displays the DC on attack spells, on the other ones it just reads the spell card, am I understanding that correctly?

**Comment by Aeristoka** [comment]
> ok, so it only displays the DC on attack spells, on the other ones it just reads the spell card, am I understanding that correctly?

Reads the Spell Card as it is on Beyond20 (which DOES include the Save DC), then formats it into the Roll20 Spell Card format which doesn't have a place for the Save DC.
