### ISSUE TITLE
Fey Wanderer Ranger's "Otherworldly Glamour"

### ISSUE THREAD

**Issue by TheRogueBadger** [kakaroto/Beyond20#673]
The Fey Wanderer Ranger's feature "Otherworldly Glamour" lets you add your Wisdom modifier to your Charisma checks. 
Beyond20 appears to be double dipping on this bonus, but only on skill checks.

On a basic, unskilled Charisma check with this feature my bonus is +2 from Charisma, and +4 from Wisdom for a total of +6. It works just fine with Beyond20.

However if I roll an Intimidation check (which I do not have proficiency in, so should have the same bonus) with Charisma Bonus of +2, a Wisdom Bonus of +4, Beyond20 overides this and rolls with a +10.

I am using Chrome Version 88.0.4324.104
Not sure if it matters, but I'm on Beyond20 Version 2.3.0

**Additional context**
Here's a link to the character sheet on DNDBeyond
https://ddb.ac/characters/39351747/aRNfMK

Screenshot below if it's useful.
![image](https://user-images.githubusercontent.com/78441263/106649551-5e161e00-6557-11eb-8b93-1e52becdc792.png)

**Comment by Aeristoka** [comment]
yep, this is known, I thought there was an Incident for it already, but thanks for bringing it back to mind!

**Comment by TheRogueBadger** [comment]
Sorry for double posting then, I tried searching first but I didn't see anything. Probably user error, never used Github before.

**Comment by Aeristoka** [comment]
> Sorry for double posting then, I tried searching first but I didn't see anything. Probably user error, never used Github before.

oh no, you're good, there IS NOT another issue for it (for some reason), it was discussed in the Discord. I'll use this one for tracking purposes and thanks again.

I think this was the result of a recent DnDBeyond change, as when I initially tested it didn't double-dip. The PR for this will just be pulling out a small part of the code I wrote for this originally (to remove the double-dips).

**Comment by TheRogueBadger** [comment]
Ah I gotcha, looking forward to a fix in the future then! Really appreciate what you guys are doing here. Its made transitioning from in person to online during the pandemic _so_ much easier!

**Comment by Aeristoka** [comment]
Pull request is in!

Looking back, I swear it was DnDBeyond was not handling it, so I added it to Ability Checks + Skill checks, and then they added it later (so my code for Skill Checks became redundant with the DnDBeyond implementation).

**Comment by Aeristoka** [comment]
> Just checked this today in Foundry, and noticed this is still an issue for skill checks.
> 
> Testing:
> 
> * On proficient skills, Beyond 20 adds the wisdom bonus twice.  (displayed skill bonus plus wisdom modifier)
> * On non-proficient skills, Beyond 20 adds the wisdom bonus twice.  (displayed skill bonus plus wisdom modifier)
> * On Charisma checks-not rolling a specific skill check- Beyond 20 correctly adds the wisdom bonus _once_

Can you open a NEW issue for this please?

I believe this is same as above, DnDBeyond slowly implementing things we'd covered for months or longer in Beyond20.
