### ISSUE TITLE
DDBeyond site not correctly recognized on chrome since few hours

### ISSUE THREAD

**Issue by SirBigoo** [kakaroto/Beyond20#674]
Hello ! 

**Description**
I started using this incredible tool today, and it worked like a charm on my chrome.
The problem is since a few hours, it seems ddbeyond website is not correctly recognized : 

![image](https://user-images.githubusercontent.com/17948077/106663643-4913ac00-65a4-11eb-8d56-5db16b05ef66.png)

A few hours ago, I had click buttons on hit / damages and now nothing appears. I tried with firefox, and it works as expected and as it was later off : 
![image](https://user-images.githubusercontent.com/17948077/106663738-6cd6f200-65a4-11eb-9d6f-99facd940aa9.png)

I tried to reinstall plugin, same problem.

**To Reproduce**
1. Go to ddbeyond website with plugin
2. Parse your sheet click Feats / Traits
3. Go on attack or spell : no more button

**Expected behavior**
We should have clickable buttons on hit / damages...

**Browser Info (please complete the following information):**
 - Browser chrome
 - Version Version 87.0.4280.88 (Official Build) (64-bit)
 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT

**Additional context**
Maybe there was an update on ddbeyond side ? I did not change anything on my computer (or I suppose...)

**Comment by Aeristoka** [comment]
Are you referring to these places?
![image](https://user-images.githubusercontent.com/7988297/106664574-78092e00-6562-11eb-9df3-d56280a67e26.png)

Because those are DnDBeyond Digital Dice click areas, not Beyond20 click areas.

**Comment by SirBigoo** [comment]
Oh, ok I didn't noticed that those are DDBeyond buttons ! After re-enabling DDBeyond dices, it's ok. So buttons are DDBeyond stuff, not plugin injection :) 

Thanks for clarification !

**Comment by Aeristoka** [comment]
Yep, with DnDBeyond Digital Dice disable, click the "Crossed Swords" to the left of the Action, or the "Cast" button on spells.
