### ISSUE TITLE
Guidance HotKey not Working

### ISSUE THREAD

**Issue by Tucker2343** [kakaroto/Beyond20#675]
Good Day! 

I setup a hotkey for Guidance, but whenever I roll it just shows a zero for the result. Just wanted to give you a heads up on this issue. 

![Guidance](https://user-images.githubusercontent.com/15664374/106686637-44dd9380-6590-11eb-972e-3ad0b35276bd.png)
![Guidance2](https://user-images.githubusercontent.com/15664374/106686727-77878c00-6590-11eb-94e2-7f9acf4f0ead.png)
![Guidance1](https://user-images.githubusercontent.com/15664374/106686729-77878c00-6590-11eb-81d6-299885a2ca99.png)

**Comment by DarrynGlass** [comment]
This is a known issues (See this issue.  https://github.com/kakaroto/Beyond20/issues/636).  To work around it, put a zero in the Custom Roll dice formula bonus.  It will "fix" the problem for now.
![image](https://user-images.githubusercontent.com/29684482/106694012-4a8da600-659d-11eb-976e-6da4d144cb3a.png)
