### ISSUE TITLE
When rolling with Beyond20 rolls show up incorrect in the Game Log

### ISSUE THREAD

**Issue by buethling** [kakaroto/Beyond20#677]
I know that the Game Log is a brand new feature in D&D Beyond, but when rolling (using Beyond20) a monsters/player attacks rolls or ability checks or pretty much anything, the rolls show up in the Game Log as everything summed together. 

I know that this is not the intended purpose of the plugin but it would be nice to have rolls show up correctly in the game log and ideally it would be nice to be able to toggle the feature on or off since I may want to hide the rolls from players.

**Comment by kakaroto** [comment]
The Game Log is a D&D Beyond feature, so we don't have control over what shows up in there, but I believe that's things that you can control as a DM. If you don't want anything to show up there though, you can disable the "Use Digital Dice" option in Beyond20 and it won't.
I'm looking into getting them to show up correctly though, as Beyond20 rolls are all considered as custom rolls when it uses the digital dice.

**Comment by buethling** [comment]
Awesome! Thanks for that tip as well.

**Comment by kakaroto** [comment]
Closing as this is now fixed with the #727 issue being fixed.
Example output of how it would look in 2.5
![image](https://user-images.githubusercontent.com/27990/132779151-b7f80994-c6c9-469d-a46b-3eb5ae981dbb.png)

**Comment by buethling** [comment]
Awesome, looking forward to this!
