### ISSUE TITLE
Foundry's "Apply damage" is now applying the sum of all attack+dmg rolls

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#683]
> This roll applied 73 damage (the sum of the upper portion: the attack roll and all individual damage amounts)
![image](https://user-images.githubusercontent.com/27990/106869755-4b5a3100-669e-11eb-873d-10ca4e30dc5b.png)

This one applied 43
![image](https://user-images.githubusercontent.com/27990/106869805-5b721080-669e-11eb-863f-05a9f2652f91.png)

**Comment by cojoMan** [comment]
I can confirm, don't know when this changed - or if it was the system I was using (DnD5e) - or a setting/addon I took for granted. At Aeristoka's suggestion, the "chat damage buttons" seem to help, but there is an issue when the monster name and attack are hidden. Will open a separate issue.
