### ISSUE TITLE
Polearm Master Feat Bonus Action + Warlock Hex Weapon?

### ISSUE THREAD

**Issue by aryairani** [kakaroto/Beyond20#685]
> **Polearm Master - Bonus Attack**
> When you take the Attack action with a glaive, halberd, quarterstaff, or spear, you can use a bonus action to make a melee attack with the opposite end of the weapon that uses the same ability modifier as the primary attack and has a damage die of d4 (bludgeoning).

![image](https://user-images.githubusercontent.com/538571/107108041-364ae280-6803-11eb-827e-3b624108ec98.png)

![image](https://user-images.githubusercontent.com/538571/107108035-2e8b3e00-6803-11eb-9565-e383fc580e35.png)

Is there some way that I can get this attack with my Hex Warrior feature to use my CHA modifier for damage?  And is the To Hit modifier right, or should it be +8 also?

Thanks!

**Comment by aryairani** [comment]
Or.. wait.. is this a D&D Beyond bug, I guess?

**Comment by Aeristoka** [comment]
This is a DnDBeyond bug.
