### ISSUE TITLE
Add hot key action "Roll damage for critical"

### ISSUE THREAD

**Issue by kyrious** [kakaroto/Beyond20#687]
There does not seem to be a way to just roll critical damage separately by itself.

Usecase: When rolling for Hit and for Damage separately, by using the areas below, 
![image](https://user-images.githubusercontent.com/16724955/107399864-8676bd00-6b01-11eb-9806-6a2233c85387.png)
one can only roll critical damage using the "Always force crit"-option or the "Roll hit and damage at the same time"-area.

If there is a hot key action, you could switch for critical damage in an instant, that one time it comes up during a session.

**Comment by Rarst** [comment]
Sounds related #768

**Comment by Aeristoka** [comment]
Closing as duplicate of #768 (more discussion over there).
