### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by kberger225** [kakaroto/Beyond20#688]
s there a way to use Beyond20 when using the Chrome app on iOS?  I DM for my kids and their friends and I want to move them to a VTT like Roll20 using DND Beyond but 3 of them do not have computer access and have ipads instead.  They have been enjoying the old fashioned way (via zoom) but being able to share maps and have them move tokens would really enhance the experience and Beyond 20's integration is fantastic.  

Sorry if a dumb question/been answered before.

**Comment by kakaroto** [comment]
Unfortunately, Apple puts strict restrictions that doesn't allow "non authorized" software to run on iOS, this includes removing the support to have extensions within any of the browsers.

**Comment by kberger225** [comment]
thanks
