### ISSUE TITLE
Sync Temporary hit points

### ISSUE THREAD

**Issue by Borgczar** [kakaroto/Beyond20#69]
Regular HP syncs fine, but temp hp do not sync.

**Comment by rcozmyer** [comment]
On the FAQ page (https://beyond20.here-for-more.info/faq#my-hp-from-dd-beyond-doesnt-synchronize-to-my-tokens), it says to use the field name "temp_hp" instead of "hp_temp"

**Comment by Aeristoka** [comment]
> On the FAQ page (https://beyond20.here-for-more.info/faq#my-hp-from-dd-beyond-doesnt-synchronize-to-my-tokens), it says to use the field name "temp_hp" instead of "hp_temp"

That needs to be updated on the page then @kakaroto

**Comment by kakaroto** [comment]
Ah, that explains why so many use hp_temp instead of temp_hp.. it's because the FAQ was misleading them! 🤦‍♂️
