### ISSUE TITLE
Beyond20 replaced icon replaced with html

### ISSUE THREAD

**Issue by CoolBastard** [kakaroto/Beyond20#691]
While in DNDBeyond, I notice that the Beyond20 icon is replaced with code when looking at character sheets in the campaign I run. 
https://imgur.com/a/fcQzZAj

I'm not sure how to produce the effect. 

I removed the app and reloaded it, but the issue persists.

Browser is Firefox 84.0.

**Comment by Aeristoka** [comment]
That's caused by some other browser extension most likely.

**Comment by CoolBastard** [comment]
> That's caused by some other browser extension most likely.

SONOFABITCH!! You were right! Ti was the "Beyond The Spire" extension that was screwing me up. I never even considered an extension being the culprit. I disabled it and DNDB works like a charm! Thank you!!!

**Comment by kakaroto** [comment]
Thanks for filing it here and awesome detective work @Aeristoka and @CoolBastard ! 👍
