### ISSUE TITLE
"Chat Damage Buttons" addon missing out on hidden attack rolls.

### ISSUE THREAD

**Issue by cojoMan** [kakaroto/Beyond20#693]
In the chrome plugin setting, if you have the "hide monster and attack name" set into the "whisper monster roll" category, the chat damage buttons do not trigger.

**To Reproduce**
- enable CDB addon in foundry
- set Whisper Monster Rolls to "General..." - roll an attack
- set Whisper Monster Rolls to "Hide..." - roll an attack

**Expected behavior**
- chat damage buttons to appear in both cases above. Instead, only on the non-hidden rolls do they appear.

**Screenshots**
The arrow points at each box the mouse cursor was hovering with the two situations above :
![s1](https://user-images.githubusercontent.com/4105124/108105478-86b31300-7041-11eb-9def-b607cd3f56e5.png)
![s2](https://user-images.githubusercontent.com/4105124/108105483-874ba980-7041-11eb-8fee-4775cdcef9ea.png)

**Browser Info (please complete the following information):**
Chrome Version 88.0.4324.150 (Official Build) (64-bit)

**Comment by Aeristoka** [comment]
@kakaroto Related to #663 I believe
