### ISSUE TITLE
Some tools do not get the "use tool" prompt

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#698]
https://www.dndbeyond.com/forums/d-d-beyond-general/general-discussion/38455-beyond20-integrating-d-d-beyond-with-roll20?page=25#c490

Brewer's supplies, Forgery Kit, Herbalism Kit and Poisoner's Kit.

**Comment by jasondashaer** [comment]
Cook's Utensils is also missing

**Comment by kakaroto** [comment]
> Cook's Utensils is also missing

oh, you posted that after I had fixed it for the others. Thanks, reopening.

**Comment by jasondashaer** [comment]
Doublechecked on Discord what DND Beyond items were left to add/fix. https://discordapp.com/channels/578874022968688640/579077147994488862/823713655652483102

Rhythm-Maker’s Drum, +3
Rhythm-Maker’s Drum, +2
Rhythm-Maker’s Drum, +1
All-Purpose Tool, +3
All-Purpose Tool, +2
All-Purpose Tool, +1
Travel Alchemical Kit
Dice Set
Dragonchess Set
Playing Card Set
Three-Dragon Ante Set
Wagon
