### ISSUE TITLE
Feature request to add a toggle for when beyond20 broadcasts to the VTT 

### ISSUE THREAD

**Issue by Gershwin12** [kakaroto/Beyond20#700]
Sometimes on dndbeyond while making characters, I roll dice to break in a character, and those rolls do not need to be sent to the rest of my party and I can see no way to temporarily disable that.

**Comment by Aeristoka** [comment]
> Sometimes on dndbeyond while making characters, I roll dice to break in a character, and those rolls do not need to be sent to the rest of my party and I can see no way to temporarily disable that.

There is already an option for this in the "More Options" section.
