### ISSUE TITLE
Shift/ctrl/alt does not modify rolls

### ISSUE THREAD

**Issue by bskizzle** [kakaroto/Beyond20#703]
**Describe the bug**
When clicking on a roll button or quick roll area, holding shift/ctrl/alt has no effect on the roll. The roll icon does not change, and the roll shows up in Roll20 chat as a normal roll. This issue persists across all of my character sheets. I am using the "normal roll" option and digital dice are disabled. I dug through a few similar bug reports but none of the proposed fixes worked. EDIT: I am using the latest version (2.3.0) of Beyond20.

**Expected behavior**
1. Hold shift/ctrl/alt
2. Click on roll button/quick roll area
3. See icon change to desired roll
4. See roll modified in Roll20

**Screenshots**
![Screenshot 2021-02-28 at 7 54 58 PM](https://user-images.githubusercontent.com/79816131/109440155-35226500-79ff-11eb-9bdf-43368cd23cdd.png)
![Screenshot 2021-02-28 at 7 55 24 PM](https://user-images.githubusercontent.com/79816131/109440179-466b7180-79ff-11eb-9d4f-0a78f010b334.png)
![Screenshot 2021-02-28 at 7 55 40 PM](https://user-images.githubusercontent.com/79816131/109440185-4a978f00-79ff-11eb-87cd-671421c1dedd.png)

**Browser Info (please complete the following information):**
 - Browser: Chrome
 - Version 88.0
 - Running on Chrome OS

**Comment by Aeristoka** [comment]
Working perfectly fine here, and has since it was added.

Important note: You have to have the window FOCUSED for this to work (ie, you have to have clicked on the DnDBeyond page somewhere (not a quick roll area) for the Shift/CTRL/Alt to work.

**Comment by bskizzle** [comment]
I have the window focused, still nothing.

**Comment by Aeristoka** [comment]
> I have the window focused, still nothing.

Try to remove/re-install the extension, otherwise, try to look at the Dev console for errors. All the other reports of issues like this were never substantiated with any useful data as to how things may or may not have actually gotten into that situation.

**Comment by bskizzle** [comment]
I've got no idea what any of this means, but I'm seeing two identical errors. Something about a map? I tried reloading the page and it still shows up.
![Screenshot 2021-02-28 at 8 50 48 PM](https://user-images.githubusercontent.com/79816131/109442615-b92c1b00-7a06-11eb-89d0-a729b42c3b54.png)

**Comment by Aeristoka** [comment]
None of that is errors, errors will appear in Red.

**Comment by Aeristoka** [comment]
Try actually screenshotting where you're clicking for me.

**Comment by kakaroto** [comment]
Can you click on the 'set hotkeys' button in the full settings of Beyond20 and confirm that the shift/alt/ctrl hotkeys are still defined there to act for advance/normal/disadvantage? Also check if there might be another extension installed that may be interfering with the hotkey. That's the only things I can think of at the moment, as to why it wouldn't work for you.

**Comment by Aeristoka** [comment]
![image](https://user-images.githubusercontent.com/7988297/109443132-02746e80-79f7-11eb-92db-cfa60451a448.png)

This is the section @kakaroto is referencing

**Comment by bskizzle** [comment]
Well, I feel like a mighty fool... I must've deleted those at some point. I set them up again and it's now working fine.

**Comment by kakaroto** [comment]
There you go! I fixed your bug! 😁 
Glad it's all working out now! 👍
