### ISSUE TITLE
FVTT 0.8.0 compatibility

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#704]
FVTT 0.8.0 doesn't seem to use the same data for rolls so it's broken when we call `roll.fromData`

**Comment by Aeristoka** [comment]
https://gitlab.com/foundrynet/foundryvtt/-/issues/4820 Might be of use.

**Comment by kakaroto** [comment]
fixed in https://github.com/kakaroto/Beyond20/commit/702082f4c9a1dafa53f36cb3caf1dd08ea9a5d33
