### ISSUE TITLE
off/next roll/ask/always for Great Weapon Master (maybe others?)

### ISSUE THREAD

**Issue by somedamnthing** [kakaroto/Beyond20#705]
I keep forgetting to go into settings to toggle Great Weapon Master. Can we replace "off/next roll" with "off/next roll/ask/always"?

This would be similar to the existing d20 'type of roll', and could be used in any other feats with similar toggles.

**Comment by Aeristoka** [comment]
It is working Rules As Written.

Best way to accomplish what you want is to customize a weapon(s). to be your GWM stuff.
