### ISSUE TITLE
Incorrect addition of skills on dndbeyond. Bug

### ISSUE THREAD

**Issue by Genopoly** [kakaroto/Beyond20#707]
I have created a fey wonderer ranger and i get +3 to charisma due to outwardly glamor. Dndbeyond shows correct (+7/+5) for Charisma stats in skills (Deception, Intimidation, Performance, Persuasion). However when I click to roll the dice it gives it additional +3 (+10/+8). When I deactivate Beyond20 it rolls correctly, but through the extension it rolls incorrectly. 

So in game I dave to deduct 3 from the total roll. Is there a fix for this? 

Thank you,

<img width="273" alt="Screen Shot 2021-03-03 at 5 16 08 PM" src="https://user-images.githubusercontent.com/80554319/111011497-a0592900-8367-11eb-99db-3b75acae3aa7.png">

<img width="501" alt="Screen Shot 2021-03-03 at 5 16 39 PM" src="https://user-images.githubusercontent.com/80554319/111011506-a7803700-8367-11eb-88b3-951a11c4b55b.png">

**Comment by Aeristoka** [comment]
This is already fixed in dev: https://github.com/kakaroto/Beyond20/pull/679

https://github.com/kakaroto/Beyond20#developer-mode-installation

**Comment by Genopoly** [comment]
Thank you. It works now.

**Comment by Aeristoka** [comment]
> Thank you. It works now.

Official release soon hopefully.
