### ISSUE TITLE
Not recogizing open sidebar when changing themes.

### ISSUE THREAD

**Issue by MaienM** [kakaroto/Beyond20#710]
**Describe the bug**

While changing themes I occasionally get a dialog saying "Not recognizing the currently open sidebar".

**To Reproduce**
1. Go to the settings.
2. Click on 'Change Theme'.
3. Switch between themes. May take multiple tries.
4. See error.

**Expected behavior**

I would expect to not get an error.

**Screenshots**

![2021-03-18-171234_1063x1576_scrot](https://user-images.githubusercontent.com/583129/111659063-316b4c80-880d-11eb-84de-faffa98e6a65.png)

**Browser Info:**
 - Firefox 86.0 (64-bit)

```
Beyond20: New side panel is : ct-character-manage-pane dndbeyond_character.js:6874:21
Beyond20: New side panel is : ct-theme-pane dndbeyond_character.js:6874:21
Beyond20: New side panel is : ct-theme-pane 3 dndbeyond_character.js:6874:21
Beyond20: New side panel is : ct-theme-pane 2 dndbeyond_character.js:6874:21
Beyond20: New side panel is : ct-theme-pane 2 dndbeyond_character.js:6874:21
EXECUTING QUICK ROLL! dndbeyond_character.js:6837:13
Beyond20: Executing panel : ct-theme-pane false false dndbeyond_character.js:6155:13
Beyond20: Displaying panel : ct-theme-pane dndbeyond_character.js:6191:13
Beyond20: New side panel is : ct-theme-pane dndbeyond_character.js:6874:21
```

**Additional context**

Doesn't seem to be character specific.

**Comment by Aeristoka** [comment]
Got any actual data for this bug?

**Comment by MaienM** [comment]
Yeah sorry, accidentally pressed enter before I was done. Updating it now.

**Comment by Aeristoka** [comment]
> Yeah sorry, accidentally pressed enter before I was done. Updating it now.

No worries, it was just funny to see the entire template come through with absolutely nothing 😂

**Comment by DarrynGlass** [comment]
Yeah I just caused it to happen.  Took two tries is all.  All I did was click on one new theme, then another and the error appeared.  Didn't affect any functionality though.

**Comment by MaienM** [comment]
I only just noticed this (for some reason this isn't visible when I have the page open in a portrait layout on my side monitor), but hovering over the center number shows the rolling tooltip. Clicking while this is up seems to consistently trigger the error, and clicking while it is not up seems to consistently avoid it. So I guess the problem might just be that it sees the theme preview elements as attributes and lets you roll on them?

![2021-03-20-125305_94x132_scrot](https://user-images.githubusercontent.com/583129/111868713-c9874400-897b-11eb-8a60-971f396483e6.png)

**Comment by kakaroto** [comment]
I can't reproduce this. I know I tried a while back too and couldn't.. not sure if this got fixed or I'm doing something wrong....

**Comment by MaienM** [comment]
I can still reproduce this, both with the latest release and when loading the master branch as a temporary addon, so I don't think it's been fixed.

The only thing I can think of is that it does depend on your used settings; it doesn't happen when 'Add Quick Roll Areas' is turned off, not sure about what other settings might affect it (if any). Could that be why you're having trouble reproducing it?

**Comment by kakaroto** [comment]
Nope, I have quick roll areas turned on, so it should reproduce... I don't know. The repro steps haven't changed, right? go to change theme and change it multiple times until at some point, the dice appears on hover of those theme examples? 
I tried with tablet, mobile and desktop mode, I tried to hide/show the side panel, nothing seems to help me get it to happen on my side.
I tried both chrome and firefox, even though the browser here shouldn't matter for this kind of behavior... I have no idea at this point 🤷

**Comment by MaienM** [comment]
I don't need to switch multiple times, the dice appear consistently for me when I hover over the text in the centre.

![Peek 2021-06-01 15-36](https://user-images.githubusercontent.com/583129/120332539-22b21300-c2ef-11eb-802c-8a0d0edea5d5.gif)

**Comment by kakaroto** [comment]
ahhhhh, finally managed to reproduce this. The trick was : need to disable the digital dice!
