### ISSUE TITLE
Digital dice anchored top left when Beyond20 enabled

### ISSUE THREAD

**Issue by escapismc** [kakaroto/Beyond20#714]
When rolling with Beyond20, the digital dice are anchored in the top left, with a heavy down/right roll pattern.  Dice often land underneath the popups in the bottom right corner making it hard for the player to see their dice results (without looking in vtt chat windows).  With Beyond20 disabled, the dice roll from many different start locations and in different directions.

Browser: Chrome Version 89.0.4389.82 (Official Build) (64-bit)
Beyond20: 2.3.0

**Comment by kakaroto** [comment]
Beyond20 does not affect where the digital dice are being rolled from in any way, we simply generate fake clicks on the floating custom dice buttons in the bottom-right of the screen to ask D&D Beyond to roll dice for us, then we parse the results as shown in the screen.
The issue of the dice hiding underneath the notification is a D&D Beyond issue which I've seen reported a few times and I spoke with the D&D Beyond team about it and they are aware of it. Both the dice rolling and the notification in the bottom right corner are from D&D Beyond itself, and unrelated to Beyond20.
