### ISSUE TITLE
Demiplane integration

### ISSUE THREAD

**Issue by dmeese** [kakaroto/Beyond20#717]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

Would like to pass rolls to Demiplane as a common log

**Describe the solution you'd like**
Pass rolls generally treat Demiplane as a VTT- similar to what we get with Discord 

**Describe alternatives you've considered**

Currently using dnd beyond, roll20, Zoom, Beyond20. Would like to drop zoom and use chat log from demiplane. 

**Additional context**

**Comment by Aeristoka** [comment]
I'll leave it to @kakaroto to answer completely, but I'll refer you here for a possible answer: https://beyond20.here-for-more.info/faq#can-you-add-support-for-insert-new-vtt-name

**Comment by dmeese** [comment]
Thanks.  Should have checked that before I submitted.

**Comment by kakaroto** [comment]
Closing as a won't fix. This might also be superceded by #833
