### ISSUE TITLE
[Question] Release Publish Plans?

### ISSUE THREAD

**Issue by kdelorey** [kakaroto/Beyond20#726]
I've noticed the latest release (@da549b2591cfe4c13e1e68c2081c1c278e449405) contains some fixes that my group is interested in having but it hasn't been pushed to the chrome webstore. Are there any plans to push the release to the chrome web store?

**Comment by Aeristoka** [comment]
> I've noticed the latest release (@da549b2591cfe4c13e1e68c2081c1c278e449405) contains some fixes that my group is interested in having but it hasn't been pushed to the chrome webstore. Are there any plans to push the release to the chrome web store?

It will in due time, there are more things to get fixed up before 2.3.1 is officially pushed, you can watch the Milestone for 2.3.1 here: https://github.com/kakaroto/Beyond20/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.3.1
And install the dev version following this: https://github.com/kakaroto/Beyond20#developer-mode-installation

**Comment by kakaroto** [comment]
I'll just add that the plan is get this done and released before the end of the month. Let's 🤞 that I don't miss this deadline once more!
