### ISSUE TITLE
Hook into the game log message broker directly

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#727]
Would allow overriding the 'custom' for beyond20 rolls for example, but would require using a page script to hook into the message broker

**Comment by Aeristoka** [comment]
> If I'm understanding this open issue correctly, it seems like implementing it would also open up Beyond20 to be able to read new messages/dice rolls added to the game log remotely by other players and/or the DM.
> 
> That would be especially good right now, as more and more people will be transitioning their online games back to in-person ones - especially now that DnDBeyond has added rolling functionality to their mobile app.
> 
> For example, if I were DMing a game in person with my DnDBeyond Campaign entry open in a browser "behind the DM screen," I'd be able to see the results of rolls my players were making on their phones. If I also had a VTT open on a second display to display a scene or battle map, it would be amazing if Beyond20 could be automatically reading the DnDBeyond Campaign log updates and sending them to the VTT, even though many of the rolls aren't being triggered by local browser interactions. It would effectively make Beyond20's supported VTTs equally good for managing both online and in person gaming without the DM or players needing to make many configuration changes.
> 
> Getting that functionality together would also improve the UX for first time TTRPG players, in person or online, because it would give the DM a way to remove one of the "getting you set up" steps; only the DM would NEED to be running Beyond20.

That's not the intention. The intention is to have it push rolls nicely into the GameLog

**Comment by kakaroto** [comment]
Yeah, that's not the intention. The purpose of the game log hook would be to clean up the **sent** roll message, not to parse incoming ones. What you're asking for can already be done on Foundry VTT using the "D&D Beyond Gamelog" module : https://foundryvtt.com/packages/ddb-game-log
You're not the first to request this, but it's not something I'm interested in doing in Beyond20, and Beyond20 isn't only about rolling the to hit and the damage, it does more than that, which your players would not get if they didn't use the extension.

**Comment by Preposthumous** [comment]
Oh, okay! That's super reasonable. Beyond20 does indeed do much much more than simply report to-hit rolls to a VTT. Thanks for the link to that game module! It seems like you've had a complicated week, so I particularly appreciate the individual help. I've bumped my sub up from Experienced Player to DM ^_^
