### ISSUE TITLE
Missing `0.7` and `0.8` git tags

### ISSUE THREAD

**Issue by robert-w-gries** [kakaroto/Beyond20#73]
I was looking to run the `0.8` release in developer mode, and I noticed that the latest available release through Github is `0.6`.  It'd be nice to have the git tags for `0.7` and `0.8` to quickly grab a zip of those releases.

In the meantime, I can run off of `master`, so it's not a high priority issue for me.

**Comment by kakaroto** [comment]
Thanks! I forgot to push the tags. Done now! :)
master just has a small fix from 0.8, so you should be good to go using master.
