### ISSUE TITLE
Great weapon fighting style issue

### ISSUE THREAD

**Issue by JustinMcDonald07** [kakaroto/Beyond20#730]
When rolling damage with the great weapon fighting style it doesn't seem to reroll both dice when using a greatsword. 2d6 rolling a 1 and 2 it rolls only one additional d6.

![bugreport](https://user-images.githubusercontent.com/81462257/112714267-d8e42100-8e96-11eb-8cfe-572af1b86be9.png)

**Comment by Aeristoka** [comment]
It's working precisely Rules as Written: 
```
Great Weapon Fighting
When you roll a 1 or 2 on a damage die for an attack you make with a melee weapon that you are wielding with two hands, you can reroll the die and must use the new roll, even if the new roll is a 1 or a 2. The weapon must have the two-handed or versatile property for you to gain this benefit.
```

![image](https://user-images.githubusercontent.com/7988297/112723180-e4edd400-8ed2-11eb-9392-b64c0d3b210c.png)
What you're seeing on Roll20 is a 2 rerolled into a 1, which was kept, Rules as Written. You can see the same from my screenshot above (just on DnDBeyond).

**Comment by Aeristoka** [comment]
And a Roll20 Example of a 1 and 2 from the same damage roll both rerolled, both ending up being 3s:
![image](https://user-images.githubusercontent.com/7988297/112723311-62194900-8ed3-11eb-8f63-eba6abebe6e7.png)

**Comment by JustinMcDonald07** [comment]
That makes sense now. Sorry! It was pretty late at night I was confused. This tool is an amazing resource as the roll20 setup is less than ideal for someone used to DnD beyond.

**Comment by Aeristoka** [comment]
> That makes sense now. Sorry! It was pretty late at night I was confused. This tool is an amazing resource as the roll20 setup is less than ideal for someone used to DnD beyond.

Yeah, Roll20 is less than idea for a lot of reasons. Get your DM to move to FoundryVTT, or even better FoundryVTT hosted on The Forge (KaKaRoTo's hosting service) 😄 https://forge-vtt.com/
