### ISSUE TITLE
Ring of Protection bonus not applied to death saving throws

### ISSUE THREAD

**Issue by Ryan-Raimondo** [kakaroto/Beyond20#732]
**Describe the bug**
Ring of Protection: You gain a +1 bonus to AC and saving throws while wearing this ring.

Similar to the issue described here: https://github.com/kakaroto/Beyond20/issues/612 , Ring of Protection does not apply the +1 when clicking to roll a death saving throw.

**To Reproduce**
1. Equip and attune a Ring of Protection
2. Roll a death save with Beyond20
3. Notice that no bonus is applied

**Expected behavior**
 With an attuned Ring of Protection equipped, a +1 bonus is applied to all saves, including death saves.

**Comment by Aeristoka** [comment]
This could be implemented by Beyond20 likely, but should probably also be requested with DnDBeyond themselves.
