### ISSUE TITLE
Roll 20 OGL Detection Purple Box - March 2021

### ISSUE THREAD

**Issue by amenokos** [kakaroto/Beyond20#739]
It appears that Roll20 might have made changes again that broke the detection of the OGL sheet. Instead of the normal display of your roll, it has the box with the purple-colored header.

1. Go to your character sheet in D&D Beyond.
2. Launch a D&D 5e game on Roll20.
2. Click on any weapon attack or cast a spell
4. See how the roll is displayed on the game log in Roll20.

**Browser Info (please complete the following information):**
 - Chrome Version 89.0.4389.95 (Official Build) (64-bit)
 - No Dev Console errors generated

**Comment by Aeristoka** [comment]
Already fixed in Dev: https://github.com/kakaroto/Beyond20/commit/73a122f7e5b405207509ba666a4aa479a2e948a4

https://github.com/kakaroto/Beyond20#developer-mode-installation

Release soon.

**Comment by amenokos** [comment]
Thank you, @Aeristoka .

**Comment by Aeristoka** [comment]
> Thank you, @Aeristoka .

The way KaKaRoTo described the fix, it sounded almost like Roll20 messed up a code push. Both the old and new detection methods are still in the code, so if they revert, Beyond20 is still covered.

**Comment by amenokos** [comment]
That's good to hear. I used the development version the last time this happened (before 2.3.0 was released). I'm hoping that Roll20 will revert their changes before next Sunday. I'd rather it weren't necessary for my players to have to install the development version.

**Comment by Aeristoka** [comment]
> That's good to hear. I used the development version the last time this happened (before 2.3.0 was released). I'm hoping that Roll20 will revert their changes before next Sunday. I'd rather it weren't necessary for my players to have to install the development version.

Beyond20 release will hopefully be tonight/tomorrow.
