### ISSUE TITLE
Toggles for Custom Rolls and Custom Damage

### ISSUE THREAD

**Issue by OrbitalBliss** [kakaroto/Beyond20#745]
**Is your feature request related to a problem? Please describe.**
To turn off Custom Rolls/Damage we need to delete them and re-enter them later.

**Describe the solution you'd like**
You could add the ability to store several Entries/Formulas, similar to how Discord servers are handled.

**Describe alternatives you've considered**
You could just put a Toggle switch right beside the Entry Box to enable diable what's in the box. Which is probably what I'd do.

**Comment by kakaroto** [comment]
It's not specifically a toggle for the custom modifier/damage fields, but it's the ability to add a custom modifier/damage and tie it to a hotkey. This would allow for having multiple different custom formulas that can be enabled independently
