### ISSUE TITLE
hotkeys list doesn't update after changing the settings

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#746]
The hotkeys list in the character sheet does not update its list of hotkeys when changing the settings using the cog button on the hotkeys list

**Comment by Stoneguard001** [comment]
I'm not sure this is the best solution, but you can fix this with the follow code changes in hotkeys.js, replace lines 132-133 with the code below. It resolves two issues: updating key_bindings, which is used in promptHotkeyManager, and it updates the settings for the in-memory global variable.

        key_bindings = await promptHotkeyManager();
        mergeSettings({"hotkeys-bindings": key_bindings});
        settings['hotkeys-bindings'] = key_bindings;

**Comment by kakaroto** [comment]
Yeah, thanks, but there's a bigger issue here that `mergeSettings` isn't getting our own settings merged automatically. It should merge, then call saveSettings and once saved, it should update the `settings` variable automatically. It's not doing that, and that's the issue I need to fix, because the `hotkeys-bindings` isn't the only thing being modified via `mergeSettings`.
Finding that settings issue is what I want fixed by this github issue

**Comment by Stoneguard001** [comment]
Yeah, I looked at the setSettings function - which is different in common/settings.js and commons/roll_renderer.js - and noticed that it had a callback function that was not being passed in, but I wonder if it is passed in anywhere (I can't quickly find where it is). It does appear that updateSetttings is being called a lot of places. I also noticed even with settings being updated, the promptHotkeyManager is not passed a parameter in hotkeys.js, so it reverts to using key_bindings, even if the settings variable is up to date. 

Anyway, that was my takeaway. I did not understand this issue referred to a larger problem with mergeSettings, so feel free to ignore my comments.

**Comment by kakaroto** [comment]
Ah, found the issue. 
If you see where `mergeSettings` is used elsewhere : https://github.com/kakaroto/Beyond20/blob/5b53c84743076ba84b3695faa1e8534ce42210ea/src/common/roll_renderer.js#L26-L34
and https://github.com/kakaroto/Beyond20/blob/5b53c84743076ba84b3695faa1e8534ce42210ea/src/dndbeyond/base/character.js#L382-L393
It's not meant to update the settings on its own, it's something that is done in the callback. I was confusing `mergeSettings` with `mergeCharacterSettings`. So yeah, just needed to add a callback to do what needed to be done. 👍
