### ISSUE TITLE
Doesn't send rolls modified by hotkeys

### ISSUE THREAD

**Issue by authyrtyr** [kakaroto/Beyond20#749]
**Describe the bug**
If a roll is modified using a hotkey (ie Adding a d4 to a roll) then the digital dice rolls in D&D Beyond but nothing gets sent to Roll20. This behavior began with the new update today. Everything works as expected if I don't use the modifying hotkey

**To Reproduce**
1. Go to Beyond20 options -> Define Custom Hotkeys, and create a hotkey for "+1d4 (Bless/Guidance)" (It's not specific to this hotkey option but this works as an example)
2. Roll anything using the new hotkey

**Expected behavior**
I'd expect the roll to appear in Roll20 modified by the d4 (or w/e other modifier I'd selected)

**Screenshots**
My Hotkey Options
![image](https://user-images.githubusercontent.com/8037494/113155105-b0498780-9206-11eb-8233-ed6011d87bb4.png)

Console from D&D Beyond after pressing the roll button. Despite it showing the event as sent, there was no response from Roll20. There was no console output on Roll20's side.
![image](https://user-images.githubusercontent.com/8037494/113155342-ec7ce800-9206-11eb-9650-dc8a67bafdbc.png)

**Browser Info (please complete the following information):**
 - Chrome
 - version 89.0.4389.90
 - console output screetshotted above.

**Comment by Aeristoka** [comment]
I can't replicate this issue:
![image](https://user-images.githubusercontent.com/7988297/113160743-fdbff780-91fa-11eb-98fb-1f5075a4a3ba.png)

Same thing, set up a Bless hotkey, rolled with it, popped right into Roll20

**Comment by Aeristoka** [comment]
Ah, try to remove and re-add your hotkeys. There was a behavior change in 2.4.0 that changed it to the actual keyboard key event, and it looks like you still have older hotkeys.

**Comment by authyrtyr** [comment]
@Aeristoka As an addendum, I'm seeing that it shows the actual die being rolled in your display but mine shows something like this 
![image](https://user-images.githubusercontent.com/8037494/113166124-78dfd880-9210-11eb-8c9e-0e4e87d9a0fb.png)

Is that also a bug?

**Comment by Aeristoka** [comment]
> It took a few tries after re-saving those hotkeys but that did do it. Thanks for the help.

@kakaroto important note here ^ People with older hotkeys (before the reference change to the actual(?) keyboard key events(? I can't remember how you phrased it) can get broken rolls.

**Comment by Aeristoka** [comment]
> @Aeristoka As an addendum, I'm seeing that it shows the actual die being rolled in your display but mine shows something like this
> ![image](https://user-images.githubusercontent.com/8037494/113166124-78dfd880-9210-11eb-8c9e-0e4e87d9a0fb.png)
> 
> Is that also a bug?

Mouseover the result, it'll show it.

**Comment by authyrtyr** [comment]
Mouseover the result shows 1d20 + 0[INT] - 1d6cs0cf0[CUSTOM]. It shows the actual rolls and the behavior is correct. I just wanted to make sure that wasn't a bug.

**Comment by kakaroto** [comment]
The `cs0cf0` means "count success 0, count failure 0`, it's just a roll modifier that Beyond20 adds to tell roll20 not to consider the attack as a critical hit if your d6 ends up being a 6... otherwise, you could do a `10 + 6` (if you rolled a 10 on the d20 and a 6 on the d6) and your attack roll shows green and the critical damages are displayed.

Surprised about having to redo the hotkeys though, it was supposed to keep working for old hotkeys... 🤔
