### ISSUE TITLE
Option "The Hexblade: Hexblade's Curse" doesn't add critical damage to disadvantage rolls (Roll20 only)

### ISSUE THREAD

**Issue by Shuro** [kakaroto/Beyond20#750]
**Describe the bug**
Normally, when using the Hexblade's Curse, one can do critical Damage on a roll of 19+.
At least in Roll20, it doesn't show the additional critical damage when rolling with disadvantage.
Honestly I can't blame it, nobody would expect it.

**To Reproduce**
1. Go to Beyond20 Options
2. Enable "The Hexblade: Hexblade's Curse"
3. Roll Attacks until it critical hits with a 19+ (you need a lot of luck, like me)
4. See output in roll20

**Expected behavior**
A damage Value + Crit + Hexblade's Curse bonus damage

**Screenshots**
Step 1. / 2. 
![grafik](https://user-images.githubusercontent.com/944030/113167362-f1ac5800-9243-11eb-979b-24d2b31df7c4.png)

Step 3.
![grafik](https://user-images.githubusercontent.com/944030/113167492-11438080-9244-11eb-95e9-08186baa9cad.png)

Step 4. (Roll20)
![grafik](https://user-images.githubusercontent.com/944030/113167579-23bdba00-9244-11eb-923c-51710f5d73fb.png)

**Browser Info (please complete the following information):**
 - Browser: Firefox
 - Version: 87.0

**Comment by Aeristoka** [comment]
What damage is missing here?

**Comment by Shuro** [comment]
The critical damage, since I rolled a 19 with Hexblade's curse (Crit on 19&20).

**Comment by Shuro** [comment]
I added a screenshot, showing a normal crit when "Hexblade's Curse" is disabled. And here is an Advantage roll with Hexblade's Curse enabled:
![grafik](https://user-images.githubusercontent.com/944030/113169913-58327580-9246-11eb-86f6-3cdf4ebfc40b.png)


So basically it is missing Crits in the sent "Disadvantage" info. And, if one is picky, the Hexblade's Curse damage on the Onehanded side, if you use "Show both Versatile"-Option.

**Comment by Shuro** [comment]
Then it may be related to the extended critical range. Not sure. It is honestly pretty hard to roll that, so it is quite niche.

**Comment by Aeristoka** [comment]
Ok, replicated it indeed.

**Comment by Aeristoka** [comment]
@kakaroto I'm struggling to find where the critical processing is taking place for this... Got any direction on that?

**Comment by Aeristoka** [comment]
Know what's not fun? Rolling a ton of rolls to replicate this on DnDBeyond ONLY (which I just did).

So this does not happen on DnDBeyond (only), or FoundryVTT, so this is a Roll20-only bug.

**Comment by Aeristoka** [comment]
I'll ask @kakaroto again, but this might be a Roll20 issue... Maybe around weird rollhandling by them of cs (consider success)?

**Comment by kakaroto** [comment]
> I'll ask @kakaroto again, but this might be a Roll20 issue... Maybe around weird rollhandling by them of cs (consider success)?

yeah, that's what it sounds to me. The fact that the roll was green meant it recognized it as being a crit, but it still didn't display the crit damage. With the roll20 template, we always put the crit damage and roll20 decides if it should show it or not, so it sounds to me like it's a roll20 bug.
Note: If you're using the digital dice, then it might be a Beyond20 bug since the rolls are made on Beyond20, not on roll20 and we're the ones deciding which damages should be shown.. but the output would look different in that case, so I don't think digital dice are enabled here.

**Comment by Aeristoka** [comment]
> > I'll ask @kakaroto again, but this might be a Roll20 issue... Maybe around weird rollhandling by them of cs (consider success)?
> 
> yeah, that's what it sounds to me. The fact that the roll was green meant it recognized it as being a crit, but it still didn't display the crit damage. With the roll20 template, we always put the crit damage and roll20 decides if it should show it or not, so it sounds to me like it's a roll20 bug.
> Note: If you're using the digital dice, then it might be a Beyond20 bug since the rolls are made on Beyond20, not on roll20 and we're the ones deciding which damages should be shown.. but the output would look different in that case, so I don't think digital dice are enabled here.

I ran all my tests with Digital Dice off, and got the same results, so it does indeed sound like a Roll20 issue.

Note: It is REALLY hard to get into this state. Really hard...

**Comment by kakaroto** [comment]
> Note: It is REALLY hard to get into this state. Really hard...

Really? I would expect it to be super easy to run into such a state.. it's what? one in 10 chances or something, right ? 

Note: if you need to retry it, I'd recommend doing a quick stealthy edit of the code to make hexbalde's curse drop the crit limit to 2 instead of 19... that would make it much easier to test... also, sorry for not telling you before, but I just caught up on this issue! 🤣

**Comment by kakaroto** [comment]
I've retested this and it looks like Roll20 have fixed their bug. I got a 19 rolling with advantage with hexblade curse enabled and the crit damages were output correctly! 👍 🥳 
![image](https://user-images.githubusercontent.com/27990/204166802-89ec1731-81f3-47e1-ac0d-f6d0e72326c0.png)

**Comment by Aeristoka** [comment]
🥳
