### ISSUE TITLE
"min" isn't working correctly

### ISSUE THREAD

**Issue by tigerhawkvok** [kakaroto/Beyond20#752]
**Describe the bug**

"min", like "min 2", isn't working correctly.

![image](https://user-images.githubusercontent.com/165937/113236362-8e2d2500-9259-11eb-8a3a-208f923e2436.png)

![image](https://user-images.githubusercontent.com/165937/113236274-6b9b0c00-9259-11eb-906a-a2ff884a8059.png)

**To Reproduce**
1. Take feat "lightning adept"
2. Cast _lightning bolt_

**Expected behavior**

Min 2 should work

**Browser Info (please complete the following information):**
 - Google Chrome Version 89.0.4389.90 (Official Build) (64-bit)

https://ddb.ac/characters/44133209/NK3rcN

**Comment by Aeristoka** [comment]
> **Describe the bug**
> 
> "min", like "min 2", isn't working correctly.
> 
> ![image](https://user-images.githubusercontent.com/165937/113236362-8e2d2500-9259-11eb-8a3a-208f923e2436.png)
> 
> ![image](https://user-images.githubusercontent.com/165937/113236274-6b9b0c00-9259-11eb-906a-a2ff884a8059.png)
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Take feat "lightning adept"
> 2. Cast _lightning bolt_
> 
> **Expected behavior**
> 
> Min 2 should work
> 
> **Browser Info (please complete the following information):**
> 
> * Google Chrome Version 89.0.4389.90 (Official Build) (64-bit)
> 
> https://ddb.ac/characters/44133209/NK3rcN

Do the math out real quick:
6+1+3+3+2+2+4+6+5 = 32

the 1 one was replaced with a 2 in the damage math (you're seeing the roll result, which was not replaced, of 1).

33 was the total damage, with the 1 upped to a 2 properly.
