### ISSUE TITLE
Issues with rolling into Roll20

### ISSUE THREAD

**Issue by Tucker2343** [kakaroto/Beyond20#753]
Since the update today (3/21) I've started having two issues. 

The first is I have to click several times to get a roll to send into roll20, where as before todays update it went every single time. 

The other issue I'm having is when I make a roll with advantage or disadvantage its highlighting the whole page and instead of rolling, see screenshot below. 

![dndissue](https://user-images.githubusercontent.com/15664374/113239168-c93a5300-926f-11eb-95c6-e47c3ce98014.png)

**Comment by Aeristoka** [comment]
Slowness rolling into Roll20 is typically a Roll20 issue, not anything to do with Beyond20. You can check this by opening the Dev console on DnDBeyond & Roll20, watch for the message sent (DnDBeyond)/Message Received (Roll20).

What hotkey do you have set for Advantage/Disadvantage rolls? I haven't seen any such behavior as highlighting the whole page.

**Comment by Tucker2343** [comment]
Currently I have the default ones of shift for advantage and control for disadvantage.

**Comment by Tucker2343** [comment]
How would I go about opening the dev console on DnDBeyond and Roll20?

**Comment by kakaroto** [comment]
That's not highlighting, that's selecting. It looks to me like you're clicking while dragging your mouse which causes it to select a bunch of texts on the page. That would probably also explain why it's not sending the messages.
Restart your browser, check your mouse for any defects, see if that helps.

**Comment by Aeristoka** [comment]
> How would I go about opening the dev console on DnDBeyond and Roll20?

Press "F12", click on the Console tab

**Comment by Tucker2343** [comment]
> That's not highlighting, that's selecting. It looks to me like you're clicking while dragging your mouse which causes it to select a bunch of texts on the page. That would probably also explain why it's not sending the messages.
> Restart your browser, check your mouse for any defects, see if that helps.

So I just restarted on computer and checked my mouse and it's still doing it, and it's never done this before until today's update.

**Comment by Tucker2343** [comment]
So I opened up the dev console and when I'm attempting to roll I'm getting the following. 

![image](https://user-images.githubusercontent.com/15664374/113241263-f426a600-9273-11eb-856c-ab45a5b48af9.png)

**Comment by Aeristoka** [comment]
> So I opened up the dev console and when I'm attempting to roll I'm getting the following.
> 
> ![image](https://user-images.githubusercontent.com/15664374/113241263-f426a600-9273-11eb-856c-ab45a5b48af9.png)

I would bet you're using an Adblocker then, as you're blocking a Google ad domain (doubleclick.net). That's nothing to do with Beyond20.

**Comment by Tucker2343** [comment]
> > So I opened up the dev console and when I'm attempting to roll I'm getting the following.
> > ![image](https://user-images.githubusercontent.com/15664374/113241263-f426a600-9273-11eb-856c-ab45a5b48af9.png)
> 
> I would bet you're using an Adblocker then, as you're blocking a Google ad domain (doubleclick.net). That's nothing to do with Beyond20.

Ah, okay that would make sense. I haven't had any issues with rolling before until today. So I was thinking maybe it was some kind of bug in the newest update. I guess I'll wait and see if maybe other people start reporting the issue as well, or if this is just me.

**Comment by DarrynGlass** [comment]
@Tucker2343 
Try these 2 possibilities.  First, hover over the crossed swords, press SHIFT for advantage, then move your mouse to over the die icon and click that.
Second, press SHIFT BEFORE you hover over anything.  Then hover over the crossed swords and click.  

Both of these have resolved the issue for me.

**Comment by HaarisQureshi** [comment]
@Tucker2343 it might not actually be that - there's a bug we've just identified with hotkeys. If you hold shift BEFORE you mouseover the whatever you're going to press (either modifier or crosswords - so have your mouse in the corner of the screen, press shift, and then move it over and click), and then try it, it should work. 

Apparently the issue is if you mouseover it first, then press the hotkey (e.g. shift) and press, Beyond20 won't pick up on the click (it'll just act as if you're shift clicking on the page - to which highlighting text is expected behaviour - or if you have digital dice turned on it'll roll the dice just in DnDBeyond and not send it to Beyond20).

**Comment by kakaroto** [comment]
> ohhhhhhhhhhh, I bet I know!
pressing the hotkey will cause the 'hotkeys list/preview' on hover thing to get updated, which changes the DOM, which causes the `documentModified` which recreates the quick areas, so the old hovered mouse event listener got destroyed
I think the solution would be to build the hotkeys list on hover instead of on hotkey-change.
Marked for 2.4.1 which will hopefully be a "soon to be released bugfix only version" 🤞

**Comment by Tucker2343** [comment]
> @Tucker2343
> Try these 2 possibilities. First, hover over the crossed swords, press SHIFT for advantage, then move your mouse to over the die icon and click that.
> Second, press SHIFT BEFORE you hover over anything. Then hover over the crossed swords and click.
> 
> Both of these have resolved the issue for me.

I tested it out and holding down the key before clicking on the roll works just fine, thanks for sharing that information!

**Comment by Tucker2343** [comment]
> > ohhhhhhhhhhh, I bet I know!
> > pressing the hotkey will cause the 'hotkeys list/preview' on hover thing to get updated, which changes the DOM, which causes the `documentModified` which recreates the quick areas, so the old hovered mouse event listener got destroyed
> > I think the solution would be to build the hotkeys list on hover instead of on hotkey-change.
> > Marked for 2.4.1 which will hopefully be a "soon to be released bugfix only version" 🤞


Perfect! I look forward to the release! 

Thank you everyone for looking into this issue, myself and my players appreciate everything you guys do for this program!
