### ISSUE TITLE
The ability to always display a spell's level, even when it is not upcast

### ISSUE THREAD

**Issue by Ronnie-McDurgen** [kakaroto/Beyond20#759]
Hello, and thank you guys so much for creating Beyond20 :-)

The following feature would be extremely useful to many different users, using many different DnD variants, on many different VTT platforms.

### Full Description of feature

1) The user goes into the Beyond20 settings, and finds there a switch that says "always display a spell's level".

2) The user flips that switch.

3) The user casts a spell without upcasting it.

4) In the VTT, the spell results are shown, including what level the spell was cast at.

This way, the user does not have to ask: "hey guys, what level is this spell again...?" ... and then the group has to look it up, thus disrupting the flow of combat.

**Comment by kakaroto** [comment]
Unsure why you closed #716 to open this one 🤔

**Comment by Ronnie-McDurgen** [comment]
Sorry, kakaroto... I'm just such a noob with this GitHub stuff, and I wasn't sure if I had originally screwed up, by modifying an existing issue, instead of creating a new one. Hope I didn't offend anyone, in either case.

Respectfully,
-Ronnie

**Comment by kakaroto** [comment]
No problem. Closing this as duplicate, I re-opened the other one which was already triaged and labeled.
