### ISSUE TITLE
Settings flicker caused by line break in firefox settings menu

### ISSUE THREAD

**Issue by AceAzzermeen** [kakaroto/Beyond20#760]
**Describe the bug**
Opening the settings inside Firefox (about:addons) causes the Whisper rolls to DM section to flicker. It tries to create a line break but then instantly resets.

**To Reproduce**
1. Go to 'Beyond 20 settings in about:addons'
2. Click on 'open settings tab'
3. Scroll down to '...'

**Expected behavior**
Create a proper line break.

**Screenshots**
Flickering between the two states shown on the screenshots.
https://cdn.discordapp.com/attachments/746985780546633872/828250912904183838/unknown.png
https://cdn.discordapp.com/attachments/746985780546633872/828250938858537060/unknown.png

**Browser Info (please complete the following information):**
 - Browser Firefox
 - Version 87.0 64-Bit
 
Not sure if relevant but just in case.
 - Win 10
 - Desktop resolution 1920x1080

**Comment by kakaroto** [comment]
I've noticed that happen to me once as well, but if I remember correctly, that looked like a Firefox bug, and there wasn't anything for me to do about it, because that options page is just displaying a static html page and FF is misbehaving on it.

**Comment by AceAzzermeen** [comment]
Can you not force a line break before "chat box" with <br>?
