### ISSUE TITLE
Beyond20 not rolling 3D dice on roll20 anymore

### ISSUE THREAD

**Issue by BoulderCODC** [kakaroto/Beyond20#763]
Beyond20 isn't rolling 3D dice on Roll20.com anymore for anyone in my friend group after we started a new campaign. This issue first came up for us on the 4th of April and has yet to resolve. We all have 3D dice enabled and have been unable to find a setting in Beyond20 that would stop it from working. The chat display for rolls also looks very different now and no one seems to like the new look of things. Is there a way to fix this? Beyond20 still functions normally in previous campaigns, it's only this new one where it does not.
Below are two screenshots, the first is the new unpleasant style and the second is the better older style.

![not working properly](https://user-images.githubusercontent.com/82016562/113665290-d772df80-9672-11eb-9e39-460cc3df3602.png)

![working properly](https://user-images.githubusercontent.com/82016562/113665352-f40f1780-9672-11eb-97ac-9fdedb77a3e7.png)

What do we need to do to make Beyond20 work in the new campaign like it did in the old one?

**Comment by kakaroto** [comment]
3D dice on roll20's side are a Roll20 setting that I believe is disabled by default on new campaigns. You'd have to enable it within the roll20 campaign settings.

**Comment by Aeristoka** [comment]
You set your Beyond20 Campaign settings (not Beyond20 Settings) to something other than `D&D 5e By Roll20`
![image](https://user-images.githubusercontent.com/7988297/113711065-bbd2fd80-96a1-11eb-8af1-43b22c26561d.png)

To get that styling of rolls
