### ISSUE TITLE
Roll20 displaying Purple Boxed Rolls again

### ISSUE THREAD

**Issue by Wraethrax** [kakaroto/Beyond20#765]
So, I know this popped up a few times and some fixes were given.  I've tried everything and now nothing works.  Last time it broke, a couple of weeks ago, and I did the Developer thing and loaded the .json file and it fixed it.  It just broke again the other day and trying the same fix again doesn't seem to work.  I've tried in Firefox and Chrome and neither seems to work.  All rolls sent to Roll20 have that ugly default script.  I do also have the D&D 5e Sheet by Roll20 selected also.

**Comment by Aeristoka** [comment]
Fixed in Dev Version: https://github.com/kakaroto/Beyond20/commit/5b53c84743076ba84b3695faa1e8534ce42210ea

You can also paste this into the Dev Console to workaround the issue: 
```js
document.body.append($('<input type="hidden" value="1" name="isOGL" id="isOGL">')[0]);
```

That will work until you refresh.

**Comment by Aeristoka** [comment]
> > ```js
> > document.body.append($('<input type="hidden" value="1" name="isOGL" id="isOGL">')[0]);
> > ```
> 
> Hmmm, I did that and got some kind of error message.

What error message? Screenshot would be most helpful.

**Comment by Wraethrax** [comment]
> 
> 
> > > ```js
> > > document.body.append($('<input type="hidden" value="1" name="isOGL" id="isOGL">')[0]);
> > > ```
> > 
> > 
> > Hmmm, I did that and got some kind of error message.
> 
> What error message? Screenshot would be most helpful.

Uncaught DOMException: Document.querySelector: '<input type="hidden" value="1" name="isOGL" id="isOGL">' is not a valid selector

**Comment by Aeristoka** [comment]
> > > > ```js
> > > > document.body.append($('<input type="hidden" value="1" name="isOGL" id="isOGL">')[0]);
> > > > ```
> > > 
> > > 
> > > Hmmm, I did that and got some kind of error message.
> > 
> > 
> > What error message? Screenshot would be most helpful.
> 
> Uncaught DOMException: Document.querySelector: '' is not a valid selector

Screenshot it please.

**Comment by Wraethrax** [comment]
> 
> 
> > > > > ```js
> > > > > document.body.append($('<input type="hidden" value="1" name="isOGL" id="isOGL">')[0]);
> > > > > ```
> > > > 
> > > > 
> > > > Hmmm, I did that and got some kind of error message.
> > > 
> > > 
> > > What error message? Screenshot would be most helpful.
> > 
> > 
> > Uncaught DOMException: Document.querySelector: '' is not a valid selector
> 
> Screenshot it please.

![image](https://user-images.githubusercontent.com/82197869/114206705-99ebac00-9929-11eb-8247-f6364ad6a6a9.png)

**Comment by Aeristoka** [comment]
> > > > > > ```js
> > > > > > document.body.append($('<input type="hidden" value="1" name="isOGL" id="isOGL">')[0]);
> > > > > > ```
> > > > > 
> > > > > 
> > > > > Hmmm, I did that and got some kind of error message.
> > > > 
> > > > 
> > > > What error message? Screenshot would be most helpful.
> > > 
> > > 
> > > Uncaught DOMException: Document.querySelector: '' is not a valid selector
> > 
> > 
> > Screenshot it please.
> 
> ![image](https://user-images.githubusercontent.com/82197869/114206705-99ebac00-9929-11eb-8247-f6364ad6a6a9.png)

You're not on a Roll20 page, so it won't work there.

**Comment by Wraethrax** [comment]
OK, I[m super confused and this kind of thing is not in my wheelhouse.  So, I'm debugging Roll20?  I thought I was debugging Beyond20 extension.  So, go into the particular campaign on Roll20?  Roll20 itself?

**Comment by Aeristoka** [comment]
> OK, I[m super confused and this kind of thing is not in my wheelhouse. So, I'm debugging Roll20? I thought I was debugging Beyond20 extension. So, go into the particular campaign on Roll20? Roll20 itself?

You are not debugging Beyond20, no. You are force-applying a HTML ID to a Roll20 campaign page that Beyond20 would NORMALLY apply, if Roll20 hadn't been screwing around with their code again.

**Comment by Wraethrax** [comment]
> 
> 
> > OK, I[m super confused and this kind of thing is not in my wheelhouse. So, I'm debugging Roll20? I thought I was debugging Beyond20 extension. So, go into the particular campaign on Roll20? Roll20 itself?
> 
> You are not debugging Beyond20, no. You are force-applying a HTML ID to a Roll20 campaign page that Beyond20 would NORMALLY apply, if Roll20 hadn't been screwing around with their code again.

Ahhhhh!  OK, so now my next question is...how the heck do I do that?  I poked around, but don't see where that's done.

**Comment by Aeristoka** [comment]
> > > OK, I[m super confused and this kind of thing is not in my wheelhouse. So, I'm debugging Roll20? I thought I was debugging Beyond20 extension. So, go into the particular campaign on Roll20? Roll20 itself?
> > 
> > 
> > You are not debugging Beyond20, no. You are force-applying a HTML ID to a Roll20 campaign page that Beyond20 would NORMALLY apply, if Roll20 hadn't been screwing around with their code again.
> 
> Ahhhhh! OK, so now my next question is...how the heck do I do that? I poked around, but don't see where that's done.

1. Open Roll20 Campaign
2. Press "F12" to open Dev Console
3. Paste `document.body.append($('<input type="hidden" value="1" name="isOGL" id="isOGL">')[0]);` in the console
4. Press "Enter"
5. Profit! (until you refresh the page, then start at 2 again)

**Comment by Wraethrax** [comment]
>     3\. document.body.append($('<input type="hidden" value="1" name="isOGL" id="isOGL">')[0]);

To be perfectly clear, Launch the campaign first or do this on the Campaign page.  Concerned that doing this and THEN launching will be the same as refreshing.

**Comment by Aeristoka** [comment]
> > ```
> > 3\. document.body.append($('<input type="hidden" value="1" name="isOGL" id="isOGL">')[0]);
> > ```
> 
> To be perfectly clear, Launch the campaign first or do this on the Campaign page. Concerned that doing this and THEN launching will be the same as refreshing.

Launch campaign first, always.

**Comment by Wraethrax** [comment]
> 
> 
> > ```
> > 3\. document.body.append($('<input type="hidden" value="1" name="isOGL" id="isOGL">')[0]);
> > ```
> 
> To be perfectly clear, Launch the campaign first or do this on the Campaign page. Concerned that doing this and THEN launching will be the same as refreshing.

I got it.  Sorry, I should have just tried it.  Yeah.  Thank you so much.  I really can't stand that purple.  It's absolutely awful.  You're my hero.

**Comment by Aeristoka** [comment]
> > > ```
> > > 3\. document.body.append($('<input type="hidden" value="1" name="isOGL" id="isOGL">')[0]);
> > > ```
> > 
> > 
> > To be perfectly clear, Launch the campaign first or do this on the Campaign page. Concerned that doing this and THEN launching will be the same as refreshing.
> 
> I got it. Sorry, I should have just tried it. Yeah. Thank you so much. I really can't stand that purple. It's absolutely awful. You're my hero.

I too enjoy hurting @kakaroto 's feelings 😂 . I agree, it's not quite as pretty as the "D&D 5e By Roll20" boxes.

**Comment by Wraethrax** [comment]
Is that really his?  I thought it was the other way around?  Wow.  Beyond20 is just brilliant, but I really don't get the purple.  He's still amazing.  :)

**Comment by Aeristoka** [comment]
> Is that really his? I thought it was the other way around? Wow. Beyond20 is just brilliant, but I really don't get the purple. He's still amazing. :)

The purple I believe is also a Roll20 default template, he just likes it because it's more clear on the overall roll data (the pretty boxes get cramped).

**Comment by Wraethrax** [comment]
Gotcha.

**Comment by kakaroto** [comment]
Oh the purple is ugly for sure! But I like how much more informative the "table style" kind of output, but not the color scheme or layout of it. I'm liking things better now with the OGL template where it's each damage in its own box instead of all crammed into a single space (with digital dice enabled vs without).
And yeah it's Roll20 "default" template which would be available on all campaigns regardless of the character template used, which is why it's the fallback when we can't detect the OGL sheet templates.

**Comment by kakaroto** [comment]
Per @Aeristoka 's request (and brilliant idea). Re-opening this issue (Even though it's fixed) just to prevent others from reporting this issue multiple times a day! :)

**Comment by Svovovs** [comment]
I am grateful that you re-opened this issue, as I don't see that it is fixed on my side.  I am using a Mac and can't seem to figure out how to open the Roll20 Dev Console for pasting in "the fix" mentioned above.  Any suggesting you can provide would be much appreciated.  p.s. thank you for developing this extension, which really is quite clever and helpful - I shall have to buy some rations.  : )

**Comment by Svovovs** [comment]
My apologies, I figured it out.  Thank you again.

**Comment by kakaroto** [comment]
Thanks. It's considered fixed because the issue has been corrected in the development code. It wouldn't be available until a new update is released but the bug itself is fixed, so we would close bugs once they are fixed, and tag them with the next release milestone

**Comment by ThatOhio** [comment]
Thanks for keeping this open! We were pulling out hair out trying to figure out why the box changed on us this morning haha

**Comment by smites88** [comment]
I tried adding the fix into my console as DM and it worked for my rolls. But my players rolls still come through as the purple box. Do we all need to do it?

**Comment by Aeristoka** [comment]
> I tried adding the fix into my console as DM and it worked for my rolls. But my players rolls still come through as the purple box. Do we all need to do it?

You all need to do it, it's a per person (until refresh) fix.

**Comment by smites88** [comment]
> > I tried adding the fix into my console as DM and it worked for my rolls. But my players rolls still come through as the purple box. Do we all need to do it?
> 
> You all need to do it, it's a per person (until refresh) fix.

What causes the issue? Is it likely to be resolved?

**Comment by Aeristoka** [comment]
> > > I tried adding the fix into my console as DM and it worked for my rolls. But my players rolls still come through as the purple box. Do we all need to do it?
> > 
> > 
> > You all need to do it, it's a per person (until refresh) fix.
> 
> What causes the issue? Is it likely to be resolved?

Roll20 screwing around with their code (again, for the second time in two weeks). It broke Beyond20's NEW detection code for the "D&D 5e By Roll20" sheet.

The dev version on GitHub has a fix (https://github.com/kakaroto/Beyond20#developer-mode-installation), release of 2.4.1 should have the fix in it.

**Comment by Wraethrax** [comment]
I used the cut and paste line in the console and now it's not working at all.  Meaning, it doesn't seem to link to Beyond20

**Comment by Wraethrax** [comment]
> 
> 
> I used the cut and paste line in the console and now it's not working at all. Meaning, it doesn't seem to link to Beyond20

OK, this is weird.  I went into another Roll20 game and it's working again.  Weird.

**Comment by Aeristoka** [comment]
> I used the cut and paste line in the console and now it's not working at all. Meaning, it doesn't seem to link to Beyond20

Your comments combined, that means the GM of the first Campaign changed the Roll20 Campaign setting away from "D&D 5e By Roll20"
![image](https://user-images.githubusercontent.com/7988297/114756001-7fde0f00-9d17-11eb-84e2-18631d9df513.png)

(Note, that is NOT a Beyond20 setting, that is a Roll20 Campaign Setting)

So the workaround broke things because the templates you told Roll20 to use with the workaround didn't exist, due to what the GM changed on Roll20.

**Comment by Wraethrax** [comment]
Yeah, I remember that being the case, but this one was weird because I'm
the GM.  I didn't change anything.  Anyway, my other campaign seem fine.
I'll check back on that one later.  Thanks for the help.

**Comment by kakaroto** [comment]
v2.4.1 has been released which included the fix, so closing this again! 🥳

**Comment by StygianTraveler** [comment]
This problem is back. :(

**Comment by Aeristoka** [comment]
> This problem is back. :(

You or your DM changed something then, it tests just fine here.

**Comment by StygianTraveler** [comment]
> You or your DM changed something then, it tests just fine here.

Uh... yeah, looks like it works in one game, but not in another. Weird, not sure why, but I guess it's not a generalized issue. Sorry!

**Comment by Aeristoka** [comment]
> > You or your DM changed something then, it tests just fine here.
> 
> Uh... yeah, looks like it works in one game, but not in another. Weird, not sure why, but I guess it's not a generalized issue. Sorry!

This is most likely what the DM of the game it's not working in changed:
![image](https://user-images.githubusercontent.com/7988297/118336990-09782c80-b4d0-11eb-978b-bd5cc27bacf8.png)

It has to be EXACTLY that setting, or the Roll templates Beyond20 wants to use don't exist, so you have to use the Purple Boxes (which are a generic Roll20 template).
