### ISSUE TITLE
Firefox on Mac to roll20 rolls twice/double

### ISSUE THREAD

**Issue by Shafaragorn** [kakaroto/Beyond20#766]
Didn't see a report on this yet, sorry if I missed it. Rolling almost anything (attacks, spells, etc.) from D&D Beyond to roll20 in Firefox on a Mac sends 2 rolls to roll20 instead of 1. Not advantage/disadvantage, two entirely separate rolls right after each other. Picture is one click on the attack button.
![image](https://user-images.githubusercontent.com/73675962/114136036-f4035780-98be-11eb-96de-61932f9ad5f3.png)

**Comment by Aeristoka** [comment]
You have "Always roll twice" selected:
![image](https://user-images.githubusercontent.com/7988297/114182906-74967800-9900-11eb-8a21-8e18be9f046d.png)

Or you have two Beyond20 versions installed (Official + Dev).

**Comment by kakaroto** [comment]
Most of the time when this happens, the user ends up finding that they had two roll20 windows open. I suggest you hunt for that second tab.

**Comment by Shafaragorn** [comment]
Looks like it's working now, thank you!

**Comment by Aeristoka** [comment]
> Looks like it's working now, thank you!

What did you change?
