### ISSUE TITLE
Default Template

### ISSUE THREAD

**Issue by dchjackson** [kakaroto/Beyond20#767]
My friend and I have been having a problem with the default template showing in Roll20 (the purple box).  I was looking through the release note that this problem was support to be fixed in the 2.4.0 update.  I just wanted to let you know that we are still having this problem and was wondering if anybody else was still having this problem.

**Comment by Aeristoka** [comment]
Duplicate of #765 , please see that for a workaround. Roll20 has been screwing around on their side yet again.

**Comment by dchjackson** [comment]
That you.  That works great!!
