### ISSUE TITLE
Force Crit for Damage Rolls [Feature Suggestion/Request]

### ISSUE THREAD

**Issue by Chelebi** [kakaroto/Beyond20#768]
**Is your feature request related to a problem? Please describe.**
I see myself constantly in situations where i get a Crit without rolling a 20 but the "Force Critical Hit" prompt only works with an attack roll and then you have to go over to the VTT and klick the "Roll Damage" prompt there. Would be really nice if the Hotkey/Toggle for "Force Crit Hit" would work if you klick on the 
![image](https://user-images.githubusercontent.com/1344472/114310789-555c3e00-9aec-11eb-83cc-2619a8b11754.png)
 next to the damage rolls like it also works with other features like sneak attack.
![image](https://user-images.githubusercontent.com/1344472/114310756-2645cc80-9aec-11eb-8243-540bf5a5d4f1.png)

There are also some magic items that roll critical damage under some circumstances that not involve rolling a 20.
it would really cut down on time too if you get an unsuspected Crit and don't have to roll an attack again with "Force Crit" enabled and then go over to the VTT and klick on the "Roll damage" prompt in the VTT chat to roll Crit damage if you could just do it in D&D beyond with Beyond 20

**Describe the solution you'd like**
Press Hotkey or Toggle Force Critical Hit Attack
![image](https://user-images.githubusercontent.com/1344472/114310893-bdab1f80-9aec-11eb-8ef5-248514cc09d4.png)
Klick on the ![image](https://user-images.githubusercontent.com/1344472/114310789-555c3e00-9aec-11eb-83cc-2619a8b11754.png) next to the roll damage prompt for any attack
![image](https://user-images.githubusercontent.com/1344472/114310756-2645cc80-9aec-11eb-8243-540bf5a5d4f1.png)
Critical damage gets rolled on D&D beyond and send over to the VTT chat.

With digital dice enabled this would also cut down on time you have to wait for your dice to roll because you go straight to rolling the damage and not roll the hit again and then have to go over to the VTT chat and press the "roll damage" prompt.

With "Roll Damage" prompt i mean the Button in this example from a Rapier, +1 attack in roll20 
![image](https://user-images.githubusercontent.com/1344472/114311309-88073600-9aee-11eb-96b5-803f7af28eaf.png)

**Additional context**
Thanks for Taking the Time to read this Comment and i hope im not to confusing on my request.

**Comment by kakaroto** [comment]
Hi,

In the character options, there's a way to set a custom critical limit : 
![image](https://user-images.githubusercontent.com/27990/114490564-14932080-9be3-11eb-9d81-d8eabe853488.png)

This is useful if you have a magic item like you said, which changes it to crit on 19 or something. 

That being said, yes, it's a good idea to have the damage rolled include the crit if force crit is enabled and we're rolling damages only.
Thanks.

**Comment by Rarst** [comment]
This also would be very useful to roll crit damage with a homebrew critical rule active. You can force a critical damage roll via native digital dice right click, but since it has no support for customized critical rules it's useless for that.
