### ISSUE TITLE
Using Beyond20 in the encounter tracker view of DnD Beyond floods the stat block slowly with purple buttons

### ISSUE THREAD

**Issue by Fabrice-Schoeneberger** [kakaroto/Beyond20#772]
**Describe the bug**
I open the encounter tracker in DnDBeyond with at least 2 Monster.
I click on the first one. All extra buttons are addet, works fine. 
I open the second monster. That already has so many buttons.
Now with every time I switch to another statblock the buttons get more and more to the point where first you can't read anything anymore and then the statblock goes of the screen. It also crashed the page once but I can't reproduce it reliably.
It also slows the page down more and more as it tries to load in the blocks

**Screenshots**
![Screenshot 2021-04-17 032230](https://user-images.githubusercontent.com/64808681/115097728-374b6f00-9f2c-11eb-804d-2cfaad9fcd39.png)
It starts normal
![Screenshot 2021-04-17 032248](https://user-images.githubusercontent.com/64808681/115097736-429e9a80-9f2c-11eb-9f35-2e51e2ea76fa.png)
That is the second Time I touch that statblock
![Screenshot 2021-04-17 031925](https://user-images.githubusercontent.com/64808681/115097694-1125cf00-9f2c-11eb-9dfd-20dda9b3a259.png)
And from there on ...
![Screenshot 2021-04-17 032100](https://user-images.githubusercontent.com/64808681/115097753-5944f180-9f2c-11eb-81ed-6cdf2f3f76b8.png)
... it just gets worse

**Browser Info (please complete the following information):**
 - Browser : firefox
 - Version: Whatever is the news at the time of posting

**Additional context**
That problem was on any encounter page I tried it on so it seems it doesn't matter what the monsters are, tho I think spellcasters are worse of.
PS: All monsters are filling up with buttons not just the ones I clicked. I can click between 2 and when I touch the 3rd for the first time it already has as many buttons as the others.

PSPS: Since I am a small programmer myself I would bet it's just a case of it either can't see the buttons anymore and adds more everytime ore it fails to remove them on close what ever you use, but I don't know your programm, you are probebly way better than I am. Take it as a tipp from me on where to start when you want to fix it but I bet you already know that yourself.

Have a wonderful day and thank you for your handy app. You are cool

**Comment by Aeristoka** [comment]
Are you 100% positive you don't have two versions of Beyond20 enabled?

**Comment by Aeristoka** [comment]
@kakaroto I just was able to replicate this on Firefox, but had to be this specific set of NPCs.

**Comment by kakaroto** [comment]
That looks beautiful! 😍 Also, I like your version of Firefox!

**Comment by Aeristoka** [comment]
> That looks beautiful! 😍 Also, I like your version of Firefox!

All the buttons!
