### ISSUE TITLE
Encounter builder page crashed with homebrew monsters

### ISSUE THREAD

**Issue by Oshcakes** [kakaroto/Beyond20#775]
**Describe the bug**
Encounter builder page recently started crashing when clicking through on homebrew monsters. Does not happen with non homebrew monsters. Seems to be a results of digital dice buttons on page.

**To Reproduce**
click homebrew monsters in the builder. It may take a few cysles tp happen.

**Expected behavior**
Don't crash

![image](https://user-images.githubusercontent.com/61471647/115115942-b5276e80-9f5c-11eb-9cbf-d438df25f60d.png)

**Comment by Aeristoka** [comment]
@kakaroto confirmed this myself, only with Homebrew monsters. It appears to be something with DnDBeyond trying to inject their digital dice onto the Monster.

**Comment by Oshcakes** [comment]
Uploading 2021-04-17_8-12-34.mp4…

**Comment by Oshcakes** [comment]
https://user-images.githubusercontent.com/61471647/115115999-fddf2780-9f5c-11eb-8e57-d28ce35341c2.mp4

**Comment by kakaroto** [comment]
So, it looks like disabling the "dice formula replacement" option fixes it : 
![image](https://user-images.githubusercontent.com/27990/115963499-8de91800-a4ed-11eb-9b13-58fe6e063ce4.png)

Also noticing that dice formulas aren't actually replaced by D&D Beyond in homebrew monsters, so I think they have a bug there where it tries to replace them and fails, and when there's also beyond20 dice in there, it crashes.
I haven't been able to do anything to prevent it, it actually crashes on its own (not when we do something) as soon as ddb *removes* the statblock to show the new one, so it doesn't like us changing the content.
I'll contact ddb about this instead so they can get it fixed.

**Comment by jaypoulz** [comment]
Not isolated to homebrew monsters.
See https://github.com/kakaroto/Beyond20/issues/827 for reproducer
