### ISSUE TITLE
Roll Sneak Attack also for Shadow Blades without renaming them Psychic blades

### ISSUE THREAD

**Issue by flyingitalianman** [kakaroto/Beyond20#781]
It would be nice if [this fix](https://github.com/kakaroto/Beyond20/issues/311) could be extended to apply also to Shadow blades ( https://www.dndbeyond.com/spells/shadow-blade )
for Arcane tricksters ( https://www.dndbeyond.com/classes/rogue#ArcaneTrickster ) without the need to name them "psychic blades" (since it is both unintuitive and undocumented).
Thank you.

So instead of 
if (action_name.includes("Psychic Blade"))
have 
if (action_name.includes("Psychic Blade") || action_name.includes("Shadow Blade"))

**Comment by Aeristoka** [comment]
Good catch! I'll get this looked at.

**Comment by Aeristoka** [comment]
So I'm trying to understand all of what you're doing here. Did you make a custom weapon for the "Shadow Blade"?

**Comment by flyingitalianman** [comment]
I have tried both, custom action and custom weapon. Neither worked until I renamed the custom action to include "psychic blade"

**Comment by Aeristoka** [comment]
Right

> I have tried both, custom action and custom weapon. Neither worked until I renamed the custom action to include "psychic blade"

Right, so that use case will not be covered, because that's a Custom Action thing.

What I'm working on covering is this:
Roll initial Spell:
![image](https://user-images.githubusercontent.com/7988297/115888327-09749780-a410-11eb-9b34-25b21b934036.png)

or this
![image](https://user-images.githubusercontent.com/7988297/115888364-11ccd280-a410-11eb-876a-c96481396479.png)

Roll for attacks after:
![image](https://user-images.githubusercontent.com/7988297/115888401-1e512b00-a410-11eb-80c7-aed17ab19b26.png)

![image](https://user-images.githubusercontent.com/7988297/115888439-2a3ced00-a410-11eb-8844-2a4dfe1e1b37.png)

Resulting in that.

**Comment by Aeristoka** [comment]
Although I just realized that DnDBeyond failed to include a To Hit for this...

**Comment by flyingitalianman** [comment]
But that requires casting the spell (and consume a spell slot), but I can use the shadow blade through an action for several turns after I cast the spell, hence my creation of the custom action.

or have I missed something?

**Comment by Aeristoka** [comment]
> But that requires casting the spell (and consume a spell slot), but I can use the shadow blade through an action for several turns after I cast the spell, hence my creation of the custom action.
> 
> or have I missed something?

The third way I posted to roll certainly does not. The first two do, on purpose.

The bigger issue here is no "To Hit:" on the spell, which radically breaks Beyond20 processing.

**Comment by flyingitalianman** [comment]
ok, I see. I'll leave this to you then. If you say that it works properly I'll accept it, no worries.

And thank you :)

**Comment by Aeristoka** [comment]
> ok, I see. I'll leave this to you then. If you say that it works properly I'll accept it, no worries.
> 
> And thank you :)

I'm conferring with KaKaRoTo about it, the brain-dead way the spell is set up on DnDBeyond makes me think your suggestion is actually better (to support the naming of the Custom Action instead), and just point people that way.

**Comment by Aeristoka** [comment]
Ok, got approval for handling the Custom Action, let me throw away all of the obtuse work I just did to handle the brain-dead incomplete spell.

**Comment by tyler-macinnis** [comment]
Another option is making a homebrew weapon in dndbeyond for Shadow Blade. I'm pretty sure that one has already probably been made. If you make a single item then you'd have to override the to hit and the damage based on the level or make multiple ones based on the level the spell is cast .

**Comment by Aeristoka** [comment]
> Another option is making a homebrew weapon in dndbeyond for Shadow Blade. I'm pretty sure that one has already probably been made. If you make a single item then you'd have to override the to hit and the damage based on the level or make multiple ones based on the level the spell is cast. But dndbeyond homebrew is a little... messy.

I'd challenge you to find it then, as with every Homebrew weapon on DnDBeyond, you have to start from a weapon, and no weapon has the 2d8 of Shadow blade: https://www.dndbeyond.com/spells/shadow-blade

**Comment by Aeristoka** [comment]
@flyingitalianman https://github.com/kakaroto/Beyond20/pull/782

**Comment by DarrynGlass** [comment]
Here is how I would handle this.  I would make a custom weapon, and then write a macro on Roll20 to prompt me for the spell level, roll the to hit and the damage, and then put this in the notes field of the custom weapon.

[[replace]]#ShadowBlade[[/replace]]

**Comment by Aeristoka** [comment]
> Here is how I would handle this. I would make a custom weapon, and then write a macro on Roll20 to prompt me for the spell level, roll the to hit and the damage, and then put this in the notes field of the custom weapon.
> 
> [[replace]]#ShadowBlade[[/replace]]

that sounds horrifying, and only works for Roll20. Beyond20 supports Roll20/FoundryVTT/Astral/Discord.

**Comment by DarrynGlass** [comment]
True, but I was providing an alternate method to deal with the leveling issue of the spell, and it isn't all that horrifying LOL.

Besides, can't you make attack rolls like this on other VTT's?  I mean I could put the entire roll template (or whatever you want to call that) inside the [[replace]] and send that to the other VTT's?

**Comment by Aeristoka** [comment]
@flyingitalianman Lets leave this open until the code is merged for it. It'll auto-close at that point.

**Comment by flyingitalianman** [comment]
sorry, was not aware. won't do it again.

**Comment by Aeristoka** [comment]
> sorry, was not aware. won't do it again.

No worries at all. 😃

**Comment by tyler-macinnis** [comment]
> > Another option is making a homebrew weapon in dndbeyond for Shadow Blade. I'm pretty sure that one has already probably been made. If you make a single item then you'd have to override the to hit and the damage based on the level or make multiple ones based on the level the spell is cast. But dndbeyond homebrew is a little... messy.
> 
> I'd challenge you to find it then, as with every Homebrew weapon on DnDBeyond, you have to start from a weapon, and no weapon has the 2d8 of Shadow blade: https://www.dndbeyond.com/spells/shadow-blade

1. Make Homebrew Rapier
2. Add the modifiers in the image below and set the weight to 0 in the additional information
3. Duplicate the item and change **Damage-Psychic** for the duplicates to represent the different levels of the spell (2d8 for 3rd/4th level, 3d8 for 5th/6th level, 4d8 for 7th+)

It's not pretty but it is certainly doable.

![Screenshot 2021-04-23 113548](https://user-images.githubusercontent.com/21990225/115895333-4c426980-a428-11eb-9b93-75bfc80f44a9.png)
![Screenshot 2021-04-23 113528](https://user-images.githubusercontent.com/21990225/115895339-4ea4c380-a428-11eb-9a91-ba5f623fe3c9.png)

**Comment by Aeristoka** [comment]
> > > Another option is making a homebrew weapon in dndbeyond for Shadow Blade. I'm pretty sure that one has already probably been made. If you make a single item then you'd have to override the to hit and the damage based on the level or make multiple ones based on the level the spell is cast. But dndbeyond homebrew is a little... messy.
> > 
> > 
> > I'd challenge you to find it then, as with every Homebrew weapon on DnDBeyond, you have to start from a weapon, and no weapon has the 2d8 of Shadow blade: https://www.dndbeyond.com/spells/shadow-blade
> 
> 1. Make Homebrew Rapier
> 2. Add the modifiers in the image below and set the weight to 0 in the additional information
> 3. Duplicate the item and change **Damage-Psychic** for the duplicates to represent the different levels of the spell (2d8 for 3rd/4th level, 3d8 for 5th/6th level, 4d8 for 7th+)
> 
> It's not pretty but it is certainly doable.
> 
> ![Screenshot 2021-04-23 113548](https://user-images.githubusercontent.com/21990225/115895333-4c426980-a428-11eb-9b93-75bfc80f44a9.png)
> ![Screenshot 2021-04-23 113528](https://user-images.githubusercontent.com/21990225/115895339-4ea4c380-a428-11eb-9a91-ba5f623fe3c9.png)

And that will already work out of the box, if the player wants to do that.

**Comment by flyingitalianman** [comment]
Can confirm that tyler's solution works for me, so I have no problem if you guys reject my proposal.

**Comment by Aeristoka** [comment]
> Can confirm that tyler's solution works for me, so I have no problem if you guys reject my proposal.

I think adding your suggestion is still perfectly appropriate, as yes, you can make a Homebrew weapon, but your first instinct was to make a Custom Action. This makes sure that both scenarios are covered.

**Comment by tyler-macinnis** [comment]
> > Can confirm that tyler's solution works for me, so I have no problem if you guys reject my proposal.
> 
> I think adding your suggestion is still perfectly appropriate, as yes, you can make a Homebrew weapon, but your first instinct was to make a Custom Action. This makes sure that both scenarios are covered.

Agreed, just pointing out that some spell effects/class features that aren't really implemented on dndbeyond character sheets can be made with their homebrew. (Haste Spell, Mage Armor, some Bladesong changes etc.)
