### ISSUE TITLE
Incorrect Elemental Adept equation is being sent to Foundry VTT

### ISSUE THREAD

**Issue by FeistyViking** [kakaroto/Beyond20#789]
**Describe the bug**
While having the Elemental Adept (Fire) feat the equation for damage that is being sent to Foundry VTT is (Dice,2)kh1+(Dice,2)kh1 which is resulting in 4 dice being rolled with the highest 1 being kept for the two damage dice sets

**To Reproduce**
1. Add Elemental Adept (Fire)
2. Click on Fire Bolt to attack
3. Click on Roll Damage in Foundry VTT

**Expected behavior**
The result of Elemental Adept should just be replacing any 1s rolled with 2s

**Comment by Aeristoka** [comment]
@kakaroto I've also seen this with Rogue: Reliable Talent, ie, anything that is a "kh1" rolls too many dice. In the case of Reliable Talent, it rolls 3.

@FeistyViking This isn't actually it getting things wrong, Dice So Nice is just misinterpreting the dice data it's getting, and rolling the correct die (which is used), and nonsense die as well.

**Comment by FeistyViking** [comment]
@Aeristoka AHA! I should have done some more searching it seems. I see now that the equation is accurate. https://foundryvtt.com/article/dice/#dice-pools

I will see where I can submit an issue with Dice So Nice.

Thanks for taking the time to reply!

**Comment by FeistyViking** [comment]
So I opened a ticket with DsN

https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/issues/179

Interestingly, when you just tell Foundry to roll that formula the correct dice are displayed. So it doesn't appear to be a DsN issue.

What would be the way to confirm what equation Beyon20 is sending to Foundry?

**Comment by FeistyViking** [comment]
Of course! Hopefully we can get it sorted.

When you say RollPool what is that? Is that just another term for [Dice Pools](https://foundryvtt.com/article/dice/#dice-pools)?

**Comment by Aeristoka** [comment]
> Of course! Hopefully we can get it sorted.
> 
> When you say RollPool what is that? Is that just another term for [Dice Pools](https://foundryvtt.com/article/dice/#dice-pools)?

Yep... See it has been awhile since @kakaroto and I went through that code 😄 . But yeah, my (maybe really bad) guess is that DSN is seeing the roll itself (which is fine) and picking up a die from there, and then ALSO seeing the Dice Pool, and picking the dice out from there. (Just pure guesswork though). I guess at that because I'm fairly certain that DSN didn't roll too many dice in other testing I did sometime back (though I don't recall clearly enough to make a definitive statement).

**Comment by FeistyViking** [comment]
Gotcha, and seems like a plausible thing to me.

So when you hover over the damage in the chat log of Foundry it displays the formula. Is there another way to confirm what formula is being sent when you click the Roll Damages button after casting the spell?

**Comment by Aeristoka** [comment]
> Gotcha, and seems like a plausible thing to me.
> 
> So when you hover over the damage in the chat log of Foundry it displays the formula. Is there another way to confirm what formula is being sent when you click the Roll Damages button after casting the spell?

If I remember correctly, the entirety of it is in the Dev Console messages that are posted as a note of "this is the data received from Beyond20".

**Comment by FeistyViking** [comment]
Ah I think I found it!

> Received roll request  
{action: "roll", character: {…}, type: "spell-attack", roll: "1d10min2 + 1d10min2", advantage: 0, …}
action: "roll"
advantage: 0
attack-source: "spell"
attack-type: "Ranged"
casting-time: "1 action"
character: {name: "Dramij Armandis", avatar: "https://www.dndbeyond.com/avatars/16967/184/158111…idth=150&height=150&fit=crop&quality=95&auto=webp", id: "48220154", type: "Character", abilities: Array(6), …}
components: "V, S"
concentration: false
critical-damage-types: Array(2)
0: "Fire"
1: "Arcane Firearm"
length: 2
__proto__: Array(0)
critical-damages: Array(2)
0: "10 + 10"
1: "8"
length: 2
__proto__: Array(0)
damage-types: Array(2)
0: "Fire"
1: "Arcane Firearm"
length: 2
__proto__: Array(0)
damages: Array(2)
0: "1d10min2 + 1d10min2"
1: "1d8"
length: 2
__proto__: Array(0)
description: "You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn't being worn or carried.\nThis spell's damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10)."
duration: "Instantaneous"
level-school: "Evocation Cantrip"
name: "Fire Bolt"
preview: "https://www.dndbeyond.com/Content/Skins/Waterdeep/images/spell-schools/35/evocation.png"
range: "120ft."
ritual: false
roll: "1d10min2 + 1d10min2"
rollAttack: true
rollCritical: false
rollDamage: false
to-hit: "+7"
type: "spell-attack"
whisper: 0
__proto__: Object


So it would appear the equation being sent contains the min2 but then Foundry converts that to this (Dice,2)kh1+(Dice,2)kh1?

**Comment by Aeristoka** [comment]
Ah, I'm misremembering, the request is sent, then the Beyond20 script on the FoundryVTT side converts it to the FoundryVTT equivalent of the roll info:

As you stated min2 -> (Dice, 2)kh2, and so on

**Comment by Aeristoka** [comment]
> What is this script?
> 
> "dist/fvtt_script.js"
> 
> Is that the script that converts the dice formula?

That's the Beyond20 script that works in FoundryVTT to convert Beyond20 stuff into FoundryVTT stuff, so yes it is. It being in dist means that it's been built for Chrome.

**Comment by kakaroto** [comment]
So... this has been a challenge to fix, but it's done in the dev version now, it shouldn't duplicate dice anymore! 🥳
