### ISSUE TITLE
Staff of Thunder and Lightning does not roll correctly

### ISSUE THREAD

**Issue by Veracity0** [kakaroto/Beyond20#797]
**Describe the bug**
I use Beyond20 to connect DnDBeyond with Roll20.
I have a character with the "Staff of Thunder and Lightning".
That is a +2 Quarterstaff with 5 extra once-per-day effects it can create.
Just like any other weapon, there are red hexes with B's at various places on the Action line.
Unlike other weapons, clicking on the Bs does not roll dice. Instead, Roll20 displays the description of the item

**To Reproduce**
1. Create a DDB character with a Staff of Thunder and Lightning.
2. Equip and attune the item
3. Go to 'Actions' and 'Attack'
4. Click on B at the left 
5. In Roll20, instead of seeing the attack and 2 possible damage rolls, the item description is displayed

**Expected behavior**
I expect to see an attack roll and 2 possible damage rolls - one-handed and two-handed

**Screenshots**
Here is a screenshot of a character with two "versatile" weapons: a longsword and the Staff of Thunder and Lightning.

![image](https://user-images.githubusercontent.com/83725298/119410163-65a03500-bcb6-11eb-9ad1-e89432b4167a.png)

Here is a screen shot of what I get in Roll20 when I click the B associated with the weapon symbol at the left of the Longsword:

![image](https://user-images.githubusercontent.com/83725298/119410389-caf42600-bcb6-11eb-97ea-b04bf39742be.png)

Here is a screen shot of what I get in Roll20 when I click the B associated with the weapon symbol at the left of the Staff of Thunder and Lightning:

![image](https://user-images.githubusercontent.com/83725298/119410557-0989e080-bcb7-11eb-9ca0-1021e85b3e87.png)

**Browser Info (please complete the following information):**
 - Browser Chrome
 - Version 90.0.4430.212 (Official Build) (arm64)
 - I see no errors, as such: I see a request being sent and received.

**Additional context**

Here is the character that I used to reproduce this issue:

https://ddb.ac/characters/40007842/XvdjEb

**Comment by Aeristoka** [comment]
https://beyond20.here-for-more.info/faq#why-doesnt-beyond20-allow-me-to-make-a-melee-attack-with-my-magic-staffs
