### ISSUE TITLE
Long Rest freezing Chrome browser

### ISSUE THREAD

**Issue by SuperSwank** [kakaroto/Beyond20#803]
**Describe the bug**
Whenever I try to take a long rest since the update, it freezes my chrome screen

**To Reproduce**
1. Open DnDBeyond character sheet
2. Select 'Long Rest' option at the top

**Expected behavior**
The screen will freeze and/or become unresponsive

**Browser Info (please complete the following information):**
 - Chrome
 - Version 90.0

**Additional context**
Didn't happen until today and I've seen a few others having the same issue.

**Comment by Aeristoka** [comment]
Is fixed in Dev right now, will be released in 2.4.3

**Comment by SuperSwank** [comment]
Many thanks!

**Comment by Aeristoka** [comment]
https://github.com/kakaroto/Beyond20/commit/e340fecd9bb4a12ea6faa6f3364b19195157f79a I believe

**Comment by Aeristoka** [comment]
Fixed in e340fecd9bb4a12ea6faa6f3364b19195157f79a
