### ISSUE TITLE
I have to select the roll visibility each time that I click on the roll from the character sheet. 

### ISSUE THREAD

**Issue by pawnshop23** [kakaroto/Beyond20#805]
**Describe the bug**
Each roll is asking me to select TO:  before the the roll is executed. I have the default set to Everyone.

**To Reproduce**
1. Go to 'actions"
2. Click on 'longsword'
3. Scroll down to 'Roll and select "everyone, dm or self'
4. Error is that other players don't have to do this for each roll.

**Expected behavior**
I would expect it to default to Everyone, as everyone is my selected default. I can verify this in the roll log window.

<img width="1113" alt="Screen Shot 2021-06-01 at 9 44 34 PM" src="https://user-images.githubusercontent.com/85210578/120422216-6a578f80-c32d-11eb-810b-b14688161963.png">

**Browser Info (please complete the following information):**
 - Browser  - Chrome
 - Version - Version 90.0.4430.212

**Additional context**
1 other player in my group has the same issue, 3 others do not. We can't seem to see any difference between us.

**Comment by pawnshop23** [comment]
In the screenshot it looks like I manually select the d20 and d10. However, those selections happened when I clicked the beyond20 icon in my attack actions.

**Comment by Aeristoka** [comment]
This is a DnDBeyond issue with their Digital Dice, not anything Beyond20 has done.

DnDBeyond apparently released their "Targeted Digital Dice" update.

**Comment by trekie80** [comment]
Adding to this, after having selected a roll type, Beyond20 will no longer roll further dice until page refresh.
i.e. can only roll one die per page load.

**Comment by Aeristoka** [comment]
@kakaroto I don't know if Beyond20 needs anything here, but DnDBeyond broke the crap out of things with this sudden push.

All: Workaround, Disable Digital Dice (sorry, that's just the way).
