### ISSUE TITLE
Do not query for Advantage/Disadvantage when rolling custom dice

### ISSUE THREAD

**Issue by doug-w** [kakaroto/Beyond20#806]
**Describe the bug**
I use the encounter builder to keep track of wildshapes.  When I select a monster in the encounter and click an attack from the stat block, the pop-up to roll with advantage/disadvantage pops up.  When I select either, it does a single roll in Out of the Abyss.

**To Reproduce**
1. Login to roll20 and start a game
2. Go to https://www.dndbeyond.com/monsters/brown-bear
3. Click the +6 link in Bite under actions
4. Select Advantage under 'Select roll mode'
5. Observe Roll20 only rolls a single Bite.

**Expected behavior**
Roll20 should show the same outcome as if the action was taken from the character stat block.

**Screenshots**
![image](https://user-images.githubusercontent.com/202737/120572628-28802500-c3d1-11eb-8c85-f506abac77b4.png)

![image](https://user-images.githubusercontent.com/202737/120572655-3170f680-c3d1-11eb-8ed2-51960b0c6f6d.png)

**Browser Info (please complete the following information):**
 - Chrome
 - Version 90.0.4430.212 (Official Build) (64-bit)
 -No Errors

**Additional context**
Same problem showed in an encounter (which is where I originally found it) but the monsters page is an easier repro.

**Comment by Aeristoka** [comment]
Please specify WHERE you clicked by circling it in the screenshot.

**Comment by Aeristoka** [comment]
In example, here, just fine:
![image](https://user-images.githubusercontent.com/7988297/120573349-aac11700-c3da-11eb-9b83-7f07b1923291.png)
![image](https://user-images.githubusercontent.com/7988297/120573370-b3195200-c3da-11eb-90b4-bcdcdcecf862.png)

Here, doesn't take the Advantage:
![image](https://user-images.githubusercontent.com/7988297/120573404-c3c9c800-c3da-11eb-8600-51e7e214eb01.png)
![image](https://user-images.githubusercontent.com/7988297/120573421-ca583f80-c3da-11eb-989e-b1f7d9a205f8.png)

**Comment by doug-w** [comment]
You are correct, it was the 2nd case not the first.  I'll edit
