### ISSUE TITLE
Beyond20 apparently crashing D&D Beyond Encounter Tracker

### ISSUE THREAD

**Issue by KeithAmmann** [kakaroto/Beyond20#809]
Sometime between last Wednesday (May 26) and this Tuesday (June 1), a change was made to either Beyond20 or D&D Beyond that has resulted in serious slowdowns and frequent crashes in the D&D Beyond Encounter Tracker. These crashes bring down encounters in progress, requiring re-entry of all initiative rolls and adjustments to character/creature hit points.

My own encounters are probably not publicly accessible, but in [this encounter](https://www.dndbeyond.com/encounters/68098a9e-509c-4b10-8c13-bac4c30997e2), with Roll20 and Beyond20 running, clicking on Tiamat's stat block followed by clicking on the stat block of the Red Mage of the Arcane Brotherhood causes the crash every time. When I disable Beyond20, that same sequence of clicks does not cause a crash. When I re-enable it, it causes the crash again.

**Screenshots**
I'm running this encounter:

![image](https://user-images.githubusercontent.com/85315670/120708028-a8b19380-c480-11eb-9e20-2c54d61ce654.png)

Here it is under way, with Tiamat's stat block opened up:

![image](https://user-images.githubusercontent.com/85315670/120708069-b535ec00-c480-11eb-9ec4-d9aa57c8c990.png)

Now I click to open the Red Mage stat block, and …

![image](https://user-images.githubusercontent.com/85315670/120708099-c1ba4480-c480-11eb-8b82-854b4184ca87.png)

… kaboom.

Beyond20 settings:
![image](https://user-images.githubusercontent.com/85315670/120707699-48225680-c480-11eb-8608-fced983d8024.png)
![image](https://user-images.githubusercontent.com/85315670/120707827-6a1bd900-c480-11eb-8278-67c7364ce2e4.png)
![image](https://user-images.githubusercontent.com/85315670/120707917-828bf380-c480-11eb-8901-8d407066f38e.png)
![image](https://user-images.githubusercontent.com/85315670/120707957-8fa8e280-c480-11eb-840f-00a36df3f493.png)

**Browser Info (please complete the following information):**
I'm running Firefox v88.0.1 under Windows 10.

**Comment by kakaroto** [comment]
Hi,
This started happening a few weeks ago. You can see the original report here : #775 
This seems to happen when you have a mix between homebrew monsters and non homebrew monsters. The encounter UI simply crashes if the statblock is modified as it conflicts with the digital dice modifying the statblock itself... 
The solution was to disable the "replace dice formulas" option in beyond20, but I just tested with the link you sent me and it appears that it does work now with the dice formulas replaced, but to prevent it from crashing you need to disable the "add roll buttons to stat blocks" instead.. so they clearly made some changes to fix things, but it didn't fix everything.
Note that I have reported the issue to D&D Beyond already, and it's up to them to fix it at this point.
Closing as duplicate/wontfix.
Thanks

**Comment by KeithAmmann** [comment]
How is it up to D&D Beyond to fix? D&D Beyond doesn't crash on me when I'm not using Beyond20. If there's a crash-causing conflict between Beyond20 and D&D Beyond, and D&D Beyond is stable on its own, it seems like the responsibility for solving the problem is on the developers of Beyond20.

Basically what you're telling me is that there's a function of Beyond20 that doesn't work with homebrew monsters, and the only way to deal with it is to nerf Beyond20's overall functionality … and that this is actually D&D Beyond's fault?

God, I can't wait to get back to F2F play.

**Comment by Aeristoka** [comment]
> How is it up to D&D Beyond to fix? D&D Beyond doesn't crash on me when I'm not using Beyond20. If there's a crash-causing conflict between Beyond20 and D&D Beyond, and D&D Beyond is stable on its own, it seems like the responsibility for solving the problem is on the developers of Beyond20.
> 
> Basically what you're telling me is that there's a function of Beyond20 that doesn't work with homebrew monsters, and the only way to deal with it is to nerf Beyond20's overall functionality … and that this is actually D&D Beyond's fault?
> 
> God, I can't wait to get back to F2F play.

The bug has to do with how DnDBeyond is adding their digital Dice hooks onto NPCs, that's why.

**Comment by kakaroto** [comment]
> How is it up to D&D Beyond to fix? D&D Beyond doesn't crash on me when I'm not using Beyond20. If there's a crash-causing conflict between Beyond20 and D&D Beyond, and D&D Beyond is stable on its own, it seems like the responsibility for solving the problem is on the developers of Beyond20.
> 
> Basically what you're telling me is that there's a function of Beyond20 that doesn't work with homebrew monsters, and the only way to deal with it is to nerf Beyond20's overall functionality … and that this is actually D&D Beyond's fault?
> 
> God, I can't wait to get back to F2F play.

I'm going to make an extraordinary effort to ignore your sarcastic and asshole-y tone and respond to the actual technical question hidden in that comment:

The ONLY way for D&D Beyond to not crash is if Beyond20 doesn't do ANYTHING AT ALL. The crash is in D&D Beyond's own javascript code which crashes unexpectedly if the page was modified in any way. You could have 100 other extensions in Chrome, if any of them modifies the page, you'd get the same problem, the bug is in D&D Beyond's code, it's up to them to fix it, not to the 100 possible extensions that may or may not be modifying the page. There is nothing that we could do, even if we wanted to.

**Comment by rafamvargas** [comment]
I have the same problem

**Comment by xNymia** [comment]
Has this issue been raised on the dndbeyond support forum, are you making them aware of this issue to see if it can be resolved? I'd rather not spam them with issues if you've already done it. @Aeristoka @kakaroto 

https://www.dndbeyond.com/forums/d-d-beyond-general/bugs-support
