### ISSUE TITLE
Beyond20 Whispered Rolls to FoundryVTT 0.8.6 do not hide properly

### ISSUE THREAD

**Issue by Aeristoka** [kakaroto/Beyond20#810]
**Describe the bug**
Rolls into FoundryVTT 0.8.6 from Beyond20 (with "Whisper Rolls") show in clear text to all players:

**To Reproduce**

1. Roll from DnDBeyond (character or Monster) with "Whisper" configured
2. Weep silently as the rolls aren't obscured from the players as they should be

**Expected behavior**
Rolls should be properly hidden as they were on FoundryVTT up to 0.7.10

**Screenshots**
Player on Left, GM on right (who performed the roll):
![image](https://user-images.githubusercontent.com/7988297/120712966-89b20200-c47e-11eb-8502-2ba20c658068.png)

(the rolls with ??? are a test with "Hide monster and attack name")

FoundryVTT 0.7.9/10 behavior:
![image](https://user-images.githubusercontent.com/7988297/120713204-ce3d9d80-c47e-11eb-82ba-5a5297cfe711.png)

(Purely Guesswork, but maybe related to this? https://gitlab.com/foundrynet/foundryvtt/-/issues/4780 )

**Comment by kakaroto** [comment]
Nice catch, it does seem to be a side effect of 4780 (I didn't think so at first, but digging in the code, that was actually it), but this is a Foundry bug, not a Beyond20 bug to be honest. There is nothing for me to do, Foundry should not be showing the message content in the case of a whisper.
I'll file it back with Foundry.
Thanks!

**Comment by Aeristoka** [comment]
> Nice catch, it does seem to be a side effect of 4780 (I didn't think so at first, but digging in the code, that was actually it), but this is a Foundry bug, not a Beyond20 bug to be honest. There is nothing for me to do, Foundry should not be showing the message content in the case of a whisper, and I have no way to prevent it from doing so.
> I'll file it back with Foundry.
> Thanks!
> 
> EDIT: Filed here : https://gitlab.com/foundrynet/foundryvtt/-/issues/5302

I think you missed my Step #2 above, you can 100% do that

**Comment by kakaroto** [comment]
LOL, yeah, I can still do that. :D
