### ISSUE TITLE
Digital Dice - Totals Bar and Duplicate Damage Values For Versatile Weapons

### ISSUE THREAD

**Issue by amenokos** [kakaroto/Beyond20#814]
**Describe the bug**
When DDB's Digital Dice are enabled in Beyond 20's settings, a _Totals_ bar and duplicate damage values are displayed in the Roll20 game log when attacking with **versatile weapons**.

**To Reproduce**
1. Within Beyond 20's settings, toggle _Use D&D Beyond's Digital Dice_ on.
2. Initiate a combo roll (attack & damage) for a versatile weapon. 
3. In Roll20, see that an attack roll is displayed with both one-handed and two-handed damage, but that information is followed by a blank _Totals_ bar and the same one-handed and two-handed damage values previously shown.
4. Disable _Use D&D Beyond's Digital Dice_, and initiate a combo roll (attack & damage) for a versatile weapon.
5. In Roll20, see that an attack roll is displayed with both one-handed and two-handed damage, but the additional boxes are not displayed.

**Expected behavior**
Why would toggling the Digital Dice option cause the rolls to be displayed differently in Roll20's game log? Toggling the _Use D&D Beyond's Digital Dice_ feature shouldn't modify how the rolls are displayed in Roll20. Preferably, the _Totals_ bar and duplicate damage values should not be displayed. If the Totals bar and additional damage display serve a purpose, why is it not displayed when Digital Dice are turned off?

**Screenshots**
With Digital Dice turned ON: 
![image](https://user-images.githubusercontent.com/69495414/120879318-8149ec00-c590-11eb-9f1d-fac334aa3b0d.png)

With Digital Dice turned OFF: 
![image](https://user-images.githubusercontent.com/69495414/120879328-93c42580-c590-11eb-95b5-c880d7526f27.png)

**Browser Info (please complete the following information):**
 - Browser: Chrome Version 90.0.4430.218 (Official Build) (64-bit)

**Comment by kakaroto** [comment]
> If the Totals bar and additional damage display serve a purpose, why is it not displayed when Digital Dice are turned off?

When digital dice aren't enabled, the rolls are made directly by Roll20 and Beyond20 has no way of calculating the totals.
The totals are technically only supposed to appear if there is more than one damage, which in this case there is, it just so happens that each of them is calculated as a separate total. Generally, you only see the totals if you have sneak attack added or rage, or 
using a weapon/spell that deals more than one damage or something of the sort.

In the situation above, yeah, it likely shouldn't show the totals, but note that not setting your versatile preference (to one handed or two handed) will also have some other unfortunate consequences when it comes to other special features handling.
