### ISSUE TITLE
Please disable the "open changelog in new tab on update" setting by defualt.

### ISSUE THREAD

**Issue by BallisticTurtle** [kakaroto/Beyond20#815]
A browser addon for D&D should not be able to randomly open a new tab in my browser when it updates and interrupt my work, or anything else. I would bet money that 95+% of the users of Beyond20 do not want to read the changelog period, let alone have it randomly take control of their browser. Please turn that setting off by default. Thanks for all you do.

**Comment by kakaroto** [comment]
Hi,
I'm sorry if it's causing you issues, but I think that 95+% of users are actually interested in reading the changelog. Those that are not, do have the option to turn it off. Most extensions do the exact same thing, but many of them don't have the option to turn it off. I try to keep releases far and few between, though this week has been pretty chaotic.
Sorry, but I will not be changing the default value for that setting. You have the option to disable it, so simply disable it if it's a problem for you.
Thank you.

**Comment by Alarich** [comment]
As the question is about interrupting work, then it can be turned off in the options. 

Both of your opinions are way off, it's probably more like 15% care, 85% don't, with various levels of caring inbetween. 

But let me remind you that this is also a part on how KaKaRoTo covers their cost of living on this planet and having their work pop up will make it more likely for people to remember to value his work. If the plugin was a fire and forget type - would you know it was updated? Would you know he's still updating it? The answer is no - not unless it breaks - and when it does, he fixes it fairly quickly. 

In case others read this, you can turn it off here:
![image](https://user-images.githubusercontent.com/5496089/120885485-d9fda100-c5f1-11eb-8878-af0bf3c27b14.png)

**Comment by BallisticTurtle** [comment]
> I think that 95+% of users are actually interested in reading the changelog.

Sorry but you're delusional if you truly believe this. It's much more likely you're just lying because having it act like a spam popup directs more people to your patreon, though. Do you know anyone who *enjoys* popups? Hope you're not in a country with laws that make this sort of thing illegal or you'll end up getting sued by someone and shut down eventually. Either way it's been reported as spam. Genuine thanks for the great extension. Shitty to make it spam by default though.

**Comment by BallisticTurtle** [comment]
> But let me remind you that this is also a part on how KaKaRoTo covers their cost of living on this planet and having their work pop up will make it more likely for people to remember to value his work. 

Yea this is called a "popup ad" and "spam" by society. Sorry but "it's for money" isn't a valid excuse for popup spam.

**Comment by pandanielxd** [comment]
Bruh its legit the slightest inconvenience _and_ has the ability to disabled. Is there still any issue after disabling it? If not I think there is not much left to complain about :)).

**Comment by Alarich** [comment]
Friend BallisticTurtle.. there's a way to turn it off. Please do so or stop using the extension if you don't enjoy the experience. 

Technically it's an opt-in popup ad you accepted when installing the plugin as a tool you wish to use, and that's really pushing it. 

Consider the feelings of others when you post online. But thank you for the feedback in general.

**Comment by kakaroto** [comment]
Please do me a favor and uninstall the extension. You don't like "spam" as you call it, then disable it. You don't like to have to click one button to disable a functionality that you don't like, and it's somehow my responsibility to save you that one click? 
Well, I don't like having to read these kinds of messages after working countless hours on releasing a free and open source tool that people actually use and enjoy and which makes their games easier. Feel free to fork the project and maintain it and have that option disabled by default in your fork.
Your comments reaching my inbox are the spam. After a long day/week/year, reading what you wrote is worse on me, my morale and my general mental stability than any popup could ever have on your life. You calling me a liar and delusional and threatening me with lawsuits (wait, did you really just do that?) is the actual "spam" that nobody wants to receive.

Please uninstall the extension if you do not like its features.
Thank you, and have a pleasant day!
