### ISSUE TITLE
Whisper rolls feature not working

### ISSUE THREAD

**Issue by ryanmcfitz72** [kakaroto/Beyond20#818]
I have not been able to get Whisper Rolls to work during gameplay this evening. It used to work — now it doesn’t.

I have been using B20 to connect to the Astral VTT over Chrome.

Restarting the browser several times had no effect. Logging in and out of DDB or in/out of Astral has no effect. No luck restarting PC either. Toggling “whisper rolls” off and on again had no effect.

Is this happening to anyone else?

**Comment by martin-clarke** [comment]
I have this exact same problem in Foundry VTT, using chrome.

**Comment by Aeristoka** [comment]
> I have not been able to get Whisper Rolls to work during gameplay this evening. It used to work — now it doesn’t.
> 
> I have been using B20 to connect to the Astral VTT over Chrome.
> 
> Restarting the browser several times had no effect. Logging in and out of DDB or in/out of Astral has no effect. No luck restarting PC either. Toggling “whisper rolls” off and on again had no effect.
> 
> Is this happening to anyone else?

Astral I'll leave to @adriangaro  to answer.

**Comment by Aeristoka** [comment]
> I have this exact same problem in Foundry VTT, using chrome.

If it's FoundryVTT 0.8.6, this is a core FoundryVTT bug (an on-purpose change to FoundryVTT that lead to a whole bunch of crap breaking): https://gitlab.com/foundrynet/foundryvtt/-/issues/5302#note_593631352

**Comment by martin-clarke** [comment]
> 
> 
> > I have this exact same problem in Foundry VTT, using chrome.
> 
> If it's FoundryVTT 0.8.6, this is a core FoundryVTT bug (an on-purpose change to FoundryVTT that lead to a whole bunch of crap breaking): https://gitlab.com/foundrynet/foundryvtt/-/issues/5302#note_593631352
> 
> So your two reports here are 100% unrelated, but the FoundryVTT side will be fixed in FoundryVTT 0.8.7

Thank you for the quick response and clear explanation :)

**Comment by adriangaro** [comment]
The whisper issue might have something to do with the fact that Astral integration might run in a fallback mode. Does by any chance all the messages sent to astral chat not have a colored border? If that's the case that's enough confirmation of the fallback mode. I have been trying to track the source of the issue and from what I gathered is some finicky shite in the firebase indexdb which contains some junk that fucks up the access token acquisition. Have seen this before on other users, although never managed to replicate it locally. Will try to see if I can make the access token acquisition logic more strict to not fail.

**Comment by adriangaro** [comment]
One quick fix, in case the above mentioned fallback mode is happening (no colored borders) would be to open dev tools in chrome, enter the application tab, go to storage, and press "Clear site data" this should technically clean the firebase indexedDB and would be recreated when logging in again, hopefully, this time without the junk.

**Comment by ryanmcfitz72** [comment]
My whispered texts are not showing up with colored borders, so that
suggests fallback mode is not occurring.

I followed your instructions for clearing site data and that resolved the
issue. Once I logged back into both D&D Beyond and Astral, whispered rolls
work correctly.

Thanks so much for the suggestions!

Cheers,
Ryan

**Comment by kakaroto** [comment]
Awesome, thanks @adriangaro for the suggestion/fix!
