### ISSUE TITLE
Can't whisper rolls in Foundry VTT (maybe caused by Foundry 0.8.x update)

### ISSUE THREAD

**Issue by ejrinkus** [kakaroto/Beyond20#819]
**Describe the bug**
When using Foundry VTT and rolling from D&D Beyond, trying to whisper rolls results in a weird mixture where the chat message in Foundry says the roll was private, but it still displays the result.

**To Reproduce**
1. In Foundry, Private GM Roll or Self Roll selected
2. Make any (Public or Whisper) roll in D&D Beyond
3. See the roll in Foundry indicating it was private, but still shows the results to all other players

Alternatively, have Public Roll selected in Foundry, and make a Whisper roll: same result.

**Expected behavior**
If a private roll appears in Foundry from D&D Beyond, it should not show the result to other players.  More precisely, the roll in Foundry should respect the _stricter_ of the two privacy settings between Beyond 20:

| Foundry Setting | Beyond20 Setting | Result |
|-------------------|---------------------|--------|
| Public                 | Public                    | Public |
| Public                 | Whisper                 | Private between player and GM |
| Private GM Roll  | Public                    | Private between player and GM |
| Private GM Roll  | Whisper                 | Private between player and GM |
| Blind GM Roll     | Public                    | Private to GM |
| Blind GM Roll     | Whisper                 | Private to GM |
| Self Roll              | Public                    | Private to player |
| Self Roll              | Whisper                 | Private to player |

**Screenshots**
Selecting a Whisper roll in Beyond 20 with Self Roll selected in Foundry:
![image](https://user-images.githubusercontent.com/2413883/121297762-0c3c2680-c8b0-11eb-963d-5a6df03921db.png)

Roll has the lavender background expected for a private roll:
![image](https://user-images.githubusercontent.com/2413883/121297883-37267a80-c8b0-11eb-98b9-be9d6ee8f0a0.png)

However, it's still visible by other players:
![image](https://user-images.githubusercontent.com/2413883/121297917-473e5a00-c8b0-11eb-9483-7615b4907e4d.png)

**Browser Info (please complete the following information):**
 - Browser: Chrome
 - Version: 91.0.4472.77

**Additional context**
I upgraded my Foundry instance to 0.8.6 today, and we only noticed this problem during tonight's session.  It looks like Foundry's Beyond 20 plugin is still targeting 0.7.x, so I'm seeing a compatibility warning on that plugin.  Could be that this is caused by changes in the new version of Foundry.

**Comment by kakaroto** [comment]
It is indeed a Foundry 0.8.6 bug, which should be fixed in 0.8.7 (planned for next week I believe), you can see the discussion around it here : https://gitlab.com/foundrynet/foundryvtt/-/issues/5302

**Comment by ejrinkus** [comment]
Of course!  As a fellow engineer I know the pain of getting poorly or tactlessly written bug reports, haha.

Thanks for following up with the link to the other issue as well!  Apologies for not finding it sooner, I didn't realize that you're using gitlabs too.  I'll try to keep an eye on that one in the future.  Good to know this is fixed in 0.8.7, I'll have to do that upgrade this week.

**Comment by kakaroto** [comment]
Foundry itself isn't open source, but they use a public bug tracker. I think the source in that repo is for the website's knowledgebase.
Note that it was confirmed fixed in 0.8.7 :)
