### ISSUE TITLE
Encounter Builder keeps crashing on DndBeyond

### ISSUE THREAD

**Issue by ysoki** [kakaroto/Beyond20#820]
For the past two weeks, switching between tabs in the encounter builder in D&DBeyond causes the encounter to crash.  When Beyond20 is disabled this no longer happens, so I think it's due to Beyond20 rather than an internal D&DBeyond issues.  Just trying to confirm if this is a known bug?

**Comment by Aeristoka** [comment]
Duplicate of #775 , workaround on that issue, the main fault lies with DnDBeyond.
