### ISSUE TITLE
Update for FoundryVTT 0.8.x?

### ISSUE THREAD

**Issue by PhluXx1** [kakaroto/Beyond20#821]
Hi, thanks for this great module my party and I really love it. 

Do you have any plans to update Beyond20 to the new 0.8.6 version on FoundryVTT? If so can you please give a time frame? 

Currently it's incompatible with the latest Foundry version and can't be found or downloaded in the module installer.

**Comment by Aeristoka** [comment]
> Hi, thanks for this great module my party and I really love it.
> 
> Do you have any plans to update Beyond20 to the new 0.8.6 version on FoundryVTT? If so can you please give a time frame?
> 
> Currently it's incompatible with the latest Foundry version and can't be found or downloaded in the module installer.

Beyond20 works just fine with FoundryVTT 0.8.6, what issues are you seeing?

**Comment by PhluXx1** [comment]
> Beyond20 works just fine with FoundryVTT 0.8.6, what issues are you seeing?

You can't download it in the module installer. Beyond20 is currently listed as compatible with 0.4.4 - 0.6.2. Since the 0.8.6 update you can't download it in-game it doesn't show up as an option.

**Comment by Aeristoka** [comment]
> > Beyond20 works just fine with FoundryVTT 0.8.6, what issues are you seeing?
> 
> You can't download it in the module installer. Beyond20 is currently listed as compatible with 0.4.4 - 0.6.2. Since the 0.8.6 update you can't download it in-game it doesn't show up as an option.

You're talking about the `Chat Damage Buttons - Beyond20 Edition`, which is not by KaKaRoTo. It still works perfectly fine in FoundryVTT 0.8.6, but it has been delisted (and the GitHub deleted), though the functionality will at some point be absorbed into the `Beyond20 Companion Module`

**Comment by PhluXx1** [comment]
You're talking about the `Chat Damage Buttons - Beyond20 Edition`, which is not by KaKaRoTo.

No, you're wrong. Please stop assuming what I'm talking about I was very clear in what the problem is. See the link below to the module I'm referring to which is infact made by KaKaRoTo and is experiencing the problem:
https://foundryvtt.com/packages/beyond20

**Comment by Aeristoka** [comment]
> You're talking about the `Chat Damage Buttons - Beyond20 Edition`, which is not by KaKaRoTo.
> 
> No, you're wrong. Please stop assuming what I'm talking about I was very clear in what the problem is. See the link below to the module I'm referring to which is infact made by KaKaRoTo and is experiencing the problem:
> https://foundryvtt.com/packages/beyond20

https://github.com/kakaroto/Beyond20/blob/master/FVTT-module/beyond20/module.json

Clearly says up to 0.7.10:
![image](https://user-images.githubusercontent.com/7988297/121446011-df3f5080-c94f-11eb-991c-c70e024dca84.png)

The FoundryVTT.com site is by no means the authority for how up-to-date a Module is, it often is VERY out of date.

**Comment by Aeristoka** [comment]
> You're talking about the `Chat Damage Buttons - Beyond20 Edition`, which is not by KaKaRoTo.
> 
> No, you're wrong. Please stop assuming what I'm talking about I was very clear in what the problem is. See the link below to the module I'm referring to which is infact made by KaKaRoTo and is experiencing the problem:
> https://foundryvtt.com/packages/beyond20

You can also install it by providing the manifest url: https://raw.githubusercontent.com/kakaroto/Beyond20/master/FVTT-module/beyond20/module.json to the Modules section of FoundryVTT 0.8.6. It works perfectly fine in 0.8.6.

**Comment by PhluXx1** [comment]
Ok, thanks I'll try that.

**Comment by kakaroto** [comment]
I've added the 1.2 version to the Foundry website. The release was made in September 2020, the website was just never updated to reflect that.
Thanks for letting me know!

**Comment by PhluXx1** [comment]
> 
> 
> I've added the 1.2 version to the Foundry website. The release was made in September 2020, the website was just never updated to reflect that.
> Thanks for letting me know!

I really appreciate you getting back to me on this and getting it resolved. Many thanks and have a great day.
