### ISSUE TITLE
Can't save class feature description for custom subclass on dndbeyond when typing dice rolls.

### ISSUE THREAD

**Issue by SkootNoog** [kakaroto/Beyond20#822]
**Describe the bug**
**ONLY WHEN THE ADDON IS ENABLED DOES THIS BUG HAPPEN**
On dndbyond.com, when you are creating a custom subclass they have features. When editing these features, you cannot save the description of them if they contain a dice roll like "1d10".

**To Reproduce**
1. Go to https://www.dndbeyond.com/homebrew/creations/create-subclass
2. Create a subclass and save it
3. Add a class feature and fill in information
4. Put a dice roll in the description, for me it happened when I typed 1d10 in the description.
5. Can't save the description. (Or load a description with a dice roll in it I think)

**Expected behavior**
I would expect to be able to save a description typed into dnd beyond.

**Screenshots**

Before pressing Save Changes
![image](https://user-images.githubusercontent.com/19879424/121468984-53461c80-c981-11eb-9252-cc3552fb722f.png)

After pressing Save Changes
![image](https://user-images.githubusercontent.com/19879424/121469052-6e189100-c981-11eb-886b-8fa3ee9294d4.png)

**Browser Info (please complete the following information):**
 - Browser: Brave
 - Version 1.25.70 Chromium: 91.0.4472.77
 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT

**Additional context**
Add any other context about the problem here, such as a link to the character sheet or D&D Beyond page that shows the problem.

**Comment by kakaroto** [comment]
This has nothing to do with Beyond20, and it seems to be a D&D Beyond specific issue.
In case you were confused, Beyond20 is a chrome/firefox extension to make rolls from D&D Beyond into an external virtual tabletop.

**Comment by SkootNoog** [comment]
I mean I'm not confused. I'm just letting you know that disabling this addon makes it work on their website. So it is an issue the addon is causing.

**Comment by Aeristoka** [comment]
> I mean I'm not confused. I'm just letting you know that disabling this addon makes it work on their website. So it is an issue the addon is causing.

I think the issue is you didn't mention that anywhere in your issue.

**Comment by SkootNoog** [comment]
Ah that one is on me. But yeah the issue only exists when the beyond20 addon is enabled.

**Comment by DarrynGlass** [comment]
Wow.,.. yeah I can confirm this.  Not only does it NOT save anything, it also deletes EVERYTHING you have in the description field (good thing that subclass was a WIP, lol).  Disabling Beyond20 resolves this issue.  I duplicated it in Chrome.

**Comment by Aeristoka** [comment]
@SkootNoog @DarrynGlass Can you both pull open your Browser Dev Consoles while doing this, click on the "Console" tab, and replicate it? Looking for errors on the Dev Console that might help indicate what is happening here.

**Comment by DarrynGlass** [comment]
I just tried this is Edge also, but I don't see ANY error in Edge at all, with or without the extension enabled.  Very odd

**Comment by kakaroto** [comment]
Thanks, I can definitely reproduce it on my side as well and can confirm it only happens with Beyond20 enabled.
This is pretty bad, so thanks for bringing it to our attention!
