### ISSUE TITLE
Foundry VTT Better CSS Styling

### ISSUE THREAD

**Issue by LorduFreeman** [kakaroto/Beyond20#823]
The current CSS style of Beyond20 rolls does not fit the Foundry VTT basic style. I suggest updating the CSS styles for Foundry to a better visual fit, maybe adhering to the same styles as the regular in-VTT rolls do. This would be beneficial for any mod that changes the Foundry CSS styling (like UI mods) and keep the visuals consistent.

For the basic Foundry look I've written a few lines of CSS to get a consistent look, currently using them privately. Pastebin here: https://pastebin.com/5brpwYNQ

![csshacks](https://user-images.githubusercontent.com/72170114/121682840-de77fd00-cabc-11eb-858a-f8e16b53fc40.png)

**Comment by kakaroto** [comment]
Hi, thanks! 
Unfortunately, CSS is not one of my strengths, so the current CSS/html of how the rolls appear is actually the same that was written for me by someone on the Foundry Discord back when I first added support for it (I think back in May or June 2019).
I do like the style you've showed in the screenshot and would gladly accept that as contribution, so please send a pull request with the change and I'll merge it!
Thanks!

**Comment by LorduFreeman** [comment]
Pull request sent!
