### ISSUE TITLE
Bard: College of Spirits - Spiritual Focus Support

### ISSUE THREAD

**Issue by DarrynGlass** [kakaroto/Beyond20#825]
Support for the new classes in VAN RICHTEN’S GUIDE TO RAVENLOFT

Bard: College of Spirits

**Spiritual Focus**
3rd-level College of Spirits feature

You employ tools that aid you in channeling spirits, be they historical figures or fictional archetypes. You can use the following objects as a spellcasting focus for your bard spells: a candle, crystal ball, skull, spirit board, or tarokka deck.

Starting at 6th level, **when you cast a bard spell that deals damage or restores hit points** through the Spiritual Focus, roll a **_d6_**, and you gain a bonus to one damage or healing roll of the spell equal to the number rolled.

**Comment by DarrynGlass** [comment]
Character
https://www.dndbeyond.com/profile/echmyr/characters/52354669

**Comment by DarrynGlass** [comment]
As an added note, the tables do not appear to be rollable either.
https://www.dndbeyond.com/classes/bard#CollegeofSpirits
![image](https://user-images.githubusercontent.com/29684482/121990314-2e77ed80-cd63-11eb-893c-36af4afaec72.png)

If you need to be invited to a campaign to see the book let me know and I will send you an invite to one.

**Comment by cgplayer2000** [comment]
I can confirm that the table doesn't seem to be rollable.  The die that you roll is whatever is your bardic inspiration die, which of course depends on the level.

**Comment by kakaroto** [comment]
> As an added note, the tables do not appear to be rollable either.
> https://www.dndbeyond.com/classes/bard#CollegeofSpirits
> ![image](https://user-images.githubusercontent.com/29684482/121990314-2e77ed80-cd63-11eb-893c-36af4afaec72.png)
> 
> If you need to be invited to a campaign to see the book let me know and I will send you an invite to one.

The table wouldn't be rollable, because that is not a dice formula in the first column. "Bardic inspiration die" will be different depending on the character, so it's not something doable. It likely could prompt for the die to use though 🤔 Can you please file a separate issue for that ? 
Thanks

**Comment by DarrynGlass** [comment]
Will do!
