### ISSUE TITLE
Support Warlock: The Undead - Grave Touched feature

### ISSUE THREAD

**Issue by DarrynGlass** [kakaroto/Beyond20#828]
Support for the new classes in VAN RICHTEN’S GUIDE TO RAVENLOFT

Not sure this one is doable because it is based on the damage die of your attack, but wanted to put it out here in case.
Character
https://www.dndbeyond.com/profile/echmyr/characters/52375493/builder#/ability-scores/manage

Warlock: The Undead

Grave Touched
6th-level Undead feature

Your patron’s powers have a profound effect on your body and magic. You don’t need to eat, drink, or breathe.

In addition, once during each of your turns, when you hit a creature with an attack roll and roll damage against the creature, you can replace the damage type with necrotic damage. **While you are using your Form of Dread, you can roll one additional damage die when determining the necrotic damage the target takes.**

**Comment by pandanielxd** [comment]
Could probably be a toggle/hotkey feature

**Comment by Aeristoka** [comment]
> Could probably be a toggle/hotkey feature

I've been thinking about it, it's gonna be a Toggle that toggles off after each use, like Sharpshooter/Great Weapon Master

**Comment by Aeristoka** [comment]
> Support for the new classes in VAN RICHTEN’S GUIDE TO RAVENLOFT
> 
> Not sure this one is doable because it is based on the damage die of your attack, but wanted to put it out here in case.
> Character
> https://www.dndbeyond.com/profile/echmyr/characters/52375493/builder#/ability-scores/manage
> 
> Warlock: The Undead
> 
> Grave Touched
> 6th-level Undead feature
> 
> Your patron’s powers have a profound effect on your body and magic. You don’t need to eat, drink, or breathe.
> 
> In addition, once during each of your turns, when you hit a creature with an attack roll and roll damage against the creature, you can replace the damage type with necrotic damage. **While you are using your Form of Dread, you can roll one additional damage die when determining the necrotic damage the target takes.**

I can't access that character sheet.

**Comment by DarrynGlass** [comment]
Sorry I grabbed the wrong URL.  I was in the builder still

https://www.dndbeyond.com/profile/echmyr/characters/52375493
