### ISSUE TITLE
Add the Hand of Harm feature for monks (similar how the crimson rite or sneak attack features work )

### ISSUE THREAD

**Issue by XRamusX** [kakaroto/Beyond20#837]
**Is your feature request related to a problem? Please describe.**
Nope , just a feature i hope it will be added cause i am playing a way of mercy monk right now and since there is not a feautre to do the damage for hand of harm in one roll , its harder to calculate damage when i get a critical hit 

**Describe the solution you'd like**
A feature that i can set a hotkey for ( i would have just used the normal hotkeys but you cant add modifiers to the damage rolls ) ,so i can choose to activate the feature when i want it and if i happen to crit it will also calculate the damage along with the normal roll .Just something that i can put on a hotkey (since you can add features to hotkeys and you can't add modifiers to normal damage rolls )
**Describe alternatives you've considered**
-----

**Additional context**
----
![1](https://user-images.githubusercontent.com/64174699/123567819-afa39b80-d7cb-11eb-8d5e-7216777b1204.PNG)
![2](https://user-images.githubusercontent.com/64174699/123567824-b03c3200-d7cb-11eb-80c3-14dfe89cccfd.PNG)

**Comment by kakaroto** [comment]
Hi,
Sorry but I don't think this is a feature I'd like to add to Beyond20, as that actually consumes Ki point, it's a special ability that you have to use. If I was to make it an option for the hotkeys (and therefore a togglable option in the character settings), then there would be no reason not to do the same for every other Ki ability, or channel divinity, or divine smite, or even spell.
The only options we add are for things that you would potentially have always-on, or if it affects how the actual roll is made (like Sharpshooter), but in this case, you make your attack, if it hits, you can decide to use Hand of Harm and roll it from your abilities. It's also a decision that gets taken **after** making the attack and only if it hits, not before attacking, so it makes no sense to enable it pre-emptively.
Thanks.
