### ISSUE TITLE
Flames of Phlegethos

### ISSUE THREAD

**Issue by BlerkMcgurk** [kakaroto/Beyond20#841]
Recently after a new update, the Flames of Phlegethos Tiefling Feat no longer automatically rerolls 1's on a fire damage in a spell. I don't know if this bug affects other similar Feats like Great Weapon Master, but it most definitely affects this current Feat.
![Problemo](https://user-images.githubusercontent.com/86864611/124342198-1b448a80-db77-11eb-88e0-88fffd72dc28.png)

**Comment by Aeristoka** [comment]
Good catch, this is something DnDBeyond just change on their side:
![image](https://user-images.githubusercontent.com/7988297/124343754-3caf7180-db8b-11eb-86e7-d2e6344c0d08.png)

All Damage Types for Spells are (apparently) now presented in LowerCase, instead of properly capitalized.
