### ISSUE TITLE
HP from DND Beyond only works if HP Management open

### ISSUE THREAD

**Issue by G1raffe** [kakaroto/Beyond20#844]
**Describe the bug**
Roll 20 HP will not update from DND beyond if using the quick Heal/dmg overview from the character sheet but now it will only work from the HP management sheet.

**To Reproduce**

1. have a working roll20 token with hp in the attributes section on a 5e sheet linked to dnd beyond
2. use the quick heal/dmg function - no show on token
3. open hp management and heal/dmg will now update
4. happy to show an example via discord.

**Expected behavior**

For the past 9 months we've been able to update our roll 20 token HP from Dnd beyond "quick HP heal/dmg" but now this will only update if you open the full HP management tab.

**Screenshots**
To help explain your problem, add screenshots of where you clicked in D&D Beyond, a screenshot of your Beyond20 character settings if applicable and the result you saw in the VTT.
![image](https://user-images.githubusercontent.com/87026912/124621554-48908180-de72-11eb-875e-13bc2ac412a4.png)

**Browser Info (please complete the following information):**
 - Browser [e.g. chrome, firefox] Chrome
 - Version [e.g. 85] Current
 - If applicable, any dev console errors (F12 to open the console) from D&D Beyond and the VTT

**Additional context**
Add any other context about the problem here, such as a link to the character sheet or D&D Beyond page that shows the problem.

**Comment by Aeristoka** [comment]
Already fixed in #840 , you can install the Dev Version here: https://github.com/kakaroto/Beyond20#developer-mode-installation , or wait for an official release with the fix.
