### ISSUE TITLE
Port the extension to Manifest V3

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#845]
MV2 is being phased out and should reach EOL soon.
Need to port to MV3 : https://developer.chrome.com/docs/extensions/mv3/intro/

**Comment by kakaroto** [comment]
Looks like firefox is getting ready to support it : https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/

**Comment by kakaroto** [comment]
Looks like we'll have to move to it by next year maximum
![image](https://user-images.githubusercontent.com/27990/144562657-6999a687-66c8-487f-b034-f95b5a0efd3e.png)

https://developer.chrome.com/blog/mv2-transition/

**Comment by kakaroto** [comment]
Chrome will disable all manifest v2 extensions by january, so we need to switch it to v3 before then. Changing milestone to next version

**Comment by kakaroto** [comment]
Reopening since I've reverted back to MV2 in commit ab19b3dd571969f211202e094a9dac75ffd1243f

This is their new timeline : 
![image](https://user-images.githubusercontent.com/27990/201501897-779ed5f9-0955-452f-ad54-6c8cd7c13c6c.png)

Which means that we'll lose our nice little Featured badge (which I didn't even realize we had) 
![image](https://user-images.githubusercontent.com/27990/201501938-dedccd94-8ad8-4135-8304-156eb4e7a8fe.png)

Our new deadline though for MV3 migration is June. We can revert commit ab19b3dd571969f211202e094a9dac75ffd1243f to get MV3 support back, but we'll need to fix #1032 before we can release the extension with MV3 support.

**Comment by kakaroto** [comment]
Droping to the next-next release due to mv2 not yet being phased out.

**Comment by Aeristoka** [comment]
https://developer.chrome.com/en/blog/extension-news-july-2023/

**Comment by kakaroto** [comment]
cool, so what I'm hearing is "we still haven't figured things out, but we may soon be"

**Comment by kakaroto** [comment]
New mv3 migration deadline is June 2024:
https://developer.chrome.com/blog/resuming-the-transition-to-mv3/
