### ISSUE TITLE
Additional "computed" lines in Roll20

### ISSUE THREAD

**Issue by DavidBartram** [kakaroto/Beyond20#848]
Unnecessary duplicate lines with "Computed" appearing in Roll20.

![image](https://user-images.githubusercontent.com/60873806/125504408-96c7deba-b25c-44c5-9d2b-24c16faabab6.png)

**Comment by Aeristoka** [comment]
@kakaroto same as on the Discord, only appears to happen with Beyond20RollRender -> Roll20, and with/without Digital Dice enabled.

**Comment by kakaroto** [comment]
huh.. that looks like it's some kind of change to the roll20 template and roll20 is the one creating it.. 
It's also appearing now in the old messages I have in my chat log from months ago, where it obviously didn't have them the last time I logged into roll20. So this looks like it's a Roll20 bug.
Easy way to test/confirm. Send this in chat : 
```
&{template:default} {{name=test}} {{Roll once=[[ 1d20 ]]}}
```
See how Roll20 creates two lines :
![image](https://user-images.githubusercontent.com/27990/125506509-0762074e-5b8e-4b0c-b12e-9904b6486492.png)

So this confirms it's a roll20 bug (a recent change to their default roll template), not a beyond20 bug.

Keeping this open until their fix. I don't know though where/how to poke them about such issues (or if they even care/reply to bug reports)

**Comment by DavidBartram** [comment]
Ah, interesting! I've posted on Roll20 here: https://app.roll20.net/forum/post/10244217/default-format-macro-has-extra-lines-with-computing

**Comment by Aeristoka** [comment]
Roll20 got their crap together.

**Comment by kakaroto** [comment]
Thanks for posting, seems it was fixed (as per that last reply in that other thread linked to your thread in that last reply, lol)!
Closing the issue now :)
