### ISSUE TITLE
DnDBeyond digital dice for two-handed attack

### ISSUE THREAD

**Issue by cjx2240** [kakaroto/Beyond20#849]
![image](https://user-images.githubusercontent.com/52527372/125515293-c173f491-3052-4975-858d-68e7b9a2c1c1.png)

This link for versatile weapons does not get picked up by Beyond20

**Comment by kakaroto** [comment]
As discussed on discord, Beyond20 only hooks on the first damage button, and you can configure your character to use one handed or two handed in the Beyond20 character specific settings.
Closing as per your request.
