### ISSUE TITLE
Animate Objects doesn't roll attack properly on R20

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#853]
> On the Animate Objects spell, if I click the attack button on the objects table, it doesn't output properly.

![image](https://user-images.githubusercontent.com/27990/127764201-f4254675-2d89-4a29-8445-cb2f2b57db25.png)

**Comment by mjames74** [comment]
Also doesn't quite format properly in Foundry. Not sure if it can be reformatted in a table like in DnDBeyond, but just wanted to show for when you started on this one just in case.

![837a6156f93a7a0f87aec16466b2aae3](https://user-images.githubusercontent.com/15372951/128605491-81919148-6d9a-46a1-958d-0d80317170d1.png)

**Comment by kakaroto** [comment]
It's because the description is text only. So the table gets lost. Would need to change the API and a bunch of stuff so the description is sent as html, then only roll20/astral would strip the html back into a text string instead. That's however a separate issue and unrelated to the roll20 issue and is not something I have planned to do in the short term as it would be a lot of work.
