### ISSUE TITLE
Custom Rolls not appearing in Roll20

### ISSUE THREAD

**Issue by neojipc** [kakaroto/Beyond20#854]
**Describe the bug**
Hate to be trite but subject is somewhat self explanatory.

Beyond20 Version 2.4.6

**Browser Info (please complete the following information):**
 - Chrome Version 92.0.4515.131 (Official Build) (arm64)
 - Big Sur 11.5

**Comment by Aeristoka** [comment]
Custom rolls meaning what?

**Comment by Aeristoka** [comment]
From here?
![image](https://user-images.githubusercontent.com/7988297/128582835-a20ac800-b1f3-4f13-ad95-d0496dc0204a.png)

![image](https://user-images.githubusercontent.com/7988297/128582840-6eea0c86-6e3d-43d8-8080-085bbfc09699.png)

Looks fine to me.

**Comment by neojipc** [comment]
Figured it out - the "Use D&D Beyond's Digital Dice" was somehow toggled
OFF but I didn't turn it off.  Turned on and voila!

[image: image.png]

[image: image.png]
