### ISSUE TITLE
Spells With DC check instead of Attack Roll/Damage Missing Spell name, Character Name

### ISSUE THREAD

**Issue by SGlanville** [kakaroto/Beyond20#856]
When casting a spell without Damage, In Roll20 it only display the DC Data, It would be nice to have spell name and range...

Fairy Fire Only Shows

DC15
Dexterity Save
Components: V

Where it should continue to add
Range
Spell Name
Character Name

Like Attack Spells do...
DC15
Intelligence Save
Components: V
12 Psychic
90ft.
Tasha's Mind Whip
MyCharacter

**Comment by Aeristoka** [comment]
Screenshot please

**Comment by kakaroto** [comment]
That's how Roll20's attack template works, if there is no roll or damage, it won't show the attack name, see : 
https://wiki.roll20.net/D%26D_5e_OGL_Roll_Templates#Attack
Beyond20 does specify the attack name (if you press the Up arrow in the chat box, you'll see what Beyond20 sends), it's simply ignored by Roll20's own template.
