### ISSUE TITLE
Custom Damage Dice; any chance a field or text string for "Damage Type" can be added?

### ISSUE THREAD

**Issue by zfreek98** [kakaroto/Beyond20#859]
**Is your feature request related to a problem? Please describe.**
Not a problem, but an update request for future versions, if possible.

**Describe the solution you'd like**
I would love to see either a blank text string for the damage type to allow us to replace the word "Custom" in the roll renderer results.  If left blank, will simply read "Custom".

**Describe alternatives you've considered**
Perhaps, a dropdown menu with damage types; Acid, Fire, Cold, Piercing, Bludgeoning, etc.  I believe the above solution is better, though. 

**Additional context**
Unrelated to the request above, but if different colors were allowed for the roll renderer frame from Beyond20 aside from purple, that'd be cool.  Thanks!

**Comment by kakaroto** [comment]
Hi, you can already customize the damage type by prepending it to the damage formula and using a semicolon as separator, and you can also provide multiple ones too separated by commas, like this :  `Acid: 1d6, Poison: 1d8`
As to the purple, we also hate it, but it's the Roll20 colors and we unfortunately have no control over it : https://wiki.roll20.net/Roll_Templates

Thanks!
