### ISSUE TITLE
Ice-Knife second damage (which includes a Saving Throw) shouldn't be affected by critical hit, I believe

### ISSUE THREAD

**Issue by Xinomorph** [kakaroto/Beyond20#863]
This isn't a bug, but more of a little nit pick related to the rules of 5e. I was unsure if in the case of Ice Knife, the second damage, which includes a Saving Throw, should be affected by the critical hit effect or not in case of rolling a nat 20 in the Attack Roll. So I found [this tweet from Jeremy Crawford](https://twitter.com/JeremyECrawford/status/805828362794987520) that claims that any damage associated with a save, shouldn't be affected by critical hit. When using the Beyond20 extension, at least on Roll20, when a critical hit happens using the Ice Knife spell, the second damage (the Cold damage one), that involves a saving throw, gets also an additional dice roll for the critical hit effect.

It's a minor thing as it also depends on how everyone decides to play the game, and the critical hit effect on the cold damage of the Ice Knife can easily be ignored by the players. I just wanted to suggest changing that eventually.

**Comment by Aeristoka** [comment]
My opinion, it will remain exactly as it is. The DM can rule whichever way they want to, and apply appropriately. Jeremy Crawford is a good source, but he contradicts himself sometimes too, and a ruling like this from him would mean a bunch of hyper-specific code that a DM might rule against anyway (and in each game, the DM is the end-all for the rules).

**Comment by BeeJayJayn** [comment]
To add to @Aeristoka answer:
As a DM I would rule that the aoe splash would also be a critical hit. This is due to the way of narrative:

"The ice knife hits the head of the owlbear and you see the shard shatter in a perfect ankle to hit the two cubs behind their mother. Both - the hit against the mother and the shards against their cubs - is perfect and all of you recognize how amazing this was. Roll damage and roll a 2nd time for the critical on both the first and the splash damage."

Especially since a completely avoidable splash damage.

@Aeristoka the rolls for the crit on the splash are listed on hover in the order they were generated, so people could simply ditch the last two dices rolled?

**Comment by Aeristoka** [comment]
> To add to @Aeristoka answer:
> As a DM I would rule that the aoe splash would also be a critical hit. This is due to the way of narrative:
> 
> "The ice knife hits the head of the owlbear and you see the shard shatter in a perfect ankle to hit the two cubs behind their mother. Both - the hit against the mother and the shards against their cubs - is perfect and all of you recognize how amazing this was. Roll damage and roll a 2nd time for the critical on both the first and the splash damage."
> 
> Especially since a completely avoidable splash damage.
> 
> @Aeristoka the rolls for the crit on the splash are listed on hover in the order they were generated, so people could simply ditch the last two dices rolled?

Exactly right, yes:
![image](https://user-images.githubusercontent.com/7988297/132129347-22226656-815a-480a-b305-9e7b92e115ed.png)

DM/Player just have to agree, and the Cold Crit (in this case) just just be ignored.

**Comment by kakaroto** [comment]
Yeah, this is very specific, and if we make a move on this, it will cause other DMs to say "that's not how I've always ruled on it". That's the point of having each damage separate, so the DM/player can select/choose which ones need to apply...
just like if you roll with the "always roll twice" option, and you get a crit on the second roll, it will show crit results, but it's up to you to decide whether to count it or not. Same for why the Magic Missile only rolls one missile's damage, it's up to the DM to multiply by the number of missiles (according to RAW/Jeremy Crawford), or the player to click multiple times to get the damage of each missile, etc..
I don't believe this would change and I don't want to have a specific ruling like this in Beyond20 for how a certain item should be used.
Thanks for bringing the question to our attention, but I'll be closing this as a won't fix.
