### ISSUE TITLE
Delay plugin update popup to beyond20 first use after update

### ISSUE THREAD

**Issue by sleepkever** [kakaroto/Beyond20#867]
I get the need for an update page but in it's current implementation it's only frustrating for me. The popup happens randomly and breaks workflow or even possibly presentations I do from my PC now that work from home is almost standard.

I know I can outright disable it in the settings, but I do like reading changelogs now and then of stuff that I use.

What would be an ideal solution for me is to only show the updated plugin page on the first time I open one of the supported websites after updating. This would ensure that the plugin update doesn't pop up randomly during the day any more, while still providing information when it's relevant. I'm not sure if that is easily implemented but I hope you take it into consideration.

**Comment by kakaroto** [comment]
Hi,
Thank you for the suggestion. That's a brilliant idea to do it that way, and I wholeheartedly agree!
I'll see if I can make it work for the next update.
Thanks!
