### ISSUE TITLE
Feature Request: Always Display The Number of Hands Used For An Attack Alongside the Damage Roll When Using Versatile Weapons

### ISSUE THREAD

**Issue by amenokos** [kakaroto/Beyond20#868]
**Is your feature request related to a problem? Please describe.**
I'm not sure I'd call it a problem, but I find myself wondering if my players used their versatile weapon with one or two hands.

**Describe the solution you'd like**
If a player has changed the default setting for versatile weapons to either _Use weapon one-handed_ or _Use weapon two-handed_, it would be nice to see that reflected in the VTT alongside the damage type, no differently than when it's labeled for when a player has not changed the default setting from _Roll both damages separately_.

**Describe alternatives you've considered**
The alternative is to hover over the damage amount to see the dice formula and compare it to the player's character sheet to match it with either the one-handed or two-handed damage formula. Another alternative would be to memorize the dice formulas.

**Additional context**
For comparison, here's the screenshot of what the roll looks like in Roll20 when both damages are rolled separately. It indicates which one is one-handed and which one is two-handed.

![image](https://user-images.githubusercontent.com/69495414/134088955-2d2b050d-0b2b-4a82-9c9f-af6526283134.png)

When the option is chosen to **only** roll two-handed damage in Beyond 20, the damage roll in the VTT only indicates the damage type (Slashing, in this case) but doesn't specify that the attack was made with two hands.

![image](https://user-images.githubusercontent.com/69495414/134089071-2af3c61d-4d56-47ad-9bfb-75faaed68f02.png)

**Comment by Aeristoka** [comment]
This will be available in the new Advanced Options section of 2.6 when it is released:
![image](https://user-images.githubusercontent.com/7988297/147598419-b45bd5a9-732d-44af-87bc-e04c392994ea.png)

**Comment by amenokos** [comment]
That's wonderful. Thank you!

**Comment by Aeristoka** [comment]
> That's wonderful. Thank you!

This request also resulted in a clean-up of the display of weapon handedness, so things are less crowded as well 😄 

![image](https://user-images.githubusercontent.com/7988297/147972270-ff761376-0f40-4abb-b040-dbf27ebe974a.png)

See this vs. your screenshot above

**Comment by amenokos** [comment]
Also wonderful. I thought about including that change with my request but then left it out. lol

**Comment by amenokos** [comment]
> 

Also wonderful. I thought about including that change with my request but then left it out. lol
