### ISSUE TITLE
Adv/Dis via shift clicking rolls 3 dice

### ISSUE THREAD

**Issue by JacobLuceno** [kakaroto/Beyond20#872]
For some reason, holding shift when rolling an attack from the dndbeyond character sheet results in 3 d20 rolls in my Foundry tab.  none of the affected characters have Elven Accuracy or other features that should enable this behavior.

1. Go to the character on dndbeyond with a foundry tab open
2. Hold shift and click the green multi-die + icon signifying an advantaged roll
3. Check result in Foundry window

Expected: 2 die rolls.

![image](https://user-images.githubusercontent.com/45406667/134582529-7a962857-8963-4178-a155-4af376434cad.png)

**Browser Info (please complete the following information):**
 - Browser Chrome
 - Version 94.0.4606.54 (Official Build) (64-bit)

**Comment by Aeristoka** [comment]
I'd almost guarantee you're holding Right-Shift instead of Left-Shift. Take a look in the Beyond20 Hotkey configurator, Left-Shift is Advantage, Right-Shift is now Super Advantage

**Comment by JacobLuceno** [comment]
yup. you are totally right and i am totally dumb.

Closed

**Comment by Aeristoka** [comment]
> yup. you are totally right and i am totally dumb.
> 
> Closed

Not at all, the addition of the new hotkeys came relatively recently with the hotkey manager, and is per-Browser if I remember right, so you may very well have had it set for both Shifts pretty recently.
