### ISSUE TITLE
[Astral TableTop] Beyond20 integration not working in Beta environment

### ISSUE THREAD

**Issue by Redmega** [kakaroto/Beyond20#875]
**Describe the bug**
We're testing changes to our chat in Beta and a user tested Beyond20 and determined it's no longer working. Some of the DOM changes a bit and things are shuffled around, I suspect this is why the integration is no longer working.

**To Reproduce**
1. Login to https://beta.astraltabletop.com (Share your Astral TableTop username with me either here or via our [Discord](https://discord.gg/ywHaUtFrnT) to gain access)
2. Open up a game and attempt to use Beyond20 to perform an action/roll

**Expected behavior**
It should send a message to chat.

**Comment by Aeristoka** [comment]
@adriangaro This sounds like something for you

**Comment by Aeristoka** [comment]
As a note here, Beyond20 development for Astral is likely to cease altogether, as Astral's development has also completely ceased.

**Comment by Redmega** [comment]
I'm no longer on the dev team but I'd like to clarify that OBS has committed to running the service as long as it's viable. Things are still looking good so I don't expect it to shut down soon.

**Comment by Aeristoka** [comment]
> I'm no longer on the dev team but I'd like to clarify that OBS has committed to running the service as long as it's viable. Things are still looking good so I don't expect it to shut down soon.

That's nice to here, and I certainly doubt that any of the Astral-specific code will be stripped from Beyond20, so as long as Astral sits in the same state, things should continue to work as they are.

**Comment by kakaroto** [comment]
Closing this issue as Redmega reported it was fixed on the Astral side. If things seem broken again, we can re-open it, and hopefully it can be fixed by a volunteer who is familiar with Astral.
Thanks for reporting and fixing it Redmega!
