### ISSUE TITLE
Great Weapon Fighting style makes attack rolls always output as 2 

### ISSUE THREAD

**Issue by Thecmar7** [kakaroto/Beyond20#880]
**Describe the bug**
The Great Weapon Fighting style makes attack rolls always output as 2 damage roll, because the equation is has a <= sign rather than just a < sign. I think anyway. 

**To Reproduce**
Create a paladin on DndBeyond and at level 2 choose great weapon fighting as the fighting style. 
Equip a great sword 
Attempt to attack with the great sword
The attack roll will always come out to a value of 2.

**Expected behavior**
When you roll a 1 or 2 on a damage die for an attack you make with a melee weapon that you are wielding with two hands, you can reroll the die and must use the new roll. The weapon must have the two-handed or versatile property for you to gain this benefit. 

**Browser Info (please complete the following information):**
 - Browser: CHROME
 - Version: 2.4.0

**Comment by Aeristoka** [comment]
Please provide the VTT you're using, screenshots, and a character sheet.
