### ISSUE TITLE
Staff of the Woodlands not rolling to hit/damage properly in Roll20.

### ISSUE THREAD

**Issue by TigerWolfe** [kakaroto/Beyond20#888]
When I click the to hit location and the damage location on the DnD Beyond sheet, it just posts the entire item description to Roll20 rather  than actually rolling the to hit/damage.

**Comment by Aeristoka** [comment]
https://beyond20.here-for-more.info/faq#why-doesnt-beyond20-allow-me-to-make-a-melee-attack-with-my-magic-staffs
