### ISSUE TITLE
Inserting alertify code in D&D Beyond's comment boxes.

### ISSUE THREAD

**Issue by sillvva** [kakaroto/Beyond20#889]
**Describe the bug**
The extension is inserting alertify.js HTML into comment boxes on D&D Beyond. It affects any page where the alertify script is loaded.

**To Reproduce**
1. Go to a spell page.
2. Click inside the comment box.
3. Click the < /> (source code) button in the toolbar.
4. See the extra script tags added by the extension.

**Expected behavior**
It should not be inserting anything into comment boxes. This affects some homebrew comment boxes as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/5138384/140082483-85ed7448-726c-4e29-92e4-75a51352669c.png)

**Browser Info (please complete the following information):**
 - Chromium Edge 94

**Comment by Aeristoka** [comment]
You can verify this 100% doesn't happen with Beyond20 disabled?

**Comment by kakaroto** [comment]
It used to be an issue, and I **thought** I had fixed them all. Or maybe I couldn't manage to fix them 🤔 I don't remember... Either way, I know I worked on this specific issue a while ago already. I'll give it another look. 
Thanks!

**Comment by sillvva** [comment]
Currently, it is happening in comment sections on official listing and homebrew listing pages where the alertify code is loaded.
