### ISSUE TITLE
Monster Initiative Tracking

### ISSUE THREAD

**Issue by x0t0x7n** [kakaroto/Beyond20#890]
Since at least last Friday night (6 November 2021), I've been unable to click on a monster token in Roll20 and have the initiative roll from the Monster sheet on D&D Beyond added to the Initiative tracker in Roll20.  The rolls are going through into the VTT, but not adding to the monster into the turn tracker.

**Comment by kakaroto** [comment]
I'm not able to reproduce the issue. It's working as expected for me, and the initiative gets sent to the Roll20 turn tracker.
The adding to initiative is a Roll20 functionality, we just add `&{tracker}` to the chat when rolling initiative, and roll20 takes care of the rest. If you don't select a token, do you see an error by Roll20 about no token being selected?
![image](https://user-images.githubusercontent.com/27990/143616548-0e6ecee8-606f-43af-aee1-328990f5648b.png)
If you don't, then you might have disabled the Beyond20 option by accident. Go to the full settings menu of Beyond20 and make sure this option is enabled : 
![image](https://user-images.githubusercontent.com/27990/143616398-a648c482-6335-4a0b-8d09-1650baf8bd6f.png)
