### ISSUE TITLE
Item "Insignia of the Claws" and Wildshape section in the "Extras" tab

### ISSUE THREAD

**Issue by JeanNicolasCrete** [kakaroto/Beyond20#891]
The "Insignia of the Claws" states that "[...] you gain a +1 bonus to the attack rolls and the damage rolls you make with unarmed strikes and natural weapons [...]"

In the "Extras" tab, you can already add beasts and roll from there but if you wear the "Insignia of the Claws", the bonus isn't added to neither rolls.

**Comment by Aeristoka** [comment]
1. The Beast would have to equip and attune to the Insignia of Claws to benefit from this
2. If you're referring to a beast added as a wildshape, this is an issue with DnDBeyond not adding the roll bonus, not Beyond20, Beyond20 parses the provided roll data and works with that (this is even worse with things like Ranger Companions, who can be added as such in the "Extras", and clearly state they scale with your Proficiency bonus in the Stat Block, but DnDBeyond makes no effort to actually scale those stat blocks)
