### ISSUE TITLE
Feature Request: Ability to send 'blind rolls' only to the GM

### ISSUE THREAD

**Issue by kinchj** [kakaroto/Beyond20#892]
**Is your feature request related to a problem? Please describe.**
I would love the option to send 'blind rolls' that only the GM can see, for things like stealth or perception checks.

**Describe the solution you'd like**
A toggle option, just like the current options for whispering rolls that includes an option for 'blind roll'.

**Describe alternatives you've considered**
Currently I have to use a custom Roll20 API, but it takes my players off of D&D Beyond to make their rolls, and it doesn't integrate with their character sheets.

**Additional context**
My understanding is that Beyond20 is sending a chat command in pretty much the same way that the Roll20 API sends commands, so I'm hoping that it would be a fairly simple addition that only sends the chat message to the DM.

**Comment by kakaroto** [comment]
As far as I know, Roll20 doesn't have support for blind rolls, so it's not something that could be added as it wouldn't work for the majority of users.
It looks as though you can do it with a custom API, but that's not something I ever had access to and I expect a minority of Roll20 users have access to. The biggest issue is that I expect it would throw an error for users if the GM doesn't have a pro subscription, which is not an ideal user experience.
Also, I would expect the custom API script would be named differently for each person, so it wouldn't be a standard command to send.
I don't know if it would be possible though to have an option for prefixing all the commands with something, so you could have your players set the prefix to `!blindroll` or whatever custom API command you set. But then it would act on everything... the complexity of getting it to work is a bit unsettling so I'm not sure if I would accept such a feature request, despite that it would be a good feature to have.
If you have thoughts on how to proceed, let me know!

**Comment by kinchj** [comment]
I don't have enough understanding of how Beyond20 'sends' information to Roll20 to give much more input unfortunately.  And my coding knowledge is limited to pretty basic html/css & even more limited javascript.  

But I guess what I _see_ is that Beyond20 is capable of sending a roll to Roll20, and that roll will use the D&D 5E by Roll20 sheet roll templates, and can be sent as either public or whispered. When it's whispered, the message is sent to both the rolling player and the GM... so would it be possible for it to only be sent to the GM? Or is the roll simply happening simultaneously on DDB & Roll20?  I don't have enough understanding of the mechanics there -- my idea wasn't intended to rely on Roll20's API scripts, and was assuming that Beyond20 already had the ability to interact with Roll20 in an API-like fashion. I hope that makes sense!

**Comment by kakaroto** [comment]
Beyond20 doesn't actually "send" the roll information or interface with Roll20 in any way other than by posting a chat message. You can press the Up arrow on your keyboard in the chat box of Roll20 after sending a roll with Beyond20 to see exactly what it sent. It simply types in text in the chat box and simulates clicking on the 'Send' button :)
When it sends a whisper, it just adds `/w gm` in front of the message. There is no way to send a blind roll through the text chat only (see https://wiki.roll20.net/Text_Chat) which is where Beyond20 limitation is.

I hope that helps clarify how it functions and why it would be very difficult to add this feature without completely changing the design of Beyond20 (if even possible).
