### ISSUE TITLE
Rolling with advantage bug

### ISSUE THREAD

**Issue by twmurphree** [kakaroto/Beyond20#893]
Rolling with advantage, rolled the same result twice, instead of taking one dice, it added the dice together
[Beyond20 advantage bug.pdf](https://github.com/kakaroto/Beyond20/files/7575532/Beyond20.advantage.bug.pdf)
.

**Comment by kakaroto** [comment]
Attaching the image here instead of pdf : 
![image](https://user-images.githubusercontent.com/27990/142744386-9334d18d-11c9-4449-988f-2260bf00b87f.png)

@twmurphree Are you sure you rolled with Beyond20? And do you have any modules that could be interefering with the rolls? Because Beyond20 will not roll an attack with advantage as a 2d20kh1, and it won't show the result like in your screenshot, so I'm guessing it's something else that you're using that's causing the problem.

**Comment by twmurphree** [comment]
It was rolled with beyond 20. I do have modules installed in the game, but none that would interfere with dice rolls.

**Comment by Aeristoka** [comment]
> It was rolled with beyond 20. I do have modules installed in the game, but none that would interfere with dice rolls.

Can you screenshot where you clicked to roll this with Beyond20 specifically?

**Comment by kakaroto** [comment]
FYI, this is what it would look like if you rolled with Beyond20 : 
![image](https://user-images.githubusercontent.com/27990/142744521-2e9a7644-f7fb-4161-8423-583f60790292.png)

If you disable the 'roll damages', you'd have a button to roll them, like this :
![image](https://user-images.githubusercontent.com/27990/142744549-50123a7d-95f0-4b32-86e2-405b74f77ff7.png)


You can see that each roll is a `1d20` and each one is rolled separately, then only one of the two results is highlighted. We never use the `2d20kh` formula.
![image](https://user-images.githubusercontent.com/27990/142744523-c69ae0f7-af0c-4bab-afb6-7ec1dc950c5e.png)

Also, you can see the little `>` icon next to the weapon name which is clickable to expand the full attack description like so : 

![image](https://user-images.githubusercontent.com/27990/142744552-0ca0a5a4-e21a-4e64-b0e3-cf863f360363.png)


All of this is why I very much doubt that it was rolled using Beyond20.

**Comment by twmurphree** [comment]
![roll screenshot](https://user-images.githubusercontent.com/94767545/142744570-f7000ac1-0b08-4870-a9b3-11e350bc564f.png)

**Comment by twmurphree** [comment]
you are right. it is sending the DND Beyond roll to the forge instead of using Beyond20. I see the style difference now

**Comment by Aeristoka** [comment]
> you are right. it is sending the DND Beyond roll to the forge instead of using Beyond20. I see the style difference now

That likely means you're using something like ddbgamelog, which is not by @kakaroto

**Comment by kakaroto** [comment]
Click on the weapon icon to the left to roll with Beyond20, press Shift to make it roll with advantage. That interface is D&D Beyond's own roller, and it's like ddbgamelog as Aeristoka mentionned.
