### ISSUE TITLE
Rage Damage for Unarmed Strikes

### ISSUE THREAD

**Issue by HamburgerPun** [kakaroto/Beyond20#898]
It seems the rage toggle doesn't recognize unarmed strikes as strength based attacks

According to Sage Advice, they should count as a melee weapon attack

For now I have to make a custom attack that adds the damage.

**Comment by Aeristoka** [comment]
Please provide a link to the Sage Advice you're referencing for confirmation.

**Comment by HamburgerPun** [comment]
Here's an excerpt from Sage Advice:
What does “melee weapon attack” mean: a melee attack with a weapon or an attack with a melee weapon?
It means a melee attack with a weapon. Similarly, “ranged weapon attack” means a ranged attack with a weapon. Some attacks count as a melee or ranged weapon attack even if a weapon isn’t involved, as specified in the text of those attacks. **For example, an unarmed strike counts as a melee weapon attack**, even though the attacker’s body isn’t considered a weapon.

Link is a DnDBeyond link: https://www.dndbeyond.com/sources/sac/sage-advice-compendium#SA130

Excerpt from Rage in the PHB:
When you make a **melee weapon attack** using Strength, you gain a bonus to the damage roll that increases as you gain levels as a barbarian, as shown in the Rage Damage column of the Barbarian table.

Link:  https://www.dndbeyond.com/classes/barbarian

**Comment by Aeristoka** [comment]
@HamburgerPun This already works
![image](https://user-images.githubusercontent.com/7988297/145416306-472c5670-15ad-48f8-8040-ae12a08a257e.png)

**Comment by HamburgerPun** [comment]
AH.  I figured out that it doesn't work if I customize the attack.  I renamed it and Beyond20 must not recognize that. 
![Capture](https://user-images.githubusercontent.com/70948592/145436272-0d4a6197-9a7e-4709-b4bd-ffeeceb3d5ce.PNG)

**Comment by HamburgerPun** [comment]
Thank you!
