### ISSUE TITLE
No longer See the ability to add Crimson Rite

### ISSUE THREAD

**Issue by Faetheless** [kakaroto/Beyond20#899]
I was able to toggle the addition of crimson rite to my damage dice, For some reason I no longer see that as an option I tried on both firefox and edge

**Comment by Aeristoka** [comment]
Please provide a character sheet link and screenshot.

**Comment by Faetheless** [comment]
![image](https://user-images.githubusercontent.com/31997562/146302325-c8cb3baa-0966-4322-8460-fd4bb117df29.png)

https://www.dndbeyond.com/profile/JesserBeyond/characters/61204278

**Comment by Aeristoka** [comment]
![image](https://user-images.githubusercontent.com/7988297/146303732-005d81af-43e0-4d3a-813c-5995b8b3c961.png)

Click "Features & Traits" so that it loads and Beyond20 can parse it

**Comment by Faetheless** [comment]
Gotcha thanks
