### ISSUE TITLE
Support for special features

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#9]
This issue is to track the special features that need to be supported:
* Sneak attack: **Done**
* Disciple of Life: **Done**
* Jack of all trades on raw abilities : **Done**
* Sharpshooter and Great weapon master:  **Done**
* Improved/Superior Critical : **Done**
* Brutal critical: **Done**
* Savage Attacks: **Done**
* Rage damage: **Done**
* Great Weapon Fighting: **DONE**
* Blood Hunter's Crisom Rite: **DONE**
* Hex Blade's curse critical threshold : **DONE**
* Oath of heroism critical threshold: **DONE**
* Dread Ambusher extra damage for Ranger Gloomstalker : **DONE**
* Rogue's Assassinate: **DONE**

TODO:
* Elven Accuracy: **TODO** (Display separate roll ?)

**Comment by kakaroto** [comment]
Added Improved Crticial

**Comment by jekface** [comment]
Hi, first of all, awesome job! Found an issue I think might need some work. Monk special skill for deflecting missiles. The roll is supposed to add Dex and monk level. It just rolls the d10 without bonuses. Anyway, thanks for this extension. Great job!! I love it.

**Comment by kakaroto** [comment]
Cool thanks for letting me know, I'll add support for it!

**Comment by kakaroto** [comment]
Deflect Missiles should work now (only if clicked from D&D Beyond, not from within the roll20 description). Same with other features that have "+ your <ability> modifier" or "+ your <class name> level", such as Second Wind.

**Comment by further-reading** [comment]
Hey man, I love this extension! I've been working on my own version but yours blows all my work out of the water.

Had some issues though today when using it with my monk:
- Monk unarmed attacks seem to use the static default damage instead of their special damage die.
- There doesn't seem to be a way to roll tool use - I expect this is because the dndbeyond card doesn't give the roll info.

**Comment by kakaroto** [comment]
@further-reading hey thanks! I just saw your dndbeyond scraper. I don't know if you're aware, but you can take any character URL in D&D Beyond and add '/json' to the URL to get the full character sheet in a json format! It might be easier than trying to parse the html :)

1 - I'm not sure about that. I can see that D&D Beyond already shows the unarmed attack as 1d4 + DEX in the case of my monk character and the right dice is rolled. Normally it would be 1 + STR.
2 - Yeah, that's a D&D Beyond issue, What I do is create a custom skill for any tools, like Thieve's tools for example, Beyond20 already supports it and if you don't specify the ability for the custom skill, it will query it in the R20 window.

**Comment by further-reading** [comment]
Oh wow, that's a great fix for the tools proficiency issue!

For my Monk I had a another test and it seems to be something to do with the custom damage option. Before I used it the roll worked properly but then after it was set it stopped rolling my Monk damage die. My Monk also has a negative strength modifier which might have impacted it too(it'd make the default damage 0)? Character sheet is here if you wanna try https://www.dndbeyond.com/profile/Further_Reading/characters/10371377

As an aside about the scraper, I know about the json but a main reason behind it is practice - I like to learn new techniques by using them to make something in my life easier so this seemed like a fun way to learn webscraping! :P

**Comment by kakaroto** [comment]
Oh you're right, my bad! it was fine for attacks and spells but for 'actions' I had it set to replace the damage instead of appending to it. All fixed now.
For the scraper, I figured as much considering the project description/README, but thought it was worth mentioning. I think it's a great project idea to get some practice!

**Comment by kakaroto** [comment]
Add Great Weapon Fighting. Reroll on a 1 or 2 on two-handed weapons. R20 uses '1d8ro<2' to do the re-roll once.

**Comment by SANSd20** [comment]
Also, how about Elven Accuracy? Most for the "Whenever you have advantage on an attack roll using Dexterity, Intelligence, Wisdom, or Charisma, you can reroll one of the dice once."

**Comment by kakaroto** [comment]
I'm trying to add Elven Accuracy, but it's a though one because D&D Beyond doesn't tell me what the ability is when you do an attack, so I'd have to add a lot of logic into the extension itself to determine if dexterity is used for weapons or strength, or what class a spell is coming from and what ability is used for attack for that class to determine if Elven Accuracy would count. Also, it would only work if you select "roll with advantage", if you use "always roll twice" then should I also do it ? Also, Roll20 doesn't allow to specify more than 2 rolls for attack. Lucky feat is similar too I guess, though you make the decision after you roll.
I'll leave it for now in the list of special things to handle, but I'm not making it a priority. In those cases, I think it makes more sense to determine in advance with the DM that the damages from the first roll are to be used and to re-roll only to get the additional 'to-hit' result and ignore the rest.

**Comment by kakaroto** [comment]
Closing this issue at this point. Future special features should get their own issues created
