### ISSUE TITLE
Encounter builder update breaks monster dice rolling

### ISSUE THREAD

**Issue by SkootNoog** [kakaroto/Beyond20#90]
The red dice rolling buttons no longer show up in the updated encounter builder.

Encounter Page
![image](https://user-images.githubusercontent.com/19879424/73993756-d03e2d80-4918-11ea-993c-505c61976551.png)

Monster Page
![image](https://user-images.githubusercontent.com/19879424/73993774-ddf3b300-4918-11ea-9a69-11fe03902315.png)

**Comment by kakaroto** [comment]
Thanks, will look into it!
