### ISSUE TITLE
Customize Spell Name and damage dice goes crazy

### ISSUE THREAD

**Issue by GammaKappaMu** [kakaroto/Beyond20#900]
Hello. I chanced the name of _**Chaos Bolt**_ and now when I roll damage it rolls 9d8. I removed the name and now it rolls just 2s8 but not the additional 1d6 noted (On a hit, the target takes 2d8 + 1d6 damage).

**Comment by Aeristoka** [comment]
Please add more specifics, name you changed it to, screenshots, etc.

Also, please test with Beyond20 Disabled, as Beyond20 may not be the culprit here.

**Comment by GammaKappaMu** [comment]
Spell: Sorcerer 1 - Chaos Bolt -> Ikol's Chaotic Balls
Image 01: Normal with Beyond 20
Image 02: Name change and Beyond 20
Image 03: Name Change Beyond 20 inactiv
![chaos bolt 01](https://user-images.githubusercontent.com/96270541/146700435-54232ce8-8fff-46dc-856d-1a80153bb400.JPG)
![chaos bolt 02](https://user-images.githubusercontent.com/96270541/146700438-a3ad6677-e6c6-41a1-922b-130978b8a0af.JPG)
![chaos bolt 03](https://user-images.githubusercontent.com/96270541/146700441-ea0a1d2d-2b7e-452b-81fb-fb31a67b72e2.JPG)
e

**Comment by Aeristoka** [comment]
yep, specifically because Chaos Bolt has a VERY specific section of code to handle it, and pare down to just one roll.

You changed the name, so it can't find that the Spell is correct. Change the name back to the default.

**Comment by Aeristoka** [comment]
```
//Moved after the new resolveRolls so it can access the roll results
if (request.name.includes("Chaos Bolt")) {
	for (let [i, dmg_roll] of damage_rolls.entries()) {
		const [dmg_type, roll, flags] = dmg_roll;
		if (dmg_type == "Chaotic energy Damage" && roll.dice[0].faces == 8) {
			const chaos_bolt_damages = ["Acid", "Cold", "Fire", "Force", "Lightning", "Poison", "Psychic", "Thunder"];
			const damage_choices = {}
			for (let r of roll.dice[0].rolls)
				damage_choices[chaos_bolt_damages[r.roll - 1]] = null;
			//console.log("Damage choices : ", damage_choices, damage_choices.length);
			let chaotic_type = null;
			if (Object.keys(damage_choices).length == 1) {
				damage_rolls.push(["Chaotic energy leaps from the target to a different creature of your choice within 30 feet of it", "", DAMAGE_FLAGS.MESSAGE]);
				chaotic_type = Object.keys(damage_choices)[0];
			} else {
				chaotic_type = await this.queryDamageType(request.name, damage_choices);
			}
			damage_rolls[i] = [chaotic_type + " Damage", roll, flags];
			critical_damage_types[0] = chaotic_type;
			break;
		}
	}
}
```

Specifically all this
