### ISSUE TITLE
roll modifier not visible in roll20 when using digital dice

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#914]
Without vs with digital dice : 
![image](https://user-images.githubusercontent.com/27990/149235844-6bf978a3-59be-4b6b-9bcc-080b47eb81f9.png)

The roll modifier should still be shown in the rendered roll
Other example : 
![image](https://user-images.githubusercontent.com/27990/149235901-03541586-6a2e-430f-9085-8afe300f5a40.png)

**Comment by jchambliss** [comment]
@kakaroto I'll take this if nobody else has.

**Comment by kakaroto** [comment]
Sounds good to me, poke me on Discord if you need some guidance on where to look! Thanks :)
