### ISSUE TITLE
Ability to send rolls to TaleSpire

### ISSUE THREAD

**Issue by oktay-sen** [kakaroto/Beyond20#915]
**Is your feature request related to a problem? Please describe.**
[Beyond the Spire](https://beyondthespire.com/) plugin already exists to send D&DBeyond rolls to TaleSpire, however:
* It is closed source
* It puts an ugly blue square on all roll buttons, with no option to change the styling
* It lacks the additional features of Beyond20. The way Beyond20 changes the rolls to take class features, feats etc into account is awesome, and would be very nice to have in TaleSpire too.

**Describe the solution you'd like**
In the extension options, there could be a toggle to enable TaleSpire integration. TaleSpire accepts links like `talespire://dice/<title>:<formula>`, so Beyond20 can just visit the URL to send the rolls.

**Describe alternatives you've considered**
I wanted to try changing the styling in Beyond the Spire but it's closed source.

**Comment by Aeristoka** [comment]
This is likely going to fall under this answer: https://beyond20.here-for-more.info/faq#can-you-add-support-for-insert-new-vtt-name

But I'll leave it to @kakaroto for a final answer.

**Comment by kakaroto** [comment]
Yeah, it falls under that. At the moment, we're also working on #833 where the user could tell Beyond20 to send rolls to any website basically, and that specific website would need to support Beyond20.
The `Beyond the Spire` extension should already be able to use Beyond20 directly as our rolls and parsed information is sent to the DDB website itself via a custom DOM event, so `Beyond the Spire` could basically require that Beyond20 be enabled for it to work and use the information we send directly and just act as a way to pass it along to talespire.
I think the biggest issue with `talespire://dice/<title>:<formula>` is that it's a very simplistic way to roll, as you don't get full HTML weapon description, you can't have to hit and damage at the same time, or multiple damage types, etc...
