### ISSUE TITLE
Vampiric Touch Roll Fails to FoundryVTT

### ISSUE THREAD

**Issue by Aeristoka** [kakaroto/Beyond20#918]
![image](https://user-images.githubusercontent.com/7988297/150664302-573a1a1a-a79d-49ff-9b26-200afc6cd94c.png)

Works with Digital Dice on, but not otherwise.

**Comment by Aeristoka** [comment]
I think it's related to this:
![image](https://user-images.githubusercontent.com/7988297/150664532-3f6f2a25-ae4f-44bf-98b3-feb4c199dae0.png)

**Comment by kakaroto** [comment]
Forgot to refer to it in the commit. Fixed by 5ba7da1f15747ab11485c25008d9e9fd498d0579
