### ISSUE TITLE
Let's Role is a new VTT that could benefit from this Roller

### ISSUE THREAD

**Issue by DarthPackman** [kakaroto/Beyond20#920]
Any chance of getting Let's Role added to the supported VTTs?

**Comment by Aeristoka** [comment]
There is not.

https://beyond20.here-for-more.info/faq#can-you-add-support-for-insert-new-vtt-name

**Comment by Aeristoka** [comment]
Possibly, if this gets done: https://github.com/kakaroto/Beyond20/issues/833

And they set up something to listen for those messages from Beyond20 you sent, then it could work. There won't be any Beyond20-specific code for it though.

**Comment by DarthPackman** [comment]
Fair, it did do amazing well on Kickstarter and causes me less eye strain then Roll20 so maybe itll get big enough. Is this code open source? Could I borrow the base code and customize it?

**Comment by Aeristoka** [comment]
> Fair, it did do amazing well on Kickstarter and causes me less eye strain then Roll20 so maybe itll get big enough. Is this code open source? Could I borrow the base code and customize it?

Yep, it's open source, the license is in the GitHub Repo. And definitely, fork it your way, customize, hand it to your players to use, just don't expect a PR with your work to be merged into Beyond20 proper :)
