### ISSUE TITLE
Spells cards appear broken on Roll20

### ISSUE THREAD

**Issue by Aeristoka** [kakaroto/Beyond20#926]
**UPDATE: This is a Roll20 bug that's affecting everyone on their platform, not just Beyond20 users.**
See https://app.roll20.net/forum/post/10662768/my-spells-spell-card-bug

Seems likely they changed something in the templates again.

Example character sheet: https://discord.com/channels/578874022968688640/579077147994488862/937823046192992298
Open Spells -> Word of Radiance -> Click "Display in VTT"

![image](https://user-images.githubusercontent.com/7988297/151893150-2456c2f8-5003-4828-bba7-a28be3add02b.png)

Display as this:
![image](https://user-images.githubusercontent.com/7988297/151893186-a92da472-a124-4b55-b959-7d5bd4c2e5ae.png)

Message still received via Beyond20 fine it appears:
![image](https://user-images.githubusercontent.com/7988297/151893219-900fe1ba-3d4a-46f5-9cfc-2102a9ff3a8d.png)

**Comment by Aeristoka** [comment]
This was caused by Roll20 pushing un-tested code into Production (likely breaking many things beyond this). Holding here to see if Roll20 reverts their broken crap.

**Comment by kakaroto** [comment]
We can follow the suspenseful intrigue from here : 
https://app.roll20.net/forum/post/10662768/my-spells-spell-card-bug

Leaving open in case someone else wants to report the issue, they'll see it's known.

**Comment by Aeristoka** [comment]
![image](https://user-images.githubusercontent.com/7988297/151974934-6c03f55a-19e4-4b68-9d20-4aa0024099b6.png)

Appears to be working for myself this morning.

**Comment by kakaroto** [comment]
Yep, I can confirm. They also posted in that forums that they fixed it, which confirms it 👍 
Closing the issue now, thx
![image](https://user-images.githubusercontent.com/27990/152296884-355d13fa-dc91-4c15-b726-01ae175fbd9e.png)
