### ISSUE TITLE
Add export/import settings options

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#931]
Having a Save/Load dialog to export and import all the Beyond20 settings would be a good idea. Other than the UI, the export/import should be trivial, though I'm not sure if we can list the saved character sheet settings to save those too, or if we'd only be able to save the global settings.

**Comment by Aidurber** [comment]
My DM has reached her limit with Roll20 character sheets. My partner and I are already using Beyond20 and our DM wants the rest of the party to get on board. 

I think this would be great addition, it would definitely speed up onboarding the party as well as helping "backup" settings.
