### ISSUE TITLE
DnDBeyond Initiative Tracker -> Roll20 sync problems

### ISSUE THREAD

**Issue by Draakpappan** [kakaroto/Beyond20#934]
**Describe the bug**
Whenever you run and encounter in DnDBeyond it only shows a few of the PCs in Roll 20s initiative tracker and the initiative order for the ones that show up is wrong.

In the screenshots below note that the character "Francesco" doesnt show up in Roll 20 after the encounter is started. 

**To Reproduce**
1. Run a created encounter in DnDBeyond with at least 1 monster and 5 player characters.

**Expected behavior**
That all players and monster appear in the initiative tracker in Roll 20. 

**Screenshots**
![dndbey1](https://user-images.githubusercontent.com/99182017/152824797-7780e923-f6b8-4dc6-a3f8-2f763b77680c.png)

![dndbey2](https://user-images.githubusercontent.com/99182017/152824820-b5164972-bfd6-40c0-b8a0-eeeab0850fae.png)

![roll20](https://user-images.githubusercontent.com/99182017/152824833-f70149de-1294-46ba-b1d2-5245c5209257.png)

**Browser Info (please complete the following information):**
Testen on Chrome

**Comment by markusdf** [comment]
I am having the same issue, only worse. The only items in the initiative list are monsters/players in dndbeyond are ones with no matching tokens in roll20. it appears as if the javascript for the combat update is missing the initiative value:
![Screenshot 2022-02-10 131727](https://user-images.githubusercontent.com/5422580/153312684-5eb40362-d2b8-4206-b5f2-757ee29718e7.png)

**Comment by Aeristoka** [comment]
From what we've (very briefly so far) gathered, they did something funky to the Turn Tracker on Roll20, so it's gonna take some digging from @kakaroto to figure it out (he's been swamped). Hold tight, it'll get fixed up, hopefully sooner than later.

**Comment by darinsydney** [comment]
I have the same issue.  Three weeks ago, it was working fine.  Now, when I use the AutoRoll Initiative in the Combat Tracker, the characters do not appear in Roll20's Turn Order.  But the monsters do.

<img width="393" alt="image" src="https://user-images.githubusercontent.com/63992124/153740553-f81dc17a-1688-4a10-8cc5-64e1f0916eff.png">
<img width="234" alt="image" src="https://user-images.githubusercontent.com/63992124/153740561-7fa5db73-59cc-4964-8512-f892ade76135.png">

**Comment by kakaroto** [comment]
Fixed in 6ce6566365d309071b50dc487538aafe2df1c840
