### ISSUE TITLE
Wildshape HP Management

### ISSUE THREAD

**Issue by BradleyStaples** [kakaroto/Beyond20#942]
Apologies if this is already covered and I just couldn't figure it out. I searched for 'wildshape' on the Features page and didn't see anything.

My group uses D&D Beyond + Beyond20 + FoundryVTT. One thing I couldn't figure out after I hit level 2 as a Druid today was how to "sync" HP between my Wildshaped form in D&D Beyond's "Extras" tab to my character sheet in Foundry. It reads/syncs off the standard HP counter in D&D Beyond just fine.

I tried manually adjusting my HP in foundry's token character sheet (double clicked my token, adjust current and max HP both), but when I marked damage off from the D&D Beyond's Extra tab for my brown bear wildshape, it reset my Foundry's HP back to the one listed in my humanoid form in D&D Beyond.

Is there any way to support this type of functionality, even in an advanced option toggle?

Thanks so much!

**Comment by Aeristoka** [comment]
Have you tried naming the Wildshape differently on both FoundryVTT + DnDBeyond? That works with other extras.

**Comment by BradleyStaples** [comment]
I have not renamed it. Are you saying I need, for example, to create another actor in Foundry that matches the name of the re-named Wildshape Extra? (So I'd need a unique name for each WIldshape/Foundry-Actor pair?)

**Comment by Aeristoka** [comment]
That's the way to do it, yes, but change the Token's name to test first

**Comment by BradleyStaples** [comment]
That worked. Thanks!

**Comment by Aeristoka** [comment]
> That worked. Thanks!

Happy to help!
