### ISSUE TITLE
Agonizing Blast Support

### ISSUE THREAD

**Issue by Slartib42tfast** [kakaroto/Beyond20#950]
Thanks for the excellent app!

I'd love to see support for the Agonizing Blast (PHB 110) Eldritch Invocation. If it's listed under a character's Features & Traits then add the damage (equal to CHA bonus) to the Eldritch Blast damage roll. If you can't make it specific to casting Eldritch Blast then adding a toggle under the B20 Character Specific Options would also be great.

Here's how it appears on my character sheet:

![image](https://user-images.githubusercontent.com/100521988/155885467-26492dbf-4222-42fc-984a-5bc73f3e4dde.png)

Thanks!
Ben

**Comment by Aeristoka** [comment]
DnDeyond already does this itself.

![Screenshot_20220227-072352](https://user-images.githubusercontent.com/7988297/155886386-e46584ec-d23e-4e87-aacb-97f54c2f8454.png)
