### ISSUE TITLE
Staff attacks not rolling when clicked

### ISSUE THREAD

**Issue by anightgirl** [kakaroto/Beyond20#952]
**Describe the bug**
When I click my staff of fire or my Gulthias staff attacks instead of sending the attack to Roll20 it sends the description of the staff.  

If I right click and hit "roll" it will send the attack. 

Other weapons etc. work fine. 

**To Reproduce**
1.Open character sheet
2. Go to actions
3.  Click on the +ATK square to make an attack
4. See it not work.

**Expected behavior**
It should send an attack to Roll20

**Screenshots**
![image](https://user-images.githubusercontent.com/101025446/156903827-f0105710-38ec-41bc-868c-3c6f76b67e4b.png)

![image](https://user-images.githubusercontent.com/101025446/156903835-efe9e52f-41b8-4c5c-a2bb-18599552109b.png)

**Browser Info (please complete the following information):**
Firefox 97.0.2 (64-bit

**Additional context**

**Comment by Aeristoka** [comment]
https://beyond20.here-for-more.info/faq#why-doesnt-beyond20-allow-me-to-make-a-melee-attack-with-my-magic-staffs

Make sure you have "Use DnDBeyond Digital Dice" enabled in Beyond20 settings:

![image](https://user-images.githubusercontent.com/7988297/156903866-e42187a4-b235-4c61-a475-48fc8149b7db.png)

**Comment by Aeristoka** [comment]
What you're doing is actually probably the proper workaround to this, DnDBeyond still steadfastly refuses to put the to-hit or damage into Magical staffs (even though they'll make the hook for their own digital dice now).

**Comment by anightgirl** [comment]
I do thanks.  Maybe I just never actually did it before and didn't realize. lol

**Comment by Aeristoka** [comment]
> I do thanks. Maybe I just never actually did it before and didn't realize. lol

We've requested it before, but DnDBeyond just won't change it. Another easy workaround is to add and equip the proper +X staff, and just roll that if you're hitting with it.
