### ISSUE TITLE
Spells with max AND min results on any dice show incorrectly with Roll20 Dark mode

### ISSUE THREAD

**Issue by Galphanore** [kakaroto/Beyond20#954]
**Describe the bug**
If you have the new Roll 20 "Dark Mode" enabled and cast a spell, sometimes the resulting value has a text color that matches the background color.

**To Reproduce**
1. Have Roll20, DNDBeyond, and Beyond20
2. Turn on Roll20 Dark Mode
3. Cast a spell and get a max value on any dice (8 on a d8, 6 on a d6, etc) _AND_ a 1 on any dice, for the same roll.
4. The text color and background color of the result are the same, so you cannot see the result.

Note : Easier to replicate on spells like Healing Word that use a d4, for obvious reasons.

**Expected behavior**
The text should change color when dark mode is swapped on and off.

**Screenshots**
Attached.

**Browser Info (please complete the following information):**
Happening both on Chrome 98.0.4758.102 and Firefox 97.0.1.

**Additional context**
Looking at the HTML, it looks rolls with the span class of "importantroll" have a hardcoded color that matches the background color.

![Beyond20DarkMode](https://user-images.githubusercontent.com/4059786/156938471-74ef51db-a8df-4773-8f05-2a8c3a1e7c8b.png)
![Beyond20DarkModeHtml](https://user-images.githubusercontent.com/4059786/156938584-008759bc-1bf1-47a6-a0b9-74129f82c47e.png)
![Thunderwave](https://user-images.githubusercontent.com/4059786/156938685-4df2d73c-b55c-4d79-91f7-b940d77786a3.png)
![ThunderwaveHTML](https://user-images.githubusercontent.com/4059786/156938715-d3978cde-2953-48d6-b8e8-b6ef963c669b.png)
![HealingWord](https://user-images.githubusercontent.com/4059786/156939085-0db8f18c-7606-46a2-ab3a-d5f81f857fa4.png)
![HealingWordHTML](https://user-images.githubusercontent.com/4059786/156939125-099b47dd-12fe-4383-bbf1-d7e2aa791ffa.png)

**Comment by Aeristoka** [comment]
That's an issue with roll20 dark mode not anything with Beyond20. Roll20 doesn't have a fully functional dark mode yet.

**Comment by Aeristoka** [comment]
Try rolls from a roll 20 character sheet you'll get the same result.

**Comment by Galphanore** [comment]
Ok, thanks! I wasn't sure where the issue was coming from. I'll submit a bug report to them.

**Comment by Aeristoka** [comment]
I wish they could get even like one code change right... Dark mode is hard for everybody but they really screwed it up.

**Comment by Galphanore** [comment]
Yeah :(
