### ISSUE TITLE
Greyed-out character sheet in dndbeyond due to Beyond20 dialog boxes/notifications

### ISSUE THREAD

**Issue by cmbarona** [kakaroto/Beyond20#956]
When Beyond20 generates a dialog box over a dndbeyond character sheet, the rest of the character sheet is greyed out and cannot be interacted with. This continues even after the dialog box has been dismissed.

This is particularly noticeable when receiving the notification to select the Features & Traits panel after leveling up a character. In order to dismiss this notification, I have to turn off Beyond20, open the character sheet, select the Features & Traits panel, then turn Beyond20 back on while that panel is selected.

Sample image: normal sheet
![image](https://user-images.githubusercontent.com/101484946/158043401-267680d8-86e6-4843-9827-250524cab2b5.png)

Sample image: Beyond20 dialog box
![image](https://user-images.githubusercontent.com/101484946/158043363-4c7ec56a-9648-4a23-97cb-d0e686171337.png)

Sample image: Greyed-out character sheet after dialog box has been dismissed
![image](https://user-images.githubusercontent.com/101484946/158043388-1899615c-70eb-43c2-b01a-a9605a10a20c.png)

 - Browser: Chrome
 - Version: 99.0.4844.51 (Official Build) (64-bit)

**Comment by Aeristoka** [comment]
Remove and re-install Beyond20, this isn't a normal behavior, or something I can replicate at all.

**Comment by cmbarona** [comment]
I've removed and re-installed. The issue persists. It also persists across devices.

**Comment by Aeristoka** [comment]
Try disabling all other extensions, and see if it persists, because this is not how Beyond20 has ever behaved.

**Comment by cmbarona** [comment]
Huh... that worked. Thanks for the suggestion. I'll re-enable them one by one to see what might have caused it.

**Comment by Aeristoka** [comment]
Yeah, it's some other extension for sure, good luck finding which!
