### ISSUE TITLE
Adventure flowchart in the call of the Netherdeep does not display properly with Beyond20

### ISSUE THREAD

**Issue by Xtallll** [kakaroto/Beyond20#957]
**Describe the bug**
Adventure flowchart in the Call of the Netherdeep dose not render properly with Beyond20 enabled.

**To Reproduce**
1. Go to ['ADVENTURE FLOWCHART'](https://www.dndbeyond.com/sources/cotn/answering-the-call#AdventureFlowchart)
2. the Flowchart is only displaying the gradient background not the text

**Screenshots**
With Beyond20 disabled
![withoutbeyond20](https://user-images.githubusercontent.com/101666618/158449135-be90ddd1-ded4-4f5d-b12e-6d5a84c418a5.PNG)

With Beyond20 enabled
![withbeyond20](https://user-images.githubusercontent.com/101666618/158449126-70e61c8c-f799-4fc1-a25c-4b7958cfbdb0.PNG)

**Browser Info (please complete the following information):**
 - Browser chrome
 - Version 99.0.4844.51 (Official Build) (64-bit)

**Comment by Jonfor** [comment]
This happens to me as well in Firefox 98.0.1.

**Comment by Jonfor** [comment]
It's strange because if I Inspect Element and uncheck the `z-index: -1` and recheck it on the `::before` it displays properly again.

**Comment by kakaroto** [comment]
Very weird indeed! As we don't do anything that might affect that flowchart.
Even looking at the elements, I see a difference between the CSS. This is with B20 enabled : 
![image](https://user-images.githubusercontent.com/27990/160444028-cb7de5a6-0a57-4103-8809-bfd2c2563cdf.png)
And this is without : 
![image](https://user-images.githubusercontent.com/27990/160444101-42a49dbc-a4b0-4c56-bce3-9757a03a647b.png)

Notice that where the issue happens, the `z-index: -1` doesn't even exist in the CSS.... 

And.... 🤦‍♂️ here's the CSS in the `<style>` header of the html : 
Correct : 
![image](https://user-images.githubusercontent.com/27990/160444592-2c1a82b8-e528-4bc5-bdf5-5842f45f9e4f.png)

Incorrect : 
![image](https://user-images.githubusercontent.com/27990/160444677-5ee0728d-b74b-48c6-b378-d422c65ed65e.png)

And so... **wow** it looks like Beyond20 is replacing the `-1` in the CSS  as if it's a dice roll modifier for `1d20-1`, thus breaking the CSS! 🤦‍♂️ 😱 

Thanks for reporting this bug! Will get it fixed!

**Comment by Aeristoka** [comment]
They put the CSS... In the Header... Of the page...?

**Comment by kakaroto** [comment]
> They put the CSS... In the Header... Of the page...?

as a `<style>` element, yes. It's very normal to do that, as it's a page-specific style.

**Comment by kakaroto** [comment]
Fixed!
And the good news is that it wasn't always modifying style, only this one for that specific page, because the `<div class="primary-content">` (which is what we parse for dice formulas) had the style in it! 🤦‍♂️ I thought it was in the `<head>` of the page, but nope... so I expect that this bug only affected that page, not everything else. Either way, it's fixed now! 👍
