### ISSUE TITLE
DNDBeyond to Roll20 Token - AC pulling, but incorrect values?

### ISSUE THREAD

**Issue by KWall24** [kakaroto/Beyond20#959]
**Describe the bug**
I've got Tokens for characters Zezix and Willow in Roll20 with names matching DNDBeyond character sheets.
In Roll20, I'm using the Token Status Bars/Radial Menu Bubbles/3 circles above the token. One is used for HP. This is working fine. I want to use another for AC. This seems to work in that it pulls a number from DNDBeyond, but it does not pull the correct number.

[Zezix](https://ddb.ac/characters/66949754/D53q9b):
Roll20 attribute "AC" pulls as 12
Character has +2 to DEX, but AC is 18 after armor and bonuses
Character also has Mastiff and Steel Defender in Extras. These seems to have the same problem. Steel Defender in Roll20 comes across as AC 11, but should be 15 after natural armor.

[Willow](https://ddb.ac/characters/67403481/o02Mdg):
Roll20 attribute "AC" pulls as 14 
Character has +4 to DEX, but AC is 15 after armor and bonuses

**Expected behavior**
If it is pulling the AC value, I would imagine it's meant to pull the correct AC value. If this is an unfinished feature, I apologize, I haven't seen anything to indicate this.

**Screenshots**
![image](https://user-images.githubusercontent.com/42083166/159136347-0b26dd28-d650-495b-92ca-04691640673a.png)

**Browser Info (please complete the following information):**
 - Browser: Firefox(my computer) and Chrome(players)
 - Version 2.6.1 on my Firefox

**Comment by Aeristoka** [comment]
Beyond20 has not ever, and will not ever sync AC.

Beyond20 does sync (only):

1. HP
2. Temp HP

**Comment by KWall24** [comment]
Understood. In that case, what is it syncing on the "ac" value? I can delete that numeric value on the token and as long as the attribute is "ac" it will repopulate itself with no Roll20 character sheet on the token.

**Comment by Aeristoka** [comment]
Nothing is syncing it, something internally in Roll20 is doing it to you. Roll20 is often a buggy mess.

**Comment by KWall24** [comment]
Understood. In that case, what is it syncing on the "AC" value? I can
delete that numeric value on the token and as long as the attribute is "ac"
it will repopulate itself with no Roll20 character sheet on the token.

**Comment by kakaroto** [comment]
That's how roll20 works. If you set it to match the ac value, it will sync it to ac. I don't think you can select ac or any value for that matter unless the token is set to represent a character sheet, so check your token settings, it's syncing to some sheet you have and it's definitely not beyond 20 related either way.
