### ISSUE TITLE
Disable pop up alerts or add extension on/off toggle?

### ISSUE THREAD

**Issue by johnjosephadams** [kakaroto/Beyond20#966]
I'd like to be able to toggle Beyond20 on/off by clicking the button in the browser toolbar, because I like to turn it off when I'm not actively playing (if I'm just doing something on a character sheet etc). Right now, I think the only way to toggle it on/off is to deactivate the extension in the "manage extensions" browser menu, which is kind of tedious to do every time. 

Or, even better, could you make it an option to disable the pop up alerts, like if it doesn't detect a VTT and the "features & traits" warning? Like, I get why you have them, but I feel like I don't need them at all and they actively bug me.

**Comment by kakaroto** [comment]
Hi,
The pop up alert you see when you open the sheet that says it couldn't find a VTT is only as a reaction to failing to set the HP, so if you disable the HP sync option, it shouldn't notify you anymore. As for the "features & traits" warning, that would only happen once per character sheet (unless you level up), so it's very low impact.
I don't plan on adding an option to disable alerts as they are directly a result of user interaction, and disabling the features&traits one is so low impact that there's a higher chance of a user disabling the option by mistake and having incorrect data than a user needing the option.
If you want to use the D&D Beyond roll buttons without Beyond20 intercepting them and showing its dialog, there's also already an advanced option to disable that behavior ("add quick rolls areas")
I hope that helps.
