### ISSUE TITLE
The Beyond20 bot won't respond to commands

### ISSUE THREAD

**Issue by sassmastermeg** [kakaroto/Beyond20#967]
Let me begin with I am already bad at using discord bots and I have no idea where I could have messed up.

I have just downloaded the Beyond20 extension and I am trying to integrate it with Discord as well. I added the bot to my server, gave it permissions and tried to use the !beyond20 info command in the chat and it wouldn't send anything back. I even tried the !beyond20 secret to see if I could get that to work and it didn't either.

I have already tried messaging the bot outside of the server and neither of the commands worked. Is this a bug? Or did I not add the bot correctly?

**Comment by kakaroto** [comment]
Hi.
The bot seems to be working fine, but I tested 6 hours ago when you opened the issue, and it was quite slow to respond (taking a minute or two), so I'm unsure, it might have been some temporary issue with Discord or the server making it slow or unresponsive.
Is it working properly for you now ?

**Comment by Aeristoka** [comment]
@sassmastermeg is the Beyond20 bot working for you now?

**Comment by sassmastermeg** [comment]
Sorry for the late reply, it is working now. Thanks for the help! I guess it was just a hiccup with Discord.
