### ISSUE TITLE
Extension icon not appearing 

### ISSUE THREAD

**Issue by AGoudreault** [kakaroto/Beyond20#970]
**Describe the bug**
When Beyond20 extension is enabled, the icon would appear on the upper right of Chrome. Now it doesn't anymore

**To Reproduce**
It suddenly was not there anymore. Tried removing/reloading Beyond20. The icon appears briefly to state that the extension has been installed successfully, but then disappears

**Expected behavior**
Would expect the icon to remain on the bar.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/77407491/161892677-15d75999-3835-44a3-8a35-fa4460da2f23.png)

During re-install:
![image](https://user-images.githubusercontent.com/77407491/161892962-8d1a118a-2c17-474f-b2e1-6c75a9c35886.png)

After:
![image](https://user-images.githubusercontent.com/77407491/161893011-c4039b49-ca00-412c-a439-8c41e10130c7.png)

**Browser Info (please complete the following information):**
 - Browser: Chrome
 - Version Version 100.0.4896.75 (Official Build) (64-bit)

**Additional context**

**Comment by Aeristoka** [comment]
![image](https://user-images.githubusercontent.com/7988297/161894408-a2b407a5-70b2-4ac2-87f9-844e7ba19610.png)

You don't have it Pinned, I'm pretty near positive.
