### ISSUE TITLE
Bug with 'Add tiebreaker to initiative rolls'

### ISSUE THREAD

**Issue by IsaacAbramowitz** [kakaroto/Beyond20#973]
I'm not sure if this is just for me but there seems to be a problem with the `Add tiebreaker to initiative rolls` feature. When rolling with it it says `NAN` and doesn't add any number to the roll even though my characters' initiatives are more than `+0`. When I turn off the `Add tiebreaker to initiative rolls` option everything works fine. I've tested this with multiple characters on D&D Beyond, with Roll 20 open and not open, and even uninstalled Beyond 20 then reinstalled it. Same result.

The browser I'm using is Opera

![image](https://user-images.githubusercontent.com/31316420/163076355-7c7135eb-1a65-41af-b2aa-fe9d704c756f.png)

**Comment by Aeristoka** [comment]
This actually isn't due to that setting, but due to a change DnDBeyond made today with how Initiative is stored in the Field here:
![image](https://user-images.githubusercontent.com/7988297/163076826-9af76933-971d-4364-8052-53efffa5c7a3.png)

It has been fixed and merged here:
https://github.com/kakaroto/Beyond20/pull/972

And we're looking at a release hopefully tonight.

**Comment by IsaacAbramowitz** [comment]
@Aeristoka  hah was just looking now at your PRs and noticed there was one for this exact fix. My bad, next time I'll look there first

**Comment by Aeristoka** [comment]
> @Aeristoka hah was just looking now at your PRs and noticed there was one for this exact fix. My bad, next time I'll look there first

No worries at all 😄 , I definitely don't ALWAYS have a PR in already. Feel free to join us at the Discord too: https://discord.gg/ZAasSVS We're usually discussing bugs, or would love to have reports of future bugs in there too!

**Comment by Aeristoka** [comment]
Re-opening as a placeholder until the 2.6.3 release

**Comment by Aeristoka** [comment]
Closing with 2.6.3 being available.
