### ISSUE TITLE
Rolling a d3 with digital dice enabled fails to calculate total

### ISSUE THREAD

**Issue by kakaroto** [kakaroto/Beyond20#978]
![image](https://user-images.githubusercontent.com/27990/164845072-52dda8e1-17ab-4ad8-8999-d6e174ecd663.png)

![image](https://user-images.githubusercontent.com/27990/164845081-bb2e2b10-bbb0-490c-b0aa-4746222c9591.png)

![image](https://user-images.githubusercontent.com/27990/164845087-535b085b-fc46-4c6e-8f71-7d8eb055065e.png)

Only happens if digital dice is enabled. Looks like it does the dice roll correctly but doesn't calculate the total which ends up causing the problem.

**Comment by Aeristoka** [comment]
Affects DnDBeyond itself too:
![image](https://user-images.githubusercontent.com/7988297/164981208-c93ff7fb-58c1-4fd4-a1bd-dde3df3ef52d.png)

**Comment by Aeristoka** [comment]
Appears this is something to do with the fact that DnDBeyond doesn't have a d3 die to roll? and the Total never gets set in the roll when it's resolved? (I'm out of my depth with this I think)

**Comment by Aeristoka** [comment]
```js
static _finishPendingRoll() {
        const [roll, resolver] = this._pendingRolls.shift()
        roll.handleCompletedRoll().then(resolver);
        if (this._pendingRolls.length > 0) {
            const nextRoll = this._pendingRolls[0][0];
            this._submitRoll(nextRoll);
        }
    }
```
