### ISSUE TITLE
Add PlanarAlly integration

### ISSUE THREAD

**Issue by DeathKhan** [kakaroto/Beyond20#980]
PlanarAlly is a free and open source, self hostable VTT. It'd be great to see you guys open support for such great community driven projects.

https://github.com/Kruptein/PlanarAlly

**Comment by Aeristoka** [comment]
Hate to be the bearer of bad news, but: https://beyond20.here-for-more.info/faq#can-you-add-support-for-insert-new-vtt-name

**Comment by Aeristoka** [comment]
At some point https://github.com/kakaroto/Beyond20/issues/833 might make it possible, but PlanarAlly would have to add code to interpret the Beyond20 Messages

**Comment by DeathKhan** [comment]
> At some point #833 might make it possible, but PlanarAlly would have to add code to interpret the Beyond20 Messages

Bummer
