### ISSUE TITLE
Halfling luck has the wrong dice effect

### ISSUE THREAD

**Issue by wewalsh** [kakaroto/Beyond20#981]
I believe the current halfling luck effect in roll20 is that the player is unable to roll a 1. This is a different effect than rerolling 1s

**Comment by Aeristoka** [comment]
Care to elaborate?

**Comment by wewalsh** [comment]
yeah, sorry. I'm new here
updated the post

**Comment by Aeristoka** [comment]
The effect is correct:
![image](https://user-images.githubusercontent.com/7988297/165433979-c6c355a6-46f2-4a8c-b5fd-f2a683d75de7.png)

https://wiki.roll20.net/Dice_Reference

![image](https://user-images.githubusercontent.com/7988297/165434066-a3e74e7a-005b-4325-9b57-8f6a8beb7044.png)

It's rerolling any 1.

**Comment by kakaroto** [comment]
https://www.dndbeyond.com/races/14-halfling
![image](https://user-images.githubusercontent.com/27990/165433976-95a346e1-5653-4a13-a9d5-b6602fa8a0a5.png)

I don't know what roll20 does, but rerolling the 1 is what it should do and likely what it does. It's the same effect either way.

**Comment by wewalsh** [comment]
Gotcha, sorry for my misunderstanding. I appreciate the quick response and all that you do.  <3
