### ISSUE TITLE
Suggestion: Character specific Discord Channel association

### ISSUE THREAD

**Issue by tomsaul** [kakaroto/Beyond20#984]
**Is your feature request related to a problem? Please describe.**
Its is too easy to 'spam' a discord channel with rolls for a character that are intended for distribution elsewhere.

**Describe the solution you'd like**
The association of the Extension to a Discord channel should be (optionally) associated with a specific DnDBeuond character sheet.  Multiple (distinct) associations should be allowed.  Basically char A goes to Channel D-A, char B to D-B, ....
 
**Describe alternatives you've considered**
Add a banner when first used in a session do a modal popup notifying the user of what Discord channel is associated.

**Comment by Aeristoka** [comment]
https://github.com/kakaroto/Beyond20/blob/master/docs/discord.md

Under #3 
```
Note that you can also override the Discord destination channel on a per-character basis, which is practical if you have multiple groups and want the right character to send their rolls to the appropriate channel. Simply set the override in the per-character settings by clicking the Beyond20 icon on the character sheet page.
```

**Comment by tomsaul** [comment]
Cool - This option is a bit buried.  Perhaps add some text to the Default setting that mentions it is present.

For those looking for this, here are the steps
0) Add all associated discord channels
1) Change the default extension option to 'Do Not Send to Discord'
2) Open your character sheet, click on the 'Beyond20' button to open its 'Quick Settings' window.  Click on 'Advanced Options'.  Change the 'Discord Destination' option to the appropriate channel
