### ISSUE TITLE
All rolls appear twice in Roll20

### ISSUE THREAD

**Issue by Umbratikus** [kakaroto/Beyond20#988]
**Describe the bug**
All rolls I click from D&D Beyond roll twice in Roll 20 - even though I have the rolls set to "Normal Rolls" - Also when I click on descriptions - everything I click on in DDB is doubled in Roll20

**To Reproduce**
Click on any roll in D&D beyond - shows up as two separate rolls in Roll20

**Expected behavior**
Should only happen once.

**Screenshots**
![image](https://user-images.githubusercontent.com/107709386/174348628-dd187e09-f124-4e6a-ac56-e297c0934307.png)

**Browser Info (please complete the following information):**
 - Chrome
 - Version 102.0.5005.115 (Official Build) (64-bit)
 - 

**Additional context**
Add any other context about the problem here, such as a link to the character sheet or D&D Beyond page that shows the problem.

**Comment by Aeristoka** [comment]
That means you have either 2x Roll20 or 2x DnDBeyond tabs open.

**Comment by Umbratikus** [comment]
Thanks - that was it
