### ISSUE TITLE
Minor display bug: negative modifiers

### ISSUE THREAD

**Issue by Ribcourt** [kakaroto/Beyond20#991]
**Describe the bug**
Rolling to Discord from DndBeyond with a negative modifier, the resolved values are signed positive in Discord. Dice formulas and results are shown correct.

Adding a negative Custom Modifier or negative Custom Damage via hotkey, the resolved dices are signed positive in Discord. Dice formulas and results are shown correct.

Using a  homebrew magic weapon with a negativ modifier has the same effect 

**To Reproduce**
1. Add a Hotkey with a negative Custom Modifier/Damage
2. Roll to Discord with Hotkey

1. Create a Homebrew Magic Weapon with a negative modifier
2. Roll attack to Discord

**Expected behavior**
Resolved Dice should be signed negative.

**Browser Info (please complete the following information):**
 - Browser Chrome
 - Version 102.0.5005.115
- Beyond 20 2.6.3

**Screenshots**
![Hotkey](https://user-images.githubusercontent.com/107406999/173351322-e8211e38-75e3-4631-bf5f-a10ffbd3dd67.png)
![Discord_Result](https://user-images.githubusercontent.com/107406999/173351365-e1ff8705-f9bd-4085-810a-f0cb879dd51f.png)
![Weapon](https://user-images.githubusercontent.com/107406999/173361685-2f52f5e3-80e3-48d7-827b-d1af639d0260.png)
![Discord_Result_Weapon](https://user-images.githubusercontent.com/107406999/173361736-4c37b8cf-43ff-40eb-b44d-e41f511195d8.png)

**Comment by Aeristoka** [comment]
@kakaroto what did you do...

This is pretty funny
