### ISSUE TITLE
Bag of Tricks, Gray - Table not rollable

### ISSUE THREAD

**Issue by DarrynGlass** [kakaroto/Beyond20#992]
**Describe the bug**
The table for the creature pulled from the Bag of Tricks (Gray) is not rollable:

**To Reproduce**
Link to Item: https://www.dndbeyond.com/magic-items/2965260-gray-bag-of-tricks
Screen Capture
![image](https://user-images.githubusercontent.com/29684482/175564699-302fe389-45fc-4274-8a26-e878991d2f31.png)

**Expected behavior**
The Table to be rollable as other tables.
Example
![image](https://user-images.githubusercontent.com/29684482/175564978-95b61d83-f04b-459a-8a04-bd869ad30cbb.png)

**Comment by Aeristoka** [comment]
Wonder what weird nonsense they're doing in formatting here that breaks this 🤔 . Thanks for the report @DarrynGlass !

**Comment by DarrynGlass** [comment]
Welcome.  I am filling out the details to run Strixhaven soon, and other tables were working, but not that one :)

**Comment by kakaroto** [comment]
Fixed in 71d4403a04ad633ac9ef08972f42a3a2540b3220
