### ISSUE TITLE
Spell scaling calculated

### ISSUE THREAD

**Issue by JohniMichels** [kakaroto/Beyond20#994]
**Feature description.**
When I use a higher level spell slot, the roll is still based only on the base roll. As example, if you invoke _Spirit Guardians_ cast as 8th level, the description will still use a `3d8` damage roll.

**Describe the solution you'd like**
I would love to have an auto calculated dice roll when a spell has a `At Higher Levels` description.

**Describe alternatives you've considered**
I roll the dice indicated on the scaling `n` times, where `n` is the difference between the spell slot and the spell level.
It could easily be transformed in a dice multiplier alongside the roll described on the spell.

**Additional context**
Example: 
Casting _Spirit Guardians_ with a 8th level spell slot

What it does:
![print of current behavior](https://user-images.githubusercontent.com/28475162/175982458-3c1691d2-f3e5-4ff4-9b03-1ec1d7e45fd8.png)

What should be done:
![print of expected behavior](https://user-images.githubusercontent.com/28475162/175983794-c4ff8350-7887-426a-a687-262b1dfece45.png)

**Comment by kakaroto** [comment]
Confirmed. If you click the "Display in VTT" button, it will **display** the spell description as it should.
If you click the "Cast on VTT" button (or just cast it from the spell list) : 
![image](https://user-images.githubusercontent.com/27990/176047353-b50e61b4-0f1b-4cc5-b335-2b4601a7b30b.png)

Then it will prompt for the damage type : 
![image](https://user-images.githubusercontent.com/27990/176047396-4b391eea-f984-42c3-a26d-1b13fd7af1f6.png)

and send this to Roll20 :
![image](https://user-images.githubusercontent.com/27990/176047449-9ab831c4-fa7d-4ee8-9308-1589893582f3.png)

I don't see a bug here.
